### ISSUE TITLE
How rendering an array.map() of component in react js?

### ISSUE THREAD

**Issue by Guilherme99** [ivmartel/dwv#1006]

**Comment by ivmartel** [comment]
I'm not sure I get your question, could you give more details please?

**Comment by Guilherme99** [comment]
I want generate thumbnails of dicom images, but unsuccessfully..

**Comment by ivmartel** [comment]
You could generate a small image from the generated canvas. What is your workflow? When do you want to generate this thumbnail?

**Comment by Guilherme99** [comment]
The idea is to show the images instead of the name, in this list:

![image](https://user-images.githubusercontent.com/28719247/140506596-331c9751-effb-46e3-b024-9fded4c2d6d4.png)

**Comment by ivmartel** [comment]
You could try to load each files in its own viewer in a small canvas.

**Comment by Guilherme99** [comment]
Understand. I'll try.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
