### ISSUE TITLE
Load dcm file from state react js ?

### ISSUE THREAD

**Issue by Guilherme99** [ivmartel/dwv#1009]

**Comment by ivmartel** [comment]
I'm not sure I get your question, could you give more details please?

**Comment by Guilherme99** [comment]
I'm trying to load the images from the url, but I get "Received errors during load. Check log for details." and the following log:

![Captura de tela de 2021-10-04 10-29-30](https://user-images.githubusercontent.com/28719247/135860284-a8a0deab-311a-46bb-bfd2-2c831fdd2db1.png)

Detail, the lib is making two requests:
![Captura de tela de 2021-10-04 10-30-22](https://user-images.githubusercontent.com/28719247/135860413-3e315a1f-9703-49df-a58b-6c982cc4ae78.png)

![Captura de tela de 2021-10-04 10-32-21](https://user-images.githubusercontent.com/28719247/135860464-a9ea1974-ce43-4abd-9735-dbb1657be465.png)

**Comment by Guilherme99** [comment]
![Captura de tela de 2021-10-04 10-37-22](https://user-images.githubusercontent.com/28719247/135861302-9cd6c80a-8b5c-4693-98a0-999928f8e7c8.png)

**Comment by ivmartel** [comment]
Not sure what is happening, do you have errors before the `Failed to execute 'drawImage'`?

**Comment by Guilherme99** [comment]
The images were protected. I reviewed the documentation. It was necessary to pass the token in this case. I got it.

**Comment by ivmartel** [comment]
Perfect, closing the issue then!
