### ISSUE TITLE
How do I install and deploy on my computer？

### ISSUE THREAD

**Issue by Jatal8080** [ivmartel/dwv#1019]

**Comment by ivmartel** [comment]
DWV is a library that parses DICOM files and creates a canvas from it. It does not provide a 'usable' viewer, just a basic one in its tests. For the possible commands, see its [readme](https://github.com/ivmartel/dwv#steps-to-run-the-viewer-from-scratch).
If you are looking for a viewer, check the demo integrations: [dwv-jqmobile](https://github.com/ivmartel/dwv-jqmobile), [dwv-react](https://github.com/ivmartel/dwv-react/), [dwv-vue](https://github.com/ivmartel/dwv-vue/)...

**Comment by ivmartel** [comment]
If you clone the code, you then need to run a `yarn install` and then `yarn run start` (see [dwv-jqmobile#steps-to-run-the-viewer-from-scratch](https://github.com/ivmartel/dwv-jqmobile#steps-to-run-the-viewer-from-scratch)).

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
