### ISSUE TITLE
Can i rotate a image?

### ISSUE THREAD

**Issue by XaloDev** [ivmartel/dwv#1025]
Can i rotate and flip a image on Dicom viewer? Already exists some functions to do that?

**Comment by ivmartel** [comment]
No rotation nor flip for now... It should not be to complicated to implement, you just have to move the canvas using  transformations, see [Canvas_API/Tutorial/Transformations](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Transformations) on MDN.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
