### ISSUE TITLE
Add folder support on URL

### ISSUE THREAD

**Issue by christianesperar** [ivmartel/dwv#103]
I think it's good to have an option to have a folder on the parameters instead of multiple files in case there are many files.

**Comment by ivmartel** [comment]
Just to keep some notes on this.
(As of 07/09/2017) Chrome >30, Firefox >50, Edge >14 and Opera >17 support the 'webkitdirectory' option for file input that allows to select / drag and drop folders.

Links:
 * [caniuse input-file-directory](http://caniuse.com/#feat=input-file-directory)
 * [developer.mozilla.org webkitdirectory](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory) (Firefox 50 release [notes](https://developer.mozilla.org/en-US/Firefox/Releases/50#Files_and_directories))
 * [stackoverflow does-html5-allow-drag-drop-upload-of-folders-or-a-folder-tree](https://stackoverflow.com/questions/3590058/does-html5-allow-drag-drop-upload-of-folders-or-a-folder-tree)

**Comment by ivmartel** [comment]
Ok, if major browser allow loading directories, lets do it!

**Comment by ivmartel** [comment]
I got confused, this issue is for folder support on URL when the webkitdirectory is for local folder support. 

Re-closed this one and created #424.

What could solve this issue is using a DICOMDIR, see #425.
