### ISSUE TITLE
Is it possible to access data of drawn data? Like boxes and rules?

### ISSUE THREAD

**Issue by XaloDev** [ivmartel/dwv#1033]
Is it possible to access data of drawn data? Like boxes and rules?

**Comment by ivmartel** [comment]
The app gives you access, via `getDrawDisplayDetails`, to the shape information such as id, position, type, colour and meta data.

**Comment by XaloDev** [comment]
@ivmartel how can i load this informations again from a database? It's possible to know the position in the slice some way?

**Comment by ivmartel** [comment]
Ok, answering your last question in #1040.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
