### ISSUE TITLE
Is possible to save and after this access and load drawn data?

### ISSUE THREAD

**Issue by XaloDev** [ivmartel/dwv#1040]
Is possible to save and after this access and load drawn data? I know it's possible to acess data, but it's possible to save locations and futhermore load them?

**Comment by ivmartel** [comment]
Yes, that's the idea behind the state, see [src/app/state.js](https://github.com/ivmartel/dwv/blob/v0.29.1/src/app/state.js) (and now `src/io/state.js`). It stores all the drawing information in a json file using the format of Konva (the drawing library). Check out this [demo](https://ivmartel.github.io/dwv-jqmobile/) where you can generate the file and load it back.

**Comment by XaloDev** [comment]
Can you point me some code that does that (Save and load the saved drawned things)? I'm not founding

**Comment by ivmartel** [comment]
As a start, you can check the tests: https://github.com/ivmartel/dwv/blob/develop/tests/state/state.test.js

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.

**Comment by XaloDev** [comment]
i checked the test but the method checkDrawings expect the "drawings" to be a object, how do i use setDrawings if this method in the application expect a array?
