### ISSUE TITLE
require() of ES modules is not supported

### ISSUE THREAD

**Issue by XaloDev** [ivmartel/dwv#1045]
After fresh install of yarn add dwv i keep getting this error 

> require() of ES modules is not supported, require() of E:\dev\colono-front\node_modules\konva\lib\index-node.js from E:\dev\colono-front\node_modules\dwv\dist\dwv.min.js is an ES module file as it is a .js file whose nearest parent package.json

**Comment by arturojain** [comment]
Is this happen with the latest v0.30.1?

**Comment by ivmartel** [comment]
I guess you are using dwv v0.30.1. What is your version of node?

**Comment by ivmartel** [comment]
Ok, cofirmed, I can reproduce with node v15 and the full error is:
> Error: Must use import to load ES Module: /app/available_modules/1638865486000/dwv/node_modules/konva/lib/index-node.js
require() of ES modules is not supported.
require() of /app/available_modules/1638865486000/dwv/node_modules/konva/lib/index-node.js from /app/available_modules/1638865486000/dwv/dist/dwv.min.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index-node.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /app/available_modules/1638865486000/dwv/node_modules/konva/package.json.

**Comment by ivmartel** [comment]
It looks like, since v12, node allows to load ES modules via `import()` (see [doc](https://nodejs.org/docs/latest-v12.x/api/all.html#esm_import_expressions)). Since v14, node will give an error if an ES module is loaded with require. 

Konva is a module since its v8 witch was included in dwv v0.30, it needs to be included with `import`.

**Comment by ivmartel** [comment]
I just published v0.30.2! I hope it helps...

**Comment by ivmartel** [comment]
Ok, it helps but does not go much further, see #1055.
