### ISSUE TITLE
LoadUrls throws error when Server is responding with error or blocked by CORS

### ISSUE THREAD

**Issue by KillerCodeMonkey** [ivmartel/dwv#1054]
I have an angular app, where i am using your wonderful project.
Everything is working when the urls are available and the server sends the images.

But, if the server crashes, e.g. response status 500 or a CORS error occurs for a file i get a not "catchable" error from dwv.

`setting getter-only property "type"`

**Comment by ivmartel** [comment]
The app should send a regular error event when a file is not accessible (status 200), see [urlsLoader.js#L313](https://github.com/ivmartel/dwv/blob/v0.30.3/src/io/urlsLoader.js#L313). What do you mean by not catchable?

**Comment by KillerCodeMonkey** [comment]
i have an error listener:

```TS
app.addEventListener('error', (event: { error: any }) => {
   console.error('DICOM errored', event.error)
})
```

but the listener is not called. the error is bubbling up to my "global" error handler.

In my case it occurs every time when the browser cancels the request because of CORS.

**Comment by ivmartel** [comment]
The test viewer in `tests/pacs/viewer.html` has a similar event listener.
When I try to load a CORS protected image, I get 3 errors:
> Access to XMLHttpRequest at 'http://i.stack.imgur.com/eyC0s.png' from origin 'http://localhost:9876' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

> load error (from the listener) _ProgressEvent {...}_

> GET http://i.stack.imgur.com/eyC0s.png net::ERR_FAILED 200

By global you mean the one that logs 1 and 3?

**Comment by ivmartel** [comment]
I hope you solved your problem, closing for now, feel free to comment if you need.
