### ISSUE TITLE
y.Group is not a constructor

### ISSUE THREAD

**Issue by ivmartel** [ivmartel/dwv#1055]
When running in a node context, calling `app.init(...)` throws:
> TypeError: y.Group is not a constructor
    at new A.tool.Draw (/home/yves/dev/src/github/local/node/parse/node_modules/dwv/dist/dwv.min.js:3:377913)
    at A.App.init (/home/yves/dev/src/github/local/node/parse/node_modules/dwv/dist/dwv.min.js:3:4228)

**Comment by ivmartel** [comment]
Ok, should have read the docs: the proper way to include Konva in a commonjs module is `require('konva/cmj')`...

Ref: https://github.com/konvajs/konva/tree/8.3.0#commonjs-modules

**Comment by dayrenlim** [comment]
Having issue when using draw tools, it will be show y.Group is not a constructor. How to resolve it?

**Comment by ivmartel** [comment]
This should have been fixed in v0.30.3. The current version is v0.31. Which version are you using?
