### ISSUE TITLE
Does this has 3-axis/3D views?

### ISSUE THREAD

**Issue by rohang1411** [ivmartel/dwv#1076]
Does this has 3-axis/3D views? If there is then I'm unable to find it. Can somebody please help

**Comment by ivmartel** [comment]
If you mean MPR (see #4), then yes, the last release (v0.30) can display MPR, see the test viewer: [tests/pacs/viewer.js](https://github.com/ivmartel/dwv/blob/v0.30.7/tests/pacs/viewer.js). You can see it in action when you run `yarn run test` (or npm).

**Comment by rohang1411** [comment]
Actually I meant does it have functionality to display the 3 views namely saggital, coronal and axial/transverse.

**Comment by ivmartel** [comment]
Then MPR is for you!

**Comment by rohang1411** [comment]
I want to see all the 3 views saggital, coronal and axial/transverse at once. Is it possible, if so, how to do it? I'm unable to find it in the demo. Please tell me the required steps.

**Comment by ivmartel** [comment]
You have to set the desired orientation in the data view config, as done at [viewer.js#L267](https://github.com/ivmartel/dwv/blob/v0.30.7/tests/pacs/viewer.js#L267).

**Comment by rohang1411** [comment]
Okay Thanks for the reply. Can you please tell will these 3 views be synchronised. For ex. if I change my coordinates on one view will the other two view automatically follow?

**Comment by ivmartel** [comment]
The synchronisation is controlled by the 'binders', they are passed in the app init (check the viewer example and see their definition at the beginning of [src/gui/stage.js](https://github.com/ivmartel/dwv/blob/v0.30.7/src/gui/stage.js)). For example, the `dwv.gui.PositionBinder` will synchronise the position between the views.

**Comment by ivmartel** [comment]
I hope I answered your question, closing for now, feel free to comment if you need.
