### ISSUE TITLE
Where could I find the dowloaded state.json explanation?

### ISSUE THREAD

**Issue by tommyJin** [ivmartel/dwv#1079]
I download the drawing record file _state.json_, and I'd like to know where could I find the explanation of it. Cause the structure seems a little bit complicated. Could u point me or give me a link to the explanation?
Thx.

**Comment by ivmartel** [comment]
The top structure is defined in [state.js#L48](https://github.com/ivmartel/dwv/blob/v0.30.7/src/io/state.js#L48). The drawing part comes directly from Konva.

Be aware that I am looking at using DICOM presentation state to store state info, follow #1020 for updates. These state files are limited and do not work well with MPR.

**Comment by tommyJin** [comment]
Thanks! I am going to check out the drawing part from Konva.
