### ISSUE TITLE
Question: In which file/function the dicom files are read and showed in Canvas?

### ISSUE THREAD

**Issue by gdet** [ivmartel/dwv#1085]
Hello!
 I would like to ask a question. I would like to get somehow the dicom files the user is uploading or their images shown on "canvas".
 I am trying to find in which file/function the process but I cannot find it. Could you point me to the correct file?

Thank you!

**Comment by ivmartel** [comment]
The parsing is done in [src/dicom/dicomParser.js](https://github.com/ivmartel/dwv/blob/v0.30.8/src/dicom/dicomParser.js).
The canvas data is created in [src/image/view.js#L705](https://github.com/ivmartel/dwv/blob/v0.30.8/src/image/view.js#L705).
