### ISSUE TITLE
Trying to load MPR...

### ISSUE THREAD

**Issue by XaloDev** [ivmartel/dwv#1097]
When i try to load the multiple axis visions i got layers with 3px height and 1325px width in the coronal and saggital view.

dwv version: 0.30.8

![image](https://user-images.githubusercontent.com/73499961/151806797-a7fa1316-6616-4cfb-86f6-309f03ee5ff4.png)
![image](https://user-images.githubusercontent.com/73499961/151806852-d8e03243-a428-4950-b261-4edb58250abf.png)
![image](https://user-images.githubusercontent.com/73499961/151806962-68a5bcc4-9ba1-465d-8138-8de90deeb6c3.png)
![image](https://user-images.githubusercontent.com/73499961/151807000-0f5bf820-ed42-4305-be02-cfc7f614791f.png)
![image](https://user-images.githubusercontent.com/73499961/151807137-f31736ab-b7bb-4b91-9b3d-e8e03c564c06.png)

**Comment by ivmartel** [comment]
You have to wait for all the slices to be present to create the MPR view, could that be your problem?

**Comment by XaloDev** [comment]
I tried this solution but still no success, can you give me a exemple in react?

**Comment by ivmartel** [comment]
I have not yet implemented it in react... It is only available in the tests of dwv in the demo viewer, below the image there is a mpr toggle.

**Comment by XaloDev** [comment]
Can you send to me the link to this demo viewer code and the demo viewer himself?

**Comment by ivmartel** [comment]
The test demo viewer's code is at [tests/pacs/viewer.html](https://github.com/ivmartel/dwv/blob/develop/tests/pacs/viewer.html). It is available with the tests when you run `npm run test`.
