### ISSUE TITLE
problem to loading the state by the URL.

### ISSUE THREAD

**Issue by Coebin** [ivmartel/dwv#1101]
I have a problem loading the state by the URL. this is the path I use

http://localhost/DicomVista/index.php?input=http%3A%2F%2Flocalhost%2FDicomVista%2FArchivosDicom%2F86%2FPrueba%2F%3Ffile%3D1.dcm%26file%3D2.dcm%26file%3D3.dcm%26file%3D4.dcm%26file%3D5.dcm%26file%3D6.dcm%26file%3D7.dcm%26file%3D8.dcm%26file%3D9.dcm%26file%3D10.dcm%26file%3D11.dcm%26file%3D12.dcm%26file%3D13.dcm%26file%3D14.dcm%26file%3D15.dcm%26file%3D16.dcm%26file%3D17.dcm%26file%3D18.dcm%26file%3D19.dcm%26file%3D20.dcm&dwvReplaceMode=void&state=http://localhost/ArchivosDicom/86/Prueba/state.json

and it gives me the image error, if I load only the DCM files there is no problem. it looks like you are spelling out the state url

![dcmfail](https://user-images.githubusercontent.com/98852969/152806567-4ba0e967-b91d-4afe-ba01-901f960a574f.png)

**Comment by ivmartel** [comment]
I had a quick look last week, you seem to be right, there is a problem...
