### ISSUE TITLE
function getLayerContainerSize() 

### ISSUE THREAD

**Issue by mmalkieli** [ivmartel/dwv#1140]
Hi
in version 0.29.1  exist function getLayerContainerSize()

I installed the latest version 0.30.8 and function getLayerContainerSize() not exist

Is there an alternative function? I need this calculation  of layer container size.

Thanks Michal

**Comment by ivmartel** [comment]
The app method `getLayerContainerSize` was defined at [application.js#L280](https://github.com/ivmartel/dwv/blob/v0.29.1/src/app/application.js#L280) in v0.29.
v0.30 introduced layer groups that each use a specific HTML div. They also try to be more respectful of the container div, so the result of their layer container size is the `offsetWidth` and `offsetHeight` of that div. If you really need to know that size, you could get the div after render and check its sizes. Tell me if that works for you.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
