### ISSUE TITLE
Incorrect shape factory set when dragging a shape group while another shape is set

### ISSUE THREAD

**Issue by matteuc** [ivmartel/dwv#1149]
I encountered this bug after I finished drawing a circle and tried to move a line I previously created. It seems that the shape group's 'dragmove.draw' event listener (`src/tools/draw.js:648`) is triggered before the `currentFactory` variable is reset for the current shape group. As a result when `currentFactory.updateQuantification` is called (src/tools/draw.js:655), an error occurs:

*Reproduced at [dwv-jqmobile](https://ivmartel.github.io/dwv-jqmobile/demo/stable/index.html?input=https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dbbmri-53323851.dcm%26file%3Dbbmri-53323707.dcm%26file%3Dbbmri-53323563.dcm%26file%3Dbbmri-53323419.dcm%26file%3Dbbmri-53323275.dcm%26file%3Dbbmri-53323131.dcm&dwvReplaceMode=void)*
![image](https://user-images.githubusercontent.com/36247196/163231718-e49cede3-0682-471d-b6eb-727b3c447323.png)

**Steps to reproduce**
- Create 2 different shapes - a ruler, a circle
- Set the draw shape to Circle
- Move the Ruler

**Proposed fix**

*`src/tools/draw.js:648`*

```js
shapeGroup.on('dragmove.draw', function (event) {
      if(!currentFactory?.isFactoryGroup(shapeGroup)) {
        var keys = Object.keys(self.shapeFactoryList);
  
        for (var i = 0; i < keys.length; ++i) {
          var factory = new self.shapeFactoryList[keys[i]];
          if (factory.isFactoryGroup(shapeGroup)) {
            currentFactory = factory;
            // stop at first find
            break;
          }
        }
      }

// ...
```

**Comment by ivmartel** [comment]
Nice one, thanks for spotting and the fix!
