### ISSUE TITLE
Ruler Factory error on double click

### ISSUE THREAD

**Issue by matteuc** [ivmartel/dwv#1150]
If the canvas is double clicked while the Ruler draw shape is set, an error will be thrown

![image](https://user-images.githubusercontent.com/36247196/163233551-0404b676-598d-4ee9-97c8-9d791840904a.png)

**Steps to reproduce**
- Set draw shape to `Ruler`
- Double click the canvas

**Proposed Fix**

*`src/tools/ruler.js:68`*
```js
dwv.tool.draw.RulerFactory.prototype.create = function (
  points, style, viewController) {
  if(!(points[0] && points[1]) return;

  // physical shape
  var line = new dwv.math.Line(points[0], points[1]);
  // draw shape
```

**Comment by ivmartel** [comment]
I chose a different solution to fix other shapes too. Thanks for your help!
