### ISSUE TITLE
Getting an error when i use the zoom function

### ISSUE THREAD

**Issue by XaloDev** [ivmartel/dwv#1151]
my code:
![image](https://user-images.githubusercontent.com/73499961/163693893-a7a61eec-d1b9-4ceb-b617-e48d1a36cee9.png)

my error:
![image](https://user-images.githubusercontent.com/73499961/163693910-50f9291e-eaf5-460b-b3e2-7e1543958e7b.png)

**Comment by XaloDev** [comment]
i'm trying to create a function that i can call in a button to zoom the image, what i have to change in this code?
![image](https://user-images.githubusercontent.com/73499961/164759891-d3b53e9a-8743-45f2-859a-5122f8b5888d.png)

**Comment by ivmartel** [comment]
I badly guessed, zoom is your friend then. Just be aware that it only zooms the active layer group.

**Comment by XaloDev** [comment]
So, how can i adjust my code to get the zoom function working?

**Comment by ivmartel** [comment]
I fixed the error you mentioned, does it still not work?

**Comment by XaloDev** [comment]
I have to update the version to "0.31.0-beta.4"?

**Comment by XaloDev** [comment]
i have updated and still doesn't work

**Comment by XaloDev** [comment]
the same error, so i have to clone the repo and do local package?

**Comment by ivmartel** [comment]
to use the latest code, yes.
