### ISSUE TITLE
new kinetic shapes ID 's

### ISSUE THREAD

**Issue by mohamedsharaf** [ivmartel/dwv#116]
hello great i see you used kinetic 

how can i get shape ID 
i see 
self.shapeName

but shapes should have an ID so we can access them or add event on them 
i need to save shapes based on id's 

how this can be done

**Comment by ivmartel** [comment]
Hi, do you know of a good id generator that I could use?

**Comment by mohamedsharaf** [comment]
i did this before may be idea not ideal but i posted pull request
https://github.com/ivmartel/dwv/pull/122


//add name to the added group element 
            var childrens = drawLayer.getChildren();
            numofchilds = childrens.length - 1;
            var extraname = numofchilds + 1;
            shapeGroup.name = "ShapeGroup" + extraname;

one thing important to look on way to separate design from code its important thing to be done
i am working in it but you from version to version make it more complicated by creating html element 
from JavaScript
