### ISSUE TITLE
How i use the undo function in my application ? 

### ISSUE THREAD

**Issue by Guilherme99** [ivmartel/dwv#1165]
I didn't understand like run the function.

You can help me?

**Comment by ivmartel** [comment]
Did you manage to solve your question? The app maintains an undo stack (`dwv.tool.UndoStack`) defined at [src/tools/undo.js](https://github.com/ivmartel/dwv/blob/v0.30.8/src/tools/undo.js).

**Comment by Guilherme99** [comment]
Yes. I did solve this question. Grateful. I implemented this same above function.
