### ISSUE TITLE
How to adjust the amount of window level change on touchmove ?

### ISSUE THREAD

**Issue by ArmeniaH** [ivmartel/dwv#1170]
Couple of my dicom files have a very big window level range (I don't know how to say it in the right terminology), and clicking and moving the mouse almost changes nothing in Window Level Mode.

Many other dicom files work as expected and clicking the mouse and moving till the edge of the window makes it full dark, or full light.

Can anyone advise how this behavior can be changed to match the range of dicoms, so no matter what range in dicom file is used, clicking and moving to the side of window makes it full light or full dark?

**Comment by ivmartel** [comment]
Hi, #1160 should help with your problem, it will come in the next release that I hope to make quite soon.

**Comment by ivmartel** [comment]
Were you able to verify that the new code behaves as you expect? I published some beta releases of v0.31 if you need (latest 0.31.0-beta.7).

**Comment by ArmeniaH** [comment]
I used the code from the pull request and it worked as expected, didn't check it on the release yet.

Thank you for the update.

**Comment by ivmartel** [comment]
Perfect! If it is good for you, can you close the issue please?
