### ISSUE TITLE
DICOM Support Wordpress

### ISSUE THREAD

**Issue by Jethweb** [ivmartel/dwv#1171]
Hello Ivmartel, a pleasure to greet you, my name is José, I am writing to you because I have a problem with your Wordpress plugin
"DICOM Support" The problem I have is when I try to view images with the viewer from a cell phone, when it starts to load, it throws me the following error; "RangeError: invalid typed array length 262144"

Do you have any idea how I can fix it? Your plugin helps us a lot.

**Comment by ivmartel** [comment]
This looks more like a data problem. Would it be possible for you to share it?

**Comment by Jethweb** [comment]
Thanks to your plugin we can send results to our patients in a simple way, especially when they have an emergency, the error is the one attached in the photo, it happens when they open the site from Google Chrome or Firefox with their cell phones. This is the URL of the site: https://cibarinas.com/olga-fuentes-de-guevara-urotac/

I manage to solve it halfway by dividing the study into 2 pages, but if I put all 5 dicom image cuts in a single page, it is more likely that the error will be thrown.

I would love to be able to fix this as I don't have much knowledge on the subject, and we are just starting out with our clinic. I also hope at some point I can make a donation to your work.

Sorry for the bad english, I'm using the translator

![IMG-20220602-WA0069(1)](https://user-images.githubusercontent.com/106829943/172158303-a9dc1627-78c1-4c0d-aa95-8334a27bf959.jpg)

**Comment by Jethweb** [comment]
In this link you can see the error https://cibarinas.com/test-dicom/

Try to open on mobile with Google Chrome or Firefox browser

**Comment by ivmartel** [comment]
Hi, did you manage to solve your problem?
