### ISSUE TITLE
How to draw DWV info in viewport with dwv-react

### ISSUE THREAD

**Issue by mariocfdias** [ivmartel/dwv#1172]
Hello, how can i get the infos and draw it on viewport like the following example?

![image](https://user-images.githubusercontent.com/82966851/172702806-564e502f-41fc-4ab1-958d-6258945dd049.png)

(I highlighted the info that i am talking about)

**Comment by ivmartel** [comment]
This is something I need to sort out, it is available in dwv-jqmobile as you point out but not in the other demo viewers...

**Comment by ivmartel** [comment]
Follow #1383 for some tentative generic implementation. Closing for now, feel free to comment if you need.
