### ISSUE TITLE
How to programmatically draw an ellipse in different DWV indexes and MPR?

### ISSUE THREAD

**Issue by mariocfdias** [ivmartel/dwv#1173]
I want to draw an ellipse in different indexes, but im struggling about how to pass the index to the setDrawings argument, all the drawings are being made at the first index, and im struggling to draw they on MPR too

**Comment by ivmartel** [comment]
Can you share your code? The demo viewer can do it, check out its code ([tests/pacs/viewer.js](https://github.com/ivmartel/dwv/blob/develop/tests/pacs/viewer.js))  for an example implementation.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
