### ISSUE TITLE
希望把移动和放大功能分开，并且移动端对放大功能不友好

### ISSUE THREAD

**Issue by winterone** [ivmartel/dwv#1174]
移动端H5放大的时候，加倍以上的放大，一瞬间黑屏或者白屏。

**Comment by ivmartel** [comment]
(google translated)
title: I want to separate the mobile and zoom functions, and the mobile terminal is not friendly to the zoom function
body: When the mobile terminal H5 is zoomed in, if the zoom is doubled or more, the screen will be black or white for a moment.

Last time I checked, yes, the finger triggered zoom was not working, I'll see what I can do.

**Comment by ivmartel** [comment]
I hope the new release will fix this, closing for now, feel free to comment if you need.
