### ISSUE TITLE
Jpeg image scrolling issue

### ISSUE THREAD

**Issue by turtle-hobbit** [ivmartel/dwv#1175]
Hi! 

I have a problem with scrolling jpeg images after its been loaded by `loadURLs` method. However, when we receive dicom files no such problem appears.

Callback function `loadedEnd` calls `canScroll` method and it returns false for jpeg files and true for dicom items.

we used this file as an example: [DWV-VUE](https://github.com/ivmartel/dwv-vue/blob/master/src/components/dwv.vue)

I'm loading images with this code:
```js
const images = [
            "./wado?requestType=WADO&contentType=image/jpeg&studyUID=1.3.12.2.1107.5.1.4.60083.30000020120414114104900000284&seriesUID=1.3.12.2.1107.5.1.4.60083.30000020120414124717100073543&objectUID=1.3.12.2.1107.5.1.4.60083.30000020120414124717100073837",
            "./wado?requestType=WADO&contentType=image/jpeg&studyUID=1.3.12.2.1107.5.1.4.60083.30000020120414114104900000284&seriesUID=1.3.12.2.1107.5.1.4.60083.30000020120414124717100073543&objectUID=1.3.12.2.1107.5.1.4.60083.30000020120414124717100073958",
            "./wado?requestType=WADO&contentType=image/jpeg&studyUID=1.3.12.2.1107.5.1.4.60083.30000020120414114104900000284&seriesUID=1.3.12.2.1107.5.1.4.60083.30000020120414124717100073543&objectUID=1.3.12.2.1107.5.1.4.60083.30000020120414124717100073716",
            "./wado?requestType=WADO&contentType=image/jpeg&studyUID=1.3.12.2.1107.5.1.4.60083.30000020120414114104900000284&seriesUID=1.3.12.2.1107.5.1.4.60083.30000020120414124717100073543&objectUID=1.3.12.2.1107.5.1.4.60083.30000020120414124717100073957",
            "./wado?requestType=WADO&contentType=image/jpeg&studyUID=1.3.12.2.1107.5.1.4.60083.30000020120414114104900000284&seriesUID=1.3.12.2.1107.5.1.4.60083.30000020120414124717100073543&objectUID=1.3.12.2.1107.5.1.4.60083.30000020120414124717100073715",
]
this.dwvApp.loadURLs(images, [{name:"contentType", value:"image/jpeg"}])
```

Please help fix that or may be we're doing something wrong?

**Comment by ivmartel** [comment]
The viewer is not ready to handle multiple non dicom data, it does not know how to put them together (I get an error in the image `appendSlice` method when trying). Can't you use the dicom files instead?

**Comment by turtle-hobbit** [comment]
Thank you. I wanted to use jpeg files because of study delivery time to the client. Will wait this enhancement with next release 👍

**Comment by ivmartel** [comment]
The backlog is pretty full, if it is something you can do, I think it will be quicker!

**Comment by ivmartel** [comment]
This feature will not be worked on soon, sorry for that.
Closing for now, feel free to comment if you need.
