### ISSUE TITLE
Angular - AppendSlice not working

### ISSUE THREAD

**Issue by shahrukhwork** [ivmartel/dwv#1187]
Hi, 

I am trying to append a slice to the existing DWV object but it keeps giving me the error of different orientation, modality etc. I have tried to fix them but the appended slice is not showing up on the frontend side 

Here's the code I am using:
    
This is the slice that needs to be added:
```js
var image10 = dwv.image.getDefaultImage(
  512,
  512,
  3,
  this.dwvApp10.getImage().getBuffer(),
  this.dwvApp10.getImage().getNumberOfFrames(),
  this.dwvApp10.getImage().getImageUids()
);
```

This is the function call
```js
this.dwvApp.getImage().appendSlice(image10)
```

**Comment by ivmartel** [comment]
The code does check some tags and meta data to validate if the append is feasible, see [image.js#L430](https://github.com/ivmartel/dwv/blob/develop/src/image/image.js#L430) for details. 
For this case, can you share your original image to check on my side?

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
