### ISSUE TITLE
Axial, Coronal and Sagittal Views

### ISSUE THREAD

**Issue by albertojmarun** [ivmartel/dwv#1188]
This is question (I don't know how to put the label)

I'm trying to use the Axial, Coronal and Sagittal Views, when I set up the orientation on the dataViewConfigs I specified the orientation that I want, but it shows me only a black line.

```js
app.init({
     dataViewConfigs: {
          '*': [
               {
                    divId: 'layerGroup0',
                    orientation: 'axial',
               },
               {
                    divId: 'layerGroup1',
                    orientation: 'coronal',
               },
               {
                    divId: 'layerGroup2',
                    orientation: 'sagittal',
               },
          ],
     },
     tools: {
          Scroll: {},
     }
});
```

This is the result that I get:
![DicomWevbViewer](https://user-images.githubusercontent.com/68714499/180404689-e93fa9b4-481f-4281-9ab9-6fd2f24c88d5.png)

I already saw that there is a MPR model in test/pacs but it doesn't work whem I run npm run test

**Comment by ivmartel** [comment]
Did you just load one slice? To view more than one line in the orthogonal views, you need more than one slice.

**Comment by Arty233** [comment]
Same for multi slice view. Checked in desktop app: coronal and sagittal orientations are fine, but here I can properly see only axial view

**Comment by Arty233** [comment]
Could we assume this as a bug?

**Comment by Arty233** [comment]
Sure. Here some examples I've found in the internet
[dicoms-from-internet.zip](https://github.com/ivmartel/dwv/files/10175625/dicoms-from-internet.zip)
As desktop solutions I use Bee DICOM Viewer and 3d Slicer. Here are screenshots from the first one: 
<img width="1024" alt="beeDicomAxial" src="https://user-images.githubusercontent.com/45117812/206171689-f4f26071-334a-411d-a9e9-9ea1e3fa73c6.png">
<img width="1025" alt="beeDicomCoronal" src="https://user-images.githubusercontent.com/45117812/206171719-86ac622d-7ea9-4fc8-b3a1-558b2cf75a47.png">
<img width="1029" alt="beeDicomSaggital" src="https://user-images.githubusercontent.com/45117812/206171730-0c7ee19a-e96f-43f9-87f0-bc242a095f6e.png">
And here some examples using dwv with next config:
```
        '*': [
            {
                divId: 'layerGroup0',
                orientation: 'axial',
            },
            {
                divId: 'layerGroup1',
                orientation: 'coronal',
            },
            {
                divId: 'layerGroup2',
                orientation: 'sagittal',
            },
        ],
```
<img width="237" alt="dicomsDWV" src="https://user-images.githubusercontent.com/45117812/206172392-5e89d0d6-2b91-4259-8e40-093695f18347.png">
As you can see we are able to render only axial view, the other two render canvas with height too small to see something.
Also, I tried some your examples, changing config to render coronal or sagittal views. The result is the same: canvas line with small height

**Comment by ivmartel** [comment]
Ah, I think I know, you cannot trigger the MPR display from the first loaded slice event. You have to wait for all the data to be loaded (`load` event) so that the MPR views can be created correctly.

**Comment by Arty233** [comment]
Any examples how to do it?

**Comment by ivmartel** [comment]
Yes! This example shows how to wait for the data to be loaded and activate a render button: https://jsfiddle.net/ivmartel/5ew3t619/. Replace the data view config by yours and it should work.

**Comment by Arty233** [comment]
Still not working. Instead of using **loadURLs** I'm using **loadFiles** function. Could this be a problem?

**Comment by ivmartel** [comment]
No, both loads send the same events. 

You can also check the demo viewer of the test suite (accessible when you launch ´yarn run tests´), it has an MPR mode.

**Comment by Arty233** [comment]
Thanks, that was helpful, also, as I understood **viewOnFirstLoadItem** is very important for situations like this

**Comment by ivmartel** [comment]
Yes! This flag decides if a render is triggered on the first slice load or not. For MPR it needs to be false.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.

**Comment by ivmartel** [comment]
Here is a fiddle if it helps: https://jsfiddle.net/ivmartel/v2mrtd4e/
