### ISSUE TITLE
Maximizing the canvas

### ISSUE THREAD

**Issue by snapey** [ivmartel/dwv#1189]
Question: 

When loading an image that has, for instance, a tall aspect ratio, the canvas is set to the dimensions of the loaded image, and then when panning and zooming, the image is obviously constrained to the shape of the canvas.

If I have a large area available for the canvas, I would prefer for it to use as much space as possible, initially resizing the image to fit the bounds, but then on zooming expand out to use the available canvas

eg, on initial load;
![The_Radiology_Academy_test](https://user-images.githubusercontent.com/328747/180466182-26664656-1225-47a2-afb3-45627c82371b.png)

when zooming and panning;
![The_Radiology_Academy_test](https://user-images.githubusercontent.com/328747/180466316-4b96b16c-e133-468c-9235-b858b0d110b3.png)

Is there a method to fix the canvas size and have the image initially fit the canvas?

**Comment by ivmartel** [comment]
This behaviour was changed with the fix to #1182 (available in the next release). It should now be as you describe, using the full canvas size.

**Comment by ivmartel** [comment]
I hope this fixed your problem, closing for now, feel free to comment if you need.
