### ISSUE TITLE
Loading urls slow and ERR_INSUFFICIENT_RESOURCES occured

### ISSUE THREAD

**Issue by JasonDoingGreat** [ivmartel/dwv#1196]
I've tried using loadURLs to load a list of 800+ dicom files in a series.

**What happend**
- Loading is slow, run for 20s to 84% complete.
- At 84% point, `Failed to load resource: net::ERR_INSUFFICIENT_RESOURCES` shown in console log.

What should I do next to fix such problem, or any other solution to increase speed and loading long url list?

**Comment by ivmartel** [comment]
Check #720 for a similar problem. I'm not sure if retrieving files by batch could help.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
