### ISSUE TITLE
failure to display compressed Dicom images

### ISSUE THREAD

**Issue by ELAHETAHERI72** [ivmartel/dwv#1197]
hello,
I have problems when I tried to display some lossy dicom images.
When I try to show it, I get this error:
![image](https://user-images.githubusercontent.com/46931044/182011077-48d7711f-858c-4383-8310-80a5bc7c3150.png)

Thank you for providing a suitable solution to solve this problem : ))).
Thank you for your good team ❤

**Comment by ivmartel** [comment]
It would help if you could share the data.

**Comment by ELAHETAHERI72** [comment]
some of issues we have on this viewer is:
1.we use FellowOakDicom library for compress dicom files in server side and its causes this issue for us
     
2.some of files witch have same studyId dosen`t scroll in dwv viewer

**Comment by ivmartel** [comment]
You can send the files directly to me.

**Comment by ELAHETAHERI72** [comment]
thank you, so I send email for you

**Comment by ivmartel** [comment]
Ok, data received!

The first data loads correctly for me, it has a transfer syntax of `1.2.840.10008.1.2.​4.​91` (JPEG 2000 Image Compression). Did you include the decoding libs in your code as in [tests/pacs/viewer.js#L5](https://github.com/ivmartel/dwv/blob/develop/tests/pacs/viewer.js#L5)?

The scroll data is not working with the previous code (v0.30) but is working fine with the most recent one (future v0.31), I made some work on MPR and oriented views that may have fixed the viewer for this case.

**Comment by ELAHETAHERI72** [comment]
I use your dwv-angular library so in it this images are not displaied well.

**Comment by ivmartel** [comment]
The compressed data seem to load correctly in the dwv-angular [demo](https://ivmartel.github.io/dwv-angular/demo/stable/index.html).

**Comment by ELAHETAHERI72** [comment]
and then try this one i will send you

**Comment by ivmartel** [comment]
Did you manage to solve your issue?

**Comment by ELAHETAHERI72** [comment]
No I can't.finally we decide to use another viewer
