### ISSUE TITLE
best standard dicomparser

### ISSUE THREAD

**Issue by mohamedsharaf** [ivmartel/dwv#120]
dwv/src/dicom/dicomParser.js

i need to know if there is any open source project for dicom parser under development

**Comment by gillesdemey** [comment]
+1

I would also be interested in this, I'm currently trying to figure out how to extract it and turn it into a Node.js module that would be Browserify compatible.

That way, both Node and the browser can use the parser and we're free to choose if the browser or a service should be responsible for parsing the files.

I'm making some good progress, Im just trying to figure out where the actual image buffer is stored that I can write to the filesystem to extract the JPG images.

**Comment by ivmartel** [comment]
At the moment, the dicom parser needs to be run, then you get a dwv.image.View from it, then from the view a dwv.image.Image object and finally the buffer. As in:
```js
var dicomParser = new dwv.dicom.DicomParser();
// parse the input buffer
dicomParser.parse(buffer);
// get the dwv.image.View 
var view = dicomParser.createImage();
// get the dwv.image.Image
var image = view.getImage();
// get the buffer
var buf = image.getBuffer();
```
I'm looking at other parsers to try to standardise all this. Keep me posted with what you come up!

**Comment by gillesdemey** [comment]
That's exactly as far as I got, but writing the buffer to the filesystem yields a broken jpeg image.

I'm guessing the Image and View modules use ArrayBuffers internally? They differ from Node's buffers.

I'll play around with it and keep you posted when I have something worth sharing :)

**Comment by gillesdemey** [comment]
I've stashed my Node.js compatible version for now, and rewrote your parser in Go to get a better understanding of how the parser actually works.

https://github.com/gillesdemey/go-dicom

I justed to thank you for all the effort you put into your parser, it's very clean and readable!

**Comment by ivmartel** [comment]
I added an API wiki page: https://github.com/ivmartel/dwv/wiki/API
With dicom parser examples to get dicom tags and image!
