### ISSUE TITLE
Imaios like pin annotation

### ISSUE THREAD

**Issue by UmarNazaket** [ivmartel/dwv#1204]
How can we place Imaios like pin annotation in dwv library?

**Comment by ivmartel** [comment]
Could you share more description and/or a snapshot of what the pin looks like?

**Comment by UmarNazaket** [comment]
[https://res.cloudinary.com/umarnazaket/image/upload/v1664883003/Screenshot_239_ntqg0m.png](url)
I have added url of the Screenshot.
- We will click anywhere on slice and a pin will be generated there and we have to add the description of it.
-

**Comment by ivmartel** [comment]
![Screenshot_239_ntqg0m](https://github.com/user-attachments/assets/f679f940-197c-4fde-8ff0-df05dae7a166)
(add screenshot to avoid browsing)

**Comment by ivmartel** [comment]
Relates to #1795, follow there for updates. Closing for now, feel free to comment if you need.
