### ISSUE TITLE
separate design or html from javascript - dont use javascript new to make new elements

### ISSUE THREAD

**Issue by mohamedsharaf** [ivmartel/dwv#121]
as in title 

may use javascript template engine or better use html

sot it can be easier to change the design 

i will have search in java script template frameworks and post here 
hope you take this decision fast as kineticjs 

thanks and keep the good work

**Comment by ivmartel** [comment]
Could you show or link to some code that does not follow this principle?
I try to group the gui code in the viewer specific `appgui.js` file. From there you can override most of the html element creating code.

**Comment by ivmartel** [comment]
Hi Mohamed, not sure if you saw the latest commits but I think they go the same way as this issue. Integrating dwv in a web page is now way simpler as you can see in this fiddle: http://jsfiddle.net/ivmartel/LteeL0gf/

**Comment by ivmartel** [comment]
On the path towards clean design! See #124...
