### ISSUE TITLE
How to center the image.

### ISSUE THREAD

**Issue by ycxj** [ivmartel/dwv#1223]
Hello, excuse me, I would like to ask you how to center the picture on the canvas.
Before: 
![image](https://user-images.githubusercontent.com/37645805/191692705-e9ab96d7-724c-4e08-ae46-204ad97e359c.png)

`app.getActiveLayerGroup().fitToContainer({ x: 1000, y: 500 });`
` app.getActiveLayerGroup().draw();`
After:
![image](https://user-images.githubusercontent.com/37645805/191693729-c7070d5f-48c0-4a52-9265-ec2f06fa8852.png)

> I wanted the image to be centered and as big as possible to cover the canvas.
It looks like this.
![image](https://user-images.githubusercontent.com/37645805/191695660-444879ee-78cc-4d61-a36a-773a814e7206.png)

What should I do to achieve this effect?

**Comment by ivmartel** [comment]
Hi, which version of dwv are you using? I think it should work with the latest code, check out the demo viewer of the tests.

**Comment by ycxj** [comment]
Hi, I am using version 0.30.8

**Comment by ivmartel** [comment]
v0.31 has got some changes regarding the use of the canvas and its centering. You can try it with the latest beta (0.31.0-beta.14).

**Comment by ycxj** [comment]
Thank you very much. Changing to the latest version has solved this problem

**Comment by ivmartel** [comment]
Nice! If you are happy, can you close the issue please?

**Comment by ycxj** [comment]
I'm having another problem. When I call onResize when my window size changes, the console reports an exception 
![微信截图_20221010153233](https://user-images.githubusercontent.com/37645805/194817619-6f46ca7d-0940-48a4-8a35-cf45efeb077f.png)

**Comment by ivmartel** [comment]
Good catch, can you create another issue please for this one?

**Comment by ycxj** [comment]
Ok, I'll create a new issue

**Comment by ivmartel** [comment]
I fixed #1233. Closing this one, feel free to comment if you need.
