### ISSUE TITLE
overlapping the images when loading

### ISSUE THREAD

**Issue by shameerasl** [ivmartel/dwv#1224]
I am using dwv-jq-mobile viewer for images view. and my code is,
```js
myapp.abortLoad();
myapp.loadURLs([selected_url]);
myapp.setDrawings(draws,drawdetails);
```
and I also used
```js
myapp.reset();
myapp.loadURLs([selected_url]); 
```
here also an alert of"A load error has occured. See log for details." occured and load images without drawings. My problem is How to load mutiple images with annotations without any overlapping. 
Any reference will be a great help. Thanks in advance

**Comment by ivmartel** [comment]
The abort and/or reset are maybe not doing their job, I'll investigate.

**Comment by shameerasl** [comment]
Hi @ivmartel ,
any update on this. 
when i am using myapp.reset() function it shows alert as "A load error has occured. See log for details.".

and when I use myapp.abort() function it shows myapp.abort() is not a function.

What to do with these issues.

**Comment by shameerasl** [comment]
hi @ivmartel ,
What is the function of reset the layers? Is there any other functions instead of reset and abort. I Tried myapp.abortLoad() function but no changes reflected. Thanks in advance

**Comment by ivmartel** [comment]
Just tested this, calling a `app.abortLoad()` and then a `app.reset()` seem to do the job.
If by no overlapping, you mean not seeing some layers, you can play with their opacity.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
