### ISSUE TITLE
Zip file not opening.

### ISSUE THREAD

**Issue by AbdulrahmanAlobaidy** [ivmartel/dwv#1226]
Hi, I was trying to import a DICOM ZIP file that opens up correctly with the **dwv-jqui** version, but when I tried to import it using the `loadURLs` method it throws the following error message: `Uncaught (in promise) RangeError: offset is out of bounds`, files such as those provided with the JSFiddle examples are opening correctly, I tried importing all the JavaScript files in the **dwv-jqui** version into my project just in case I was missing something but it kept displaying the same error message.

This is what I am starting with:
```js
var app = new dwv.App();

var tools = {
	Scroll: {},
	Draw: {
		options: ['Arrow'],
		type: 'factory'
	}
};

app.init({
  dataViewConfigs: {'*': [{divId: 'layerGroup0'}]},
  tools
});

app.addEventListener('load', function () {
  app.setTool('Draw');
  app.setDrawShape('Arrow');
});

app.loadURLs([
	'http://someurl.com/Anonymized_20220917.zip'
]);


var range = document.getElementById('sliceRange');
range.min = 0;
app.addEventListener('loadend', function () {
  range.max = app.getImage(0).getGeometry().getSize().get(2) - 1;
});
app.addEventListener('slicechange', function () {
  var lg = app.getLayerGroupById(0);
  var vc = lg.getActiveViewLayer().getViewController();
  range.value = vc.getCurrentPosition().k;
});
range.oninput = function () {
  var lg = app.getLayerGroupById(0);
  var vc = lg.getActiveViewLayer().getViewController();
  var index = vc.getCurrentIndex();
  var values = index.getValues();
  values[2] = this.value;
  vc.setCurrentIndex(new dwv.math.Index(values));
}
```

**Comment by ivmartel** [comment]
Do the files load when not zipped?

**Comment by AbdulrahmanAlobaidy** [comment]
Yes, they do load when unzipped, but only in the demo, not in my code.

**Comment by AbdulrahmanAlobaidy** [comment]
Hi, this is the ZIP file
<https://doc-10-48-docs.googleusercontent.com/docs/securesc/p3i0nvhnp1v0gui4i787vu7idtattnq6/fpf4mrtnr6on08ucuf1tvdon2723me8p/1664343150000/01242323117592524924/01242323117592524924/17URwq5OSoyAMQnWX7LcDdh9ClnmNyFpi?e=download&authuser=0>
that I am working with in case you want to inspect it closely.

**Comment by ivmartel** [comment]
Can you try with the latest beta (0.31.0-beta.14)? It does work for me. The new version has an updated dictionary that may be the cause of your error.

**Comment by AbdulrahmanAlobaidy** [comment]
Thankfully, the problem was solved, it turned out that the decoders weren't being loaded properly for some reason.

I have another problem though, the measurement units aren't being displayed when drawing, are they optional?

how could I get them to be displayed?

I will open another issue for this one.
