### ISSUE TITLE
Angular - AppendSlice not working

### ISSUE THREAD

**Issue by HamzaPooki** [ivmartel/dwv#1232]
Hello. I am trying to append a single slice into my original image but it is giving me this error
RangeError: offset out of bounds
Can you please help me with this error?
Using 0.30.8 version of dwv

**Comment by HamzaPooki** [comment]
@ivmartel can you please help me with this issue as soon as possible?

**Comment by ivmartel** [comment]
The slice you are adding has the good dimensions? Maybe the storage is different (8-16bits), so when dwv tries to allocate memory ([image.js#L379](https://github.com/ivmartel/dwv/blob/v0.30.8/src/image/image.js#L379)), it does not get the numbers right.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
