### ISSUE TITLE
An exception was caught when onResize was called

### ISSUE THREAD

**Issue by ycxj** [ivmartel/dwv#1233]
When I call onResize when my window size changes, the console reports an exception (dwv-0.31.0-beta.14)

![微信截图_20221010153233](https://user-images.githubusercontent.com/37645805/194829104-1da27d08-ff15-4095-b3ef-ed7fcdaa3a47.png)

**Comment by ivmartel** [comment]
Confirmed, I have to fix it!

**Comment by ivmartel** [comment]
Fixed in f9c952c.
