### ISSUE TITLE
plugin development

### ISSUE THREAD

**Issue by eugenem** [ivmartel/dwv#1242]
Hi! 

If I'll want to integrate DVW into React app and add more tools there, like more filters, more drawing tools, etc.

Is it possible to attach modules from outside, or will I have to fork the project and add them directly to the source?

**Comment by ivmartel** [comment]
The idea for dwv is to be flexible, tools can be added during the dwv initialisation, there should be no need to modify the core code. Happy to help if some 'hooks' are missing!
