### ISSUE TITLE
How can I display the meta-data for the particular slice that I am viewing?

### ISSUE THREAD

**Issue by LeoReubelt** [ivmartel/dwv#1254]
I am using dwv in a react site. 

I load an array of dicom files using the following...

```
    const loadDWVApp = () => {
        const app = new dwv.App();
        app.init({
            dataViewConfigs: { '*': [{ divId: props.seriesUID + props.divModifier }] },
            tools: tools,
        });

        appRef.current = app;

        setupRequiredEventListeners(app);

        if (props.enableTools) {
            setupToolEventListenersForDWVApp(app);
        }

        app.loadFiles(props.files);
    };
```
And when I scroll through the slices, I would like to be able to display the meta data for the slice that the user is on.
But I don't know how to determine the slice that is currently being viewed.

If I log the renderstart or renderend events, i see that is has a layer and an index. But they are always the same. The layer ids are always layer-0-0 and the data index is always 0. So I don't know how to determine what slice I am on.
{type: 'renderstart', layerid: 'layer-0-0', srclayerid: 'layer-0-0', dataindex: 0}

**Comment by ivmartel** [comment]
The library stores the meta data with the image. You can access it with `app.getMetaData(index)`, index being the one of the data that you can find the event object of a `loadend` event.
If there are multiple slices, the meta data is merged. Tags that have different values will become arrays indexed with the instance number.

**Comment by LeoReubelt** [comment]
so, if i am understanding correctly, if i use `app.loadFiles(props.files);` and props.file.length is greater than one, and i use the included mouse base tool for scrolling,  i have no way of knowing which tag value to use for those tags with different values. is that true?

**Comment by LeoReubelt** [comment]
Thanks for the response. So if i understand correctly...
- If i load a dicom series using `app.loadFiles(props.files);` and props.files.length > 1.
- And i use the mouse controls to scroll through slices.
- I have no way of knowing the index of the slice that i am on.
- And therefore have no way of knowing which value to use for those tags that have different values for each slice.

Or is there a way that I can get the index of the slice that I am currently on?

**Comment by LeoReubelt** [comment]
Oh. I think i get it. I can get the index using...
```
const vc = lg.getActiveViewLayer().getViewController()
const index = vc.getCurrentIndex(); 
```
and taking the last position. is that correct?

**Comment by ivmartel** [comment]
Uhm, the index used to merge the meta data of different slices is the dicom tag `InstanceNumber`. This number is different from the slice position `k` that you get from the current index `[i, j, k]`. Do you really need access to the slice specific tags, displaying the merged ones is not enough?

**Comment by ivmartel** [comment]
I hope you solved your problem, closing for now, feel free to comment if you need.
