### ISSUE TITLE
Window and scroll tool not working on one data series.

### ISSUE THREAD

**Issue by LeoReubelt** [ivmartel/dwv#1258]
I have been using DWV to make a dicom viewer. And I am using the provided tools for scroll and window. They work great for most files. But the files below do not work. Window works with a single file, but not when two or more are added. And scroll works with 2 files, but gets stuck with 3, and does not work at all with 4. I tested this with https://github.com/ivmartel/dwv-react to make sure it wasn't something that I was doing wrong. A sample of the files are in the archive below.
[Archive.zip](https://github.com/ivmartel/dwv/files/9951469/Archive.zip)

**Comment by ivmartel** [comment]
:thinking: not sure what is happening, but it seems fixed in the latest code (future v0.31.0), check it there: [dwv-jqmobile/demo/trunk](https://ivmartel.github.io/dwv-jqmobile/demo/trunk/index.html)

**Comment by LeoReubelt** [comment]
thanks @ivmartel
