### ISSUE TITLE
select the draw from fetched image

### ISSUE THREAD

**Issue by shameerasl** [ivmartel/dwv#1260]
Hi @ivmartel ,
what is the function calling for select the draw in dwv jqmobile viewer.I wanted to select and edit the draw which is fetched from db with annotations, but I cant select it normally. After one draw I can able to select the others. so I want to implement the select function first. Hope you can direct to me for this particular issues. Thanks in advance.

**Comment by ivmartel** [comment]
You mean that once you have fetched and displayed a draw, you want to manually edit it in the viewer? You can't select it how you do from a recently created draw?

**Comment by shameerasl** [comment]
Yes. I wanted to manually edit the annotation in the viewer that once i fetched the image.
How to do this?

**Comment by shameerasl** [comment]
Hi @ivmartel ,
    What is the select event in dwv jqmobile viewer. when the select function is called even after the draw and what is the function name?

**Comment by shameerasl** [comment]
Hi @ivmartel ,
 I understood that on mouse down event the selection and draw is updated. That is When I opened a viewer and select Draw, 
 the Annotation is drawn(the event called is mousedown). then I save this in to my Database.
After some time I retrieve the Image and set the Drawings Through 

myapp.loadURLs([selected_url]);
myapp.setDrawings(draws,drawdetails);

 After that I wish to edit the draw and click the mouse(mousedown), it will again start to draw.
What I wanted instead of this is to select the shape(setShape or setAnchors on)

How to get this?

**Comment by ivmartel** [comment]
Hi, ok, you are right, it seems it is not possible to select a pre loaded draw. I'll look into it.

**Comment by shameerasl** [comment]
@ivmartel Thank you for your response. Hope you may help me to resolve problem.

**Comment by ivmartel** [comment]
Sorry, not much progress on this one...
Regarding changing the label, once loaded you can try a `app.updateDraw`.

**Comment by ivmartel** [comment]
The problem should be fixed with my last commit. Feel free to comment if it is still there.
