### ISSUE TITLE
Using draw events

### ISSUE THREAD

**Issue by ehzan** [ivmartel/dwv#1261]
Hi
I want to apply draw events (drawcreate, drawchange, etc), but unfortunately it doesn't work.
I'm using dwv-0.30.8 and my code is like:

```js
var app = new dwv.App();
app.init({
    dataViewConfigs: {"*": [{divId: "id0"}]},
    tools: {
        WindowLevel: {},
        Draw: {options: ["Ruler"], type: "factory"},
    },
});
app.addEventListener('load', function () {
    app.setTool('Draw');
    app.setDrawShape('Ruler');
    {#app.setTool('WindowLevel');#}
});
app.addEventListener("drawcreate", function () {
    console.log("drawcreate");
});
```

**Comment by ivmartel** [comment]
You need to specify the events with the tool configuration in the options passed to the app init. Something like this:
```js
Draw: {
  options: shapeList,
  type: 'factory',
  events: ['drawcreate', 'drawchange', 'drawmove', 'drawdelete']
}
```
It is a bit hidden, I'll update the documentation!

**Comment by ivmartel** [comment]
I created #1269 to simplify this. It should land in v0.31.

**Comment by ehzan** [comment]
Merci beaucoup

**Comment by ivmartel** [comment]
Ok. closing for now, feel free to comment if you need.
