### ISSUE TITLE
Viewers cannot read all the dicom files and stuck in the middle of process 

### ISSUE THREAD

**Issue by ycxj** [ivmartel/dwv#1274]
hello,
There is a problem that often happen on the loading progress on more than 10+ url files, it stucked in middle of process when I try to render DICOM, and the process cannot be completed wtih no error occurs.  

All the url files are downloaded and viewed in chrome's devTools. 

![image](https://user-images.githubusercontent.com/37645805/205209351-b564ec14-5095-4385-99e7-76bbe8bb2ed8.png)

In my investigation, 
when I press "Noraml Refresh" the page,  it doesn't load properly.

![image](https://user-images.githubusercontent.com/37645805/205208593-3dfc6867-3645-4bb9-bc86-a719d5ab8f7e.png)

![image](https://user-images.githubusercontent.com/37645805/205211084-6aadb637-d1ee-4ed9-8338-7d7e3da8d274.png)

However, when I press "Hard Refresh" & Emtry Cache & Hard Refresh" the page,  the viewer load normally.

![image](https://user-images.githubusercontent.com/37645805/205208895-b8f96ac9-8c69-4a3d-a57b-c9d4ff56643c.png)

![image](https://user-images.githubusercontent.com/37645805/205211113-96ce5ce2-7f4a-4a3b-b4e7-444e5237c823.png)

**Comment by ivmartel** [comment]
When it gets stuck, does it give an error or just stays idle?

**Comment by ivmartel** [comment]
Closing for now because of inactivity... Feel free to comment if you need.
