### ISSUE TITLE
load and unload state.json file

### ISSUE THREAD

**Issue by s-hammad-a** [ivmartel/dwv#1293]
Hello, I have a question. I have two different state.json files saved for same DICOM file. if I load one file it shows the saved drawings then if I load second file it shows drawings saved in both of them. But I want to unload previous state.json file before loading another. Is this possible without reinitializing the app or reloading the dicom file? If yes can you share an example? Thank you in advance.

**Comment by s-hammad-a** [comment]
@ivmartel please reply.

**Comment by ivmartel** [comment]
I'm sorry, there is no such functionality... You have to reload the dicom and the state with the current code. To implement it, you have to call `drawController.reset()` before loading the state to start from a clean one.

**Comment by s-hammad-a** [comment]
@ivmartel can you show an example of how to use state.json and app.setDrawings() functions to display drawings?

**Comment by ivmartel** [comment]
Sorry for the late answer. You have to pass through the active layer, something like `app.getActiveLayerGroup().getActiveDrawLayer().getDrawController()`.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
