### ISSUE TITLE
Require canvas to run as a node module

### ISSUE THREAD

**Issue by RafaelBravo97** [ivmartel/dwv#1294]
Hi, when I try to use dwv as a node module, it throws me the following error:
```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'canvas'
```

This could be fixed by installing canvas with `npm install canvas`, but I'm not sure if this is a correct solution.

**Comment by ivmartel** [comment]
Yes, that's ok, it is a dependency of Konva (the drawing library).

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.

**Comment by arturojain** [comment]
As of my latest tests konva is not installing canvas, so it creates an error that Canvas is required.

**Comment by gams123** [comment]
The error message you're seeing suggests that the `canvas` module is missing, which is a dependency of the `dwv` library. Installing `canvas` with `npm install canvas` should fix the issue.

`canvas` is a Node.js module that provides a way to create and manipulate images using an HTML canvas-like API. The `dwv` library uses `canvas` to render DICOM images in the browser with the HTML5 canvas element.

So, installing `canvas` with `npm install canvas` is a correct solution to fix the error you're seeing. After installing `canvas`, you should be able to use the `dwv` library as a Node module without any issues.

**Comment by arturojain** [comment]
Correct, but this should be documented in the installation or maybe being added to the dependencies so it is auto-installed?
