### ISSUE TITLE
Transform image

### ISSUE THREAD

**Issue by semakmillev** [ivmartel/dwv#1306]
Hi!
I m trying to rotate/flip/ image (apply transformation), but cannot find out, how to do it. Yes, i can access directly to canvas using querySelector etc, but i dont think that it is right way to do it.

**Comment by ivmartel** [comment]
The library does not provide methods for rotation nor flip of the image, you have to manipulate the inner buffer for that. If this is just for viewing purposes, I would say that it is ok to just play with the canvas.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
