### ISSUE TITLE
Review pdf.js jpeg2000 support

### ISSUE THREAD

**Issue by ivmartel** [ivmartel/dwv#131]
Work has been done to fix JPEG 2000 support for the DICOM subset in jpx.js (see mozilla/pdf.js#5725). It should be reviewed and compared with the currently used [j2k.js](https://github.com/kripken/j2k.js) (openjpeg) lib.

**Comment by louismullie** [comment]
I haven't actually benchmarked this, but the speed doesn't even compare - I'm thinking almost an order of magnitude faster with JPX.js

**Comment by ivmartel** [comment]
Ok, compared and confirmed. Using code from [pdf.js](https://github.com/mozilla/pdf.js/releases/tag/v1.1.1) v1.1.1 and [jpx-medical](https://github.com/jpambrun/jpx-medical) latest (fcaf281).

**Comment by louismullie** [comment]
Nice! this will be a great addition

**Comment by ivmartel** [comment]
Note: DWV support for JPEG2000 started at #62.
