### ISSUE TITLE
RTStruct Orientation

### ISSUE THREAD

**Issue by LeoReubelt** [ivmartel/dwv#1310]
First of all. Thanks for doing this. Good work.

I am trying to overlay RTStruct contours on the Dicom slices. And, while it is working pretty well, the Image Plane calculations are proving difficult (Image Position (Patient): (0020,0032), Image Orientation (Patient): (0020,0037), Slice Location: (0020,1041), Pixel Spacing: (0028,0030)). And I wanted to know if there was existing functionality that would take the raw contour points and convert them to the view coordinate space so they align properly with the rendered slice image. I am looking at functions like getOrientedXYZ(values) → {object} but i am not sure what to use or how to use it.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
