### ISSUE TITLE
Cannot see small Dicom Files, getting the following message in log 

### ISSUE THREAD

**Issue by Heli-Shamay** [ivmartel/dwv#1317]
When the loaded files are too small, I'm getting the following message in log , and the Image is not loaded into the viewer 
![image](https://user-images.githubusercontent.com/124562809/221873979-9ac54ade-1425-45fa-a7f6-d230a6869e7a.png)

**Comment by ivmartel** [comment]
Can you share the data?

**Comment by ivmartel** [comment]
Closing for now because of inactivity. Feel free to comment if you need.
