### ISSUE TITLE
Is there no startOffset&endOffset in the latest version?

### ISSUE THREAD

**Issue by hellocxj** [ivmartel/dwv#1326]
When I update the latest version, startOffset & endOffset cannot be found, below is how I use it
dcmParser.dicomElements[key].startOffset, this.dcmParser.dicomElements[key].endOffset
Can you help me solve the above problem? Thans advance.

**Comment by ivmartel** [comment]
Yes, `startOffset` and `endOffset` were removed from the tag element object. I now recalculate the offsets when writing since they can vary according to tag change/removal and possible character set change.

**Comment by hellocxj** [comment]
Used to encode and decode strings, for example: patientadmin.
my code :
vl = bufferToString(file.rawData.slice(this.dcmParser.dicomElements[key].startOffset, this.dcmParser.dicomElements[key].endOffset), this.dcmParser.dicomElements[key].vl, charset)
            file[element_dic[2]] = vl;

**Comment by hellocxj** [comment]
this.dcmParser.dicomElements[key].startOffset,   Now, 'startOffset' can not be found, can u tell me how to solve it?

**Comment by ivmartel** [comment]
The `dicomElements[key].value` gives you the character set decoded value of the tag. Is that what you are looking for?

**Comment by ivmartel** [comment]
I hope my answer helped. Closing for now, feel free to comment if you need.
