### ISSUE TITLE
VR type "US or OW"

### ISSUE THREAD

**Issue by bstiffler582** [ivmartel/dwv#1330]
I have a DCM file that contains VRs of type "US or OW". If I add a condition in the 'interpretElement' function to simply detect this type and default it to one or the other, the viewer works appropriately. Otherwise it will throw the "Unknown VR" warning and the viewer is not rendered. Perhaps other viewers address this type explicitly, or have a fall through condition which will default to US/OW?

Thank you!
Brandon

**Comment by ivmartel** [comment]
Not sure for the writing part... @bstiffler582, if you can share the data, I'm interested!
