### ISSUE TITLE
White circle around some scans

### ISSUE THREAD

**Issue by louismullie** [ivmartel/dwv#135]
Some scans have a "white circle" around them when loaded into DWV. Unfortunately I couldn't reproduce with any publicly available scans. Any ideas as to what may be causing this?

![image](https://cloud.githubusercontent.com/assets/681636/6653694/403a15fc-ca72-11e4-9f86-838f72a11958.png)

**Comment by ivmartel** [comment]
It could be a signed/unsigned data problem, what is the value of the PixelRepresentation tag? Another possible problem could be with the RescaleSlope and RescaleIntercept, what are they?

**Comment by louismullie** [comment]
RescaleIntercept -1024 
RescaleSlope 1
PixelRepresentation 1

I have 3 working scans and 3 others that are not working. All of them have the same values for the above fields. Any other ideas?

**Comment by louismullie** [comment]
I can also send an anonymized version of a scan that doesn't work if that's helpful.

**Comment by ivmartel** [comment]
Yes please!

**Comment by louismullie** [comment]
Issue was caused by other intervening code outside of DWV. Closing.
