### ISSUE TITLE
Add & toggle shapes/drawings programmatically

### ISSUE THREAD

**Issue by beckmarc** [ivmartel/dwv#1363]
I'm currently developing an application to view brain scans and need to show areas where a stroke is suspected to be. I have multiple AI models that produce different results so I need to be able to programmatically toggle them on or off. I'm using angular-dwv to be more specific. 

My first approach would be to create a custom shape that connects some points to enclose a specific area of interest. However, I have to say that I really struggle with understanding the documentation. My main issue is that I don't know what all methods and classes do and how they are interconnected since there is no linking with parameters and return types. The examples also hardly scratch the surface about what's possible. 

Can someone give me some advice how I can better understand the library? Also if anybody could simply show me how to create a simple shape like a Line and how to add this to a dwv.App object it would be really great.

**Comment by ivmartel** [comment]
Draw shapes come from Konva, check out their doc to understand how to create one (for example the [line tutorial](https://konvajs.org/docs/shapes/Line_-_Simple_Line.html)). dwv can then load the shape from a `state.json` file.

Regarding types, I'm working on it! See #669

Related (?): #1366

**Comment by beckmarc** [comment]
@ivmartel Yes, I think that #1366 and me are trying to accomplish the same task which is adding annotated regions to the dicom viewer. Maybe that is an idea for a new feature? Would be really handy to highlight certain regions on the dicom viewer and modify them programmatically.

**Comment by beckmarc** [comment]
I have serval AI models that predict wether a stroke is present based on a NCCT image or not. In addition, my team has created explainable AI models that show the important regions for the AI to make this decision. These results we want to present to the user by overlaying them on the original image. Like here e.g.


![1CanonMedicalAutoStrokeAPNoncontrastCTASPECTS](https://github.com/ivmartel/dwv/assets/61294771/aae8b998-69c8-402c-a9a8-6f9021dfac40)

The representation of the highlighted areas is not fixed though. The backend just returns a mask which I can use to calculate the highlighted regions on the dicom viewer.

**Comment by beckmarc01** [comment]
That's just an example image I searched to illustrate what I mean but yes in essence that's it. So showing the activated regions (with different levels of importance maybe) and the possibility to load them and toggle them on or off.

**Comment by ivmartel** [comment]
Konva shapes then seem more appropriate. Check out this demo [viewer](https://ivmartel.github.io/dwv-jqmobile/demo/stable/index.html?input=https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dbbmri-53323851.dcm%26file%3Dbbmri-53323707.dcm%26file%3Dbbmri-53323563.dcm%26file%3Dbbmri-53323419.dcm%26file%3Dbbmri-53323275.dcm%26file%3Dbbmri-53323131.dcm&dwvReplaceMode=void), you can draw shapes on the image and then change some of their properties from the draw list page (pencil icon in the top tool bar).

**Comment by MehmetStead** [comment]
we would like to draw programmatically, using the API? any examples for this?

**Comment by ivmartel** [comment]
Check out the state tests, they contain example states: https://github.com/ivmartel/dwv/tree/develop/tests/state
