### ISSUE TITLE
setCurrentIndex(index, silent) → {boolean} does not change image.

### ISSUE THREAD

**Issue by LeoReubelt** [ivmartel/dwv#1364]
I am setting the the current index using the following...

```js
const vc = dwvAppRef.current.getActiveLayerGroup().getActiveViewLayer().getViewController();
const index = vc.getCurrentIndex();
const values = index.getValues();
values[2] = sliceNumber;
vc.setCurrentIndex(new dwv.math.Index(values));
```

And so far it has been working. But I have a series where it doesn't. When I use setCurrentIndex, the image does not change at all. But in Osirix it changes as expected.

If I replace `vc.setCurrentIndex(new dwv.math.Index(values));` with `vc.setCurrentIndex(new dwv.math.Index([sliceNumber, sliceNumber, sliceNumber]));` it seems to work correctly. 

So my questions are... Why is that? How do I know I have to do that?
I have also tried changing the x or y alone. That also did not work.

**Comment by ivmartel** [comment]
Your code is the same as in the scroll second example (see [scroll doc](https://ivmartel.github.io/dwv/doc/stable/dwv.tool.Scroll.html#Scroll)). Not sure what is happening with this data, can you share it?

**Comment by LeoReubelt** [comment]
[En_Ankle_2023_010.zip](https://github.com/ivmartel/dwv/files/11487539/En_Ankle_2023_010.zip)

thanks for looking at this.

**Comment by ivmartel** [comment]
It is working for me with the latest code and I think it should work with v0.31. The data has 30 slices, so a `sliceNumber` in a [0, 29] range should work.

**Comment by LeoReubelt** [comment]
thanks @ivmartel. i am on 0.30.8. i will upgrade and see if it fixes it.

**Comment by LeoReubelt** [comment]
yes. that does fix it. thanks.
