### ISSUE TITLE
Error: Cannot append a slice with different number of columns

### ISSUE THREAD

**Issue by srivastavadevesh124** [ivmartel/dwv#1365]
I am trying to upload multiple .dcm (dicom) files to dwv-react demo site locally [https://github.com/ivmartel/dwv-react](url) but this is only showing me one file not the others . throwing this error whenever i am trying to upload my files . here are the error screenshots provided :- 
![image](https://github.com/ivmartel/dwv/assets/119391602/68e7346c-7b3c-4a65-bb44-8821e7646e49)
![image](https://github.com/ivmartel/dwv/assets/119391602/e54c5c67-5a3c-4c12-9a1b-0902587ace6e)

[Breast-20230508T050826Z-001.zip](https://github.com/ivmartel/dwv/files/11459199/Breast-20230508T050826Z-001.zip)
here is the dcm files zip folder , you can try and see .

**Comment by ivmartel** [comment]
The 'Cannot append a slice with different number of columns' would suggest you are trying to load unrelated data, for example different series. Since the images do not have the same size, dwv does not know how to display them.
