### ISSUE TITLE
Dicom meta data

### ISSUE THREAD

**Issue by ychyss** [ivmartel/dwv#1407]
I used version 0.31.0 before,  I got the meta data by `this.dwvApp.getMetaData(0)`, and it is a object with 'PatientName' key while '00100010' key.

so how can I get the this kind of object in 0.32.0? I just want to access by name, not group & element number.

**Comment by ychyss** [comment]
i know it is easy to transform the array in dwv-vue example, but why remove that object or function?

**Comment by ychyss** [comment]
i found the `getMetaDataWithNames ` function in test/pacs/viewer.js, I suggest add it into App because App has function `getMetaData(index)`

**Comment by ivmartel** [comment]
Hi, the idea for now is to return something as close as possible as DICOM-json. I let the clients restructure it according to their needs while providing tools such as the `Tag` class (used in the test/pacs/viewer.js `getMetaDataWithNames`) that help finding tag details.
