### ISSUE TITLE
How to compute statejson properties

### ISSUE THREAD

**Issue by isreeshna** [ivmartel/dwv#1408]
stateJson has drawingDetails and drawings as properties. Inside this each properties they have surface, scaleX, scaleY, shadowOffsetX, shadowOffsetY. How all these are computed manually?

**Comment by ivmartel** [comment]
These look like Konva shape properties, you'll have to check their code. dwv adds a `meta` property to the text objects to allow for the display of some quantification such as the surface of a rectangle for example.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
