### ISSUE TITLE
Unable to set current index after selecting draw tool and changing orientation.

### ISSUE THREAD

**Issue by LeoReubelt** [ivmartel/dwv#1430]
When I select the draw tool using...
```js
dwvAppRef.current.setTool(`Draw`);
setDrawingFeatures(`Ruler`);
```

And then change the orientation using...
```js
dwvAppRef.current.setDataViewConfig({
    '*': [
        {
            divId: divContainerId,
            orientation: props.dicomViewOrientation?.orientation.toLowerCase(),
        },
    ],
});
```

And then try to change the slice with...
`vc.setCurrentIndex(new dwv.Index(values));`

I get the following error....
`TypeError: Cannot read properties of undefined (reading 'getDrawController')`

I have tried calling `dwvAppRef.current.reset()` before or after changing the orientation, but could not get the images to display after reset. Even if I reloaded the files.

After changing the orientation, if I log `dwvAppRef.current?.getActiveLayerGroup()?.getActiveViewLayer()`, it is undefined.

I think this is how it happens...
I call `App.setTool('Draw')`.
`setTool` calls `setSelectedTool(name)` in toolboxController.js.
`setSelectedTool(name)` calls `selectedTool.activate(flag)` in draw.js.
`activate(flag)` calls `updateDrawLayer(layerGroup)` in draw.js.
`updateDrawLayer(layerGroup)` calls `activateCurrentPositionShapes(visible, layerGroup) `in draw.js. 
`activateCurrentPositionShapes(visible, layerGroup)` contains the line... `const drawController = layerGroup.getActiveDrawLayer().getDrawController()`;
But after setting the orientation, layerGroup is undefined and the error is thrown.

So is there a way that I can fix this?

**Comment by ivmartel** [comment]
Looks very similar to #1423

**Comment by LeoReubelt** [comment]
yes. ok. thanks. i will close this.
