### ISSUE TITLE
Drawing shapes from coordinates

### ISSUE THREAD

**Issue by FlorianChavernac** [ivmartel/dwv#1435]
I have DICOM files as well as files exported from Materialise Mimics (3D medical image segmentation software). I'd like to know whether and how I can draw shapes from vectors or coordinates. I'd like to display masks over the viewer corresponding to the segmentation performed on the software.

**Comment by ivmartel** [comment]
Your question is similar to #1363, check it out and tell me how it goes.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.

**Comment by MehmetStead** [comment]
I am also trying to do this, and I need an example, just need to draw a simple line using the z- coordinate. This seems to be an extremely complex procedure

**Comment by ivmartel** [comment]
I answered your same question in #1363

**Comment by MehmetStead** [comment]
@ivmartel I have also solved this problem, myself, you can also do it without the states, by getting the konvoLayer object, now I have another question: https://github.com/ivmartel/dwv/issues/1580
