### ISSUE TITLE
Active layer group

### ISSUE THREAD

**Issue by ychyss** [ivmartel/dwv#1449]
I notice that `src/gui/stage.js` return the active layergroup by `getActiveLayerGroup`. But I cannot change the current active one and it don't fire the events like 'active-lg-change'...

I use multi layergroups in my project. But I cannot notify the control buttons when user change into different layergroups. They display different data, so I need different status of my buttons.

Could you consider about that?  some function like `setActiveLayergroup` and event loops. :-)

**Comment by ivmartel** [comment]
Seems reasonable, check out #1455 for progress.
