### ISSUE TITLE
What goes into the calculation of getCurrentPosition()?

### ISSUE THREAD

**Issue by LeoReubelt** [ivmartel/dwv#1451]
When I use `veweController.getCurrentPosition()` i get 3 values. One of the components aligns with image position patient, but the others do not.  So what are the other two values?

**Comment by ivmartel** [comment]
`Image Position (0020,0032) specifies the x, y, and z coordinates of the upper left hand corner of the image` ([ref](https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.2.html#sect_C.7.6.2.1.1)). The current position is the point at which the viewer has been set by tools such as the mouse click of the Scroll tool. So yes, the `z` will match but not the others if you click at another position than the top left.

**Comment by LeoReubelt** [comment]
Thanks. That makes sense.
