### ISSUE TITLE
Photometric Interpretation RGB dcm is Abnormal display

### ISSUE THREAD

**Issue by wangwangliu** [ivmartel/dwv#1452]
A few dicom files generated by post-processing workstation are displayed abnormally, but they are displayed normally by RadiAntViewer tool.
![8F3D7722-0198-45D3-8AF4-7280E33363C0](https://github.com/ivmartel/dwv/assets/6262259/344c9cfd-89ca-41f8-8716-c982fa03e8bc)
source file:
[000004.zip](https://github.com/ivmartel/dwv/files/12117502/000004.zip)

thx

**Comment by ivmartel** [comment]
It seems the viewer has problems with your data, if you found a solution, I'm interested!

**Comment by wangwangliu** [comment]
> It seems the viewer has problems with your data, if you found a solution, I'm interested!

I changed the imageFactory.js file
<img width="853" alt="32B34A02-AAC5-4497-B32B-E14C65F21C76" src="https://github.com/ivmartel/dwv/assets/6262259/2b2adf22-dc75-485e-9be1-3656f0d32d21">

**Comment by wangwangliu** [comment]
Sorry i use cornerstoneWADOImageLoader。Here's how I changed it
![Uploading 1690337652853.jpg…]()
![Uploading 1690337744063.jpg…]()

**Comment by wangwangliu** [comment]
Sorry i use cornerstoneWADOImageLoader。Here's how I changed it
![1690337652853](https://github.com/ivmartel/dwv/assets/6262259/adbc9023-9c63-4e25-81da-10364b5f8497)

**Comment by ivmartel** [comment]
The problem is not the planar configuration but the orientation of the image. The orientation matrix is of a coronal plane that dwv seems to have problems with.

Relates to #1459.
