### ISSUE TITLE
Question about measurement when using multiplanar reconstruction.

### ISSUE THREAD

**Issue by LeoReubelt** [ivmartel/dwv#1458]
I am using the draw, measure tool in a viewer that I am working on. It works great. But when I reorient the series as shown below, I don't understand the measurements.

I reorient using...
```js
dwvAppRef.current.setDataViewConfig({
  '*': [
    {
      divId: divContainerId,
      orientation: orientation,
    },
  ],
});
```

And then when I measure, I get the following...
![Screenshot 2023-07-26 at 7 57 13 AM](https://github.com/ivmartel/dwv/assets/7289094/d5778192-fcb3-4ed9-975a-03a9887a9723)

But the 33.97 dimension is too small for the aspect ratio of the image. So I just wanted to know if that number is reflecting something else. 

I have a pointer x,y display that i had a similar issue with. And I ended up multiplying the position by slice thickness over pixel spacing to bring it into alignment with the image aspect ratio. But I don't know if this is as intended or not. 

In any case, for our purposes, I would like to change that dimension. Is there a way that I can change the calculated value? Or can I make my own measurement tool?

**Comment by LeoReubelt** [comment]
Thanks @ivmartel . I think i am on the latest version. 0.32.1?

**Comment by ivmartel** [comment]
Yes please, the develop branch.

**Comment by ivmartel** [comment]
Closing for now, I hope the current code fixed your problem. Feel free to comment if you need.
