### ISSUE TITLE
Image offset and oriented incorrectly

### ISSUE THREAD

**Issue by LeoReubelt** [ivmartel/dwv#1459]
I have attached a series that I am testing with. When I open it, the image is oriented offset incorrectly. When I load the files, the screen is blank. But if I zoom out, eventually, it shows up. This file used to work in a previous version of dwv.
[dicom_test.zip](https://github.com/ivmartel/dwv/files/12195153/dicom_test.zip)

**Comment by ivmartel** [comment]
I need to check the flips the code does when creating a view (see [application.js#L1552](https://github.com/ivmartel/dwv/blob/develop/src/app/application.js#L1552)), its logic does not seem to handle your data...

**Comment by LeoReubelt** [comment]
If I comment out that entire section (shown below) the image shows up in the correct location and correct orientation, but when I zoom, it flips. Does that indicate anything to you? Commenting it out only removes `layerGroup.flipScaleZ()`.

`    // extra flip offset for oriented views...
    // if (typeof dataViewConfig.orientation !== "undefined") {
    //   if (majorIndex === 2) {
    //     // flip offset Y for axial aquired data
    //     if (dataViewConfig.orientation !== "axial") {
    //       viewLayer.addFlipOffsetY();
    //       if (typeof drawLayer !== "undefined") {
    //         drawLayer.addFlipOffsetY();
    //       }
    //     }
    //   } else if (majorIndex === 0) {
    //     // flip offset X for sagittal aquired data
    //     if (dataViewConfig.orientation !== "sagittal") {
    //       viewLayer.addFlipOffsetX();
    //       if (typeof drawLayer !== "undefined") {
    //         drawLayer.addFlipOffsetX();
    //       }
    //     }
    //   }
    // }

    // view layer scale
    // only flip scale for base layers
    // if (isBaseLayer) {
    //   if (typeof dataViewConfig.orientation !== "undefined") {
    //     if (majorIndex === 0 || majorIndex === 2) {
    //       // scale flip Z for oriented views...
    //       layerGroup.flipScaleZ();
    //     } else {
    //       viewLayer.setScale(layerGroup.getScale());
    //       if (typeof drawLayer !== "undefined") {
    //         drawLayer.setScale(layerGroup.getScale());
    //       }
    //     }
    //   } else {
    //     if (majorIndex === 0) {
    //       // scale flip Z for sagittal and undefined target orientation
    //       layerGroup.flipScaleZ();
    //     } else {
    //       viewLayer.setScale(layerGroup.getScale());
    //       if (typeof drawLayer !== "undefined") {
    //         drawLayer.setScale(layerGroup.getScale());
    //       }
    //     }
    //   }
    // } else {
    //   viewLayer.setScale(layerGroup.getScale());
    //   if (typeof drawLayer !== "undefined") {
    //     drawLayer.setScale(layerGroup.getScale());
    //   }
    // }`

**Comment by LeoReubelt** [comment]
@ivmartel - I was modifying a fork at... `https://github.com/EnHatch/dwv/tree/v0.32.e`. Is seems to work with all my test cases. All the changes (except the creation of new flip functions) are in app.js. The changes are in the same place where the flips occur along with a few helper functions. it won't work for image patient orientations that have decimal values, but maybe the logic will still help.

**Comment by ivmartel** [comment]
Thanks for all this. How did you validate the code? Do you have data for every possible orientation?

**Comment by LeoReubelt** [comment]
At this stage it was just round 1. 
1) assembled a group of files with different orientations - i think i covered them all, but i would have to double check that.
2) visually checked that the image was in the correct location on load and in each orientation.
3) i compared some of them with osyrix to make sure the orientation was correct
4) i used the zoom/pan tools with some of them to make sure everything worked there. in one of my earlier attempts, when i tried to pan, the image filpped. 

I think we do have data for every orientation but only orientations with -1's, 1's, and 0's. if you need files, i can see if i can get them for you.

**Comment by ivmartel** [comment]
Yes, if you can share the data, that would be very helpful.
