### ISSUE TITLE
getCurrentIndex not working in multiframe images

### ISSUE THREAD

**Issue by helghast79** [ivmartel/dwv#1479]
When multiframe dicom images are loaded, the getCurrentIndex() method of viewController does not return the current frame. Is there an alternative to get the current frame? I'm using version 0.33.0-beta.6 and relevant code below
```js
const lg = dwvApp.getLayerGroupByDivId( viewportId );
const vc = lg.getActiveViewLayer().getViewController();
currentIndex = vc.getCurrentIndex().get(2) // always = 0 in multiframe images, works fine on single frame's
```

**Comment by ivmartel** [comment]
It is normal, the third index is the Z direction. For multiframe it will stay at 0. The 'time' index is the fourth index.

**Comment by helghast79** [comment]
ok, then how could we get the current frame number? The purpose is to update the slider with the scroll event but I don't see anything changing on multiframes but the stack updates correctly nevertheless, so where is the change happening and how can we set the stack for a specific frame number?

**Comment by ivmartel** [comment]
The index class provides a `get(number)`, `get(3)` will give you the frame index.
The `value` property of the `positionchange` event should be changing when the position changes.

Check it out in the demo: https://ivmartel.github.io/dwv/demo/trunk/viewer.html?input=https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2Fmultiframe-test1.dcm

**Comment by helghast79** [comment]
Was missing the `event.value[0]` of `positionchange` event, which on multiframes has the new frame number on index `[3]`. It works fine now, thanks!
