### ISSUE TITLE
use KineticJS for image and Temp or make new project with full depend on kineicJS

### ISSUE THREAD

**Issue by mohamedsharaf** [ivmartel/dwv#149]
i see its used in draw layer

why not use it in image layer and temp layer

this will solve issues
https://github.com/ivmartel/dwv/issues/136
https://github.com/ivmartel/dwv/issues/143
https://github.com/ivmartel/dwv/issues/101

https://github.com/ivmartel/dwv/issues/133
by using group of elements as used in Arrow draw input and text

https://github.com/ivmartel/dwv/issues/143 
 (i think this will be one of best development for the system at all)
KinetcJs Events could be registered through jquery easily

**Comment by mohamedsharaf** [comment]
KineticJS End of life

**Comment by ivmartel** [comment]
Yep, see #152. Have you used Konva.js?

**Comment by ivmartel** [comment]
Seems a bit old... Closing for now, feel free to comment if you need.
