### ISSUE TITLE
how call an app method in new version 10 beta

### ISSUE THREAD

**Issue by ajabnoor** [ivmartel/dwv#150]
hi,
i used before to call a method like this 
app.getToolBox().setSelectedTool('Zoom/Pan');
and it worked fine for me when i put it inside a click event in a new button
but in the new version i could not understand how it can be done!!!

thanks for your help

**Comment by ivmartel** [comment]
Sorry for the change, but it is now [getToolbox](https://github.com/ivmartel/dwv/blob/src/app/application.js#L203) (lower case b). I'm trying to clean all this up and have introduced a getToolboxController, it would be better tu use this one, I hope to remove the getToolbox in the future.
Regarding GUIs, have you checked the simple viewer, it's a good example of how to change the standard one.

**Comment by ajabnoor** [comment]
thanks a lot for the reply
i am going to try it ASAP

**Comment by ivmartel** [comment]
Ok closing for now. Will reopen if you tell me it still does not work.

**Comment by ajabnoor** [comment]
thanks a lot it works fine for me....
