### ISSUE TITLE
Investigate using Konvajs

### ISSUE THREAD

**Issue by ivmartel** [ivmartel/dwv#152]
[Konva.js](https://github.com/konvajs/konva) is a fork of the mothballed [Kineticjs](https://github.com/ericdrowell/KineticJS/). Its usage should be investigated.

**Comment by mohamedsharaf** [comment]
its first time i know through you 

kineticjs was the best its infrastructure was great 
i used EaselJS http://www.createjs.com/EaselJS
its great but i think if yours is fork from kinetic it may be better i will have a look

**Comment by ivmartel** [comment]
Seems all good, no big changes, just fixed deprecated in 76c3414.
