### ISSUE TITLE
Parse 3d data

### ISSUE THREAD

**Issue by lingdu0001** [ivmartel/dwv#153]
Can dwv parase 3d data ,and make up 3d view?
Just like wpacs, the demo video is here :http://pan.baidu.com/s/1nt2zoNn

**Comment by ivmartel** [comment]
dwv can parse multiple dicom files that will end up being a 3d data. But it can't create a 3d view of it like what you could get with XTK for example (like [this](http://lessons.goxtk.com/10/)).
I can't access your link, it seams to ask for some login. What is wpacs?

**Comment by lingdu0001** [comment]
I have send an email to ivmartel@gmail.com, please have a look .Thank you .
