### ISSUE TITLE
Error openning dicom images

### ISSUE THREAD

**Issue by ManuelTinoco** [ivmartel/dwv#154]
I can´t open my dicom images (.dcm). DWV says me:

Error: Unsupported DICOM transfer syntax (JPEG): 1.2.840.10008.1.2.4.70.

Why is doing this?
How can I solve?

Regards,
Manuel

**Comment by ivmartel** [comment]
Sorry, as mentioned in the [Dicom-support](https://github.com/ivmartel/dwv/wiki/Dicom-Support#transfer-syntax) page, DICOM files with JPEG encoded content cannot be decrypted.
I'm still looking for a javascript JPEG decompression library that supports lossless (see #61)... 

Feel free to tell me if you know one or modify the [jpg.js](https://github.com/mozilla/pdf.js/blob/master/src/core/jpg.js) of the pdf.js project!

**Comment by ivmartel** [comment]
Fixed in #165!
