### ISSUE TITLE
ipad crash while load more than 30 dicoms.

### ISSUE THREAD

**Issue by lingdu0001** [ivmartel/dwv#155]
Hi ivmartel ,
I have used dwv in my project (webapp), but i found an very important issue. If i load more than 30 dicoms, it will crash imeedialy. 
I have tried on iphone 6, ipad air ,iphone 5s.

Please help me...

**Comment by ivmartel** [comment]
Strange, I can load more than 30 on a windows or linux browser. Are you using Safari? Could you try another browser (ideally Chrome or Firefox)?

**Comment by lingdu0001** [comment]
I can load more than 30 on a windows or linux browser too.
But it's performance is very poor on ipad or iphone.（ I have tried it on safari and chrome）

**Comment by lingdu0001** [comment]
There is another way to solve it.
 If you can support some api which i can use it to destroy the dicom which have been loaded completely ,  then i can write code to loop this circle ( load 20 dicoms, destroy these ,load 20 new dicoms ,destroy thess) .

Regards

**Comment by ivmartel** [comment]
I added support for web workers in #208, can you try to see if it helps?
To activate, add a `"useWebWorkers": true` in your application call to `init` as in [applauncher.js#L39](https://github.com/ivmartel/dwv/blob/master/viewers/mobile/applauncher.js#L39).

**Comment by ivmartel** [comment]
Closing in the meantime. Feel free to reopen if it still gives problems.
