### ISSUE TITLE
Loading segmentation mask overwrites base image events

### ISSUE THREAD

**Issue by helghast79** [ivmartel/dwv#1551]
Loading base image series sets eventHandlers like positionchange, wlchange, etc., but if a segmentation series is loaded after base series, this events will be replaced and associated to the last series loaded (seg) so, for example, if a base series has 20 slices and seg series has only 2 slices, than positionchange for example will only change within those 2 slices. Is there a way to prevent certain eventHandlers from being created when the second series is loaded (dataId>0)? or is there an alternative way to prevent the above behaviour?

**Comment by ivmartel** [comment]
The last loaded layer automatically becomes the 'active' layer. The app switched to listen to mouse events from this layer. To revert to another, you need to set it as active. There are various ways to find a layer, if you know the `dataId` that it contains, you can search for its layer from its layergroup. See the test viewer and the radio buttons in the table bellow the images for examples.

**Comment by helghast79** [comment]
In test viewer the following code works:
```
const lg = _app.getLayerGroupByDivId(groupDivId);
lg.setActiveViewLayerByDataIndex(parseInt(dataId, 10));
```
but in newer versions, "setActiveViewLayerByDataIndex" is no longer available, but "setActiveViewLayer" is, and does same thing. Leaving this here for future reference
```
const lg = _app.getLayerGroupByDivId(groupDivId);
lg.setActiveViewLayer(parseInt(dataId, 10));
```

thanks

**Comment by ivmartel** [comment]
:warning: `setActiveViewLayerByDataIndex` is now called `setActiveViewLayerByDataId`, this change was made for v0.33 (see https://github.com/ivmartel/dwv/issues/1460, index was a number, now id is a string).

`setActiveViewLayer` takes the layer id as input.

**Comment by helghast79** [comment]
yes, both work fine. In my case base image is always in index zero, so lg.setActiveViewLayer(0) or lg. setActiveViewLayerByDataId("0") both work in setting active view layer back to the base image
