### ISSUE TITLE
Getting the error attached for specific image files

### ISSUE THREAD

**Issue by anbutm** [ivmartel/dwv#156]
![capture](https://cloud.githubusercontent.com/assets/13043018/8346301/21dc6cd0-1b18-11e5-94a8-370561d86beb.PNG)
we are facing this error only for few dicom formats.  Also if I open more than 3 images simultaneously, the browser hangs and becomes  non responsive.  Please suggest.

**Comment by ivmartel** [comment]
The viewer does not support the PALETTE COLOUR (meaning that the palette is embedded with the file). Pull request are welcome!
About the 3 files, how big are they? What are the sizes (rows and columns)? The viewer can have troubles with big files...

**Comment by ivmartel** [comment]
Check out #664 for progress.
