### ISSUE TITLE
Slips in documentation

### ISSUE THREAD

**Issue by mbarnig** [ivmartel/dwv#158]
Let me first say that DWV is an outstanding project which is very well structured and documentated. When I was reading the DWV documentation at YUI, I noted that the following classes have two methods with the same name : 
dwv.App -> loadFiles, translate ; 
dwv.gui.base -> refreshSelect ; 
dwv.image.filter.Treshold / Sharpen / Sobel  -> setOriginalImage; 
dwv.tool.Toolbox -> init; 
dwv.ViewController -> setCurrentPosition2D
I know that there is no impact on the program working, but I think it's not an intention, but a small slip in the comments of the corresponding javascript files.

**Comment by ivmartel** [comment]
Thanks Marco, I will get cracking!
