### ISSUE TITLE
Not a valid DICOM file (no magic DICM word found) on JPEG image still occured

### ISSUE THREAD

**Issue by christianesperar** [ivmartel/dwv#159]

**Comment by ivmartel** [comment]
Yep, still with a :x: in [Dicom-Support](https://github.com/ivmartel/dwv/wiki/Dicom-Support)...
I have to check if I could use this [JPEGLosslessDecoderJS](https://github.com/rii-mango/JPEGLosslessDecoderJS).

**Comment by ivmartel** [comment]
Hi, I do not get the "not a valid DICOM file" error with the data you passed me but it hangs Google Chrome, so it is more like what you describe in #166. You can try with smaller data (in terms of rows*columns), it should work.

**Comment by pervez8ktt** [comment]
whenever i load more than 250 dcm images my browser will be hang
