### ISSUE TITLE
Cannot load any dcm file from Google Drive

### ISSUE THREAD

**Issue by c-a-m-a-c** [ivmartel/dwv#1612]
Learned about this app via Google Workspace Marketplace and I like it a lot! I'm no developer, just a patient trying to share my x-ray scans with other parties.

I successfully linked the app with my Google Workspace and made it available to all users. When I try to open a file from Google Drive or GMail (via "Open with") I get a browser message "A load error has occured. See log for details."  and I have to refresh the browser in order to do another try.

When refreshed (or when I directly open from https://github.com/ivmartel/dwv), I can load the files without a problem from local storage.

I don't know what log the error message refers to and where to find it?

Using "dwv-jqmobile 0.7.0" on "Microsoft Edge Version 121.0.2277.128 (Official build) (arm64)" (latest) on "Microsoft Windows 11 Pro" (10.0.22621 Build 22621) on a "Surface Pro X" (ARM64-based PC).

**Comment by ivmartel** [comment]
Thanks for reporting, I think I know what is the problem, stay tuned for a fix.

**Comment by ivmartel** [comment]
Ok, should be better now. Google drive should open "dwv-jqmobile 0.7.1", if not, refresh the page to force the update.
