### ISSUE TITLE
loadFiles method is giving me an Error

### ISSUE THREAD

**Issue by danielyaa5** [ivmartel/dwv#162]
Trying to work off of the JSFiddle example but when I try and load a local dicom image Im getting an error message on the console that says "Uncaught TypeError: Cannot read property 'split' of undefined" and nothing shows on the screen.
<img width="828" alt="screen shot 2015-07-24 at 2 37 02 pm" src="https://cloud.githubusercontent.com/assets/6629098/8881976/ae4a8c5a-3211-11e5-80d8-96ed735e5471.png">
![screen shot 2015-07-24 at 2 37 27 pm](https://cloud.githubusercontent.com/assets/6629098/8881981/b74ab97e-3211-11e5-8103-04c0e417919e.png)

**Comment by ivmartel** [comment]
The loadFiles method expects an array of [File](https://developer.mozilla.org/en-US/docs/Web/API/File) objects given by a drag and drop or a html input. The loadURL should work for what you want to do.
