### ISSUE TITLE
Loading file url with dynamic url

### ISSUE THREAD

**Issue by JDufrenneAnsys** [ivmartel/dwv#1628]
I have a dynamic way to get my files: https://myserver/getFile?fileName=test.dcm&fileID=XXXXXXXXXXX

Today it's not possible to load the files due to "canLoadUrl" of each loaders.

Is it possible to extend default capabilities by detecting"filename" or "fileName" params in url and to use it instead of urlObjext.pathname ?

**Comment by ivmartel** [comment]
I'm thinking of adding a `force` parameter to the loadURLs options to override the checks. Would that be ok with your use case?

**Comment by JDufrenneAnsys** [comment]
Yes it should be perfect !

**Comment by ivmartel** [comment]
The option is added in the latest code and will be available in the, I hope soon, v0.33 release.
