### ISSUE TITLE
How to add custom tools?

### ISSUE THREAD

**Issue by adamcanray** [ivmartel/dwv#1643]
hi,

i want to add custom tools like: rotate, flip, shift, zoomin, zoomout, etc. 

how to do it? should i add new files to `src/tools`? is there an example to add a custom tool?

one of the goals is to spread panzoom into pan, zoomin and zoomout as separate tools.

thank you.

**Comment by ivmartel** [comment]
The discussion is on #1644. Closing this one, feel free to comment if you need.
