### ISSUE TITLE
package this app in electron? 

### ISSUE THREAD

**Issue by davidawad** [ivmartel/dwv#1653]
Hey there, this project could have a lot more impact if it was packaged as a cross-platform desktop app. 

you could do that with electron, there's a lot of projects that do it from slack to [jan](https://github.com/janhq/jan) which is open source. 

that would also enable things like brew and chocolatey formulas to install dwv and get it to fully solve the problem. a yarn install is beyond most nurses but installing a .exe file isn't. 

if you want  help with this let me know. I'd love to point you to resources.

**Comment by ivmartel** [comment]
Thanks for the tip! I had a go at electron some time ago, check it out there: https://github.com/ivmartel/dwv-jqmobile-electron. It needs updating...
