### ISSUE TITLE
"node_modules" folder missing in Source code

### ISSUE THREAD

**Issue by NandhiniDhand** [ivmartel/dwv#1654]
Hi,
The "node_modules" folder missing in the Source code
Could you please assist me in including the "node_modules" and all references in Asp.net MVC project

**Comment by NandhiniDhand** [comment]
I'm using the Asp .Net MVC project with .netframework
could you please assist how can i install the  npm install or yarn install

**Comment by ivmartel** [comment]
Please check their respective install guides:
- https://docs.npmjs.com/downloading-and-installing-node-js-and-npm
- https://yarnpkg.com/getting-started/install

**Comment by ivmartel** [comment]
I hope you fixed your problem. Closing for now, feel free to comment if you need.
