### ISSUE TITLE
DWV sometimes hangs

### ISSUE THREAD

**Issue by christianesperar** [ivmartel/dwv#166]
There are times that  DWV hangs, this includes my computer system (both laptop and desktop). Tested on chrome browser.

**Comment by ivmartel** [comment]
Is it with specific data? How big are they?

**Comment by christianesperar** [comment]
It's less than 2mb jpg image. I will email some of the details.

**Comment by ivmartel** [comment]
I added support for web workers in #208, can you try to see if it helps?
To activate, add a `"useWebWorkers": true` in your application call to `init` as in [applauncher.js#L39](https://github.com/ivmartel/dwv/blob/master/viewers/mobile/applauncher.js#L39).

**Comment by ivmartel** [comment]
Closing in the meantime. Feel free to reopen if it still gives problems.
