### ISSUE TITLE
Issues Loading DICOM: "Error: JPX Error: Unknown codestream code: ff."

### ISSUE THREAD

**Issue by NeutronTon** [ivmartel/dwv#169]
The first time I tried loading the DICOM file I received "SOI not found". File has multiple frames and TransferSyntaxUID is "1.2.840.10008.1.2.4.50 [JPEGBaseline]". Using OsiriX I re-exported and selected "Compress all DICOM files in JPEG" but now I am getting "Error: JPX Error: Unknown codestream code: ff.". This is my first time posting on GitHub, so hope I am following proper etiquette! ;)

**Comment by ivmartel** [comment]
The first error, "SOI not found" is thrown by the JPEG decoder when it tries to decode multi-frame data. I updated it to send a proper error while waiting for the functionality to be implemented.
The second error, "Error: JPX Error: Unknown codestream code: ff.", I need to check...

**Comment by NeutronTon** [comment]
I mistyped, my file is actually multi-slice, not multi-frame. Sorry for the confusion. My understanding is that multi-slice is currently supported.

**Comment by NeutronTon** [comment]
Thanks for your help, indeed the error seems to be due to unsupported multi-frame file. Hoping multi-frame can be supported soon!
