### ISSUE TITLE
How to Show Multiple Viewer on same page

### ISSUE THREAD

**Issue by kamleshsindhal08** [ivmartel/dwv#170]
How to Show Multiple Viewer on same page and compare the slice

**Comment by ivmartel** [comment]
You can show multiple viewers as in this [fiddle](http://jsfiddle.net/ivmartel/jkcmj0px/) from the [API page] ( https://github.com/ivmartel/dwv/wiki/API) but there is no link between each views yet...

**Comment by kamleshsindhal08** [comment]
thanks for reply, but how to used  app.loadFiles function and in both viewer all functionality working like scroll, cilck event etc. ,  i am waiting for your reply....

**Comment by ivmartel** [comment]
In theory by setting each app individually. I'll try to find time to add a new fiddle!

**Comment by ivmartel** [comment]
Or you could have controls that set both apps at the same time.
