### ISSUE TITLE
Error: Invalid dimensions for plot, width = null, height = null.

### ISSUE THREAD

**Issue by kamleshsindhal08** [ivmartel/dwv#171]
when add mutiple viewer on same page , then show this message on alert popup and in second viewer not show dicom files when click on viewer then show m see attach screenshot
![untitled](https://cloud.githubusercontent.com/assets/14357332/10157134/f0014ac2-66a4-11e5-9bd0-5c1e3b69372e.png)

**Comment by ivmartel** [comment]
I've tried multiple viewers with the simple one, not this one (static) or the mobile one. I'll check and see if I can fix this.
