### ISSUE TITLE
Support for DICOM Structured Reports (DICOM SR)?

### ISSUE THREAD

**Issue by andrescastano** [ivmartel/dwv#1719]
Hi,

I am starting to implement a DICOM Structured Report (DICOM SR) that contains the study report embedded in a DICOM file. Does the current version of the fo-dicom library support this DICOM format?

Thanks in advance.
![weasis-dicom-sr](https://github.com/user-attachments/assets/b5b407aa-dd2a-4003-8e83-1c4136454f02)

**Comment by ivmartel** [comment]
This is the repo of the dwv project, not fo-dicom. For fo-dicom see https://github.com/fo-dicom/fo-dicom.

Regarding DICOM SR support, there is an ongoing task to support it for 2D annotations, see #1020. More general support is not planned for now.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
