### ISSUE TITLE
Error: No loader found for url

### ISSUE THREAD

**Issue by kortuta** [ivmartel/dwv#1751]
When trying to load a dicom image from a webserver via an url with get parameters an error  "No loader found for url: " is thrown.
My url looks like this:

https://appsrv-entw.rz.lsv.de:8071/system/cgi-bin/dicom.fcgi?get&pVersion=0046&contRep=ZDI&docId=E72CF78F1FE41EDEBDCF33D86DB1084C&compId=1

Loading the same file with a static url works totaly fine.

**Comment by ivmartel** [comment]
dwv cannot guess from the url which loader to use. The dicom loader is used if one of these conditions is met:
  - the HTTP request headers contains a 'Accept: application/dicom',
  - the url has a 'contentType' parameter and it is 'application/dicom' (as in wado urls),
  - the url has no 'contentType' and no extension or the extension is 'dcm'.

You can also force the loader when call the `loadUrl` method. Check out [dicomDataLoader::canLoadUrl](https://github.com/ivmartel/dwv/blob/v0.33.1/src/io/dicomDataLoader.js#L113)
