### ISSUE TITLE
Error display when .dcm file upload

### ISSUE THREAD

**Issue by kamleshsindhal08** [ivmartel/dwv#176]
why show error "TypeError: invalid argumensts " when upload dicom files and also see attach screenshot.
![untitled](https://cloud.githubusercontent.com/assets/14357332/10215345/54b976c0-683e-11e5-8b4f-2079a19fcc0a.png)

**Comment by ivmartel** [comment]
Does it happen with some specific data? If it does, can you share an anonymised version of the data?

**Comment by kamleshsindhal08** [comment]
Hi,
I am sharing my two dcm files which i can not processed.

https://drive.google.com/folderview?id=0B8t3ymMbTgM8dHBsdkRMdFNCMVE&usp=sharing

**Comment by kamleshsindhal08** [comment]
we are using latest version of ivm dwv

**Comment by pervez8ktt** [comment]
i think there is a problem with dicomParser.js line no. 889 after tag x21111010 exception occurred. after this tag there are some places where uint8 variable can't create.

there are new dicomParser.js at this link

https://github.com/chafey/dicomParser

if there are anyone who can merge this dicomParser.js with this project then it will be work for all projects.

**Comment by ivmartel** [comment]
About the data you attached:
1. CR-MONO1-10-chest.dcm: the header does not start with the standard 'DICM' and it does not have a transfer syntax. DWV does not support non standard DICOM files, it is yet difficult enough to support standard files!
2. The second data is encoded with JPEG2000 and causes decoding troubles, to be investigated...

**Comment by ivmartel** [comment]
The JPEG2000 error now has its issue.
