### ISSUE TITLE
Full Screen image

### ISSUE THREAD

**Issue by eduardoricheli** [ivmartel/dwv#1760]
view Full Screen image on browse!

**Comment by ivmartel** [comment]
Not sure I get your question. 
Regarding full screen, the client controls the div that contains dwv and dwv should adapt if the div changes size. For an example, check out how full screen is handled in [dwv-simplistic](https://github.com/ivmartel/dwv-simplistic).

**Comment by ivmartel** [comment]
I hope the link helped and you solved your problem. Closing for now, feel free to comment if  you need.
