### ISSUE TITLE
error: Cannot append a slice with different orientation

### ISSUE THREAD

**Issue by adamcanray** [ivmartel/dwv#1769]
hi @ivmartel,

i am facing an error for load image slices from series, that prevously edited on other PACS (GE MEDICAL SYSTEMS). its not render the images, sometimes its render the first image (but not scrollable).

indication:
- i think the first image is different orientation than the rest (maybe its REFORMATTED and somehow its orientation is different), because i've tested load instance number 2 to instance number n, its perfectly loaded and scrollable. but when i include the instance number 1 (the first image), it shows the error.

<img width="598" alt="Screenshot 2024-10-15 at 17 41 41" src="https://github.com/user-attachments/assets/b20f247b-f0db-47c4-b2d6-098b55763abf">

instance number 1 looks like (usually display/text/thumbnail/etc):
<img width="462" alt="Screenshot 2024-10-15 at 17 41 51" src="https://github.com/user-attachments/assets/e5b3dec9-b585-460d-85ce-5c28e789cd25">
<br/>
instance number 2 to instance number n looks like (normal slices):
<img width="1440" alt="Screenshot 2024-10-15 at 17 45 30" src="https://github.com/user-attachments/assets/a34e8543-2765-41be-8f35-a4fb91add321">

<br/>
<br/>
<br/>
<br/>
<br/>

is there any solution for this case?
thanks.

**Comment by ivmartel** [comment]
For the moment, you have to sort the data manually so that you just pass geometrically related data to dwv. #646, adding a series 'browser', could be a solution for this but it needs to be implemented...

**Comment by ivmartel** [comment]
Follow progress on #646. Closing for now, feel free to comment if you need.
