### ISSUE TITLE
Combined Scroll and Window/Level tool

### ISSUE THREAD

**Issue by JDWarner** [ivmartel/dwv#179]
The behavior I'm looking for is the ability to scroll through images with the mouse wheel _while also_ changing the window/level by clicking and dragging. This is to enable a rich interactive viewer embedded in a Reveal.JS presentation. To minimize presentation clutter I do not want a selection box or anything to select between tools; I want them active simultaneously as listed above.

At present it's relatively simple to do either, but when attempting to have both active simultaneously they conflict and it seems the first in the `tools` list "wins". I think this means selectively disabling click-and-drag scrolling and/or an entirely separate tool, or I'm missing something.

**Comment by ivmartel** [comment]
You are right, the selected tool captures all the events so behaviour cannot be shared between tools.

The solution is to create a tool that does scroll and window/level which was how it was a long time ago. Basically you need to add the `DOMScrollMouse` and `mousewheel` methods of the scroll tool (see [scroll.js#L137](https://github.com/ivmartel/dwv/blob/master/src/tools/scroll.js#L137)) to the window level tool.

**Comment by ivmartel** [comment]
I hope the comment was clear enough. I would be interested to see the result! Closing for now.

**Comment by sanbangarh309** [comment]
hi @ivmartel  please tell me the supported tools for this. i need tool for brightness is it different from windowlevel
