### ISSUE TITLE
Error parsing image - nested sequences?

### ISSUE THREAD

**Issue by bisol** [ivmartel/dwv#180]
I'm using DWV 0.11.1, and got this error while trying to display an image:
>Error: Missing or empty DICOM image number of columns

I've traced it to these tests on dwv.dicom.DicomParser.prototype.parse
```javascript
// end of sequence with explicit length
if ( dataElement.vr !== "SQ" && sequences.length !== 0 ) {
```

Seems like it can't handle a sequence with another sequence as it's last item.

This site limits attachments by file extension, so I uploaded the DICOM file renamed to png :p

![6809 anon](https://cloud.githubusercontent.com/assets/13683655/10462307/67b8c3fa-71b4-11e5-9a39-8a0ab640e90d.png)

**Comment by bisol** [comment]
I have tried and failed to commit a new branch. Anyhow, this worked for me:
```javascript
        // handle nested sequences of explicit length
        if (dataElement.vr == "SQ" && sequences.length > 1 ) {
            sequences[sequences.length - 2].vlCount -= 4;  // offsets the +12 below 
        }
        
        // end of sequence with explicit length
        if ( dataElement.vr !== "SQ" && sequences.length !== 0 ) {
            var last = sequences.length - 1;
            sequences[last].vlCount += tagOffset;
            // check if we have reached the sequence vl
            while ( sequences.length > 0 && sequences[last].vlCount === sequences[last].vl ) {
                // last count + size of a sequence
                var lastVlCount = sequences[last].vlCount + 12;
                // remove last sequence
                sequences = sequences.slice(0, -1);
                // add nested sequence vl
                if ( sequences.length !== 0 ) {
                    last = sequences.length - 1;
                    sequences[last].vlCount += lastVlCount;
                }
            }
        }
```

**Comment by pervez8ktt** [comment]
there are so many problems with current dicomParser.js

you need to update dicomParser.js with new one that is

https://github.com/chafey/dicomParser

**Comment by ivmartel** [comment]
Thanks for your code @bisol!

**Comment by ivmartel** [comment]
Your comment is not really helping the issue @pervez8ktt... Feel free to contribute to the [dcmbench](https://github.com/ivmartel/dcmbench) project to prove your point!

**Comment by bisol** [comment]
@ivmartel  
I should mention that I don't fully understand the magic numbers (+12 and -4). I tested this with a handful of DICOM images, but that's far from thorough. Maybe it will break with a triple nested sequence...

**Comment by ivmartel** [comment]
Ok, got it, the problem is implicit/explicit transfer syntax. The 4 bytes are used to store the VR in the explicit case (see DICOM [sect_7.5.html#table_7.5-1](http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_7.5.html#table_7.5-1)) which was what I tested against. Yours is implicit so no need for those 4 bytes.
