### ISSUE TITLE
DWV Marking issue on JPEG (Question)

### ISSUE THREAD

**Issue by SaqifHaque** [ivmartel/dwv#1812]
I am trying to use the DWV to mark jpeg image but it triggers error in the example. I want to confirm that is it possible to mark Jpeg and dicom images also download it including the annotations? will those become permanent markings in the image. Also Can you tell me how can i see slices of the multiframe dicom on mouse scroll? it seems like it only works when i click on the picture and move sideways.
Thank you.

**Comment by ivmartel** [comment]
You are right, drawing annotations on jpeg does not work with v0.34. I created #1813 to fix it. Please note that this is not the main use case, annotations are saved as dicom. They can be loaded back on the original image but I did not do extensive testing...

**Comment by ivmartel** [comment]
Follow #1813 for updates, I should publish a 0.34.1 soon. Closing for now, feel free to comment if you need.
