### ISSUE TITLE
Accessing app and state from a new js file

### ISSUE THREAD

**Issue by ish3lan** [ivmartel/dwv#191]
I am creating a new javascript file in the static view folder. I want to access the state (e.g. json file for the drawings). but I couldn't. All what I was able to get is the function itself printed. Can any body suggest a solution or refer to a one ? 

thanks in advance

**Comment by ivmartel** [comment]
Did my answers to #192 and #193 help you on this topic?

**Comment by ish3lan** [comment]
Yes, thank you 👍🏻

**Comment by ivmartel** [comment]
Ok, closing...
