### ISSUE TITLE
How to add a state to a .dcm image?

### ISSUE THREAD

**Issue by ish3lan** [ivmartel/dwv#193]
I have loaded an image using loadFiles() function and it is shown on the viewer, However I have state.json file and want the drawings in this state to be shown on the image. Is it possible ?

**Comment by ivmartel** [comment]
The `loadFiles` method can also be used for state (json) files, it differentiates them using the file extension. For more details, see [application.js#L488](https://github.com/ivmartel/dwv/blob/master/src/app/application.js#L488).
