### ISSUE TITLE
dwv access adress with manifest file

### ISSUE THREAD

**Issue by nihels1** [ivmartel/dwv#196]
Hi,
i want to access dwv with multi slice serie so i deployed dwv with weasis pacs connector in my tomcat server. I 'am able to access dwv using : http://localhost:8080/dwv-master/viewers/static/index.html?

and i get serie manifest file using weasis pacs connector using this url: http://localhost:8080/weasis-pacs-connector/manifest?patientID=15037257

I followed the instrection in https://github.com/ivmartel/dwv/wiki/User-Stories to access dwv with  Multiple data Manifest but i didn't succed in that.
is their any one can help with the url ?

**Comment by ivmartel** [comment]
Could you send an example url that you generate?
Side question: you do not want to use the dcm4chee web interface?

**Comment by nihels1** [comment]
Thanks for your replay,
my fault was in the weasis pcs connector url that was'nt encoded.
i used :http%3A%2F%2Flocalhost%3A8080%2Fweasis-pacs-connector%2Fmanifest%3FpatientID%3D15037257
 insted of : http://localhost:8080/weasis-pacs-connector/manifest?patientID=15037257
and that solve my probleme.
