### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by HimanshuN** [ivmartel/dwv#199]
Hello,
I am getting an error of "No Access-Control-Allow-Origin header" while accessing the url using xmlhttprequest ajax method. 
The url is actually a file path not a web service.
Though this was solved by google chrome CORS extension but I want it to do without using any such extensions. This should be solved using code in file so that any remote user could be able to use it without any interupption as they might not know that such extensions should be used for accessing image url.

Thanks in advance

**Comment by ivmartel** [comment]
What I advise to do (cf [Error-Messages#requesterror](https://github.com/ivmartel/dwv/wiki/Error-Messages#requesterror)) is to either host dwv on the same server as the data or enable Cross-Origin Resource Sharing (CORS) on the server.

Do I understand you well, dwv is on server A and you want it to show data that is on server B via its url?

**Comment by HimanshuN** [comment]
Yes, you understood it well, that is the issue. 
Thank you.

**Comment by ivmartel** [comment]
So which option will you choose?

(and If the answer is good enough for you, can you please close this issue)

**Comment by HimanshuN** [comment]
Actually I am busy on another project so I have done it using same server. So closing it here but I will try to enable CORS on another server later and reopen it then if stuck anywhere.
Thanks
