### ISSUE TITLE
Preload Image

### ISSUE THREAD

**Issue by riki420** [ivmartel/dwv#202]
Hello, how can i load an image/dicom file when the page is open instead of upload. 
So how can i hardcode the path of local file system?

**Comment by ivmartel** [comment]
You can load images via the gui: on this (demo page)[http://ivmartel.github.io/dwv/demo/stable/viewers/mobile/index.html], use the `+` button. Drag and drop is also available.
Hard coding local paths is not really permitted by browsers, you need to tell them: see this (text)[https://github.com/ivmartel/dwv/wiki/Error-Messages#requesterror] for the browser flags.
