### ISSUE TITLE
Change Event Trigger

### ISSUE THREAD

**Issue by ish3lan** [ivmartel/dwv#211]
I have modified the Rectangle option behavior to be a fixed rectangle (e.g h=128, w=128).
The problem I want to solve now is how to make the rectangle drawn only by clicking on the image not by dragging on it.

**Comment by ivmartel** [comment]
The draw listeners are set in the Draw class, see [draw.js#L229](https://github.com/ivmartel/dwv/blob/master/src/tools/draw.js#L229). You need to deactivate the mousemove handler, remove the move checks from the mouseup and make the factory create the fixed size rectangle by providing it the points you want.

**Comment by ivmartel** [comment]
Closing for now. Feel free to reopen if you need.

**Comment by ish3lan** [comment]
I am not sure how to reopen it, 
I tried following your comment but I could not accomplish what I needed.
So I tried : 
1- commenting this.mousemove
2- commenting the (started ) in the first if in  this.mouseup 
but it did not work
I mean I could not accomplish drawing any shape without drawing 
I am able to draw a fixed size square.
Thank you for your concern.

**Comment by ish3lan** [comment]
@ivmartel

**Comment by ivmartel** [comment]
Ok, had a look and think I have something. Check out this [gist](https://gist.github.com/ivmartel/1bd4205d8a30be94e556c9160761a967), download the files and replace them in the repository.
Is it the behaviour you are looking for?

**Comment by ish3lan** [comment]
@ivmartel 
Using the two gist files did not solve the problem, it creates new lags and unexpected behaviour while moving the shape.
I was able to create a rectangle with a predefined width and height.
The only problem I have is the trigger of the creating process.

**Comment by ivmartel** [comment]
Hi, just in case, did you try the gist from a clean repo?

**Comment by ivmartel** [comment]
Closing while waiting for an answer...
