### ISSUE TITLE
Change default DVW to from "Invplain" to "plain"

### ISSUE THREAD

**Issue by christianesperar** [ivmartel/dwv#218]
We have a task to "Check default DVW to from Invplain to plain", I browse to the code and there is some Default colour maps and plain is already included. Does it mean that plain is already a default?

**Comment by ivmartel** [comment]
Which task are you referring to?
Yes, plain is the default colour map (see [view.js#L33](https://github.com/ivmartel/dwv/blob/master/src/image/view.js#L33)) apart when the Photometric Interpretation is "MONOCHROME1" (see [view.js#L120](https://github.com/ivmartel/dwv/blob/master/src/image/view.js#L120)).

**Comment by christianesperar** [comment]
Solve. I just found that this is on the bottom and it's depend on the file.

**Comment by arturojain** [comment]
Is there a way to overwrite the file Photometric Interpretation?

**Comment by ivmartel** [comment]
One way I see (not tried it) would be to save a state file and load it with the data.
