### ISSUE TITLE
create shapes programmatically

### ISSUE THREAD

**Issue by ish3lan** [ivmartel/dwv#221]
Lets say I have a rectangle attributes such as {"Height":40,"Width":40,"XCoordinate":132,"YCoordinate":157}

How to draw it on the image ?

this is my attempt [in application.js

 ```javascript
    this.addRect = function (rect) {
        var currentState = new dwv.State(this).toJSON();
        console.log(currentState);
        currentState = JSON.parse(currentState);
        currentState.drawings.push(
            dwv.tool.RectangleFactory.prototype.create(
              [rect.XCoordinate, rect.YCoordinate],
              this.getStyle(), this.getImage())
         );
        
        var state = new dwv.State(self);
        state.fromJSON(currentState, fireEvent);
        console.log(currentState);
    }

```

**Comment by ivmartel** [comment]
You are trying to draw the shape from the state, may I ask why?

Using a shape factory and the layer, you could just do something like:
```javascript
var shapeGroup = myfactory.create(/*arguments*/);
drawLayer.add(shapeGroup);
drawLayer.draw();
```

**Comment by ish3lan** [comment]
Thank  you for the reply 👍 
I tried this : 
`var shapeGroup = dwv.tool.RectangleFactory.prototype.create([9,9], this.getStyle(), this.getImage());`
and I got this error:
_**TypeError: end.getX is not a function
    at new dwv.math.Rectangle (shapes.js:260)
    at dwv.tool.RectangleFactory.create (rectangle.js:43)
    at addROI (application.js:262)
    at Array.<anonymous> (applauncher.js:61)
    at fireEvent (application.js:1550)
    at urlIO.onloadend (application.js:999)
    at addLoaded (url.js:63)
    at onLoad (url.js:171)
    at onLoadDicomRequest (url.js:178)
    at XMLHttpRequest.onLoadBinaryRequest (url.js:250)**_

**Comment by ish3lan** [comment]
Update :::

I got it working like this: 

`var shapeGroup = new  dwv.tool.RectangleFactory.prototype.create([new dwv.math.Point2D(9,9), new dwv.math.Point2D(49,49)], this.getStyle(), this.getImage());`
