### ISSUE TITLE
Inverted X-ray picture

### ISSUE THREAD

**Issue by ajabnoor** [ivmartel/dwv#222]
Some of the conventional x-ray pictures are displayed inverted, so white become black and black become white. I am tryin to find which part of the code responsible for this inversion to prevent this form happening. could you please help me with this? and why is this happening?

**Comment by ajabnoor** [comment]
I think this is happening because MONOCHROME1 pictures are being displayed as MONOCHROME2 pictures and then become reversed in contrast

**Comment by ivmartel** [comment]
You are right, `MONOCHROME1` is displayed inverted. This comes from the DICOM [specs](https://www.dabsoft.ch/dicom/3/C.7.6.3.1.2/):

> The minimum sample value is intended to be displayed as white after any VOI gray scale transformations have been performed.

**Comment by ajabnoor** [comment]
I have solved it with this
`case "MONOCHROME1":
    sliceOffset = (sliceNumber || 0) * sliceSize;
    var iMax = sliceOffset + sliceSize;
    for(var i=sliceOffset; i < iMax; ++i)
    {
        pxValue = parseInt( windowLut.getValue(
                image.getValueAtOffset(i) ), 10 );
        array.data[index] = (pxValue === 3 ? 1 : 255) - colourMap.red[pxValue];
        array.data[index+1] = (pxValue === 3 ? 1 : 255) - colourMap.green[pxValue];
        array.data[index+2] = (pxValue === 3 ? 1 : 255) - colourMap.blue[pxValue];
        array.data[index+3] = 0xff;
        index += 4;
    }`

**Comment by ivmartel** [comment]
`MONOCHROME1` data is shown inverted not because of its pixels, but because it uses the `invPlain` colour map. You could deactivate this by commenting the lines that search for it (search for `MONOCHROME1` in the code).
