### ISSUE TITLE
Load State

### ISSUE THREAD

**Issue by ish3lan** [ivmartel/dwv#223]
when loading a state i get 
`Uncaught SyntaxError: Unexpected token a`

I use the same state json file that was returned from the toJSON() function and pass it to fromJSON()
but was not able to get it works.

**Comment by ish3lan** [comment]
Since there are related:
if I added a drawing object from a state and insert it later in the viewer, will it be shown properly? That I could move it remove it etc ?

I mean by drawing object : `"0": {
        "attrs": {
            "name": "rectangle-group",
            "id": 1460627035448
        },
        "className": "Group",
        "children": [{
            "attrs": {
                "x": 53,
                "y": 157,
                "width": 40,
                "height": 40,
                "stroke": "Yellow",
                "strokeWidth": 1.7414965986394557,
                "name": "shape",
                "draggable": true
            },
            "className": "Rect"
        }, {
            "attrs": {
                "x": 53,
                "y": 168,
                "text": "0",
                "fontSize": 0,
                "fontFamily": "Verdana",
                "fill": "Yellow",
                "name": "text",
                "width": "auto",
                "height": "auto"
            },
            "className": "Text"
        }]
    }`

**Comment by ivmartel** [comment]
First question: this should work, can you share the code that fails?
Second question: it should work too but drawing could be simpler (see my comments in #221).

**Comment by ish3lan** [comment]
it worked following [#221](https://github.com/ivmartel/dwv/issues/221)
thank you
