### ISSUE TITLE
Create New Shape

### ISSUE THREAD

**Issue by ish3lan** [ivmartel/dwv#224]
I am trying to add a new shape to the shape list: 

e.g. Square shape where height and width are equal.
my try :
copy rectangle class.
rename any rectangle word by square ( of course not replace all :) ) expect the call to `dwv.math.Rectangle(...)`
add new type to `Application.js` in init function in the switch case block:
`                                    case "Rectangle":
                                        shapeList.Rectangle = dwv.tool.RectangleFactory;
                                        break;
`
then added it to the list in` applauncher.js `file 
But it was not enough to get it done

**Comment by ivmartel** [comment]
In theory you do not need to touch the `application.js` code. You need to create the shape class as you did, include it in you html file and add it to the argument list when you call `app.init` such as:
```javascript
app.init({
        "containerDivId": "dwv",
        "fitToWindow": true,
        "gui": ["tool", "load", "help", "undo", "version", "tags"],
        "loaders": ["File", "Url", "GoogleDrive", "Dropbox"],
        "tools": ["Draw"],
        "shapes": ["MyNewShape"],
        "isMobile": true,
        "useWebWorkers": true
});
```

**Comment by ish3lan** [comment]
Thank you , it is working now.
I had to modify the application.js file though.
I added a case in the case of "Draw" in init(). 
`                                   case "Square":
                                        shapeList.Square = dwv.tool.SquareFactory;
                                        break;
  `
otherwise it won't show the square option in the available toolsList.

**Comment by ivmartel** [comment]
Be careful, you are using an old version of the code. Since commit 05fe54f you do not need this draw shape switch loop.
