### ISSUE TITLE
'draw-create' event source type

### ISSUE THREAD

**Issue by ish3lan** [ivmartel/dwv#225]
How can I know the event source type (e.g. rect, roi ,.. ) shape ?
Can I have something like 
`app.addEventListener("draw-create", function () {if (event.source .... ?) do something}`
I printed the event and it only contains 
`{"isTrusted":true,"_xs":56,"_ys":131,"_x":74,"_y":174}`

**Comment by ish3lan** [comment]
my hack to get it done for now is : 
`        console.log("event source: " + JSON.stringify(myapp.getToolbox().getSelectedTool().shapeName));
`
and the result is `event source: "Rectangle"`

**Comment by ivmartel** [comment]
The `draw` events include the `id` of the shape group that was the origin of the event. From the draw layer, you can search for it and then search for the shape in the group:

```javascript
// get the group
var group = myapp.getDrawLayer().getChildren( function (node) {
    return node.id() === event.id;
})[0];
// get the shape
var shape = group.getChildren( function (node) {
    return node.name() === "shape";
})[0];
```

**Comment by ish3lan** [comment]
var group = myapp.getDrawLayer().getChildren(function (node) {
            return node.id() === event.id;
        })[0];

the group is undefined. 
this happens when there is no drawing on the image and I create the first shape

**Comment by ivmartel** [comment]
You should check for the event type in the event listener and only process draw events.
And if it still happens, you can check for the length of the array returned by `getChildren`.

**Comment by ish3lan** [comment]
That solves it, Thank you
