### ISSUE TITLE
Feature added - seed segmetation

### ISSUE THREAD

**Issue by rafasoyyo** [ivmartel/dwv#227]
Hi ivmartel,

I have done a module to implement seed segmetation (https://en.wikipedia.org/wiki/Flood_fill). I have tried to continue with your programming style and imitate what you do and how you do. Anyway, it would be really nice if you have time to have a look and give me your feedback.

You can see the code here:
https://github.com/rafasoyyo/dwv/commits/floodfill

Thanks for your great job!

**Comment by ivmartel** [comment]
Hi Rafa, this looks awesome! I'll give it a close look as soon as possible. What is your plan with the code, can it be integrated in the dwv repo?

**Comment by rafasoyyo** [comment]
Hi ivmartel,

The reason to do it on this way is to make this feature easily integrable with the rest of your code. 
Please, use all the code you consider interesting from my fork.
