### ISSUE TITLE
Preload images

### ISSUE THREAD

**Issue by Grecko14** [ivmartel/dwv#228]
hi
I need to load an image from initiating DWV for example;
i have the next URL "file:///C:/Users/Jorge/Desktop/DICOM/dwv-master/viewers/mobile/index.html?path=C:/Users/Jorge/Desktop/DICOM/S58170/S20", "path" is reference from specific folder i need read all the images from this folder and load automatically without having to click on the "+" button

**Comment by ivmartel** [comment]
Hi, the scheme followed by dwv is detailed there: [User-Stories#io](https://github.com/ivmartel/dwv/wiki/User-Stories#io), in 'Multiple data URL'.
Listing a directory with javascript is not possible in a cross browser way so you have to build the list.
For local files, you can load them with the '+' and choose file or via drag and drop.
Hope this helps, I'm not sure I got the question...

**Comment by Grecko14** [comment]
hi, i tried to use one of your examples to open a file directly with url but doesnt work and send this error 
"RequestError: An error occurred while retrieving the binary file (via http): http%3A%2F%2F192%2E168%2E0%2E6%2Fbootstrap3%2FResource%2FimagesDICOM%2F%3Ffile%3Dbbmri-53323131.dcm&dwvReplaceMode=void (status: 0)" could you help me to build the url correctly thanks

**Comment by ivmartel** [comment]
Check your console log, this will give you more clues on why it failed. It could be related to cross origin sharing or mixed content.

**Comment by Grecko14** [comment]
thanks i solve

**Comment by niravpatel** [comment]
Could you please share that code, I really need that one
