### ISSUE TITLE
Does this viewer support gif images?

### ISSUE THREAD

**Issue by smjezhalloor** [ivmartel/dwv#232]
Is this viewer support gif and tiff image? I want to load gif and tiff image on this viewer. Can you suggest any method to load all types of images.

**Comment by ivmartel** [comment]
Static gifs do work, check: [Röntgens' wife hand](https://ivmartel.github.io/dwv/demo/stable/viewers/mobile/index.html?input=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fe%2Fe3%2FFirst_medical_X-ray_by_Wilhelm_R%C3%B6ntgen_of_his_wife_Anna_Bertha_Ludwig%27s_hand_-_18951222.gif)
