### ISSUE TITLE
Is this viewer support tif & tiff image?

### ISSUE THREAD

**Issue by smjezhalloor** [ivmartel/dwv#233]
Is this viewer support tif and tiff image? I want to load tif and tiff image on this viewer. Can you suggest any method to load all types of images.

**Comment by ivmartel** [comment]
No, DWV does not support tiff images since not all browsers support it natively. See this wikipedia page section about [image format support](https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support) in web browsers.

**Comment by ivmartel** [comment]
A solution would be to use javascript tiff parsers. Here are some possible libraries:
* https://github.com/seikichi/tiff.js
* https://github.com/GPHemsley/tiff-js
* https://github.com/image-js/tiff-js

**Comment by ivmartel** [comment]
(transferred to #253)
