### ISSUE TITLE
Image not Opening (page crashes)

### ISSUE THREAD

**Issue by hassaankamran** [ivmartel/dwv#236]
Hi ivmartel,
I have tried this viewer and find it really helpful. I am facing a issue in opening some images. The page crashes as i choose these images. I am attaching the screenshot of problem and link for the image on dropbox for your ease. Kindly figure it out that why this is happening in some cases. 

Link: https://www.dropbox.com/s/99g38l0ln5pvgnw/image1.dcm?dl=0

![dwv issue](https://cloud.githubusercontent.com/assets/13729551/15245730/cc751248-1921-11e6-98eb-56cd51df8fa9.PNG)

**Comment by ivmartel** [comment]
The image is quite big: 3480*4248. I thought web workers would have helped but it seems not. I'm trying to find if there is a limit in canvas array size, can't find anything for now...

**Comment by jongo** [comment]
You should expect 5000*5000 images in real world

**Comment by ivmartel** [comment]
The page does not crash with version 0.16. But it takes a long time to load...
Closing this issue while keeping in mind that large data support needs to be improved!
