### ISSUE TITLE
Wordpress plug in not opening .jpg galleries as image stacks ?

### ISSUE THREAD

**Issue by snek60** [ivmartel/dwv#245]
Hello, I was wondering, is there any way to force the wordpress plugin to read and display jpg image stack galleries ?
http://irmcardiaque.free.fr/wordpress/?p=294
Like in my website example : top dicom cardiac mri works like a charm, but when I try loading a stack of .jpg, it opens the usual gallery of wordpress instead of dwv.
Is there any simple modification to the plug in I can make to force image galleries to dwv ? because users are more likely to upload stacks of jpg named 1.jpg 2.jpg 3.jpg, etc than dicom files.

Thanks for any input !
(By the way if anyone is willing to code me a custom plug in based on dwv my corporation is willing to pay for it (would be used for this wordpress website only) good money... you can contact me at snek60@gmail.com)

**Comment by ivmartel** [comment]
Hi, the plugin filters gallery content in the `post_gallery` function of the [DicomSupport](https://plugins.svn.wordpress.org/dicom-support/trunk/DicomSupport.php) file (last function). 

Currently, it only selects dicom files but could accept more. Accepting jpeg seems incorrect, this means that regular image galleries of your blog will not work anymore. I was thinking of some kind of tag on the image that would say that you want it displayed with dwv. There is this [MediaTagger](https://wordpress.org/plugins/wp-mediatagger/) that could be used.

When you say you would be interested in a custom plugin, what functionality are you missing in this one?

I tagged this question as invalid since it would be more appropriate to post it on the dicom-support plugin [support](https://wordpress.org/support/plugin/dicom-support) page.

**Comment by snek60** [comment]
Hi. Thanks for the explanation.
I am not using jpg image galeries at all on my website (when I post à JPEG
I only post one never multiple ones in gallery).

Is it possible to enable DWV to display only the JPG that are called as
gallery ? That solution woul be enough for me.

When I am talking about a custom plug in, I am thinking of having
parameters somewhere in plug in settings to set up the default size of the
DICOM/JPG viewer, having like scrolling on left click by default and levels
on right click, stuff like that. But I am wondering is it possible to have
a bigger less minimalistic choice of plug in interface like on your website
demo where you drag and drop the data onto ? Is there any code I can alter
for that in the plug in ?

Thanks a lot.
John.

Hi, the plugin filters gallery content in the post_gallery function of the
DicomSupport
<https://plugins.svn.wordpress.org/dicom-support/trunk/DicomSupport.php>
file (last function).

Currently, it only selects dicom files but could accept more. Accepting
jpeg seems incorrect, this means that regular image galleries of your blog
will not work anymore. I was thinking of some kind of tag on the image that
would say that you want it displayed with dwv. There is this MediaTagger
<https://wordpress.org/plugins/wp-mediatagger/> that could be used.

When you say you would be interested in a custom plugin, what functionality
are you missing in this one?

I tagged this question as invalid since it would be more appropriate to
post it on the dicom-support plugin support
<https://wordpress.org/support/plugin/dicom-support> page.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ivmartel/dwv/issues/245#issuecomment-230714516>, or mute
the thread
<https://github.com/notifications/unsubscribe/ATVTa4KqigH2tHF2OWNDN9r-DwbCUO20ks5qS2wCgaJpZM4JD-JC>
.

**Comment by ivmartel** [comment]
About activating the viewer for image files, you can change in the `DicomSupport.php` file `post_gallery` method, the line:

`'post_mime_type' => 'application/dicom',`

by:

`'post_mime_type' => array('application/dicom', 'image/jpeg'),`

The plug in does not include the viewer (as the demo on github), it just injects the code to create a viewer for the images you give it. If you want these demo viewers, you need to copy the dwv release and your preferred viewer from https://github.com/ivmartel/dwv/tree/master/viewers.

**Comment by snek60** [comment]
Okay thank you very much this is awesome.
I was wondering too if it is possible to add a button "Play/Pause" that
would play in loop the files in the image stack at a speed of 5 frame per
second like a video or zomething like that, is that possible ? To play
cardiac cine dicoms ? Doesnt your plug in already support this in the other
viewers ?

Thanks a lot!

Le 12 juil. 2016 12:07 PM, "ivmartel" <notifications@github.com> a écrit :

>

> About activating the viewer for image files, you can change in the
DicomSupport.php file post_gallery method, the line:
>
> 'post_mime_type' => 'application/dicom',
>
> by:
>
> 'post_mime_type' => array('application/dicom', 'image/jpeg'),
>
> The plug in does not include the viewer (as the demo on github), it just
injects the code to create a viewer for the images you give it. If you want
these demo viewers, you need to copy the dwv release and your preferred
viewer from https://github.com/ivmartel/dwv/tree/master/viewers.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
<https://github.com/ivmartel/dwv/issues/245#issuecomment-231995916>, or
mute the thread
<https://github.com/notifications/unsubscribe/ATVTa1I9k6SAQlrA9NnIf7CVDJWGlWSZks5qU2dFgaJpZM4JD-JC>
.

**Comment by snek60** [comment]
Or maybe just allowing looping of the image stack (infinite scrolling)
would do the trick as the cine video would play as long as the user is
scrolling through the stack. Just another idea.

**Comment by ivmartel** [comment]
This is another topic. I'm closing this one as resolved and you can create a new issue for the Play/Pause.
