### ISSUE TITLE
Loop scrolling 

### ISSUE THREAD

**Issue by snek60** [ivmartel/dwv#251]
Hello.
Is there a code settings that can be altered to have infinite scrolling ? (Go back at image 1 when scrolling over the last image).
I am looking at a way to display the image stack like a looping video either by infinite scrolling or a play / pause button with 5 frame per second for example.

Thanks in advance.

**Comment by ivmartel** [comment]
The viewer does not have this functionality integrated. But it can be done externally.  You need a button that triggers a loop that calls `app.getViewController().incrementSliceNb()`.

**Comment by ivmartel** [comment]
Closing for now. Feel free to re-open or create a new issue if you have problems.
