### ISSUE TITLE
DicomWriter

### ISSUE THREAD

**Issue by jssuttles** [ivmartel/dwv#252]
I tried to use the DicomWriter for something that I'm working on but it doesn't seem to work as intended.
Here's a fiddle: https://jsfiddle.net/v2j2n6pc/45/
I think it has something to do with the sorting and the file meta and the FileMetaInformationGroupLength not being placed at the top and changed. I tried to fix it up but I'm working on this immense project that only recently needs to be able to manipulate DICOM meta data. Generally, I just work with basic well documented node modules that do small specific things. DICOM meta data seems to be very complex and difficult to manipulate.

**Comment by ivmartel** [comment]
I updated this class a few weeks ago and added example html pages to anonymise or create test DICOM files. You can find all this in the current code, I should release it soon as version 0.15.
I hope this helps you solve your problem.

**Comment by ivmartel** [comment]
Closing for now, feel free to re-open or create a new issue if you have problems.
