### ISSUE TITLE
Mobile viewer crash with big number of images on Google Chrome

### ISSUE THREAD

**Issue by ftaurino** [ivmartel/dwv#255]
Hi all,

I've a mobile viewer, version 0.15-beta, which can display CT with over 200 images with no glitches.
But when I try to load a CT with over 400 images, the Google Crome (version 52) tab crashes.
Firefox 47 is slower than Chrome in rendering the two series, but it does not crash.
The Mozilla browser also correctly display the spinning circle while receiving the images...

Francesco

**Comment by ivmartel** [comment]
Kind of similar to #236, you are reaching the maximum the browser can handle. I need to find a better way of handling memory.

**Comment by Zaid-Safadi** [comment]
One way might be to support virtual loading of images. such that you load only enough for current view + X (where X is a number of adjacent images) and on scroll you start pre-loading and freeing. Another way would be loading the full stack in low resolution e.g. 128x128 (if possible) as a preview and when user release the scroll start loading the current full resolution image, this might require a server that support fetching low resolution though.

**Comment by ajabnoor** [comment]
this can be a good solution Zaid

**Comment by vmaindarkar** [comment]
I handled the big data but having one issue. In some case Tool.info.position count start from zero and in some case it's shows max count. Can u help how it's come

**Comment by ivmartel** [comment]
See #323 for more information.

@vmaindarkar, could explain what you mean when you say "I put the paging for images with 25 images"?

**Comment by ivmartel** [comment]
I like @Zaid-Safadi's solution too, I created #342 for that.

Closing this issue since it is a bit old, checkout #342 for progress!

**Comment by ivmartel** [comment]
_Not sure about labels, wontfix now but will in kind of duplicate #342..._
