### ISSUE TITLE
How can i associate default file ?

### ISSUE THREAD

**Issue by ziaahmedshaikh** [ivmartel/dwv#256]
I want to connect DWV with my custom written c# application in which i already have an array of .dcm files. I want this DWV to load those files initially by default as user comes to DWV window.

Please let me know how can i pass an array of default files ?

**Comment by ivmartel** [comment]
You need to use the application [`loadUrls`](https://github.com/ivmartel/dwv/blob/master/src/app/application.js#L525) method.
Set up the app as usual and then pass the files list.
