### ISSUE TITLE
Can i draw/highlight separated pixels, not lines?

### ISSUE THREAD

**Issue by kmanijak** [ivmartel/dwv#258]
Hi, I would like to mark some area on the image, I have got an array of coordinates, so I can create an array of Point2D. I tried to use RoiFactory and other tools, but actually it uses them to draw a lines, rectangles, countours. I haven't found a tool which would just highlight the separated pixels.
Is there any or should I write it myself?
Thanks in advance.

**Comment by ivmartel** [comment]
The functionality your are describing is not available. How do you want to highlight pixels?

**Comment by ivmartel** [comment]
Still waiting for an answer... Closing for now...
