### ISSUE TITLE
Image sorting

### ISSUE THREAD

**Issue by rafasoyyo** [ivmartel/dwv#261]
I have associated some data to each layer but I am having problems with the sorting when I ask for the data that I have previously set. I am trying to find out how do you handle the sorting of the images but I cannot find it... could you help me with this???

Thanks in advanced!

**Comment by ivmartel** [comment]
If by data you mean draw data, then to associate a draw layer to a slice/frame, I have a big two-dimensional array in the application.js: the [drawLayers](https://github.com/ivmartel/dwv/blob/master/src/app/application.js#L66). 
Does this answer your question? What data are you trying to sort?

**Comment by rafasoyyo** [comment]
Hi, 

You can see the data I try to associate here: https://github.com/rafasoyyo/dwv/blob/master/src/app/application.js#L485 https://github.com/rafasoyyo/dwv/blob/master/src/app/application.js#L560 

You can see how I do it here: https://github.com/rafasoyyo/dwv/blob/master/src/app/application.js#L612 

And how I get it here: https://github.com/rafasoyyo/dwv/blob/master/src/app/state.js#L38 

The issue is that, sometimes, if you order files alphabetically by their names, the result does not correspond with the real image sorting. When this happen, the data I have associate is not correctly sorted and I do not know how do you order the image before display them to fix it.

Thanks for your help

PD.- In this cases DWV sort the images on a different way compared with most populars dicom viewers.

**Comment by ivmartel** [comment]
The slice sorting is done in the Image class, in the [appendSlice](https://github.com/ivmartel/dwv/blob/master/src/image/image.js#L294) method. It uses the slice origin (the ImagePositionPatient) to guess where it should insert the slice.
Do you have example data you can share where the sorting fails?

**Comment by rafasoyyo** [comment]
I have changed my code. 

Now I define the information here: https://github.com/rafasoyyo/dwv/blob/master/src/image/image.js#L162-L175 

I add the data here: https://github.com/rafasoyyo/dwv/blob/master/src/image/image.js#L381 

And I get them back like this: 
https://github.com/rafasoyyo/dwv/blob/master/src/app/state.js#L40

Thanks for your help and your quickly reply.

You can close this issue and utilize the code if you think that it could be helpfull

**Comment by ivmartel** [comment]
Do you do this because the current dwv code does not work? I'm not sure I get what your code fixes...

**Comment by rafasoyyo** [comment]
No , DWV works fine, but I need to be able to match drawings and slices with the ImagePositionPatient tag, that the reason of that feature.

PD.- About the images sorting, I realized that some dicom viewer sort the images from last to first, instead from first to last as your code does.

**Comment by ivmartel** [comment]
Hi, following on this one, the changes made to fix #317 improve slice sorting. Different orientations are now supported and the order is defined using the DICOM orientation matrix.

**Comment by jonesf14** [comment]
When I use the DMV plugin for Wordpress on sagittal projections the slices are out of order when scrolling.  I don't have this issue on axial. Does this relate to this issue?  If so, could you possibly update the plugin with this fix?

**Comment by ivmartel** [comment]
Yes, it is related. Could we continue this discussion on the thread of #317 please?
