### ISSUE TITLE
DICOM Writer

### ISSUE THREAD

**Issue by nvd-ai** [ivmartel/dwv#264]
Does DWV currently support manipulating and exporting DICOM files? If not, is there is plan to implement this in the future?

**Comment by ivmartel** [comment]
DWV has got a 'beta' class to write DICOM: [dicomWriter](https://github.com/ivmartel/dwv/blob/master/src/dicom/dicomWriter.js). First written to anonymise data, it can also be used to create new data. You can see some example usage in the tests folder: [dicom/anonymiser.html](https://github.com/ivmartel/dwv/blob/master/tests/dicom/anonymiser.html) and [dicom/generator.html](https://github.com/ivmartel/dwv/blob/master/tests/dicom/generator.html). I used them to create test data, I hope they are still functional!

**Comment by nvd-ai** [comment]
Works just fine. I can properly create a JSON object, write elements and pixel data, export and open it in a DICOM viewer. The DICOM dictionary file is very helpful. Thanks for references.

just wondering: to attach an image the default bits per pixel is 16. The images I am working with are 8bit per pixel. I changed the "BitsAllocated" in DICOM object to 8, which caused an error in the writer.  My current workaround is to set "BitsStored" to 8 and "HighBit" to 7 and it works just fine. But I am guessing the generated pixel array is twice the necessary size. Do you have any suggestions for supporting 8bit images?

**Comment by ivmartel** [comment]
The generated pixel data uses 16bits. You could modify the generator to create 8bit data, check from this line [generator.html#L183](https://github.com/ivmartel/dwv/blob/master/tests/dicom/generator.html#L183) to the creation of the `dicomElements.x7FE00010`.
It could be an option of the generator, not sure how to implement it since the JSON is only the DICOM tags.

**Comment by nvd-ai** [comment]
It can be an input argument in the writer call. For now I got around it by keeping pixel data as 2 bytes. If I get to fix the library, I will request a pull. Closing the issue for now.

Thanks for the timely support.

**Comment by rafasoyyo** [comment]
I think something got broken.
Tested on version 18 with 12 diferentes images from different acquisition machines.
Error: Offset is outside the bounds of the DataView.

**Comment by ivmartel** [comment]
Thanks @rafasoyyo, could you create a new issue with this problem?
