### ISSUE TITLE
After loadURLs, For some images Scrolling down doesn't work.

### ISSUE THREAD

**Issue by patilms16** [ivmartel/dwv#268]
Hi,

I am reading the image file names from a directory via nodeJS http sevice and sending the array of  URLS to following function : 

``` javascript
$scope.feedImagesToDWV = function(imageList, dirUrl){
    var list = [];
    _.each(imageList, function(fileName) {
        list.push(dirUrl + "/" + fileName);
    });
    $scope.autoViewConfig.mrDwv.loadURLs(list);         
 }
```

once above images series get loaded, If I scroll down mouse wheel, image scrolling doesn't happen. I have to scroll up mouse wheel for scrolling images and after this scrolling down takes me to default state.

This happens for some image series only. For other image series after image loading I can scroll down  mouse wheel and scrolling works perfectly.

Could someone please let me know what would be the reason for such behavior? (I tried with .dcm and .jpg formats)
Should I load images in any sequence so that scroll down works every time?

**Comment by ivmartel** [comment]
I don't see anything wrong with your code. 
Isn't it just that you are a slice 0 and you can't go less?

**Comment by ivmartel** [comment]
No answer so closing for now, feel free to reopen.
