### ISSUE TITLE
PixelData parse error. PixelData VR=OB,TransferSyntax=1.2.840.10008.1.2.1

### ISSUE THREAD

**Issue by Refactoring** [ivmartel/dwv#270]
As described in the title, (7FE0,0010)Pixel Data VR=OB  and (0002,0010)Transfer Syntax=1.2.840.10008.1.2.1, when pixeldata parse error. <br>

My Capacity is limited, I don't know where to start.  :)
[Download DCM File:](https://www.thinkingnote.com/TESTDCM.zip)

DWV Parse:
![qq 20160924223547](https://cloud.githubusercontent.com/assets/451129/18809175/11d8cbbe-82a8-11e6-8d4e-fefb3d3a06b5.jpg)
ClearCanvas Parse:
![qq 20160924223553](https://cloud.githubusercontent.com/assets/451129/18809174/1153a6d2-82a8-11e6-9929-dd48a7062ae4.jpg)

**Comment by ivmartel** [comment]
Hi, I can't find the test data, the TESTDCM zip file just contains a corrupted png file. Could you recreate it?

**Comment by Refactoring** [comment]
Modify the file extension name for “.dcm”  or download again.

**Comment by Refactoring** [comment]
![1](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

----
I'm too stupid! I had seen your modified code, I follow the `bitsAllocated` judgement, but I was the original `else if (VR === "OB")` logic in the process, I found my code forgot `else`. 

```
    // OB
    else if( vr === "OB")
    {
        // PixelRepresentation 0->unsigned, 1->signed
        var pixelRep = 0;
        if ( typeof this.dicomElements.x00280103 !== 'undefined' ) {
            pixelRep = this.dicomElements.x00280103.value[0];
        }
        if(tag.name === "x7FE00010"){
            //TODO bitsAllocated logic process
            data = reader.readUint16Array( offset, vl );
        }
        // read accordingly
        /*forgot else*/ if (pixelRep === 0) { 
           data = reader.readUint8Array( offset, vl );
        }
        else {
           data = reader.readUint8Array( offset, vl );
        }
        offset += vl;
    }
```
