### ISSUE TITLE
Opening Images with different Series instance UID

### ISSUE THREAD

**Issue by hassaankamran** [ivmartel/dwv#276]
Hi ivmartel,
                 I got an error on opening images if they have different series instance UID, different no of rows or coloumns etc. Is there any way of opening each series in different canvas or tabs. Mainly reffering to MRI or CT study. Kindly suggest me any other solution if you having.

**Comment by ivmartel** [comment]
When you pass multiple files to dwv it tries to put them together in one volume. So when they have different sizes it cannot know how to do that and gives you the error. It also checks some meta data such as the series/study UID, if different then it suggests they cannot be appended. 
You could have a page with two instances of dwv, one for each image. Different tabs will also work. 

What is your use case? Do you want to compare images? If you looking for one being overlaid on the other this is not possible, but would be a nice addition!

**Comment by ivmartel** [comment]
Problem seems solved so closing for now, feel free to reopen.

**Comment by LaedaSt** [comment]
Hello, i have the same problem, but in one volume of files. User gets his "disk" in hospital, then tries to upload it on my app, and there is this problem. I don`t know why he got diffrents files (seriers UID and number of columns) in one "disk", but is there any way to make all of files be in the same format? Thank you!
