### ISSUE TITLE
Open /viewers/static/index.html on Firefox 49.0.2 failed

### ISSUE THREAD

**Issue by fcjxxl** [ivmartel/dwv#279]
Console logs as follows:

**DOMException [NS_ERROR_DOM_BAD_URI: "Access to restricted URI denied"
code: 1012
nsresult: 0x805303f4
location: file:///E:/dwv/ext/i18next/i18nextXHRBackend.min.js:1]i18nextXHRBackend.min.js:1:860
DOMException [NS_ERROR_DOM_BAD_URI: "Access to restricted URI denied"
code: 1012
nsresult: 0x805303f4
location: file:///E:/dwv/ext/i18next/i18nextXHRBackend.min.js:1]**

**Comment by ivmartel** [comment]
For development purposes, I use [http-server](https://github.com/indexzero/http-server) based on node.js. It avoids this kind of problems when accessing local files.

That being said, Chrome gives the same kind of error but allows to run the app.

**Comment by fcjxxl** [comment]
I want to integrate dwv into a existing project(e.g. a website called ProA), is that mean common user can't use Firefox to view dicom images on ProA?

**Comment by ivmartel** [comment]
I'm sorry but I do not know ProA, would you have a link?
If it comes with a http server, then there should be no problem.

**Comment by fcjxxl** [comment]
I'm sorry but I don't have a link now, it's still in developing.
You mean if dwv is running on a http server rather than locally there should be no such browser problems, right?

**Comment by ivmartel** [comment]
Yes.

**Comment by fcjxxl** [comment]
Thank you.
