### ISSUE TITLE
How to preload images

### ISSUE THREAD

**Issue by niravpatel** [ivmartel/dwv#280]
As we need to click on + sign, can anyone tell me how would I load images directly

**Comment by ivmartel** [comment]
You can either load the data:
 * via the input url, something like: `https://ivmartel.github.io/dwv/demo/stable/viewers/mobile/index.html?input=https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dosirix-toutatix-100.dcm%26file%3Dosirix-toutatix-101.dcm&dwvReplaceMode=void`, check out the [IO user story](https://github.com/ivmartel/dwv/wiki/User-Stories#io)

* in the code of your web page using the `app.loadURLs()` as I do in the visual tests: [tests/visual/appgui.js#L66](https://github.com/ivmartel/dwv/blob/master/tests/visual/appgui.js#L66)

**Comment by niravpatel** [comment]
Thanks for your all helps :) great tool :+1:

**Comment by ivmartel** [comment]
Thanks. Closing for now, feel free to reopen if you still have questions!
