### ISSUE TITLE
multi-frame support in dicomWriter

### ISSUE THREAD

**Issue by yulia-tue** [ivmartel/dwv#294]
Hi there, 
thanks a lot for your work on this! 
The comment in the dicomWriter file says, that multi-frame images are not supported yet. Are you planning on working on this part? This would really help my project.
Best,
Yulia

**Comment by ivmartel** [comment]
No time on my side in the close future... Could you do it if I guide you?

**Comment by yulia-tue** [comment]
That would be great! 
I saw that currently dicomWriter only takes element.value[0] for pixel data whereas element.value is an array of arrays for multi-frame.

So does the element.value needs to be flatten from array of arrays to a large array first?

**Comment by ivmartel** [comment]
Yes, that should do the trick. You also need to set the `NumberOfFrames` tag.

**Comment by yulia-tue** [comment]
I added the method to flatten the array and NumberOfFrames tag was already set. Please check the pull request.

**Comment by ivmartel** [comment]
Thanks @yulia-tue for pull request #296!
