### ISSUE TITLE
anonymisation rules can't be defined per tag itself, e.g x00100020

### ISSUE THREAD

**Issue by yulia-tue** [ivmartel/dwv#297]
Hi, 
for my project I want to use tags instead of tag names in anonymisation rules, so that I don't need to compile the dictionary since we have a lot of private manufacturer tags in our images. 
I also think that the order of rule checking in dicomWriter should be a little bit different: 
1. init with default rule
2. check if a group name rule is available, if so, apply it
3. check if tag name rule is available, if so, apply it 
(4. check if tag rule is available, if so, apply it)

In this order you can specify a rule for the group and a special rule for a tag name in the group and it won't be overridden, as it happens now. 

If you think, that would be useful I could send you a pull request. 

Best,
Yulia

**Comment by ivmartel** [comment]
I'm ok with adding tag key rules.

But I'm not sure I get your reordering... The current order defined in [dicomWriter.js#L500](https://github.com/ivmartel/dwv/blob/master/src/dicom/dicomWriter.js#L500) is:
1. if tag name rule, apply it
1. if group name rule, apply it
1. if none, use default

Which does what you want: specify a default group rule and some specific for tags inside that group. The tag names are the ones defined in the `dictionary.js` file and use camel case (no spaces between words). Whereas the group names can contain spaces. Could it be that you misspelled?

The tag key rule could go before or after the tag name rule.

**Comment by yulia-tue** [comment]
Hi, 
you are right, I confused this a little. 
Should I add the tag rule as the first 'if' then or between the tag and the group?

**Comment by ivmartel** [comment]
Ok. Having it as first 'if' looks good.

**Comment by yulia-tue** [comment]
Thanks for accepting my merge request. 
Really great work, ivmartel! Thanks a lot
