### ISSUE TITLE
Can not open files via url

### ISSUE THREAD

**Issue by Sorbon07** [ivmartel/dwv#298]
Hi ivmartel, i cant open dicom files via url, get error: An Error occured while retrieving the binary file (via http) how can I solve this problem?

**Comment by ivmartel** [comment]
Your problem is maybe related to Same Origin Policy, check the [requesterror](https://github.com/ivmartel/dwv/wiki/Error-Messages#requesterror) wiki page.
tl;dr Either tell the browser to not do security checks or run your code in a local server.

**Comment by ivmartel** [comment]
Closing for now. Feel free to re-open if you have questions.

**Comment by mtaylor456** [comment]
WHat do you mean with same origin policy? This should not affect image files, I can load an image from another server in HTML so why not JS?

**Comment by ivmartel** [comment]
By default, you can't directly query for local files from JavaScript, like when you try to load files from url. This is considered a security breach and is also labelled as a 'Cross origin request' (your file system being another origin, I guess). The W3C drafted a FileSystem API but did not go through with it so there is no programmatic way of going around this. 

The way I recommend to do load files via url is by using a local http server.
