### ISSUE TITLE
dwv.min.js or Clarification of the minimum dependencies

### ISSUE THREAD

**Issue by ivanhuay** [ivmartel/dwv#299]
I do not know what are the minimal dependencies.

It could generate a dwv.min.js that includes all the necessary files for the operation. For this you can use browserify or concatenate and minify the files.

It is very confusing for me the number of js files included in the examples.

**Comment by ivanhuay** [comment]
Find the .min.js file but it is not in the repo but in the release list

https://github.com/ivmartel/dwv/releases

**Comment by HernanGH** [comment]
+1

**Comment by brian91dd** [comment]
+1

**Comment by ivmartel** [comment]
As specified in [Gruntfile.js#L33](https://github.com/ivmartel/dwv/blob/master/Gruntfile.js#L33), the minified version is created from all the js code in the `src` folder.

I do not know how to tell bower to include the min.js file, do you?

But you are right, there should be more doc on the dependencies!

**Comment by ivanhuay** [comment]
@ivmartel Apparently the only way is to add the .min.js file to the repository in the dist folder.

**Comment by ivmartel** [comment]
I'm cleaning up in the process of making dwv module compatible (see 12cfd2b). Once it is I will put the release in a 'dist' folder.

**Comment by ivmartel** [comment]
v0.19.0 should fix this issue.
