### ISSUE TITLE
I'm working with a client that wants a DICOM server and 10+ viewer clients.

### ISSUE THREAD

**Issue by webguy210** [ivmartel/dwv#304]
I've seen your solution here on GitHub, I've played with the online demo page.  I don't see search / query but the viewer is close to meeting my client's requirements.  Can I contact you privately to discuss this?
I need a few missing features:
   1 - Search / Query with image preview in the search results.
   2 - ability to show 2 images side by side when viewing images.
   3 - ability to show 4 images (2x2) when viewing images.

**Comment by ivmartel** [comment]
My email is there: https://github.com/ivmartel
