### ISSUE TITLE
dicomWriter support for tags with "u/l" value length 

### ISSUE THREAD

**Issue by yulia-tue** [ivmartel/dwv#308]
Hi there, 

could you please provide some guidance on how I could patch this issue? 
I have an example dicom file that gets parsed with sequences (vr="SQ") and pixel data elements (vr="OB") with vl="u/l". So the dicomWriter can't handle those: before getting the buffer we need the size and its NaN. 
I believe I could calculate the length of those elements before writing, could you help me with this?

Here is the file: 
https://www.dropbox.com/s/sj1t125fcvmtykp/private_tags.dcm?dl=0

**Comment by ivmartel** [comment]
Hi, sorry for taking so long, I created a branch for this: [308-dicom-write-ul](https://github.com/ivmartel/dwv/tree/308-dicom-write-ul).
It is passing the tests and seems to anonymise your data well. Can you try it and tell me what you think?

**Comment by yulia-tue** [comment]
Hi, thanks a lot for the effort! I'll have a look at the branch and try to run it with my other data. I'll let you know.
cheers

**Comment by yulia-tue** [comment]
Hi there, 
I tested the code on my other data and it works great on most, but some have the following problem: 
the first item (basic offset table), we read in dwv.dicom.DicomParser.prototype.readPixelItemDataElement, has in some files a value and a value length, for example an array of zeros of length 4. This length is being calculated into the length of the whole pixel sequence, but the item itself is ignored.
When we then write the pixel sequence we create a "dummy" first item with a null value and a length of 0. So we have 4 bytes left at the end of the buffer. And when we try to parse back the created buffer, it fails because we haven't reached the buffer length after the last element. 
Unfortunately, I am not sure whether I can provide the example file here, since we work with files from real studies, but I hope you get the idea.
I'll try to think of a patch for this behavior. 
Hope this feedback helps.

**Comment by yulia-tue** [comment]
please have a look at my pull request, thanks a lot! :) 
#312
