### ISSUE TITLE
Add support for different image orientation

### ISSUE THREAD

**Issue by ivmartel** [ivmartel/dwv#317]
DICOM data have orientation information that needs to be taken into account. One effect is the bad ordering of slices when the axis perpendicular to the slices is not Z as expected in the `geometry.getSliceIndex` method.

**Comment by ivmartel** [comment]
Following your comment on #261, @jonesf14, before updating the wordpress plugin, could you try loading your data on the [trunk demo page](https://ivmartel.github.io/dwv/demo/trunk/viewers/mobile/index.html) and check it is ok?

**Comment by jonesf14** [comment]
Yes, I just checked and it scrolls correctly on the demo page.  Thanks.

**Comment by jonesf14** [comment]
Any plans to update the Wordpress plugin to fix this issue?  Thank you for all your help!! @ivmartel

**Comment by ivmartel** [comment]
I'm on it. Hoping to have something in the next days!

**Comment by jonesf14** [comment]
Thanks! 😁

**Comment by ivmartel** [comment]
🚀 dwv v0.18.0 corrected and [dicom-support](https://wordpress.org/plugins/dicom-support/) wordpress plugin v0.5.2 published! Tell me how it goes!

And if possible, can you tell what you will use the wordpress plugin for and in which context?

**Comment by jonesf14** [comment]
Great. Thanks!  I am a radiology resident and I'm working on an educational website to help residents prepare for call.
