### ISSUE TITLE
i18next.min.js fail?

### ISSUE THREAD

**Issue by jiapei100** [ivmartel/dwv#320]
Hi, all:

I'm testing dwv, but met the following ERROR message:

> i18n: Test i18n en. (10, 0, 10)Rerun35 ms
> Failed loading 'en' language.@ 13 ms
> Expected: 	
> true
> Result: 	
> false
> Source: 	
>     at ....../dwv/tests/utils/i18n.test.js:18:16
>     at ....../dwv/ext/i18next/i18next.min.js:1:8313
>     at Array.forEach (native)
>     at t.e.emit (....../dwv/ext/i18next/i18next.min.js:1:8291)
>     at Function.<anonymous> (....../dwv/ext/i18next/i18next.min.js:1:28604)
>     at ....../dwv/ext/i18next/i18next.min.js:1:8400
> Assertion after the final `assert.async` was resolved@ 15 ms
> Source: 	
>     at Assert.equal (....../dwv/ext/qunit/qunit-2.1.1.js:1792:11)
> i18n en translation exists@ 15 ms
> Expected: 	
> true
> Result: 	
> false
> Source: 	
>     at ....../dwv/tests/utils/i18n.test.js:28:20
>     at ....../dwv/ext/i18next/i18next.min.js:1:8313
>     at Array.forEach (native)
>     at t.e.emit (....../dwv/ext/i18next/i18next.min.js:1:8291)
>     at Function.<anonymous> (....../dwv/ext/i18next/i18next.min.js:1:28604)
>     at ....../dwv/ext/i18next/i18next.min.js:1:8400
> Assertion after the final `assert.async` was resolved@ 16 ms
> Source: 	
>     at Assert.equal (....../dwv/ext/qunit/qunit-2.1.1.js:1792:11)
> i18n en translation is ok@ 17 ms
> Expected: 	
> "Open"
> Result: 	
> "basics.open"
> Diff: 	
> "Obasics.open"
> Source: 	
>     at ....../dwv/tests/utils/i18n.test.js:29:20
>     at ....../dwv/ext/i18next/i18next.min.js:1:8313
>     at Array.forEach (native)
>     at t.e.emit (....../dwv/ext/i18next/i18next.min.js:1:8291)
>     at Function.<anonymous> (....../dwv/ext/i18next/i18next.min.js:1:28604)
>     at ....../dwv/ext/i18next/i18next.min.js:1:8400
> Assertion after the final `assert.async` was resolved@ 18 ms
> Source: 	
>     at Assert.equal (....../dwv/ext/qunit/qunit-2.1.1.js:1792:11)
> i18n en translation exists@ 18 ms
> Expected: 	
> true
> Result: 	
> false
> Source: 	
>     at ....../dwv/tests/utils/i18n.test.js:28:20
>     at ....../dwv/ext/i18next/i18next.min.js:1:8313
>     at Array.forEach (native)
>     at t.e.emit (....../dwv/ext/i18next/i18next.min.js:1:8291)
>     at Function.<anonymous> (....../dwv/ext/i18next/i18next.min.js:1:28604)
>     at ....../dwv/ext/i18next/i18next.min.js:1:8400
> Assertion after the final `assert.async` was resolved@ 19 ms
> Source: 	
>     at Assert.equal (....../dwv/ext/qunit/qunit-2.1.1.js:1792:11)
> i18n en translation is ok@ 19 ms
> Expected: 	
> "Close"
> Result: 	
> "basics.close"
> Diff: 	
> "Cbasics.close"
> Source: 	
>     at ....../dwv/tests/utils/i18n.test.js:29:20
>     at ....../dwv/ext/i18next/i18next.min.js:1:8313
>     at Array.forEach (native)
>     at t.e.emit (....../dwv/ext/i18next/i18next.min.js:1:8291)
>     at Function.<anonymous> (....../dwv/ext/i18next/i18next.min.js:1:28604)
>     at ....../dwv/ext/i18next/i18next.min.js:1:8400
> Too many calls to the `assert.async` callback@ 19 ms
> Source: 	
>     at ....../dwv/tests/utils/i18n.test.js:34:9
>     at ....../dwv/ext/i18next/i18next.min.js:1:8313
>     at Array.forEach (native)
>     at t.e.emit (....../dwv/ext/i18next/i18next.min.js:1:8291)
>     at Function.<anonymous> (....../dwv/ext/i18next/i18next.min.js:1:28604)
>     at ....../dwv/ext/i18next/i18next.min.js:1:8400
>     at Array.forEach (native)
>     at t.e.emit (....../dwv/ext/i18next/i18next.min.js:1:8372)
> Source: at ....../dwv/tests/utils/i18n.test.js:42:7
> i18n: Test i18n fr. (10, 0, 10)Rerun29 ms
> Source: at ....../dwv/tests/utils/i18n.test.js:51:7
>

Can anybody help please?

Cheers
Pei

**Comment by ivmartel** [comment]
These tests cannot be run from the local file system since they load the translation files via an `XMLHttpRequest`. Browsers consider it a `Cross origin request` and forbid it for local files. The solution is to run the tests from a local web server.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to reopen.
