### ISSUE TITLE
Tool.info.position issue in some case

### ISSUE THREAD

**Issue by vmaindarkar** [ivmartel/dwv#323]
Hi all,

I've a mobile viewer, which can display DR, CT, MRI images etc.
But when I try to load a CT with over 50 images then mobile browser gets crashes (in case low RAM devices)
So I put the paging for images with 25 images after that next page load with another 25 images get load and so on. 
But in some case Tool.info.position shows = 24 count where as in some case Tool.info.position = 0. Due to this my next & previous paging not work proper.

**Comment by vmaindarkar** [comment]
Its means for A patient its shows myapp.getViewController().getCurrentPosition().k value shows zero and for another B patient myapp.getViewController().getCurrentPosition().k shows 24 count while load the page

**Comment by ivmartel** [comment]
The current position is set by the first slice to be loaded. Since the loading process is asynchronous, any slice could be the current one if it arrives first. The rest of the slices are then appended to the image following the image position patient DICOM tag.
Could this be what you are seeing?

**Comment by ivmartel** [comment]
Closing for now (old issue, still valid?), feel free to comment if you need.
