### ISSUE TITLE
setWindowLevel() not working in v0.18.0 and v0.19.X

### ISSUE THREAD

**Issue by yoannpe** [ivmartel/dwv#331]
Hi, 

I used to use DWV v0.17.0 and everything worked well but when I updated to v0.19.2, the setWindowLevel() function (viewerApp.getViewController().setWindowLevel()) stopped working. It doesn't show any error, it just doesn't change the window level.

I tried every versions between v0.17.0 and v0.19.2 and the error is present in all of them.

Thanks.

**Comment by ivmartel** [comment]
The `viewerApp.getViewController().setWindowLevel()` method is used by the window/level tool and is working in the demos.
The class changed quite a lot when fixing #316. Maybe the sequence of calls changed and someone is changing (again) the window level after your call?

**Comment by yoannpe** [comment]
It's strange but I achieved to make it work by calling : 
`this.viewerApp.getViewController().addWindowLevelPresets( { "manual": {
            "wl": new dwv.image.WindowLevel(this.windowCenter, this.windowWidth),
            "name": "manual"} } );
    this.viewerApp.getViewController().setWindowLevelPreset("manual");` instead of `viewerApp.getViewController().setWindowLevel()`

Thank you for your help !

**Comment by ivmartel** [comment]
Ok, I had a look into it and you are right, it does not work as it should! I'll try to think about a solution...
