### ISSUE TITLE
how to load an JSZip uncompressed file to DWV?

### ISSUE THREAD

**Issue by arturojain** [ivmartel/dwv#332]
I'm trying this but it doesn't seem to work

```javascript
JSZip.loadAsync(data)
	.then(function (zip) {
		zip.file('1.dcm').async("arraybuffer").then(function (file) {
			app.loadFiles([file])
		})	
	})
```

I think it has something to do with the file format.

**Comment by ivmartel** [comment]
The `loadFiles` method takes as input a list of (web API) Files as defined [here](https://developer.mozilla.org/en-US/docs/Web/API/File). It will not work with an `arraybuffer`. 

What would need to be done is more like what you can find in [io/file.js](https://github.com/ivmartel/dwv/blob/master/src/io/file.js), which is not that well designed... If you know of a better one, I'm interested!

**Comment by tmskmr** [comment]
Hi, I have done it successfully as follows:
1. create a new class "dwv.io.Memory" from dwv.io.File (see the attached file)
[memory.zip](https://github.com/ivmartel/dwv/files/960404/memory.zip)

2. add a new function loadImagesFromMemory() to dwv.App
`    this.loadImagesFromMemory = function (files)
    {
        // clear variables
        self.reset();
        nSlicesToLoad = files.length;
        // create IO
        var memIO = new dwv.io.Memory();
        memIO.setDefaultCharacterSet(defaultCharacterSet);
        memIO.onload = function (data) {
            if ( image ) {
                view.append( data.view );
                if ( drawStage ) {
                    appendDrawLayer(image.getNumberOfFrames());
                }
            }
            postLoadInit(data);
        };
        memIO.onerror = function (error) { handleError(error); };
        memIO.onloadend = function (/*event*/) {
            if ( drawStage ) {
                activateDrawLayer();
            }
            fireEvent({ 'type': 'load-end' });
        };
        memIO.onprogress = onLoadProgress;
        // main load (asynchronous)
        fireEvent({ 'type': 'load-start' });
        memIO.load(files);
    };
`
3. call the above function as follows 
`var filename = "";
var files = [];
var zobjs = null;

/**
 * JSZip.async callback
 * @param {ArrayBuffer} content unzipped file image
 * @return {}
 */
var prefixUnzip = "Unzipping... ";
function zipAsyncCallback(content)
{
	files.push({"filename": filename, "data": content});
	dwv.gui.displayProgress(Math.round(files.length*100/zobjs.length), prefixUnzip);

	if (files.length < zobjs.length){
		var num = files.length;
		filename = zobjs[num].name;
		zobjs[num].async("arrayBuffer").then(zipAsyncCallback);
	}
	else
		TheApp.loadImagesFromMemory(files);
}

/**
 * JSZip.loadAsync callback
 * @param {JSZip} zip JSZip object
 * @return {}
 */
function loadAsyncCallback(zip)
{
	files = [];
	zobjs = zip.file(/.*\.dcm/);

	var num = files.length;
	filename = zobjs[num].name;
	zobjs[num].async("arrayBuffer").then(zipAsyncCallback);
	dwv.gui.displayProgress(0, prefixUnzip);
}

/**
 * Load images in DMX file after download from URL
 * @param {String} url URL to download
 * @return {}
 */
var prefixDownload = "Downloading... ";

function loadFromDmxFile( url )
{
	dwv.gui.displayProgress(0, prefixDownload);

	JSZipUtils.getBinaryContent(url, function(err, data) {
		if(err) {
			alert(err.name+": "+err.message+".");
		}

		dwv.gui.displayProgress(100);
		JSZip.loadAsync(data).then(loadAsyncCallback);
	}, function( event ) {
		if (event.lengthComputable){
			dwv.gui.displayProgress(Math.round(event.loaded*100.0/event.total), prefixDownload);
		}
	});
}

`

**Comment by ivmartel** [comment]
I adapted your code to the new design, see #339. 

One difference is the zipped file extension, you use `dmx`, what is it?

**Comment by tmskmr** [comment]
Thank you for your adaptation. I am glad to make some contribution to this  software.
The dmx extension is used locally in a DICOM images database site for associating the zipped file to the program  which unzip it and invoke a standalone viewer. You may ignore it.

**Comment by ivmartel** [comment]
Thanks to you! Closing this issue for now, feel free to reopen if you see a problem.
