### ISSUE TITLE
Allow for easier file loader integration 

### ISSUE THREAD

**Issue by ivmartel** [ivmartel/dwv#337]
The file/url loading code is not flexible: it is complicated to add support for a new file extension. This must be made more adaptable.

**Comment by rafasoyyo** [comment]
The ability to load arraybuffer directly and stop loading will be appreciated, especially in urls.

**Comment by ivmartel** [comment]
Ok... What would be your use case?

**Comment by ivmartel** [comment]
Have you seen what @tmskmr did in #332? His memory class is what you are asking for?

**Comment by rafasoyyo** [comment]
Yes, this is usefull te load data from Arraybuffers.
A generic method like app.stopLoading() to be able to cancel load progess can be also usefull.

It is just an idea...

**Comment by ivmartel** [comment]
I create a specific issue for stopping the load: see #340.
