### ISSUE TITLE
Set HTTP request headers 

### ISSUE THREAD

**Issue by HernanGH** [ivmartel/dwv#338]
How set Headers in loadUrls method? i don't found in the documentation. Because i need apply security in this request. ex: jwt

**Comment by rafasoyyo** [comment]
It is posible to add header as a parameter un loadURLs method as shown here: 
https://github.com/ivmartel/dwv/blob/master/src/app/application.js#L561 
They are set before request is done as shown here:
https://github.com/ivmartel/dwv/blob/master/src/io/url.js#L337

**Comment by ivmartel** [comment]
@rafasoyyo, you meant [application.js#L524](https://github.com/ivmartel/dwv/blob/master/src/app/application.js#L524) and not [application.js#L561](https://github.com/ivmartel/dwv/blob/master/src/app/application.js#L561) for your first link?

The example usage is in the [viewers/mobile/google.js](https://github.com/ivmartel/dwv/blob/master/viewers/mobile/google.js) adapter. 

The argument format is an array of `{name, value}` passed to `XMLHttpRequest.setRequestHeader()`.

**Comment by ivmartel** [comment]
@HernanGH, did our answers help you?

**Comment by HernanGH** [comment]
Thanks @ivmartel, @rafasoyyo. Yes, they did..
here i found the solution application.js#L524

**Comment by ivmartel** [comment]
Ok, closing then. Feel free to reopen if you have problems.
