### ISSUE TITLE
DicomWriter transfer syntax limit

### ISSUE THREAD

**Issue by ivmartel** [ivmartel/dwv#343]
Currently, the DicomWriter limits itself using the input transfer syntax (`dwv.dicom.isWriteSupportedTransferSyntax`) which is misleading since it could write the data but with another transfer syntax (at the moment '1.2.840.10008.1.2.1: Explicit VR - Little Endian').

The code must be changed to allow other input transfer syntax and set the output one to what is used to write the data.

Originated from a [comment](https://github.com/ivmartel/dwv/issues/335#issuecomment-302017126) by @yulia-tue on #335.

**Comment by yulia-tue** [comment]
Hi @ivmartel ,
so is it correct, that I can allow all readSupported syntaxes, but I need to change "1.2.840.10008.1.2.1"  Explicit VR - Little Endian and "1.2.840.10008.1.2.2" Explicit VR - Big Endian to "1.2.840.10008.1.2" Implicit VR - Little Endian? And the JPEG syntaxes I don't need to change? 

Best,
Yulia

**Comment by ivmartel** [comment]
**All** transfer syntax can be supported (including JPEG) and would be written as `1.2.840.10008.1.2.1: Explicit VR - Little Endian`. Meaning that the code will force the syntax.

**Comment by yulia-tue** [comment]
I am not an expert in dicom, so could you please clarify this part?
If the original dicom file has JPEG syntax and it's written as Expl VR Little Endian, than when the new file is parsed it is not the same as the original one. Could this affect the handling of this file in medical systems, e.g. Telemis and such? Could this affect how the pixel data looks like?

**Comment by ivmartel** [comment]
Yes, you are right, this would not work for compressed data. Either the writer does not decode the data and writes it as is or it decodes it and writes it as 'Explicit VR - Little Endian'. The first solution *should* work...

**Comment by ivmartel** [comment]
Some news about this issue: the latest code removed the transfer syntax check. The parser does not decode encoded data, so anonymisation without touching the pixel data is possible, and this for all transfer syntaxes. The only modified content is the header meta data.

On the other hand, the current code cannot handle modified pixel data that needs to be encoded in order to be written using the same input transfer syntax. The current decoders to not provide encoding... So the  solution would be to write the data using a non encoded transfer syntax.
