### ISSUE TITLE
It is possible to reset the container div measurements

### ISSUE THREAD

**Issue by HernanGH** [ivmartel/dwv#344]
Hi, i am Hernan
I am loading an image as follows:
```javascript
    var decoderScripts = {
        'jpeg2000': 'components/dwv/ext/pdfjs/decode-jpeg2000.js',
        'jpeg-lossless': 'components/dwv/ext/rii-mango/decode-jpegloss.js',
        'jpeg-baseline': 'components/dwv/ext/pdfjs/decode-jpegbaseline.js'
    }
    dwv.gui.getElement = dwv.gui.base.getElement;
    dwv.image.decoderScripts = decoderScripts;
    self.app = new dwv.App();
    self.app.init({
        'containerDivId': 'dwv',
        'tools': ['WindowLevel']
    });
    $scope.loadImage = funcion(url, headers){
      self.app.loadURLs(url, headers);  
    }
```
But when I open a series of images with different proportions for example:
    50X50,
    250x250,
    900x900

If I open the images in the given order, the image diviner starts with height 50 and width 50, Then when I load the second image the div is not set to height 250 and width 250 but it stays with 50x50 and even decrements
    
In the documentation I did not find how to solve this problem. Please, as I would solve it

**Comment by ivmartel** [comment]
No, the viewer is not able to support this. But what is the use case? Would you expect the images to be zoomed/shrink to fit one of the sizes?
Not sure if it could be a solution, but I would open them in different viewers that could be on the same page.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to reopen if you need more details.

**Comment by HernanGH** [comment]
Sorry for the delay.
Find the solution for my problem, every time I reload an image I apply a manual resize.

var decoderScripts = {
        'jpeg2000': 'components/dwv/ext/pdfjs/decode-jpeg2000.js',
        'jpeg-lossless': 'components/dwv/ext/rii-mango/decode-jpegloss.js',
        'jpeg-baseline': 'components/dwv/ext/pdfjs/decode-jpegbaseline.js'
    }
    dwv.gui.getElement = dwv.gui.base.getElement;
    dwv.image.decoderScripts = decoderScripts;
    self.app = new dwv.App();
    self.app.init({
        'containerDivId': 'dwv',
        'tools': ['WindowLevel']
    });
    $scope.loadImage = funcion(url, headers){
      layer = document.getElementsByClassName('layerContainer');
      layer[0].style.height = '100%';
      layer[0].style.width = '100%';
      self.app.loadURLs(url, headers);  
    }

But I think I'm not using the library correctly. XD
One question, how should I open 100 images? Open them in different viewers?
Thanks

**Comment by ivmartel** [comment]
I still don't get your use case, you are trying to load images of the same series that have different sizes? Or are these different image loads: load one, view it, load another?

**Comment by HernanGH** [comment]
Yes, i am trying to load images of the same series that have different sizes, But this are test data for now. when the project goes to production will be with real dates, and I guess they will be the same size. I do not know if there will be scans or studies with different sizes, in which case this bug would be reproduced.

**Comment by ivmartel** [comment]
I was hoping to find a link that said that a serie with images of different sizes is forbidden but can't find one (yet...). I have no plans to support this use case for now and would not know how to handle it so I hope it does not happen!
