### ISSUE TITLE
Integrating DWV dicom viewer into my Own PACS

### ISSUE THREAD

**Issue by Sherkhan345** [ivmartel/dwv#347]
I have created my own PACS in which studies are uploaded from different machines into my own web based PACS server which is using .NET and SQL Server in backend. My PACS creates a folder for each study on the server. Now I want to view that study in the viewer using the study folder address of server. It means a preloaded dicom is required.
I know there are prior preloaded questions but that does not solve my problem.

**Comment by ivmartel** [comment]
Sorry for the question when you say "my own PACS", you mean a PACS you implemented yourself?

I'm not sure I get your question, you can load the data but you would prefer it to be preloaded, meaning the current solution is too slow?

**Comment by Sherkhan345** [comment]
Yeah sure, We have developed our own PACS, and now want to implement after completing it. Our PACS structure is for LOCAL network, huge amount of DICOM FILES are saved on DICOM server, And this current dicom viewer solution is for viewing studies, but our requirement is that we provide a link to each patient so that when a doctor need to check specific patient's record, the doctor will not need to find and search dicom files of that specific patient. So on clicking the name of a patient, the doctor will be redirected to the dicom viewer having opened the dicom file of that patient. In current solution the doctor will not be able to find specific patient record. So that by providing the link to the doctor will make it easy and fast to see the dicom files without browsing it.
