### ISSUE TITLE
dwv demo site can load my dicom file, but dwv api can't

### ISSUE THREAD

**Issue by taehun1214** [ivmartel/dwv#348]
I really need dwv api.. but it said my dicom file is invalid.. (no magic word?? sorry I'm new here) 

however, dwv demo site can load my dicom image perfectly..

I got the file using dcm4che query from pacs.. and it has Prefix- "DICM"

It is absolutely perfect dicom file. I got confirmation that from my hospital.

And also, its information has full values tested by DICOM Validation Toolkit.

I tested another dicom file from on the web,

but the result is the same.. "Error: Not a valid DICOM file (no magic DICM word found)."

please tell me what should I do??.. how to make my dicom file valid?

**Comment by ivmartel** [comment]
Can you share your code to see how you are loading the data?

**Comment by taehun1214** [comment]
I just copy and paste your example. except url.. I change it to my dicom file path which is from my web server.

app.loadURLs(["https://raw.githubusercontent.com/ivmartel/dwv/master/tests/data/bbmri-53323851.dcm"]);
											
app.loadURLs(["/backend/pacsOne/0EC19DC9-0228-7258-A574-0983945CF193.dcm"]);

**Comment by ivmartel** [comment]
Does `/backend/pacsOne/0EC19DC9-0228-7258-A574-0983945CF193.dcm` resolve to something (if you put it in your browsers' url, does it download the file)? It looks like it is missing protocol (http) and root (127.0.0.1).

**Comment by taehun1214** [comment]
In other server, I let me try "http://video.softnet.co.kr:8000/data/files/check/B9E8DDA0-6E35-CCDB-CA04-61B573990217.dcm" Do I have to do other process?? I just use "dwv.min.js" and my goal is only show the dicom image simply.

**Comment by taehun1214** [comment]
I did test....  
"http://video.softnet.co.kr:8000/data/files/check/B9E8DDA0-6E35-CCDB-CA04-61B573990217.dcm"
It said : Error: No JPEG 2000 decoder provided.

.. what should I do??

**Comment by ivmartel** [comment]
1. content from `raw.githubusercontent` is provided with CORS enabled, so no cross origin error
 1. you should be able to view the image without any process
 1. the viewer supports JPEG2000 encoded DICOM data, you need to provide the decoders in the applauncher (see [mobile/applauncher.js#L55](https://github.com/ivmartel/dwv/blob/master/viewers/mobile/applauncher.js#L55))

**Comment by taehun1214** [comment]
Thank you, I tried,  but... following errorr.. please help me..
---error1 on console----
dwv.min.js:14 Uncaught TypeError: a.use is not a function
    at Object.g.i18nInitialise (dwv.min.js:14)
    at applauncher.js:64
g.i18nInitialise @ dwv.min.js:14
(anonymous) @ applauncher.js:64
register:699  
pace.min.js:8 
a.open @ pace.min.js:8
send @ jquery.min.js:4
ajax @ jquery.min.js:4
getMenuHtml @ register:391
(anonymous) @ register:381
j @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
I @ jquery.min.js:2

------error2 on console------
dwv.min.js:11 Uncaught Error: Cannot append a slice with different number of columns
    at g.image.Image.appendSlice (dwv.min.js:11)
    at g.image.View.append (dwv.min.js:12)
    at g.io.Url.c.onload (dwv.min.js:3)
    at d (dwv.min.js:12)
    at l (dwv.min.js:12)
    at g.utils.WorkerTask.callback (dwv.min.js:12)
    at Worker.b (dwv.min.js:14)

**Comment by taehun1214** [comment]
why your dicom no need decoder in example? If there is default dicom image, please let me know... I think I can change some base image from jpeg2000 to another..

**Comment by ivmartel** [comment]
Because it loads the decoders as I point out in '3.'. You can use the non minified dwv (`dwv.js`), it will give you more detailed error logs.

It would be easier for me to help you if you could share your code.

**Comment by taehun1214** [comment]
Thank you... really appreciate!! I solve the problem.. delete duplicated loadULRs method..

**Comment by ivmartel** [comment]
You are missing the i18next includes (adapt to your paths):
```html
<script type="text/javascript" src="i18next.min.js"></script>
<script type="text/javascript" src="i18nextXHRBackend.min.js"></script>
<script type="text/javascript" src="i18nextBrowserLanguageDetector.min.js"></script>
```
Unfortunately there is no South Korean translation available. If you are willing to create it, we can add it to the languages in [transifex](https://www.transifex.com/ivmartel/dwv/). Available languages are in the [locales](https://github.com/ivmartel/dwv/tree/master/locales) folder. Check the English one for an example.

**Comment by ivmartel** [comment]
Ok, I hope I answered all the questions. Closing for now, feel free to reopen if needed!

**Comment by ShahnewazSarker** [comment]
Hello @ivmartel ,

I tried to load one dicom image but not working. Error message: No JPEG Baseline decoder provided

Here is my code:

```
    <!DOCTYPE html>
    <html>
        <head>
            <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
            <script type="text/javascript" src="dist/dwv.min.js"></script>
			<script type="text/javascript" src="src/utils/i18next.min.js"></script>
			<script type="text/javascript" src="src/utils/i18nextXHRBackend.min.js"></script>
			<script type="text/javascript" src="src/utils/i18nextBrowserLanguageDetector.min.js"></script>

		    <script type="text/javascript" src="src/dicom/dicomParser.js"></script>
			<script type="text/javascript" src="src/dicom/dicomWriter.js"></script>
			<script type="text/javascript" src="src/dicom/dictionary.js"></script>
			<script type="text/javascript" src="src/dicom/dicomElementsWrapper.js"></script>
			<script type="text/javascript" src="src/image/decoder.js"></script>
			<script type="text/javascript" src="src/image/domReader.js"></script>
			<script type="text/javascript" src="src/image/image.js"></script>
			
			<script type="text/javascript" src="src/app/application.js"></script>
			<script type="text/javascript" src="src/app/drawController.js"></script>
			<script type="text/javascript" src="src/app/infoController.js"></script>
			<script type="text/javascript" src="src/app/state.js"></script>
			<script type="text/javascript" src="src/app/toolboxController.js"></script>
			<script type="text/javascript" src="src/app/viewController.js"></script>
            <style type="text/css" >
                body { background: #252525; color: #fff; }
                button {
                    margin: 5px; padding: 10px 10px;
                    border: 0 none; border-radius: 4px;
                    font-size: 14px; font-weight: 600;
                    color: #fff; background-color: #444; }
                button:hover { background-color: #555; }
                button:disabled { background-color: #08b; }
                .toolbar { font: 14px arial, sans-serif; margin-bottom: 5px; text-align: center; }
                .wl-button, .reset-button { margin-right: 5px; }
                .layerContainer { margin: auto; text-align: center; }
                .imageLayer { left: 0px; }     
            </style>

            <script type="text/javascript">
                window.onload = function() {
                    var imgUrl = document.getElementById("imageHidden").src; 
                    dwv.gui.getElement = dwv.gui.base.getElement;
                    dwv.gui.displayProgress = function(percent) {
                    };

                    // create the dwv app
                    var app = new dwv.App();
                    // initialise with the id of the container div
                    app.init({
                        "containerDivId": "dwv",
                        "tools": ["WindowLevel"], // or try "ZoomAndPan"
                    });
                    // load dicom data
                    app.loadURLs([imgUrl]);
                    var range = document.getElementById("sliceRange");
                    range.min = 0;
                    app.addEventListener("load-end", function() {
                        range.max = app.getImage().getGeometry().getSize().getNumberOfSlices() - 1;
                    });
                    app.addEventListener("slice-change", function() {
                        range.value = app.getViewController().getCurrentPosition().k;
                    });
                    range.oninput = function() {
                        var pos = app.getViewController().getCurrentPosition();
                        pos.k = this.value;
                        app.getViewController().setCurrentPosition(pos);
                    }

                };
                $(document).ready(function() {
                    // base function to get elements

                });
            </script>

        </head>
        <body>
 <img id="imageHidden" src="http://localhost/dicom/test.dcm" hidden="true">
            <div id="dwv">

                <!-- Layer Container -->
                <div class="layerContainer">
                    <canvas class="imageLayer">Only for HTML5 compatible browsers...</canvas>
                </div><!-- /layerContainer -->


            </div><!-- /dwv -->
            <input type="range" id="sliceRange" value="0">
        </body>
    </html>
```

Can you please give me some idea whats wrong here. Its bit emergency for me.

**Comment by ivmartel** [comment]
Check out my answer in the #596 issue.
