### ISSUE TITLE
JPX Error: Unsupported COD options (dwv api) please.. help me...

### ISSUE THREAD

**Issue by taehun1214** [ivmartel/dwv#349]
Thanks for this wonderful library,

most patientID dicom files can be loaded perfectly.

but some patientID dcm files show following error...

I can provide image if needed

...........error console... I just want to show simple thumbnail....

```javascript
jpx.js:339 Uncaught Error: JPX Error: Unsupported COD options (selectiveArithmeticCodingBypass)
    at JpxImage_parseCodestream [as parseCodestream] (jpx.js:339)
    at JpxImage_parse [as parse] (jpx.js:91)
    at decode-jpeg2000.js:13
```
.......my code............
```javascript
<script src="/resources/dicom/js/dwv.js"></script>
<script src="/resources/dicom/js/applauncher.js"></script>
<script src="/resources/dicom/js/i18next.min.js"></script>
<script
	src="/resources/dicom/js/i18nextXHRBackend.min.js"></script>
<script
	src="/resources/dicom/js/i18nextBrowserLanguageDetector.min.js"></script>

.........
function onSearch() {
    pacsService.connect($scope.pacs).then(
            function(response) {
                console.log(response);
                if (response != 0) {
                    console.log(response);
                    
                    dwv.gui.getElement = dwv.gui.base.getElement;
                    dwv.gui.displayProgress = function(percent) {
                    };
                    var app = new dwv.App();
                    
                    app.init({
                        "containerDivId" : "dwv",
                        "tools" : [ "Scroll" ],
                    });
                    // load dicom data
                    app.loadURLs(response);
                } 
            });
}
```

please tell me what should I do??....

**Comment by ivmartel** [comment]
This is a current limitation of the JPEG2000 decoder. This third party library comes from Mozilla's [pdf.js](https://github.com/mozilla/pdf.js) project. See these two related issues:
 * [pdf.js/issues/6365](https://github.com/mozilla/pdf.js/issues/6365) (mozilla)
 * [image-JPEG2000/issues/4](https://github.com/OHIF/image-JPEG2000/issues/4) (OHIF)

**Comment by taehun1214** [comment]
How to implement on decoder side?

They said it is easy to solve this problem..

I think "cornerstone.js" which is other library is working..

**Comment by taehun1214** [comment]
I have to this right now.. Could you let me know the progress? Please.. I really beg you..

**Comment by taehun1214** [comment]
please... any suggestions???

**Comment by ivmartel** [comment]
Sorry, I do not know how to fix the decoder, maybe best to ask @jpambrun directly.

**Comment by taehun1214** [comment]
At the moment, I asked him.. By the way, If I could ignore checking this exception, Is it possible??.. I really need this. And I just want to show the dicom image and I don't care the quality of the image..

**Comment by jpambrun** [comment]
I think the selectiveArithmeticCodingBypass COD should be easy to
implement, but I don't have the time to investigate.
You should consider using this Emscripten build of OpenJpeg :
https://github.com/chafey/openjpeg.
It is the reference implementation and should support all you need.

**Comment by ivmartel** [comment]
I created an issue to study the integration of openjpeg. Please comment there if you need.

**Comment by taehun1214** [comment]
ok. I really need.

**Comment by Mamta92** [comment]
Can I get to know the exact reason why it is failing? I'm also facing the same issue for a particular series.

**Comment by ivmartel** [comment]
@Mamta92 please use #718 for comments. As mentioned there, if you could share some data that would help.
