### ISSUE TITLE
DWV dicom viewer can't read .dcm files from asp.net server folder

### ISSUE THREAD

**Issue by mansoorahmadkk** [ivmartel/dwv#350]
Hi, (i am new to javascript)
i tried .jpg file from my asp.net file server in dwv dicom viewer it can read this file successfully
 
url:(http://localhost:2792/dwv-master/dwv-master/viewers/static/index.html?input=http://localhost:2792/UploadControl/1011401.5127/10211c4354/c012z8/file.jpg)

but 
when i give the .dcm file name in place jpg file i can not read

url:(http://localhost:2792/dwv-master/dwv-master/viewers/static/index.html?input=http://localhost:2792/UploadControl/1011401.5127/10211c4354/c012z8/study.dcm)

it shows the following error

(RequestError: Error status: 404 while loading 'http://localhost:2792/UploadControl/1011401.5127/10211c4354/c012z8/study.dcm' [DicomDataLoader].)

(note: jpg and dcm files are in same folder)
please help me in this issue
thanks

**Comment by ivmartel** [comment]
Does the console log give more details about the error? If you copy the dcm url in your browser, it downloads the dcm file?

**Comment by mansoorahmadkk** [comment]
![error](https://cloud.githubusercontent.com/assets/28978956/26499431/77469464-41e7-11e7-99a0-e82e0e2d2f81.jpg)

**Comment by mansoorahmadkk** [comment]
it can not find the file located on the servers folder

**Comment by ivmartel** [comment]
The first error is dwv trying to find a translation file. You can modify the default path in the applauncher call to the dwv.i18nInitialise function (see code [i18n.js#L20](https://github.com/ivmartel/dwv/blob/master/src/utils/i18n.js#L20)).

If you cannot download the file by copying the url `http://localhost:2792/UploadControl/1011401.5127/10211c4354/c012z8/renam.dcm` in your browser address bar, then dwv cannot neither...

**Comment by mansoorahmadkk** [comment]
sir, can you give me any hint or work area on which i should work

**Comment by ivmartel** [comment]
My hint is to check that the file is accessible by pasting its url in the address bar of your browser. If you cannot download the file the problem is with your server, otherwise it could be with dwv.

**Comment by tmskmr** [comment]
@mansoorahmadkk , in my case, I had to add a MIME type "image/dicom" associated with ".dcm" extension on IIS Manager.

**Comment by mansoorahmadkk** [comment]
tmskmr thanks for your solution, it worked with adding MIME type "application/dicom" extension
thanks once again

**Comment by ivmartel** [comment]
Thanks @tmskmr!

**Comment by RkReddy88** [comment]
@tmskmr Thank you, Its working on IIS manager but when I am trying to access the .dcm files from an linux machine  ., I could not find the files. Is there any config for Linux to access those dcm files

**Comment by tmskmr** [comment]
@RkReddy88 I am not familiar with linux, but Google Search says that you should edit web.xml or mime.types file for adding a new MIME type in case of Tomcat.
