### ISSUE TITLE
How to upload multiple pictures in url using asp.net

### ISSUE THREAD

**Issue by mansoorahmadkk** [ivmartel/dwv#351]
I have successfully read single dicom image from asp.net server folder using url
Response.Redirect("http://Localhost:3029/dwv-master/dwv-master/viewers/static/index.aspx?input=" + serverImagePath);

But now i want multiple images on single of button click

How can i do it using Response.Redirect(?)

**Comment by taehun1214** [comment]
I did it in JAVA

-controller side-
add multiple url in array
return array

 -jsp side-
app.loadURLs(array)

**Comment by ivmartel** [comment]
Check out this wiki page [User-Stories#io](https://github.com/ivmartel/dwv/wiki/User-Stories#io) to learn how to create a url with multiple files.

**Comment by ivmartel** [comment]
I hope I answered the question. Closing for now, feel free to reopen if needed.
