### ISSUE TITLE
Dicom Directory

### ISSUE THREAD

**Issue by Farzaal** [ivmartel/dwv#352]
Hello everyone, I am new to Dicom I have seen some other viewers as well but I prefer to use and configure dwv. I have a study or a dicom directory and I want to open it in a viewer  so can anyone suggest me where to get started.

**Comment by ivmartel** [comment]
The viewer cannot load all the content of a directory (I think only Google chrome could allow that). What you have to do is load all the files.

**Comment by Farzaal** [comment]
Thanks for reply but my confusion is If I have a directory
like 01012015135630 and url till that dir is
http://localhost/NgDicomViewer/01012015135630/1.1( Image ). How can I open
multiple images through URL like 4 to 5. What will the URL be If I want to
open 4 to 5 slices from that folder through URL.

**Comment by ivmartel** [comment]
Check out this wiki page [User-Stories#io](https://github.com/ivmartel/dwv/wiki/User-Stories#io) for the documentation.

Basically the scheme is: `[root]?key0=value00&key1=value10`

So in your case: `http://localhost/NgDicomViewer/01012015135630?key0=img0&key1=img1`

You then need to urlencode it and you can give it the browser as in: `[dwv root]?input=encodeURIComponent('your-url')&dwvReplaceMode=void`

**Comment by Farzaal** [comment]
Thank You for your reply sir. I will try it.

**Comment by ivmartel** [comment]
Ok, closing for now. Feel free to reopen if needed.
