### ISSUE TITLE
How Save Drawing on DICOM image?

### ISSUE THREAD

**Issue by Sherkhan345** [ivmartel/dwv#354]
If Dr want to highlight the specific area by drawing circle or line on Dicom file, How can I save that, so that next time by studying that file, the drawing is shown already?

**Comment by ivmartel** [comment]
In the mobile interface, the fifth button on the top row will save the state of the gui as a json file. You can then load it back via url or file. 

The code of the state is there: [app/state.js](https://github.com/ivmartel/dwv/blob/master/src/app/state.js)

**Comment by ivmartel** [comment]
I hope I answered the question. Closing for now, feel free to reopen if needed!

**Comment by srivathsapv** [comment]
What if I want the drawings to be burnt in the DICOM file itself? Is there something that I can do to achieve this?

**Comment by ivmartel** [comment]
I'm not too clear on this one, the idea is to investigate using radiation therapy structure sets (RTSTRUCT), see #306 for more details.
