### ISSUE TITLE
loadURLs stopped when set requestHeaders

### ISSUE THREAD

**Issue by GustavoDiogo** [ivmartel/dwv#355]
*UPDATE 1: I read the doc, tried to fix it and now I got another problem*

Hi ivmartel, I'm building an test project using your DWV, Orthanc and a simple backend in node to authenticate the user via an <b>api</b>, using token.

The code:
```javascript    
        var url = "http://" + address + "/api/dicom/file/" + instanceID;

        var requestHeaders = {
            name:"Access-Token",
            value: token
        }

        myapp.loadURLs([url], [requestHeaders]);
```
It shows loading until 99% and fails, returning with this error: <b>RangeError: attempting to construct out-of-bounds TypedArray on ArrayBuffer</b> on Firefox and <b>RangeError: Invalid typed array length</b> in Chrome and the both console prints:

```
dwv.dicom.DataReader/this.readUint8Array@http://192.168.2.160/dwv-0.18/demo/stable/dwv-0.18.0.min.js:2:23659
dwv.dicom.DataReader/this.readString@http://192.168.2.160/dwv-0.18/demo/stable/dwv-0.18.0.min.js:2:25602
dwv.dicom.DicomParser.prototype.readDataElement@http://192.168.2.160/dwv-0.18/demo/stable/dwv-0.18.0.min.js:2:31719
dwv.dicom.DicomParser.prototype.parse@http://192.168.2.160/dwv-0.18/demo/stable/dwv-0.18.0.min.js:3:1001
dwv.image.DicomBufferToView/this.convert@http://192.168.2.160/dwv-0.18/demo/stable/dwv-0.18.0.min.js:11:8112
dwv.io.Url.prototype.load/f@http://192.168.2.160/dwv-0.18/demo/stable/dwv-0.18.0.min.js:11:20195
dwv.io.Url.prototype.load/i@http://192.168.2.160/dwv-0.18/demo/stable/dwv-0.18.0.min.js:11:21024
``` 

This url <b>always</b> worked fine. It stopped when I setted the headers as a second argument in the function.

Thanks for the attention.

**Comment by GustavoDiogo** [comment]
I fixed it, the error was quite unpredictable. Closing the issue.

In my backend I used axios as my user agent to make the request and his default configuration had an encoding(the request was changing the dicom from <b>utf-8 to latin1</b> for some reason) that was breaking the dicom in the middle of the request so I changed axios to the default request agent and passed the encoding as null.

```javascript
var request = require("request").defaults({encoding:null})
```

**Comment by ivmartel** [comment]
Good debugging! Would you have a link to 'axios' for those who don't know it?

**Comment by GustavoDiogo** [comment]
Sure!

Axios(This one <b>broke</b> the encoding of request): 
https://www.npmjs.com/package/axios

The native user agent of NodeJS that worked/I used: 
https://www.npmjs.com/package/request

**Comment by ivmartel** [comment]
Thanks!
