### ISSUE TITLE
Texts don't load when I run the app from a Windows Server

### ISSUE THREAD

**Issue by donatorouco** [ivmartel/dwv#357]
I'm hosting the dwv on a **Windows 2k12** server and when I open any of the viewers in any browser the app is unable to load any text from the locales json files.

**Comment by ivmartel** [comment]
The `dwv.i18ninitialise` can take the locales folder as input in the case the default does not suit your settings.
It is called in the viewer's applauncher.

**Comment by ivmartel** [comment]
I hope my comment helped. Closing for now, feel free to comment/reopen.
