### ISSUE TITLE
Manual windowLevel controls on a strip of images

### ISSUE THREAD

**Issue by HernanGH** [ivmartel/dwv#364]
Hi! 
I am trying to do some manual controls to change the WindowLevel, using event.
 So, i do this:
var contrastRange = document.getElementById("contrastRange");

```
app.addEventListener("load-end", function () {
    contrastRange.min = app.getViewController().getWindowLevel().center - 100;
    contrastRange.max = app.getViewController().getWindowLevel().center + 100;
});
app.addEventListener("wl-change", function () {
    contrastRange.value = app.getViewController().getWindowLevel().center;
});
contrastRange.oninput = function () {
    app.getViewController().setWindowLevel(this, app.getViewController().getWindowLevel().center, 'manual);
}
```

I have the following problems,
First when the next slice passes, the values of "center" and "width" are altered, so the input range moves,
Second does not work setwindowsLevel when altering the input range is running the setwindowsLevel function but does not work, only works this function when previously change the contrast by clicking on the viewer, on the canvas. From there it works.

How I could solve my problems, how to use an input range with many images and how to set the windowLevel without having to configure the 'tools: [' WindowLevel ']', that this listen the click on the canvas? Thanks

**Comment by ivmartel** [comment]
I made some changes to fix #331 in v0.20.0, are you using the latest code?

**Comment by ivmartel** [comment]
Also maybe related to #395.
Did you manage to solve your problem? Some data can have a per slice window/level which could be tricky to handle...

**Comment by HernanGH** [comment]
Yes I can solve my problem, Thanks Iv!
