### ISSUE TITLE
Anonymize DICOM files with javascript

### ISSUE THREAD

**Issue by krunalrspl** [ivmartel/dwv#366]
I'm triying to anonymize dcm (dicom) files before uploading it to the server. 

I want to do it on the client side using javascript. But I can't find more that dicom viewers.

I searched about the tags of dicom and I have found a lot of tools for remove metadata tags using python, java and ruby, but I don't know how to portrait it to javascript.

I have even decided what tags I would remove, but I'm not sure about how to do it.

Any ideas about?

Thanks for your time

**Comment by andkhong** [comment]
Currently, DWV doesn't work with the client unless you use Browserify and/or RequireJS

**Comment by ivmartel** [comment]
Regarding DICOM anonymisation there is a beta [DicomWriter](https://github.com/ivmartel/dwv/blob/master/src/dicom/dicomWriter.js) class and some example anonymiser in the tests: [anonymiser.html](https://github.com/ivmartel/dwv/blob/master/tests/dicom/anonymiser.html). The writer is limited and needs more work to support writing more DICOM files, see #343.

@andkhong it does not work when used with react/vue but does when used on its own.

**Comment by quinton-ashley** [comment]
I've been working on this somewhat user friendly CLI tool for editing DICOM tags: [https://github.com/quinton-ashley/automaDICOM](url)
I'm going to have a local website UI for it soon

**Comment by ivmartel** [comment]
I hope I answered the question. Closing for now, feel free to reopen.
