### ISSUE TITLE
Unable to import from library 

### ISSUE THREAD

**Issue by andkhong** [ivmartel/dwv#367]
```javascript
import dwv from 'dwv';
```
```javascript
./~/dwv/dist/dwv.min.js
Module not found: Empty dependency (no request)
```
I am unable to import with front end libraries such as React/Vue

Is it possible for you to incorporate RequireJS  and/or Browserify which will enable Client side use?

**Comment by ivmartel** [comment]
The code is modularised using this [intro.js](https://github.com/ivmartel/dwv/blob/master/resources/module/intro.js) file. It should work with RequireJS. 
Not sure what it is missing to import it in React/Vue... How does their import work?

**Comment by LaedaSt** [comment]
UP! 
I'm developing an application on Laravel and I encountered the same problem. Standard methods, such as npm install / update, adding libraries React, Vue, Require, also did not solve the problem. Can someone else come across this and solve the problem?

**Comment by ivmartel** [comment]
Ok, it's maybe time to use es6 `import` and package dwv using webpack instead of these manual scripts. This should solve this import error.

**Comment by ivmartel** [comment]
While waiting for an es6 update, I think I have a quick fix. You can use the webpack [exports-loader](https://github.com/webpack-contrib/exports-loader) to package dwv in a way you can import it.
Install it and then, in your code, import using:
```javascript
// eslint-disable-next-line import/no-webpack-loader-syntax
import dwv from 'exports-loader?dwv!dwv';
```
The comment line disables the default linting error preventing the use of webpack loaders.

I tried it in a react environment, I hope it works in others... This solves the import error, I'll try to create a dwv-react viewer to check if there could be others...

**Comment by ivmartel** [comment]
I forgot to say that the fix I describe above works for the **non** modularised dwv, meaning stripped of the [intro.js](https://github.com/ivmartel/dwv/blob/master/resources/module/intro.js) and [outro.js](https://github.com/ivmartel/dwv/blob/master/resources/module/outro.js)...

**Comment by ivmartel** [comment]
A dwv-react viewer is a bit tricky... It needs to import the appgui file which is not 'importable' as it is. Not sure what's the best way to go forward...

**Comment by ivmartel** [comment]
I created an issue for this (#399). Please comment there if you need.

**Comment by ivmartel** [comment]
Maybe not related to es6 modules but more to modernizr #467 and AMD #468 issues...

**Comment by ivmartel** [comment]
:rocket: Got it working! Check out the new [dwv-react](https://github.com/ivmartel/dwv-react) and [dwv-vue](https://github.com/ivmartel/dwv-vue) repos.
