### ISSUE TITLE
Multiplanar Reconstruction (MPR)

### ISSUE THREAD

**Issue by MMSSAA** [ivmartel/dwv#369]
I think if the Multiplanar Reconstruction (MPR) option is added to DWV viewer , There is no other flaw.

**Comment by ivmartel** [comment]
Would be nice indeed! But never found the time... it is one of the first tickets: #4!

**Comment by ivmartel** [comment]
Thanks for the comment. Closing this issue, refer to #4 for further discussion. Any comments / help are welcome!
