### ISSUE TITLE
Get the json object of drawn object such as rectangle or eclipse

### ISSUE THREAD

**Issue by parthmehta17888** [ivmartel/dwv#371]
Hello Team,

I would like to get json object  for the drawn object such as rectangle and eclipse on button click event. I would like to implement the same logic which is written for state.json

Can you please suggest ? this is not an issue but required your assistance.

**Comment by ivmartel** [comment]
The code that handles the save is in the apps' [onStateSave](https://github.com/ivmartel/dwv/blob/master/src/app/application.js#L959) method. The download state button is in fact a link which content gets filled by this method. The creation of this button for the mobile viewer is done in [appgui.js#L192](https://github.com/ivmartel/dwv/blob/master/viewers/mobile/appgui.js#L192).

**Comment by parthmehta17888** [comment]
Thanks for the prompt response. I checked that code. My requirement is get the json object on another button's click event. how may I get the OnStateSave method over there ?

It will be very helpful for me. Thanks in Advance !

**Comment by ivmartel** [comment]
The method could be externalised, all you need is an application (`app`) object to create the state via:
```javascript
var state = new dwv.State( app );
```

**Comment by parthmehta17888** [comment]
Ok... May I get the same object inside the document.ready ?
 $("#btnGet").click(function () {
//  var state = new dwv.State( app ); ???
});

**Comment by ivmartel** [comment]
That will depend on your code and if the `app` object is available. If it is, it should work.

**Comment by parthmehta17888** [comment]
Ok Thanks for the your response.
