### ISSUE TITLE
Allow Multiple file and put masking on all the images.

### ISSUE THREAD

**Issue by parthmehta17888** [ivmartel/dwv#372]
Hello Team,

Please provide your feedback. It will be very helpful for me to integrate this viewer into my project.

Is it possible to open multiple dicom images in dwv ?
Is it possible, if I put masking on one image and the same masking available on the rest of files as well (such as rectangle and ellipse) ?

Thanks,
Parth Mehta

**Comment by ivmartel** [comment]
Yes, you can open multiple DICOM images in dwv, as long as they are of the same study.
Yes, you can draw shapes on individual slices but there is no tool to propagate them onto others, it would be a nice functionality to implement!

**Comment by parthmehta17888** [comment]
Thanks for the reply.
I checked with the multiple file upload and it is working. To put mask on multiple images (within same place)
I just change into drawController => activateDrawLayer (line num 74) drawLayers[k][f].visible(true);

It allows to put same object on each page at same location. I hope this implementation is proper. I need your suggestion for the same.

**Comment by ivmartel** [comment]
What you seem to be doing it make the same draw visible on all slices. I would prefer having a different draw object per slice or give a third dimension to draws (saving them all in one).

**Comment by ivmartel** [comment]
I create an issue for the annotation propagation. Please comment on it if you need.
