### ISSUE TITLE
How to use dwv in typescript?

### ISSUE THREAD

**Issue by neromaycry** [ivmartel/dwv#373]
I'm using Angular2 in the project with typescript. 

I have a problem that how to use dwv in typescript? It would go wrong, if I import dwv directly.

**Comment by ivmartel** [comment]
Relates to #363.

I do not have much experience in these frameworks but am very interested in your findings. Please tell me if there is anything I can do to make dwv more integrable!

**Comment by ivmartel** [comment]
I created an issue for this. Please comment there if you need.

**Comment by ivmartel** [comment]
Maybe not related to es6 modules but more to modernizr #467 and AMD #468 issues...

**Comment by ivmartel** [comment]
Got it working! Check out the new [dwv-angular](https://github.com/ivmartel/dwv-angular) repo.
