### ISSUE TITLE
Threshold filter slider behavior

### ISSUE THREAD

**Issue by diaztula** [ivmartel/dwv#374]
Hello, I have a question about the threshold filter. We can apply the threshold filter to an image by moving the slider to the right. But after that, moving the slider back to the left produces no change in the image, it remains with the same threshold applied. I can only undo the threshold by clicking "undo" button. Is this behavior expected?
Regards

**Comment by ivmartel** [comment]
This is the current behaviour... and I understand it is not very optimal... The problem is that the filters use the latest image as their input but the threshold should use the original one. It would be nice to change that but I do not have much time these days...
