### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Assem** [ivmartel/dwv#376]
Hi,

I checked the docs and examples pages but I couldn't find a clear doc on how to use as js: something like:
add this code to the header: <script...>
initialize using: new app...

am I missing something ?
Thks
Assem.

**Comment by ivmartel** [comment]
The [Examples](https://github.com/ivmartel/dwv/wiki/Examples) wiki page lists demo fiddles where you can find such information. Isn't it what you are looking for?

**Comment by ivmartel** [comment]
I hope I answered the question. Closing for now, feel free to reopen.
