### ISSUE TITLE
Further Development

### ISSUE THREAD

**Issue by Astoltzweb** [ivmartel/dwv#378]
Hi. First of all I want to thank ivmartel and all the contributors for making such a wonderful product. I am currently using source to make customized version with some additional functions. In two days I were able to complete Russian localisation and make print button + fixes and customization. 

TODO: 
1. import from PACS (OpenPACS).
2. Annotations function, which seems to be currently broken. It is supposed to be placed at the bottom and provide an ability for doctors to make medical report and then print the result

I am going to complete those functions in one way or another, and I was wondering, if those functions already exist and just not working properly or disabled for some reason. It would be very nice if you could guide me in this task, so the commits could be added to master version painless.

Anyways, thank you for your enthusiasm.

**Comment by ivmartel** [comment]
Thanks for your comments!
I do not know OpenPACS, would you have a link to its web?
Annotations should be working, does it give you an error?

**Comment by ivmartel** [comment]
Closing for now. Feel free to comment / reopen if you need.
