### ISSUE TITLE
ENOENT: no such file or directory, open '/home/himanshu/.git/packed-refs'

### ISSUE THREAD

**Issue by HimanshuN** [ivmartel/dwv#379]
When I am running "grunt publish --verbose" it is giving me the error 
Fatal error: ENOENT: no such file or directory, open '/home/himanshu/.git/packed-refs'

Can anyone tell me why this error is coming and how to resolve it

**Comment by ivmartel** [comment]
This seems to be a git error but I am not sure why it happens when you run grunt. Do you run it on top of a clean dwv repo?

**Comment by ivmartel** [comment]
I hope my comment helped. Closing for now, feel free to comment/reopen.
