### ISSUE TITLE
Embedding in reveal.js or other browser-based presentation framework

### ISSUE THREAD

**Issue by JDWarner** [ivmartel/dwv#381]
I'd very much like to use DWV for presentations, preferably in [Reveal.JS](https://github.com/hakimel/reveal.js/), but despite my attempts at hacking DWV into Reveal.JS to date I have needed to use DWV in a separate tab.   

Is there any guidance available for embedding a simple (simplistic, possibly with tweaked styling) DWV viewer into a Reveal.JS presentation?  Scrolling and window/level tools would be sufficient.

**Comment by ivmartel** [comment]
Here is my try at it: [reveal-dwv.zip](https://github.com/ivmartel/dwv/files/1282718/reveal-dwv.zip)

The main points:
 * I adapted the simplistic viewer, its applauncher.js (in `js/dwv/viewers/simplisitic`) loads the data in two separate apps with two separate divs
 * the main index file defines two slides with the apps' divs
 * I'm not too sure on when is best to call the `Reveal.initialize()`...

Tell me what you think about it.

**Comment by ivmartel** [comment]
I hope the content of the zip file was helpful. 

Closing for now, feel free to comment / reopen if you need.
