### ISSUE TITLE
No memory clean up when loading new files!!

### ISSUE THREAD

**Issue by ajabnoor** [ivmartel/dwv#382]
When I try to load new files at the same session using the open button the memory start to add and accumulate (Reaching more than a gig by opening many files many times)  despite you are cleaning the objects before loading new DICOM images with (this.reset()) function.
I tried to clean other objects but the memory still more consumed!!
Is there is any solution for this?
Thanks

**Comment by ivmartel** [comment]
I had a look and you are right, there seem to be some memory leak when you load an image on top of another. I'm not too sure why and who could be the culprit, to investigate...

**Comment by ivmartel** [comment]
I created an issue to follow your question. Please comment there for more details.
