### ISSUE TITLE
Encoding failed on IE

### ISSUE THREAD

**Issue by heeyMoon** [ivmartel/dwv#386]
Hi!
I tried running Static Viewer on IE, and some characters failed encoding.
But when I tried running Chrome, Firefox, and Opera, the characters encoded well.
On IE, I succeeded only with the Specific Character Set is 'ISO_IR 100'.

Is there any way to encode well on IE?

ex)
On DICOM Tag, Patient Name was "Zavřít" and Specific Character Set was "ISO_IR 101"
But Static Viewer on IE said "Zavøít".

**Comment by ivmartel** [comment]
The text decoding uses the `TextDecoder` class that is not available on IE (see [caniuse.com/#feat=textencoder](http://caniuse.com/#feat=textencoder) for all browser support). Maybe you could find a project that develops an equivalent class for IE, I am not aware of any.

**Comment by ivmartel** [comment]
I hope my comment helped. Closing for now, feel free to comment/reopen.
