### ISSUE TITLE
How to run on localhost?

### ISSUE THREAD

**Issue by mayioit** [ivmartel/dwv#387]
[Hi All,
I have a problem when i run example. This problem like in the [picture](https://drive.google.com/file/d/0BzGKYCHI-zBvY3pfU2loeEY2NEk/view?usp=sharing).
`XMLHttpRequest cannot load file:///D:/Test/ivmartel-dwv-f8bba58/locales/en/translation.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`
What is the problem and how to fix?

Thanks.]

**Comment by ivmartel** [comment]
I recommend running dwv through a local web server, see [Error-Messages#xmlhttprequest-cannot-load-file-non-dicom](https://github.com/ivmartel/dwv/wiki/Error-Messages#xmlhttprequest-cannot-load-file-non-dicom) for details.

**Comment by gurre** [comment]
Start a local webserver `python -m SimpleHTTPServer 8000` navigate to http://localhost:8000/viewers/static/

**Comment by ivmartel** [comment]
I hope the comments helped. Closing for now, feel free to comment/reopen.
