### ISSUE TITLE
How to make a slider work in the simple layout?

### ISSUE THREAD

**Issue by MikeDacre** [ivmartel/dwv#390]
I am trying to use this app to display some MRI images, and I am new to javascript so I am having trouble.

I have tried two ways, the first is a really simple version based on an example on the wiki, it works great, except I cannot figure out how to make it scale with the window. The second is using a close of the simple layout from the full github repo, but in this version the slider does not respond.

The simple one from the example is: https://www.michaeldacre.com/brain/t2_flair_ax.html
The simple layout is: https://www.michaeldacre.com/brain/t1_flair_sag.html

Apologies for the simple question, but I have been trying for a few hours and I just cannot figure it out.

**Comment by ivmartel** [comment]
Adapting the size of the viewer to the window is activated with the `"fitToWindow": true` option when calling the `init` function on the app.

Regarding the non working slider for the second example, these 'fancy' sliders need to be refreshed manually by calling `dwv.gui.refreshElement(app.getElement("slice-position"));`. This should work:
```javascript
  myapp.addEventListener("load-end", function () {
        range.max = myapp.getImage().getGeometry().getSize().getNumberOfSlices() - 1;
        dwv.gui.refreshElement(app.getElement("slice-position"));
  });
  myapp.addEventListener("slice-change", function () {
        range.value = myapp.getViewController().getCurrentPosition().k;
        dwv.gui.refreshElement(app.getElement("slice-position"));
  });
  range.oninput = function () {
        var pos = myapp.getViewController().getCurrentPosition();
        pos.k = this.value;
        myapp.getViewController().setCurrentPosition(pos);
        dwv.gui.refreshElement(app.getElement("slice-position"));
  }
```

**Comment by MikeDacre** [comment]
Thanks!

I had trouble getting the `refreshElement` function to work, but I managed to get the `"fitToWindow"` method to work, I just had to define it by adding this at the top of the script:

```js
dwv.gui.getWindowSize = function () {
  return { 'width': ($(window).width()), 'height': ($(window).height()) };
}

**Comment by ivmartel** [comment]
I'm not sure I understand, did you manage to make the refresh work?

**Comment by MikeDacre** [comment]
Apologies, yes, I did manage to get the refresh to work eventually, I had to tinker with the refresh function to make it work properly on my site, but it works now. I ended up just switching to the simple version though because I managed to get resizing to work. Thanks for your help.
