### ISSUE TITLE
Level and Zoom Sliders?

### ISSUE THREAD

**Issue by MikeDacre** [ivmartel/dwv#391]
From example 3 (https://jsfiddle.net/ivmartel/zvt0xemc/) I figured out how to make a position slider.

What API calls should I use to also make a zoom slider (with panning available?) and a windowlevel slider? Or do I have to use the toolbar to switch between the modes?

I tried just adding a minimal toolbar by inserting `<div class="toolbar"></div>` into the `dwv` div and then using the following init:

```js
  app.init({
    "containerDivId": "dwv",
    "gui": ["tool"],
    "tools": ["Scroll", "ZoomAndPan", "WindowLevel"],
    "fitToWindow": true,
    "isMobile": true,
  });
```

However this gives the following error:

```
Uncaught TypeError: u.gui.Toolbox is not a constructor
    at u.tool.Toolbox.setup (dwv-0.20.1.min.js:3)
    at ToolboxController.setup (dwv-0.20.1.min.js:3)
    at App.init (dwv-0.20.1.min.js:3)
    at MRI (mri.js:20)
    at t2_fse_ax.html:31
```

Possibly the issue is that I am using the compiled minimized js, rather than the full application. This error isn't a big deal if I can just make some sliders with simple js calls. Thanks!

**Comment by ivmartel** [comment]
You do not need the toolbar html div if you don't want tool buttons. Remove it and you should not see the error.

Your question about a window/level slider is a good one... There only is a `wl-change` event that wont allow you to set window and / or level separately. I'll create a ticket for this!

**Comment by MikeDacre** [comment]
Great, thanks! In the meantime I managed to get the simplistic viewer working for my needs, so I am very happy about that. You can see the final product on https://kb.michaeldacre.com/kb/mri-images. Thanks for the amazing work.

**Comment by ivmartel** [comment]
Events have been updated in #395.

**Comment by ivmartel** [comment]
Closing for now. Feel free to comment or reopen if you need.
