### ISSUE TITLE
RequestError (http status: 0) [DicomDataLoader].

### ISSUE THREAD

**Issue by Decade1993** [ivmartel/dwv#392]
when I try to load dicom that on nginx server, like this:
`app.loadURLs(["http://ip/a.dcm"]);`

then the js alert a error:
` RequestError: An error occurred while reading 'http://ip/a.dcm' (http status: 0) [DicomDataLoader].`

did i miss some thing?

**Comment by ivmartel** [comment]
Does the console log give more details?

**Comment by ivmartel** [comment]
@Decade1993, did you make any progress on your issue? Do you need more help?

**Comment by ivmartel** [comment]
The wiki page [](https://github.com/ivmartel/dwv/wiki/Error-Messages) also gives more information.

Closing for now. Feel free to comment or reopen if you need.
