### ISSUE TITLE
How to load local dicom?

### ISSUE THREAD

**Issue by Decade1993** [ivmartel/dwv#393]
i use the function below:
`app.loadURLs(["flower.dcm"]);`

but it cause a error:
RequestError: An error occurred while reading 'flower.dcm' (http status: 0) [DicomDataLoader].

any help?

**Comment by ivmartel** [comment]
Same as for #392, the console log of your browser probably gives clues on what caused the error.

**Comment by ivmartel** [comment]
@Decade1993, did you make any progress on your issue? Do you need more help?

**Comment by ivmartel** [comment]
Closing for now. Feel free to comment or reopen if you need.
