### ISSUE TITLE
I need the last tag for installation by bower

### ISSUE THREAD

**Issue by HernanGH** [ivmartel/dwv#396]
Hola Iv, yo estaba usando los scripts de la carpeta decoders, pero todo usando bower, y actualmente no esta la ultima versión que contiene la carpeta de decoders para descargar por bower. 
Gracias

**Comment by ivmartel** [comment]
Ok, I'll clean-up the issues and try to publish a release as soon as possible.

**Comment by ivmartel** [comment]
Done! Let me know if you have any (or no) problem.

**Comment by HernanGH** [comment]
Great!! I hadn´t problem.
