### ISSUE TITLE
Add MPR

### ISSUE THREAD

**Issue by ivmartel** [ivmartel/dwv#4]
The viewer must provide MPR functionality. Multiplanar reconstruction (MPR) is the creation of slices in more anatomical planes than the one (usually transverse) used for initial tomography acquisition. See [X-ray_computed_tomography#Multiplanar_reconstruction](http://en.wikipedia.org/wiki/X-ray_computed_tomography#Multiplanar_reconstruction) on wikipedia.

**Comment by HerlanAssis** [comment]
Hii, any news about Multiplanar Reconstruction?

**Comment by ivmartel** [comment]
Getting there slowly, I recently added image iterators to easily switch view generation (see #749).
