### ISSUE TITLE
DICOM image to JPEG

### ISSUE THREAD

**Issue by jagjotwadali** [ivmartel/dwv#401]
I need to convert DICOM image to JPEG image and then display it on the web page.
Is there any dwv library to do this.
Kindly help .

**Comment by ivmartel** [comment]
This is not something dwv can do for now, but it should not be that complicated to implement. Basically you need to convert an HTML canvas to a JPEG image.

**Comment by anoob09** [comment]
@ivmartel @jagjotwadali  I have the same question. Any solution?

**Comment by jagjotwadali** [comment]
Yes I have a solution for this .the code is in C#.If you need I will send .

**Comment by anoob09** [comment]
@jagjotwadali I need php or javascipt if you can help me with that.. it would be awesome. Can you show me how to display DICOM image using location of the DICOM file. Basically any help would be appreciated. I don't have much knowledge about this.

**Comment by jagjotwadali** [comment]
I dont have the code in javascript and php.
I had made a DLL in .NET which converts DICOM image to JPEG and then I
display that JPEG image on the webpage but when I click on that JPEG image
the original DICOM image is displayed in the DICOM viewer.

You can display the DICOM image by providing the URL
http://index.html?input=[path of DICOM image on the server]

**Comment by anoob09** [comment]
@jagjotwadali  Can you help me in displaying it as JPEG using html5 and php and javascript. I really need your help right now. Any article, repo blogs will do too.

**Comment by jagjotwadali** [comment]
Well ,I dont have any idea about html5 and php and javascript .You can
refer the library cornerstone .It will be helpful in displaying the image .

search cornerstone library on github.

**Comment by anoob09** [comment]
I had gone through the library but couldn't find anyway to upload the DICOM file.
And which index.html you are referring to in the above comment?
Could you provide me the link?

**Comment by anoob09** [comment]
@jagjotwadali 
sure thanks for the help. I couldn't find which index you were talking about. But I can wait till monday. Enjoy the weekend <3

**Comment by anoob09** [comment]
about that index page code ? Can you get it now?

**Comment by ivmartel** [comment]
Hi, I created a fiddle to show how you can do it with dwv: https://jsfiddle.net/ivmartel/cuz4tsun/

It uses the canvas and its [toDataURL](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) method. Right click on the link and choose `save target as` to download as png.

**Comment by anoob09** [comment]
@ivmartel  I want to use local address of the DICOM file, not the URL. How to do that?

**Comment by AbdoulazizMaharou** [comment]
you can use local url like
app.loadURLs(["https://localhost/file/dicom/bbmri-53323851.dcm"]);

2018-05-28 10:36 GMT+01:00 anoob09 <notifications@github.com>:

**Comment by anoob09** [comment]
@AbdoulazizMaharou which javascript files do I need to include if I want to run this code https://jsfiddle.net/ivmartel/cuz4tsun/ on my web app ?

**Comment by ivmartel** [comment]
The only resource needed to run the code of this fiddle is [dwv-0.23.4.min.js](https://github.com/ivmartel/dwv/releases/download/v0.23.4/dwv-0.23.4.min.js).

**Comment by anoob09** [comment]
@ivmartel when I am using the local address http://localhost/0002.DCM. I am getting the following error.
Error: No JPEG Baseline decoder provided
    at H.image.SynchPixelBufferDecoder.decode (dwv-0.23.4.min.js:3:278951)
    at H.image.PixelBufferDecoder.decode (dwv-0.23.4.min.js:3:279685)
    at H.image.DicomBufferToView.convert (dwv-0.23.4.min.js:3:280876)
    at H.io.DicomDataLoader.load (dwv-0.23.4.min.js:3:321542)
    at XMLHttpRequest.<anonymous> (dwv-0.23.4.min.js:3:321851) (15:10:10:582 | error, null)
     at dwv-0.23.4.min.js:3

**Comment by ivmartel** [comment]
This simple example does not handle DICOM file with JPEG encoding, check out one of the more advanced examples such as dwv-jqmobile and look for `dwv.image.decoderScripts`.

I answered your second question in #506.

**Comment by jagjotwadali** [comment]
Hi ,I am sorry for the delay.Got stuck in some important work.You are
online now ? I can help .

Well ,you can download the source code of this library DWV and then you can
find the index.html page  in the folder

dwv-master->viewers->mobile->index.html

use that index.html page like
index.html?input=[path to dicom image]

**Comment by anoob09** [comment]
@jagjotwadali  I will try that..
And I want to store the annotation and its coordinates in database using php and mysql and javascript... Is it possible?

**Comment by anoob09** [comment]
Sorry, I couldn't dwv-master->viewers->mobile->index.html folder.

**Comment by ivmartel** [comment]
You can export a `state.json` file with the annotations.

The mobile demo was moved to [dwv-jqmobile](https://github.com/ivmartel/dwv-jqmobile).

**Comment by anoob09** [comment]
and ```state.json``` file will have coordinates and all the other data that I can use to create annotations again when I launch the app ?

**Comment by jagjotwadali** [comment]
I will explain you everything ,chat with me .my email id is
jagjotwadali@gmail.com

**Comment by anoob09** [comment]
Yeah sure
