### ISSUE TITLE
Conquest 1.4.19 and dwv

### ISSUE THREAD

**Issue by ysharoiko** [ivmartel/dwv#405]
I could not connect Conquet 1.4.19 and dwv 0.21 or dwv 0.16

Got 

```javascript
dwv-0.22.0-beta.min.js:9944 Uncaught TypeError: t.t is not a function
    at Object.u.i18n (dwv-0.22.0-beta.min.js:9944)
    at dwv.gui.Scroll.setup (appgui.js:187)
    at u.tool.Scroll.setup (dwv-0.22.0-beta.min.js:9693)
    at u.tool.Toolbox.setup (dwv-0.22.0-beta.min.js:9723)
    at ToolboxController.setup (dwv-0.22.0-beta.min.js:656)
    at App.init (dwv-0.22.0-beta.min.js:237)
    at HTMLDocument.<anonymous> (dgate.exe?port=5678&address=127.0.0.1&mode=dwv-simple&study=1:1.2.840.113619.6.260.4.1075578330.200.1451901231.346&size=560:35)
    at j (jquery-2.1.4.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.1.4.min.js:2)
    at Function.ready (jquery-2.1.4.min.js:2)
```
so I tried to pick the old one for wich lua script was in Conquest's package. It was 0.16
And even here it failed to work with error

```javascript
dwv-0.16.0.min.js:4978 GET http://127.0.0.1/cgi-bin/dgate.exe?requestType=WADO&contentType=application/dicom&seriesUID=&studyUID=1.2.840.113619.6.260.4.1075578330.200.1451901231.346&objectUID=1.2.840.113619.2.275.57473.13914671.21225.1451901264.721 500 (Internal Server Error)
```

But I suppose this one can be solved on server side, but i have no idea how.

cgi script http://127.0.0.1/cgi-bin/cgi.cgi 
works fine

dgate itself also gives everything? but when it gives image it failes to handle. Any help would be precious.

**Comment by ysharoiko** [comment]
Even 
http://127.0.0.1/cgi-bin/dgate.exe?requestType=WADO

Gives me 

Server error!

The server encountered an internal error and was unable to complete your request.

Error message: 
End of script output before headers: dgate.exe

If you think this is a server error, please contact the webmaster.

Error 500

127.0.0.1

**Comment by ivmartel** [comment]
I created #406 to solve the current scripts.

**Comment by ivmartel** [comment]
Closing, I suppose it helped! If not, feel free to reopen or comment.

**Comment by ysharoiko** [comment]
Tryed with 1.4.17

**Comment by ysharoiko** [comment]
Tryed with 1.4.7 version and dwv   "version": "0.22.0-beta" :

In dwv-simple.lua, got no 
\dwv\dwv-0.22.0-beta.min.js 
in distribution but dgate.exe was looking for it, copied \dwv\dwv.min.js to \dwv\dwv-0.22.0-beta.min.js got error
dgate.exe?port=5678&address=127.0.0.1&mode=dwv022sim&study=0009703828:1.3.46.670589.5.2.10.2156913941.892665384.993397&size=560:95 Uncaught TypeError: dwv.i18nOnInitialised is not a function
    at dgate.exe?port=5678&address=127.0.0.1&mode=dwv022sim&study=0009703828:1.3.46.670589.5.2.10.2156913941.892665384.993397&size=560:95
(anonymous) @ dgate.exe?port=5678&address=127.0.0.1&mode=dwv022sim&study=0009703828:1.3.46.670589.5.2.10.2156913941.892665384.993397&size=560:95


in dwv-simple.lua 
got the same trouble
Uncaught TypeError: dwv.i18nOnInitialised is not a function
    at dgate.exe?port=5678&address=127.0.0.1&mode=dwv022s&study=0009703828:1.3.46.670589.5.2.10.2156913941.892665384.993397&size=560:131

in dwv-mobile.lua 
Uncaught TypeError: dwv.i18nOnInitialised is not a function
    at dgate.exe?port=5678&address=127.0.0.1&mode=dwv022m&study=21:1.2.840.113619.6.260.4.1075578330.3049.1452249460.45&size=560:141

**Comment by ysharoiko** [comment]
In 1.4.19
got error accessing 
http://127.0.0.1:88/cgi-bin/dgate.exe?port=5678&address=127.0.0.1&mode=dwv022m&study=21:1.2.840.113619.6.260.4.1075578330.3049.1452249460.45&size=560

Server error!
The server encountered an internal error and was unable to complete your request.
Error message: 
Premature end of script headers: dgate.exe

If you think this is a server error, please contact the webmaster.

Error 500

127.0.0.1
Apache/2.4.28 (Win32) OpenSSL/1.0.2l PHP/7.1.10

**Comment by ivmartel** [comment]
See my answer on #406 [issuecomment-342998199](dwv/issues/406#issuecomment-342998199).
