### ISSUE TITLE
Save JSON State of the Annotated Image at server side

### ISSUE THREAD

**Issue by jagjotwadali** [ivmartel/dwv#409]
@ivmartel  I have one more question .

I want to save json state of the annotated image on the server and then I want to add a button on the dicom viewer which will display the annotated image .User should have option to view the image or the annotated image .Image can load the json state from the server .

I need a help and I also need to which is the javascript file ?

Thanks

**Comment by ivmartel** [comment]
For now the state is saved locally via the application [onStateSave](https://github.com/ivmartel/dwv/blob/master/src/app/application.js#L972) method, You would need to make it upload the file to your server. 

The application [loadURLs](https://github.com/ivmartel/dwv/blob/master/src/app/application.js#L491) will suppose that json files are state files, so you could add a button to load this server side state file.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment/reopen.

**Comment by JoyZhou007** [comment]
> For now the state is saved locally via the application [onStateSave](https://github.com/ivmartel/dwv/blob/master/src/app/application.js#L972) method, You would need to make it upload the file to your server.
> 
> The application [loadURLs](https://github.com/ivmartel/dwv/blob/master/src/app/application.js#L491) will suppose that json files are state files, so you could add a button to load this server side state file.

i want know if state.json was storage in server's database, i got state data from http xhr response, how can i load the state obj ?

**Comment by ivmartel** [comment]
@JoyZhou007, I guess #872 was related to you question.

**Comment by JoyZhou007** [comment]
> @JoyZhou007, I guess #872 was related to you question.

Yes,eventually I found the method `state.apply()` to solve my question.
