### ISSUE TITLE
Different series UID and number of columns

### ISSUE THREAD

**Issue by LaedaSt** [ivmartel/dwv#410]
Hello, i have the same problem (https://github.com/ivmartel/dwv/issues/276 , unfortunately, the topic is closed) ,but in one volume of files. User gets his "disk" in hospital, then tries to upload it on my app, and there is this problem. I don`t know why he got diffrents files (seriers UID and number of columns) in one "disk", but is there any way to make all of files be in the same format? Thank you!

**Comment by ivmartel** [comment]
One solution I can see is to parse the files and group the ones that have the same series UID. Each group can then be provided separately to the viewer and should load properly. This can be done using the parser of dwv or another one.

**Comment by LaedaSt** [comment]
Okey, thank you for answer. But can i do this in new .js,  without any changes in library? Or should i do it in some place in your code?  Or may be some advice, where should i find this in repo? Or its not a trivial task at all?

Thank you

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment/reopen.
