### ISSUE TITLE
about support image rotate and inversion

### ISSUE THREAD

**Issue by liangsu** [ivmartel/dwv#414]
hello!

  I think it's difficult for you to read this paper because my english is so bad! I am so sorry!

  I think this dwv very good ! but sometimes I am very hard to make image rostate and inversion,
can you give me some suggestion or give me some algorithm about this way.

In this plugin, I had modified some code to just support  rostate and inverse image, but on this time, I want draw a Line 、Arrow and Length， I find it's so difficult to draw a Line or Arrow on the position where the mouse glides over. At last, there is a picutor about my page.

thank you very much!

![aa](https://user-images.githubusercontent.com/16495294/31893425-13fe9eb0-b83e-11e7-9554-c975db4443de.png)

**Comment by ivmartel** [comment]
You need to also flip / rotate the draw layer. I'm not too sure on how to do this, the simplest would be to rotate all the shapes, maybe Konva has something for that.

**Comment by ivmartel** [comment]
Relates to #356.

**Comment by ivmartel** [comment]
Closing this issue, please refer to #356.
