### ISSUE TITLE
Magnifier Tool

### ISSUE THREAD

**Issue by jagjotwadali** [ivmartel/dwv#419]
Hi ,
I had integrated this dicom viewer into telemedicine application.

Now I need to have a magnifier glass   to view the enlarged part of the image. If you can help me with any javascript library or jquery library for this purpose 

Regards
Jagjot

**Comment by ivmartel** [comment]
It seems doable without a library, directly with the canvas, checkout this SO: [magnifying-glass-that-follows-cursor-for-canvas](https://stackoverflow.com/questions/23971717/magnifying-glass-that-follows-cursor-for-canvas).

**Comment by ivmartel** [comment]
Closing for now. Fell free to comment. Tell me how it went!
