### ISSUE TITLE
static viewer gui - window level error

### ISSUE THREAD

**Issue by jonathanface** [ivmartel/dwv#422]
I was playing around with the static viewer and saw this in the dropdown for window levels:

![dwv-issue](https://user-images.githubusercontent.com/30864098/32669062-505e4b9e-c60d-11e7-863c-c1e95a776d12.jpg)

I tracked it back to /src/gui/html.js line 489:
`for (var i in list)`

Adding this just below it fixed it:
`if (list.hasOwnProperty(i)) {`

Just thought I'd report it.

**Comment by ivmartel** [comment]
Thanks for your help! Do you know when this happens, on regular cases or were you trying to add pre-sets?

**Comment by jonathanface** [comment]
This happened to me while running the example static viewer on localhost. All I think I changed was removed some of the example filters & tools, and set it to use multiple dcm files via loadURLs().

**Comment by ivmartel** [comment]
Ok, integrating, thanks!
