### ISSUE TITLE
Questions about Json state from url

### ISSUE THREAD

**Issue by kongdetai** [ivmartel/dwv#431]
Hi ivmartel,
        Thank you for your wonderful job about DWV Project on Github !
	I have a question about DWV want to consult with you：
        If we did some annotation using DWV and generate a Json file, are there any way we can reload the annotation from the same file and allow the DWV viewer to display the same annotation information as stored in the Json file?  (May be other people see the same dicom file wants to see my Annotation)

I read the code from /src/app/application.js , I do not know if it is works and how to config?
```javascript
        // possible load from URL
        if ( typeof config.skipLoadUrl === "undefined" ) {
            var query = dwv.utils.getUriQuery(window.location.href);
            // check query
            if ( query && typeof query.input !== "undefined" ) {
                dwv.utils.decodeQuery(query, this.onInputURLs);
                // optional display state
                if ( typeof query.state !== "undefined" ) {
                    var onLoadEnd = function (/*event*/) {
                        loadStateUrl(query.state);
                    };
                    this.addEventListener( "load-end", onLoadEnd );
                }
            }
        }
        else{
            console.log("Not loading url from address since skipLoadUrl is defined.");
        }
```

**Comment by ivmartel** [comment]
Yes, you can load the state json file, either as a file (via file open or drag and drop) or as an url (as the code you mention shows, ie as `?state=[path to state file]`).

**Comment by kongdetai** [comment]
Thank you very much!
I got it.

One more question:
Do you have the description about Json state structure?
If I want to generate a Json file from database table ,how to organize the Json structure?
(Then I can reload the annotation from the generated Json state file, only for Drawing
Ellipse is enough. )

**Comment by ivmartel** [comment]
I do not have an official documentation of the state structure, best to check out the code: https://github.com/ivmartel/dwv/blob/master/src/app/state.js#L15

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now. Feel free to comment if you need more details.
