### ISSUE TITLE
DWV integration with android application

### ISSUE THREAD

**Issue by jagjotwadali** [ivmartel/dwv#444]
I had successfully integrated DWV DICOM viewer in telemedicine website .

Now I want to integrate the same in the Andriod Application.
Is it possible ?

Anyhelp in this regard

**Comment by ivmartel** [comment]
It should be possible, now I do not have a lot of experience with this so can't give much advice... Keep us posted with your progress!

**Comment by ivmartel** [comment]
Closing for now but still interested if you managed to do the integration!

**Comment by ivmartel** [comment]
I forgot to say that if you can share your web site, I'm interested!

**Comment by jagjotwadali** [comment]
I tried to integrate DWV dicom viewer in the andriod application using webview but the DICOM image is not visible in Full screen mode so I left it and now i am looking for another open source DICOM viewer for andriod application.

For web application DWV dicom viewer is working fine.the website is www.esanjeevani.com
