### ISSUE TITLE
Error : Not a Valid DICOM File (no magic DICM word found)

### ISSUE THREAD

**Issue by ikhsansofyan** [ivmartel/dwv#446]
I tried to open some dicom file, but there is one file that appeard error like that, nut when the file was I open in other viewer it was no problem. 
![image](https://user-images.githubusercontent.com/33239977/34855050-25cd0f84-f770-11e7-8d8d-b5558a8dfbc0.png)

**Comment by ivmartel** [comment]
Check this paragraph in the wiki: [Error-Messages#not-a-valid-dicom-file](https://github.com/ivmartel/dwv/wiki/Error-Messages#not-a-valid-dicom-file).

**Comment by ivmartel** [comment]
I hope my comment helped. Closing for now.

**Comment by ikhsansofyan** [comment]
I'm sorry for late reply, thanks for your help, but I need help about Dicom Premeable and prefix, can you help me where i found that?
Thankyou

**Comment by ivmartel** [comment]
I answered your preamble question in #188.
