### ISSUE TITLE
Load multiple remote slices

### ISSUE THREAD

**Issue by ivmartel** [ivmartel/dwv#45]
Via a simple url syntax, each slice being stored in different urls.

**Comment by danielsnider** [comment]
I'm really excited for this feature. I'm looking for an example of multiple slices loaded by URL. I am having a hard time finding an example.

Here are two URLs, what would be the DWV url to display both?
https://imagej.nih.gov/ij/images/pet-series/PT604001001.dcm
https://imagej.nih.gov/ij/images/pet-series/PT604001002.dcm

Thanks!

**Comment by danielsnider** [comment]
Found an example from you! I am including your example here:

> You need to url encode the input part of the url so that dwv does not try to interpret it.
> 
> Your input part: https://raw.githubusercontent.com/ivmartel/dwv/master/tests/data/?file=bbmri-53323851.dcm&file=bbmri-53323707.dcm&file=bbmri-53323563.dcm&file=bbmri-53323419.dcm&file=bbmri-53323275.dcm&file=bbmri-53323131.dcm
> 
> Becomes: https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dbbmri-53323851.dcm%26file%3Dbbmri-53323707.dcm%26file%3Dbbmri-53323563.dcm%26file%3Dbbmri-53323419.dcm%26file%3Dbbmri-53323275.dcm%26file%3Dbbmri-53323131.dcm
> 
> So the final url is: http://localhost:8080/index.html?input=https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dbbmri-53323851.dcm%26file%3Dbbmri-53323707.dcm%26file%3Dbbmri-53323563.dcm%26file%3Dbbmri-53323419.dcm%26file%3Dbbmri-53323275.dcm%26file%3Dbbmri-53323131.dcm&dwvReplaceMode=void (dwvReplaceMode is not in the input part)
> 
>

**Comment by veronikaslc** [comment]
@ivmartel There is a little issue with multi slice load. When there are alot of slices the URL is getting way too long. Is there a way to pass the slices URLs in a payload instead of chaining it to the main URL?

**Comment by ivmartel** [comment]
I'm not sure about payloads, I would have to look into it.

For now, what can be done is send a DICOMDIR (introduced recently, see #425) or a manifest (as described in [User-Stories#dwv-urs-io-006-data-manifest](https://github.com/ivmartel/dwv/wiki/User-Stories#dwv-urs-io-006-data-manifest)).
