### ISSUE TITLE
How to extract coordinates from annotation/drawing.

### ISSUE THREAD

**Issue by aksg87** [ivmartel/dwv#451]
What is the recommended way to extract the x, y coordinates from a drawing (i.e. circle annotation)? I know we can parse the JSON object but if there is a direct method please let me know!

**Comment by ivmartel** [comment]
There is no direct method to get the position of a drawing. I agree that it would be useful! Don't forget that the drawing position is in pixel, you need to apply the data spacing to get it in read world.

**Comment by ivmartel** [comment]
Closing for now, but interested in your findings if you solved your problem.
