### ISSUE TITLE
Parameter input

### ISSUE THREAD

**Issue by borgessys** [ivmartel/dwv#452]
In the input parameter I can pass the folder instead of the file?
Or if you have how do I view the DICOM images from my server directory?

**Comment by ivmartel** [comment]
Folder support is only on the gui side via the open file, you cannot programmatically do it, javascript code is not allowed to get a list of files from a folder (there has been an API proposal but it did not get accepted, see [html5rocks - filesystem](https://www.html5rocks.com/en/tutorials/file/filesystem/)).

The only solution I have for now is for you to provide the list of files to the app... While waiting for the implementation of #425 and the support of DICOMDIR.

**Comment by ivmartel** [comment]
Closing for now. Refer to #425 to follow its progress.
