### ISSUE TITLE
DICOM Files and Folders

### ISSUE THREAD

**Issue by tpitman** [ivmartel/dwv#453]
I am just learning how to use DWV and want to integrate it into my web site.

I have some CDROM images of DICOM data. They were produced by different doctors. All of them have a file called DICOMDIR in the root that looks like it is a standard DICOM file. Then there is a folder called DICOM with folders and what look like images at the very lowest level.

1 of the CDs has that format and the other 2 have different formats.

I am trying to figure out how I would load this into DWV for testing. I tried opening the folder and get an exception in the JS console:

`Uncaught Error: No loader found for file: [object File]
    at u.io.FilesLoader.load (dwv-0.22.1.min.js:3)
    at t (dwv-0.22.1.min.js:3)
    at dwv-0.22.1.min.js:3
    at App.loadFiles (dwv-0.22.1.min.js:3)
    at App.onChangeFiles (dwv-0.22.1.min.js:3)
    at HTMLInputElement.t (dwv-0.22.1.min.js:3)`

When I try to open the DICOMDIR file I get this error:

`dwv-0.22.1.min.js:3 TypeError: Cannot read property 'value' of undefined
    at u.image.DicomBufferToView.convert (dwv-0.22.1.min.js:3)
    at u.io.DicomDataLoader.load (dwv-0.22.1.min.js:3)
    at FileReader.<anonymous> (dwv-0.22.1.min.js:3)`

**Comment by ivmartel** [comment]
Folder support is only on the gui side via the open file, you cannot programmatically do it, javascript code is not allowed to get a list of files from a folder (there has been an API proposal but it did not get accepted, see [html5rocks - filesystem](https://www.html5rocks.com/en/tutorials/file/filesystem/)).

The good way to do it is via the DICOMDIR, as you tried, and this is a known task: #425. Not too sure when it will start...

The only solution I have for now is to provide the list of files to the viewer...

**Comment by ivmartel** [comment]
Closing for now. Refer to #425 to follow its progress.

**Comment by ivmartel** [comment]
Forgot to say that if you can share your web site, I'm interested!
