### ISSUE TITLE
DWV Integration into .NET Web App

### ISSUE THREAD

**Issue by tpitman** [ivmartel/dwv#454]
I have a web app written using knockout, Vue (changing to Vue) and .NET. I have it hosted on Azure.

I am trying to figure out the best way to integrate DWV into my web site as a viewer.

I will be storing DICOM information in my site and would also like to know the best way to handle that.

If someone has a tutorial or guide on doing so with details about the best place to put the DWV folders in my existing folder structure for the project / solution I would really appreciate it.

**Comment by ivmartel** [comment]
Other had troubles integrating with Vue (see #363), the solution I see for this is to make dwv importable as a module, see #399.

**Comment by ivmartel** [comment]
Once done, I'll try to create some integration examples in these platforms. Follow #399 for details.

**Comment by ivmartel** [comment]
Ok, the solution was not #399 but some other issues and mainly #468.

Check out the new [dwv-vue](https://github.com/ivmartel/dwv-vue) repo for some example integration with Vue.js.
