### ISSUE TITLE
Konva instance is already exist in current eviroment. Please use only one instance.

### ISSUE THREAD

**Issue by summy00** [ivmartel/dwv#458]
hi, I just want to add a draw tool to the sample code,
add in html:
```javascript
<script type="text/javascript" src="ext/konva/konva.js"></script>
<script type="text/javascript" src="dist/dwv.js"></script>
```
add in applauncher.js:
```javascript
myapp.init({
        "containerDivId": "dwv",
        "fitToWindow": true,
        "gui": ["tool", "drawList"],
        "tools": ["Scroll", "ZoomAndPan", "WindowLevel", "Draw"],
        "shapes": ["Ellipse"],
        "isMobile": false
    });
```

it appear error: Konva instance is already exist in current eviroment. Please use only one instance.
any suggestion?
thx

**Comment by ivmartel** [comment]
From [konva/issues/266](https://github.com/konvajs/konva/issues/266): "This message means that you have two copies of Konva code on the page. Added it twice?"

**Comment by ivmartel** [comment]
I hope my comment helped. Closing for now, feel free to comment.
