### ISSUE TITLE
Error: Cannot append a slice with different number of columns

### ISSUE THREAD

**Issue by AbdoulazizMaharou** [ivmartel/dwv#464]
Hi, please excuse my english
I have recently discover this open source project and i find it very interresting. So thanks  to the delevoper.
My question is when i triy to upload many dicom images, i meet the folowing error : ** Cannot append a slice with different number of columns**:
Please help me.

**Comment by ivmartel** [comment]
Please check this paragraph in the wiki error page: [cannot-append-a-slice](https://github.com/ivmartel/dwv/wiki/Error-Messages#cannot-append-a-slice).

You are most probably loading all the DICOM data from a folder and there is more that one study in it. DWV cannot mix both and does not know which one you want to load so it sends an error.

**Comment by AbdoulazizMaharou** [comment]
Thank you for your answer. Son how i can solve his case ?

**Comment by ivmartel** [comment]
_Copied message from @AbdoulazizMaharou on wrong thread_

var globalUrl = "http://localhost/radiologie/public/uploads/";
self.loadURLs([ "http://localhost/radiologie/public/uploads/
m9FuvxIUTycoaaBR42Re.DCM","http://localhost/radiologie/public/uploads/
lOuJYhqNiMX3BckeWtNC.DCM"]);
It fonctionned with on file example: self.loadURLs([ "
http://localhost/radiologie/public/uploads/m9FuvxIUTycoaaBR42Re.DCM"]);
But if exceeded one file the follow alert dialog appears:   ​Error: Cannot
append a slice with different number of columns
 m9FuvxIUTycoaaBR42Re.DCM
<https://drive.google.com/file/d/1rJtiuNqip0uifv6D5fSds2nhqH7AlfAb/view?usp=drive_web>
​​
 lOuJYhqNiMX3BckeWtNC.DCM
<https://drive.google.com/file/d/1Nqc4WR3JRFYmaZCVZudKE2KykR9lyOeI/view?usp=drive_web>
​Thanks to you for taking your times to answer me.🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏

**Comment by ivmartel** [comment]
These are different patients, you cannot load them in the same call to `loadURLs`. When you give several images to `loadURLs`, they need to be from the same study.

**Comment by AbdoulazizMaharou** [comment]
Ok now i understand. But my dicom files are provided from the same study( the same hospital). It is possible to delete the comparaison ?

**Comment by AbdoulazizMaharou** [comment]
My Dicom images or the integrality of my project ??

**Comment by ivmartel** [comment]
No, you cannot remove the comparison, the idea is to have a call to `loadURLs` for every different study (a study is a set of images from the same patient).

I don't understand your second question, what are you talking about?

**Comment by AbdoulazizMaharou** [comment]
I wrote in the  https://github.com/ivmartel/dwv/issues/462#issuecomment-372328071)
would still be interested if you could share the data so that I could think of a solution that uses both the image position and the instance number.

**Comment by ivmartel** [comment]
That comment was for the author of the other issue, not for you!

**Comment by AbdoulazizMaharou** [comment]
now i am sure that my two images are from the same study. I get the following error:
Error: Cannot append a slice with different SeriesInstanceUID

**Comment by ivmartel** [comment]
Did you find a solution to your problem or are you still getting the error?

**Comment by ivmartel** [comment]
Closing for now. Feel free to reopen/comment if you need.

**Comment by deitch** [comment]
I am hitting the same issue. Single DVD, single study. Running the included Windows dicom viewer treats them as a single study.

I guess it is possible that something is different with the tags, but how would I work around that?

**Comment by ivmartel** [comment]
The solution is to filter the files before loading them and just load those that belong together. I recently committed a fix for #466 which could be related.

It's true dwv could do this work and propose a list to the user to select what he wants to load.

**Comment by deitch** [comment]
Yeah. Most DICOM viewers just work with this, treating it as a single study.
