### ISSUE TITLE
Integrating with .NET Application

### ISSUE THREAD

**Issue by tpitman** [ivmartel/dwv#481]
I am trying to integrate dwv with a ASP.NET MVC application.

I am using Require to load javascript classes.

I am having trouble reconciling all the dwv dependencies. I have modified the main.js file with the following:

		"dwv": "../dwv",
		"i18next": "../dwv/utils/i18n",
		"i18next-xhr-backend": "../dwv/utils/i18n",
		"i18next-browser-languagedetector": "../dwv/utils/i18n",
		"jszip": "../dwv/io/zipLoader",

I figured this out one at a time as I tried to load the page and kept getting 404 errors on different .js files. I am not even sure the above is totally correct, I am just guessing.

The current file that is giving an exception when I try to load the page is konva.js. The problem is I can't seem to find any files in the dwv source for konva.js.

I assume it is some external module.

So my bigger question is do you have some document somewhere that would describe how I would go about setting this up? Assume a basic ASP.NET MVC app that uses Require and ViewModels in js.

I have a BundleConfig.cs file that has lines like these:

			bundles.Add(new ScriptBundle("~/bundles/toastr").Include(
				"~/Scripts/toastr.min.js"));

			bundles.Add(new ScriptBundle("~/bundles/dwv").Include(
				"~/Scripts/dwv.min.js"));

And I have a main.js that loads things and has dependencies like thiese:

		"utilities": "../utilities",
		"dwv": "../dwv",
		"i18next": "../dwv/utils/i18n",
		"i18next-xhr-backend": "../dwv/utils/i18n",
		"i18next-browser-languagedetector": "../dwv/utils/i18n",
		"jszip": "../dwv/io/zipLoader",
	},
	shim: {
		"jquery": { exports: "$" },
		"signalr.core": { deps: ['jquery'], exports: "$.connection" },
		"signalr.hubs": { deps: ['signalr.core'] },
		"signalr": { deps: ['jquery'], exports: "$.signalR" },
		"knockout": { deps: ['jquery'] },
		"bootstrap": { deps: ['jquery'] },
		"jqueryUi": { deps: ['jquery'] },
		"jquery.validate": { deps: ["jquery"] },
		"jquery.validate.unobtrusive": { deps: ["jquery", "jquery.validate"] },
		"bootstrap/modal": { deps: ["jquery"], exports: "$.fn.modal" },
		"tipr": { deps: ["jquery"], exports: "$.fn.tipr" },
		"textComplete": { deps: ["jquery"] },
		"dwv": { deps: ["i18next"] }
	}

Any help would be greatly appreciated.

**Comment by ivmartel** [comment]
Are you using the latest code? I made some cleanup with the dependencies, I do not include them in the repository, you need to run npm to download them. Yes, Konva is an external dependency. You can find the latest list at [package.json#L18](https://github.com/ivmartel/dwv/blob/develop/).

**Comment by ivmartel** [comment]
I hope you found a solution to your problem. If so, could you share it?

Closing for now. Feel free to comment / reopen if you need.
