### ISSUE TITLE
Is it to have a more than one view in the same window, as for example a 4*4 layout?

### ISSUE THREAD

**Issue by hellocxj** [ivmartel/dwv#482]
Hi ivmartel,
   As the title, I have a feature to implement the web viewer to show multi slice in muliti layout,how to do it?

**Comment by ivmartel** [comment]
This is not included in the viewer (yet), the only solution I can give you is to create multiple viewers as in this fiddle: [display example #1.1](https://jsfiddle.net/ivmartel/jkcmj0px/).

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now. Feel free to reopen/comment.
