### ISSUE TITLE
[Question] Rendering the DICOM info layer 

### ISSUE THREAD

**Issue by luckyvs1** [ivmartel/dwv#483]
I have a basic image viewer working using the DWV package, and was wondering how I can integrate the infoLayer which displays attributes about the DICOM file?

Is there any references you can recommend in order to recreate the info layer aspect of the DICOM viewer?

Thanks

**Comment by BrianMcRails** [comment]
Are you using one of the framework integrations (React/angular/vue) or just a standard implementation?

**Comment by BrianMcRails** [comment]
Check out the appgui, applauncher, and index.html from [this link](https://github.com/ivmartel/dwv/tree/v0.22.0/viewers/static) if you are doing a standard implementation. I think it’s not supported yet with the frameworks.

**Comment by ivmartel** [comment]
@BrianMcRails is right, this is not yet integrated in the React/Angular/Vue demos. The link points to the old static demo which is now [dwv-jqui](https://github.com/ivmartel/dwv-jqui). The other demo laking use of the layer is [dwv-jqmobile](https://github.com/ivmartel/dwv-jqmobile). 

The html and css code set the necessary div where the overlay will be displayed. The code of `applauncher` loads the `overlay.json` that defines the content of the overlay.

**Comment by ivmartel** [comment]
Check the demo viewers for progress and maybe post an issue on a specific one to make it move faster! 

I hope I answered your question. Closing for now. Feel free to reopen/comment.
