### ISSUE TITLE
Error: No loader found for url

### ISSUE THREAD

**Issue by deyung** [ivmartel/dwv#484]
I get this when loading an image url. Tried several different images.

**Comment by ivmartel** [comment]
If you could share what went wrong and how you fixed it, that would be cool.

**Comment by ketansarjen** [comment]
I am facing the same error. can anyone provide me solution if found any? Thanks

**Comment by ivmartel** [comment]
@ketansarjen, could you open another issue for your problem and share the url that gives the error? Thanks.
