### ISSUE TITLE
How to reset scroll event 

### ISSUE THREAD

**Issue by lavkesh1608** [ivmartel/dwv#487]
Hi,
I am using the same HTML for multiple Dicom images. **I am having the issue is that when I switch to view another image, on other image scrolls, the old image also appearing there**. I have call reset method before initializing other images. This issue is with only scroll event, rest control is working fine when viewing selected image.

I am attaching screenshots here :
1) When the first image is selected to view, doing a scroll with 1st [image.](https://ibb.co/iHCuUx)
2) When another image is selected to view, doing a scroll with 3rd [image.](https://ibb.co/iTndpx)
3) 1st image appeared in the scrolling of the 3rd [image](https://ibb.co/htdJpx)

My way of implementation is follow : 

```
function changeDicomImage(image){

       $(".drawList").html('');
       //console.log("clickeddddddddddd",image);
       $(".toolList").html('');
       $(".toolbar").html('');
       $(".imageLayer").html('');
       $(".drawDiv").html('');
      $(".imageLayer").html();
       $(".layerDialogDiv").hide();
       $("#progressbar").show();
  
    
    //applauncher.js  
    launchApp(image);
       

    };
```

//application.js
```
     this.init = function ( config ) {


       //reseting here 
        self.reset();

        var requestHeaders = "";
        var urls = []; 
        if(config.image && config.image.image){
            urls[0] = "../../DicomFiles/"+config.image.image;
        }else{
            urls[0] = "../../DicomFiles/image1"
        }
         //I15FP3O2";
         //urls[0] = "../../DicomFiles/Damwwwages-damages-17913774-1600-1200.jpg"
       // urls[0] = "http://10.10.3.48/plugins%20extra/Dicom/image1";
       self.loadURLs(urls, requestHeaders);`
  
      .............etc
}

```

**Comment by ivmartel** [comment]
I'm missing the rest of your code to really understand your issue, but if you are trying to do a side by side you need two independent apps as in this example: https://jsfiddle.net/ivmartel/jkcmj0px/

**Comment by ivmartel** [comment]
I hope my last comment helped. If you found a solution, it would be nice if you could share it. 

Closing for now, feel free to comment / reopen if  you need.

**Comment by sanbangarh309** [comment]
hi @ivmartel  is it implemented in latest code ?
