### ISSUE TITLE
Dynamically opening JSON state

### ISSUE THREAD

**Issue by jagjotwadali** [ivmartel/dwv#489]
I had already integrated DWV application into telemedicine application .I want to save the JSON state on the server .
I want to show a button on the DICOM viewer where the user can click and save the annotations and can view the annotated image.

I was also reading the document about ?state=[path to state file]) but it was not working .

```javascript
var ff="http://localhost:62919/images/417.dcm?state=[http://localhost:62919/images/417.dcm]";
var fimage = "viewers/mobile/index.html?input=" +ff;
window.open(fimage, "_blank", "status=0,top=0,left=0,toolbar=0,menubar=0,resizable=1,width=" + (screen.width) + ",height=" + (screen.height));
```

Any help in this regard.

**Comment by jagjotwadali** [comment]
Thanks @ivmartel .Its Working.

**Comment by anoob09** [comment]
I am getting this error 
```Cannot read property 'getParent' of undefined```
when I am trying to load ```state.json``` file with this URL
```http://localhost/MIC/index_dicom.php?input=http://localhost/MIC/mammos/case333/0003.DCM&state=http://localhost/state.json```

**Comment by ivmartel** [comment]
Could you share the console log to better understand what is going on?

**Comment by anoob09** [comment]
its ok now. I had to use state just after input and it went good

**Comment by Coebin** [comment]
I have a problem loading the state by the URL. this is the path I use

http://localhost/DicomVista/index.php?input=https%3A%2F%2Fmedicalsoftplus.com%2FbaseGeneral%2FArchivosDicom%2F86%2FPrueba%2F%3Ffile%3D1.dcm%26file%3D2.dcm%26file%3D3.dcm%26file%3D4.dcm%26file%3D5.dcm%26file%3D6.dcm%26file%3D7.dcm%26file%3D8.dcm%26file%3D9.dcm%26file%3D10.dcm%26file%3D11.dcm%26file%3D12.dcm%26file%3D13.dcm%26file%3D14.dcm%26file%3D15.dcm%26file%3D16.dcm%26file%3D17.dcm%26file%3D18.dcm%26file%3D19.dcm%26file%3D20.dcm&dwvReplaceMode=void&state=http://localhost/ArchivosDicom/86/Prueba/state.json

and it gives me the image error, if I load only the DCM files there is no problem. it looks like you are spelling out the state url

![dcmfail](https://user-images.githubusercontent.com/98852969/152065631-a8805f63-ca8c-4b48-a2e5-bc7ff4a71e54.png)

**Comment by ivmartel** [comment]
Moved to issue #1101 (thanks for creating it!)
