### ISSUE TITLE
Integration with joomla site

### ISSUE THREAD

**Issue by marcarea** [ivmartel/dwv#490]
Hi
I have some basic questions:
I am trying to add dwv to a joomla site, there is no documentation on this and I get continual errors.
I have the dwv folder unzipped and in my includes folder on the site.
1. Is it necessary to have a separate  jquery.js file on my server? Where does it go? Any particular version?
2. Joomla recommend that jquery is added using such code as:
  $document = JFactory::getDocument();
  $document->addScript('/includes/dwv/src/appgui.js')
BUt I get errors including
dwv is not defined
dwv.gui is undefined

3. What is the main script here? applauncher.js, app.js, or the jquery.js?

I find the documentation for dwv a bit useless, there seems to be no simple example for integrating into a CMS, Ive read that there may be conflicting versions of jquery may be the problem, but Ive no clue where to start!
ANy help is hugely appreciated
PS - the tool looks great on the examples, I would love to get it working!!
Cheers marc

**Comment by ivmartel** [comment]
dwv is the core library, example viewers can be found in separate repositories, see [Examples#viewers-and-integrations](https://github.com/ivmartel/dwv/wiki/Examples#viewers-and-integrations) for a full list but the one you may be interested in is [dwv-simplistic](https://github.com/ivmartel/dwv-simplistic) which does not have dependencies on jQuery.

In this viewer, the main script can be found in the `applauncher` file. This is where the JavaScript App object is created. 

A good starting point could also be the code of the WordPress plugin: see https://wordpress.org/plugins/dicom-support/

What is your plan? How do you see the viewer integrated? Do you plan on doing a plugin?

**Comment by marcarea** [comment]
Hi
thanks for your reply!
Sadly I still get the error using dwv-simplistic.

My code in the php file looks like this:
--------------------------------------------
echo '
<div data-role="page" data-theme="b">
	
	<div data-role="content">
		
		<div id="dwv">
			
			<div class="toolbar"></div>
			
			<div class="layerContainer">
				<canvas class="imageLayer">Only for HTML5 compatible browsers...</canvas>
			</div>
		</div>
	</div>
</div>
';

$document = JFactory::getDocument();
$document->addScript('/includes/dwv-simplistic-master/src/applauncher.js');
$document->addScript('/includes/dwv-simplistic-example.js');

------------------------
dwv-simplistic-example.js looks like this:
----------------------------

 // base function to get elements
dwv.gui.getElement = dwv.gui.base.getElement;
dwv.gui.displayProgress = function (percent) {};

// create the dwv app
var app = new dwv.App();
// initialise with the id of the container div
app.init({
    "containerDivId": "dwv"
});
// load dicom data
app.loadURLs(["includes/test.dcm"]);

-------------------------------
the errors thrown are :+1: 
------------------------------
ReferenceError: dwv is not defined - /includes/dwv-simplistic-master/src/applauncher.js (line 31) 
ReferenceError: dwv is not defined - /includes/dwv-simplistic-example.js (line 3)

I really dont see where the dwv object is defined - is it in the HTML <div>???
Thanks again, marc

**Comment by ivmartel** [comment]
You are right, you are missing the dwv library and its dependencies. Checkout the release folder (for ex: [dwv-simplistic/releases](https://github.com/ivmartel/dwv-simplistic/releases)), there is a zip file that contains all the necessary code. Copy it and try to mimic what is done in the `index.html` and `applaucher` to make your integration work.

**Comment by marcarea** [comment]
Thanks, Ive got something working now, although still not properly integrated into joomla it seems to run happily alongside it.
Can you please tell me if there are different scripts for differetn versions as I would like something more advanced that the simple viewer but cant seem to put my finger on the right files.
Nowhere in the documentation did I see an instruction to download the dwv script separately, I may have missed it but think the docs could be a bit clearer about it!
Thanks again for your replies, and of course your excellent coding work.
marc

**Comment by ivmartel** [comment]
[dwv-jqmobile](https://github.com/ivmartel/dwv-jqmobile/) and [dwv-jqui](https://github.com/ivmartel/dwv-jqui/) are more advanced demos. Check their release folder for full working packages.

Point noted for the documentation, any help is appreciated!

**Comment by ivmartel** [comment]
I hope my last comment helped. Will you make your Joomla integration / plugin public?

Closing for now. Feel free to comment / reopen if you need.

**Comment by ivmartel** [comment]
Thanks. Here is the code:

```php
---CODE TO PLACE DWV WINDOW WITHIN JOOMLA php SCRIPT----
---------------------------------------------------------------------------------
// shortcut pointing to the conquest data folder
$full_Path ="/includes/datalink/".$file_path;

echo '
    <!-- Main page -->
    <div data-role="page" data-theme="b">
        <!-- Main content -->
        <div data-role="content">
            <!-- DWV -->
            <div id="dwv">
                <!-- Toolbar -->
                <div class="toolbar"></div>
                <!-- Layer Container -->
                <div class="layerContainer">
                    <canvas class="imageLayer">Only for HTML5 compatible browsers...</canvas>
                </div><!-- /layerContainer -->
            </div><!-- /dwv -->
            <div id="dicomtags">
                dicom tags go here!
            </div><!-- /tags -->
        </div><!-- /content -->
    </div><!-- /page -->
';

$document = JFactory::getDocument();
$document->addScript('includes/dwv-jqui/node_modules/dwv/dist/dwv.js');

echo'
    <script>
    // base function to get elements
    dwv.gui.getElement = dwv.gui.base.getElement;
    dwv.gui.displayProgress = function (percent) {};

    // create the dwv app
    var app = new dwv.App();
    // initialise with the id of the container div
    app.init({
        "containerDivId": "dwv",
        "tools": ["WindowLevel"]
    });
    // load dicom data
    //app.loadURLs(["includes/test.dcm"]);
    app.loadURLs(["'.$full_Path.'"]);
    </script>
';
```
