### ISSUE TITLE
Image sorting 4D

### ISSUE THREAD

**Issue by rafasoyyo** [ivmartel/dwv#493]
Image sorting for 4d studies (different echo times, dynamics, b values) is not performed as expected because the tag "ImagePositionPatient" is the tag considered for the sorting.

We would like to work on this part, so it would be nice if you could share how to start considering other tags like "EchoTime", "EchoNumbers", "DiffusionBValue" or others...

Thanks in advanced

**Comment by rafasoyyo** [comment]
I use this comment to share some dicoms as example

[dcm.zip](https://github.com/ivmartel/dwv/files/1950325/dcm.zip)

**Comment by ivmartel** [comment]
Unfortunately no...

**Comment by dajunwu2006** [comment]
So what is the difference between this frame and slice?  It is a bit confusing, does it supports 2-dimensional browsing? Thanks!

**Comment by ivmartel** [comment]
Sorry, yes there is, see @rafasoyyo's comment above.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
