### ISSUE TITLE
Very Basic Viewer Javascript Exception

### ISSUE THREAD

**Issue by tpitman** [ivmartel/dwv#494]
I am trying to make a very simply dicom image viewer. I have a dicom study that one of my partners received from a doctor. It is an MRI of a shoulder. There are 6 images in the series.

I copied the very basic javascript dwv viewer and am simply passing in the list of files as an array and then I use the loadURLs function on the dwv app to load them.

I just have the range scroll control.

The first image comes up fine. As soon as I try to scroll to the second image I get an exception in the console.

Once I get the exception, nothing works anymore.

I tried modifying the dwv.js file to include a check for rhs being undefined (that is what it is when I debug it) and that gets me past this exception, but then I have another exception when I get to the last file. I figured maybe we get past this exception first and then worry about that one because maybe this one is causing that one.

Can someone tell me what I am missing? If I load this same image set into the example viewer on your web site it works fine without any exceptions.

Here is the exception:

dwv.js:16025 Uncaught TypeError: Cannot read property 'getCenter' of undefined
    at dwv.image.WindowLevel.equals (dwv.js:16025)
    at dwv.image.View.getCurrentWindowLut (dwv.js:16121)
    at dwv.image.View.generateImageData (dwv.js:16497)
    at generateAndDrawImage (dwv.js:1233)
    at Array.onSliceChange (dwv.js:956)
    at dwv.image.View.fireEvent (dwv.js:16665)
    at dwv.image.View.setCurrentPosition (dwv.js:16273)
    at dwv.ViewController.setCurrentPosition (dwv.js:2840)
    at HTMLInputElement.DWVViewModel.range.oninput (DWVViewModel.js:48)

I have the non min version of the dwv.js file so I can debug. Here is the html:

```html
<progress id="progressLabel" max="100"></progress>

<div id="dwv">
	<div class="layerContainer">
		<canvas class="imageLayer"></canvas>
	</div>
</div>

<input type="range" id="sliceRange" value="0">
```

Here is the javascript:
```javascript
define(["jquery"],
    function ($) {
    	return (function () {
    		var DWVViewModel = function (params) {
    			var self = this;

    			self.params = params;

    			self.progressLabel = document.getElementById("progressLabel");

    			// base function to get elements
    			dwv.gui.getElement = dwv.gui.base.getElement;
    			dwv.gui.displayProgress = function (percent) {
    				self.progressLabel.value = percent;
    			};

    			// create the dwv app
    			var app = new dwv.App();

    			// initialise with the id of the container div
    			if (self.params.ImageList.length > 1) {
    				app.init({
    					"containerDivId": "dwv",
    					"tools": ["Scroll"]
    				});
    			}
    			else {
    				app.init({
    					"containerDivId": "dwv"
    				});
    			}

    			// load dicom data
    			app.loadURLs(self.params.ImageList);

    			if (self.params.ImageList.length > 1) {
    				var range = document.getElementById("sliceRange");
    				range.min = 0;
    				app.addEventListener("load-end", function () {
    					range.max = app.getImage().getGeometry().getSize().getNumberOfSlices() - 1;
    				});
    				app.addEventListener("slice-change", function () {
    					range.value = app.getViewController().getCurrentPosition().k;
    				});
    				range.oninput = function () {
    					var pos = app.getViewController().getCurrentPosition();
    					pos.k = this.value;
    					app.getViewController().setCurrentPosition(pos);
    				}
    			}
    		}

    		return DWVViewModel;
    	})();
    });
```

**Comment by ivmartel** [comment]
The code seems correct. You mention a rhs being undefined, where is this happening? Have you checked that the value at which you are setting the slice position is coherent with the number of slices?

**Comment by ivmartel** [comment]
I hope you found a solution to your error, if so could you share it?

Closing for now. Feel free to comment / reopen if you need.
