### ISSUE TITLE
How to draw ruler line programmatically

### ISSUE THREAD

**Issue by ManojSolanki** [ivmartel/dwv#495]
I have tried so hard to find method for drawing ruler line by given coordinated programmatically but i unable to find any methods. Please help me to draw ruler line programmatically.

Thanks in advance.

**Comment by ivmartel** [comment]
Hi and thanks for your question, the functionality you are asking for was not anticipated as such. 

What you can do is create a State and apply it (as in [state.js#L68](https://github.com/ivmartel/dwv/blob/develop/src/app/state.js#L68)). Check out the tests for some example states: [tests/state](https://github.com/ivmartel/dwv/tree/develop/tests/state). The format of the state regarding drawings is the one of Konva, the third party drawing library,

**Comment by ManojSolanki** [comment]
I have tried to draw ruler line with test data that was mentioned in state_ruler_multi-slice.json with below-mentioned code but only DICOM image showing blurry and nothing happen.

This is my application.js code that is called on button event -

applicationJsObj = {
    renderCoordinatesByJSON : function(inputJson){
        var appinstance = new dwv.App();
        var stateObj = new dwv.State();
        stateObj.apply( appinstance, stateObj.fromJSON(JSON.stringify(inputJson) ) );
    }
}

Please help me. Meanwhile, I am still trying to figure out the problem.

Thanks in advance.

**Comment by ivmartel** [comment]
You should use the same app instance as the one you configured and used to load the dicom. In your code, it seems to be a new one.

**Comment by ManojSolanki** [comment]
Thanks for your reply.
New app instance was just to show you but we are using the previously created app icon.

**Comment by ivmartel** [comment]
Be careful with the sequence of events, Best to wait for the image data to be loaded and then load the state. This code works for me:
```javascript
app.addEventListener("load-end", function () {
    var jsonUrl = "https://raw.githubusercontent.com/ivmartel/dwv/develop/tests/state/v0.3/state-ruler.json";
    $.getJSON( jsonUrl, function( data ) {
        var stateObj = new dwv.State();
        stateObj.apply( app, stateObj.fromJSON(JSON.stringify(data)) );
    });
});
```

**Comment by ivmartel** [comment]
I hope the last comment helped. Closing for now. Feel free to comment / reopen if you need.
