### ISSUE TITLE
viewer Folder loss Or Can't find viewer Folder

### ISSUE THREAD

**Issue by bianliuzhu** [ivmartel/dwv#504]
After downloading, no viewer folder has been found, but this Demo: "https://ivmartel.github.io/dwv-jqui/demo/stable/index.html" has a UI interface (Chinese UI), how to download the UI in Demo, thank you!!!

**Comment by ivmartel** [comment]
The ability to open a folder (introduced at #424) should be available for all, the only limitation will be that some browser do not support it, checkout the current [caniuse input-file-directory](https://caniuse.com/#feat=input-file-directory). 

Have you checked the console log? It could maybe give a clue on what is happening...

**Comment by bianliuzhu** [comment]
How to use "DWV" in the "Vue" framework.

**Comment by ivmartel** [comment]
Ah, this is not implemented in the dwv-vue example, you can check the dwv-jqmobile example and try to reproduce.

**Comment by ivmartel** [comment]
Closing for now. Please open an issue on [dwv-vue](https://github.com/ivmartel/dwv-vue) if you still have problems.
