### ISSUE TITLE
Image Loading

### ISSUE THREAD

**Issue by anoob09** [ivmartel/dwv#507]
How can I use  local address of the DICOM file in app.loadURLs method?

**Comment by ivmartel** [comment]
Loading local files via url resolves to a cross origin error (see [Error-Messages#requesterror](https://github.com/ivmartel/dwv/wiki/Error-Messages#requesterror)). Best to serve them too.

**Comment by anoob09** [comment]
https://jsfiddle.net/ivmartel/LteeL0gf/
How to run this file on my browser after downloading? Which JS files I have to include?
