### ISSUE TITLE
Store annotations in database and retrieve them later

### ISSUE THREAD

**Issue by salif-04** [ivmartel/dwv#509]
I want to draw red rectangular annotations on the images and store them in the database. Later when that image is viewed again, those annotations should be retrieved and viewed. Is there a way by which I can target these annotations, and further redraw them.

**Comment by ivmartel** [comment]
We can continue discussing here. 

To create the state you could use this code:

```javascript
var state = new dwv.State();
var json = state.toJSON(app);
```

You would then have to write the code that sends the state to your server.

**Comment by salif-04** [comment]
I made a simple page, included the dicom and added zoom and pan functionality.
https://github.com/salif-04/tmp/blob/master/index.php

Now how to add the toolbox.

**Comment by ivmartel** [comment]
Check out the code of [dwv-jqui](https://github.com/ivmartel/dwv-jqui), copy all and remove what you do not need.

**Comment by salif-04** [comment]
Loaded the image from url #489. 
Then I removed the history window. After removing the history window, it showed errors.
```Uncaught TypeError: Cannot read property 'hasChildNodes' of null```

**Comment by ivmartel** [comment]
Can you share the full console log to have more details on the error?

**Comment by salif-04** [comment]
Sure.
![untitled](https://user-images.githubusercontent.com/32351953/40830713-c5a39c38-65a4-11e8-834b-cbe67e699bff.png)

**Comment by ivmartel** [comment]
You also need to remove the `undo` gui from the app configuration, see [applauncher.js#L16](https://github.com/ivmartel/dwv-jqui/blob/v0.1.0/src/applauncher.js#L16).

**Comment by salif-04** [comment]
Still the same error.

**Comment by salif-04** [comment]
![untitled1](https://user-images.githubusercontent.com/32351953/40833980-0ac7f1da-65ad-11e8-8c49-14eff4767c44.png)

**Comment by anoob09** [comment]
@ivmartel 
About saving the `state.json` file.
Where do I need to make the changes that you mentioned above ?
Should I change `dwv.min.js` file or I can create a new `JavaScript` function ?

**Comment by salif-04** [comment]
Ok. Now I am done with loading the image.
Need just one more help.

I want to rename the json file before downloading it. Means I dont want that dialog box thats prompts us for the download. I want to provide a specific name and download the image in background.

**Comment by ivmartel** [comment]
@anoob09 The code I mention above can go in an event handler that you create, so in another js file than the main dwv one.
@salif-04 How did you fix your error? If you send data to a server, I guess you will be able to store it as you want. The name of the file comes from the html link, see [appgui.js#L196](https://github.com/ivmartel/dwv-jqui/blob/v0.1.0/src/appgui.js#L196)  for the dwv-jqui.

**Comment by anoob09** [comment]
@ivmartel  I used the simplest `dwv` from your `js-fiddle` and then passed the `URL` and added the `jpg` and `jpeg` decoders for good measure.

**Comment by anoob09** [comment]
`VM110 state.json&case_id=20&image=LMLO&type=report&view_id=5:74 Uncaught ReferenceError: app is not defined
    at HTMLButtonElement.document.getElementById.onclick (VM110 state.json&case_id=20&image=LMLO&type=report&view_id=5:74)
document.getElementById.onclick @ VM110 state.json&case_id=20&image=LMLO&type=report&view_id=5:74`

**Comment by salif-04** [comment]
@ivmartel I dynamically opened the image #489 and it worked.
 
Now since I loaded the image dynamically, what object/parameter do we need to pass to state.toJSON()
```var state = new dwv.State();
var json = state.toJSON(app);```

**Comment by salif-04** [comment]
@ivmartel I dynamically opened the image #489 and it worked.

Now since I loaded the image dynamically, what object/parameter do we need to pass to state.toJSON()

```var state = new dwv.State();
var json = state.toJSON(app);```

**Comment by salif-04** [comment]
@ivmartel I dynamically opened the image #489 and it worked.

Now since I loaded the image dynamically, what object/parameter do we need to pass to state.toJSON()

```var state = new dwv.State(); var json = state.toJSON(app);```

**Comment by salif-04** [comment]
@ivmartel I dynamically opened the image #489 and it worked.

Now since I loaded the image dynamically, what object/parameter do we need to pass to state.toJSON()

```var state = new dwv.State();```
```var json = state.toJSON(app);```

**Comment by salif-04** [comment]
@ivmartel I dynamically opened the image #489 and it worked.

Now since I loaded the image dynamically, what object/parameter do we need to pass to state.toJSON()

```
var state = new dwv.State();
var json = state.toJSON(app);
```

**Comment by anoob09** [comment]
Tried changing the code for `dwv.min.js` since that's where this code is present
`this.onStateSave=function(){var e=new H.State;o.getElement("download-state").href="data:application/json,"+e.toJSON(o)}`
But for some reason all the changes I make are reverted. When I open `dwv.min.js` via editor, it shows that code has been changed. But when I inspect code for the Download Button after launching app, I don't see the changes I made. It shows the default `dwv.min.js` code.

**Comment by ivmartel** [comment]
The application `onStateSave` is used if you bind it to an event. It updated the download link with the content of the state (`o.getElement("download-state").href=...`). You are quoting the code of the minified version of dwv, replace it with the non minified version to better understand the code.

@anoob09, are you running one of the watch scripts provided with dwv? If so, it is possible that they re-create the minified dwv at each code change.
In the code you share there is no need to call `JSON.stringify(new_json)`. I think this is why @salif-04 is getting the `Unknown state file format` error.

Are you two working together? And no need for the sir, Sir!!

**Comment by anoob09** [comment]
@ivmartel  We tried it without using `JSON.stringify(new_json)` but it didn't work, it put `double qoute` (`"`)  in the `JSON` file which is invalid. If we use `stringify` then we are able to create the same `JSON` file as we get from the download link. So I don't think the error is due to `JSON` file. Its something else.

**Comment by salif-04** [comment]
What we are doing is 
**dwv.min.js:**
```
this.onStateSave=function(){
var e=new H.State;
var new_json = e.toJSON(o);
jQuery.post("add_annotation_script.php",
            {myJSON:new_json}
            );
}
```
**add_annotation_script.php:**
```
$myJSON = json_decode($_POST['myJSON']);
$rad_id = $_SESSION['rad_id'];
$image = $_SESSION['image'];
$case_id = $_SESSION['case_id'];
$view_id = $_SESSION['view_id'];
if (!file_exists("anno/".$rad_id)) {
    mkdir("anno/".$rad_id,0777,false);    
}
$path = "C:/wamp64/www/MIC/anno/".$rad_id."/".$image.$case_id.".json";
$f = fopen($path, "w+");
fwrite($f, $myJSON);
fclose($f);
chmod($path, 0777);
```

**Comment by salif-04** [comment]
After removing `JSON.stringify(new_json)`, we got different error while loading the state.json file.

We are loading it from URL(`http://localhost/MIC/annotation.php?input=http://localhost/MIC/mammos/case0006/000137.dcm&state=http://localhost/MIC/anno/5/LMLO6.json&case_id=6&image=LMLO&type=report&view_id=5`)

_SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data_

**Comment by salif-04** [comment]
We are getting the annotations back in the history window(not all, some of the annotations are missing) but these annotations are not visible by default on the dicom. They are visible after chicking on them from the showAnnotation tab.

**Alert :**
_TypeError: Cannot read property 'getParent' of undefined_

**Error :**
_TypeError: Cannot read property 'getParent' of undefined (dwv.min.js:2)
    at Konva.Group.add (konva.min.js:43)
    at H.DrawController.setDrawings (dwv.min.js:11)
    at App.setDrawings (dwv.min.js:2)
    at State.apply (dwv.min.js:11)
    at H.io.JSONTextLoader.R.t.onload (dwv.min.js:2)
    at H.io.JSONTextLoader.load (dwv.min.js:11)
    at XMLHttpRequest.<anonymous> (dwv.min.js:11)_

We are loading the state.json file through URL
_http://localhost/MIC/annotation.php?input=http://localhost/MIC/mammos/case0006/000137.dcm&state=http://localhost/MIC/anno/5/LMLO6.json&case_id=6&image=LMLO&type=report&view_id=5_

**Comment by anoob09** [comment]
`dwv.min.js:2 TypeError: Cannot read property 'getParent' of undefined
    at Konva.Group.add (konva.min.js:43)
    at H.DrawController.setDrawings (dwv.min.js:8)
    at App.setDrawings (dwv.min.js:2)
    at State.apply (dwv.min.js:8)
    at H.io.JSONTextLoader.R.t.onload (dwv.min.js:2)
    at H.io.JSONTextLoader.load (dwv.min.js:8)
    at XMLHttpRequest.<anonymous> (dwv.min.js:8)
G @ dwv.min.js:2`
Getting this error while loading the JSON file via URL. I tried using the `dwv.js` file instead of `dwv.min.js`. It worked at first. But when I reloaded the page I got the same error. After that, when switched back to `dwv.min.js` and it worked again. But when I reloaded the page, I got the same error. I don't think `JSON` file has anything to do here. Are you storing the `JSON` files in the browser via cookies or something ?

**Comment by ivmartel** [comment]
It seems Konva has troubles loading the json as if it does not contain the information it expects. Have you tried to load the state manually to see if the file is ok? No cookies, just a json file.

**Comment by anoob09** [comment]
How to load it manually? I have verified that the json file created via download link and json file created by me are same.

**Comment by ivmartel** [comment]
You can drag and drop it on the dwv-jqmobile demo for example (after having loaded the DICOM).

**Comment by salif-04** [comment]
It is gives the same error.

_TypeError: Cannot read property 'getParent' of undefined (dwv.min.js:3)
    at Konva.Group.add (konva.min.js:43)
    at H.DrawController.setDrawings (dwv.min.js:3)
    at App.setDrawings (dwv.min.js:3)
    at State.apply (dwv.min.js:3)
    at H.io.JSONTextLoader.R.t.onload (dwv.min.js:3)
    at H.io.JSONTextLoader.load (dwv.min.js:3)
    at FileReader.<anonymous> (dwv.min.js:3)_

**Comment by salif-04** [comment]
However, I created some annotations on the Baby MRI example dicom, downloaded the state and tried to load the state.json manually. It was also showed error.

**Comment by ivmartel** [comment]
Then there is a problem with the sate file. Does it look like the one used in the tests (see [tests/state/v0.3](https://github.com/ivmartel/dwv/tree/v0.23.4/tests/state/v0.3))?

**Comment by anoob09** [comment]
Yes. It looks like these examples only.

**Comment by anoob09** [comment]
Should I mail you the `JSON` file created by us and the the file created by the download link ? You can check if the fault is in the `JSON` file or not.
And also when tried I using this code
`var state = new dwv.State();
 var json = state.toJSON(app);`
in `dwv.js`. We got an error saying `app` is not defined. How to solve this, since I want to use `dwv.js` instead of `dwv.min.js` since it is more oraganised.

**Comment by ivmartel** [comment]
Yes, you can send me the state file.
In what context are you launching the code? Are you using the npm/yarn scripts?

**Comment by anoob09** [comment]
![image](https://user-images.githubusercontent.com/35919595/41096211-8a48ba98-6a71-11e8-8762-fbc090637ebc.png)

`{
	"version": "0.3",
	"window-center": 2047,
	"window-width": 4096,
	"position": {
		"i": 0,
		"j": 0,
		"k": 0
	},
	"scale": 1,
	"scaleCenter": {
		"x": 0,
		"y": 0
	},
	"translation": {
		"x": 0,
		"y": 0
	},
	"drawings": {
		"attrs": {
			"listening": true,
			"visible": true
		},
		"className": "Layer",
		"children": [{
			"attrs": {
				"name": "position-group",
				"id": "slice-0_frame-0",
				"visible": true
			},
			"className": "Group",
			"children": [{
				"attrs": {
					"name": "line-group",
					"visible": true,
					"id": "e17db3o4bhkr8",
					"draggable": true
				},
				"className": "Group",
				"children": [{
					"attrs": {
						"points": [38, 499, 2530, 499],
						"stroke": "#ffff80",
						"strokeWidth": 12.974658869395713,
						"name": "shape"
					},
					"className": "Line"
				}, {
					"attrs": {
						"x": 43,
						"y": 499,
						"sides": 3,
						"radius": 5,
						"rotation": -90,
						"fill": "#ffff80",
						"strokeWidth": 12.974658869395713,
						"name": "shape-triangle"
					},
					"className": "RegularPolygon"
				}, {
					"attrs": {
						"x": 2505,
						"y": 506.5,
						"name": "label"
					},
					"className": "Label",
					"children": [{
						"attrs": {
							"fontSize": 77.84795321637428,
							"fontFamily": "Verdana",
							"fill": "#ffff80",
							"name": "text"
						},
						"className": "Text"
					}, {
						"attrs": {
							"height": 77.84795321637428
						},
						"className": "Tag"
					}]
				}]
			}, {
				"attrs": {
					"name": "line-group",
					"visible": true,
					"id": "xlqbq0roptj1k",
					"draggable": true
				},
				"className": "Group",
				"children": [{
					"attrs": {
						"points": [51, 1349, 2549, 1316],
						"stroke": "#ffff80",
						"strokeWidth": 12.974658869395713,
						"name": "shape"
					},
					"className": "Line"
				}, {
					"attrs": {
						"x": 55.99956375930118,
						"y": 1348.9339529207139,
						"sides": 3,
						"radius": 5,
						"rotation": -90.75686579029184,
						"fill": "#ffff80",
						"strokeWidth": 12.974658869395713,
						"name": "shape-triangle"
					},
					"className": "RegularPolygon"
				}, {
					"attrs": {
						"x": 2524,
						"y": 1301,
						"name": "label"
					},
					"className": "Label",
					"children": [{
						"attrs": {
							"fontSize": 77.84795321637428,
							"fontFamily": "Verdana",
							"fill": "#ffff80",
							"name": "text"
						},
						"className": "Text"
					}, {
						"attrs": {
							"height": 77.84795321637428
						},
						"className": "Tag"
					}]
				}]
			}, {
				"attrs": {
					"name": "line-group",
					"visible": true,
					"id": "jy68jas9zz6vi",
					"draggable": true
				},
				"className": "Group",
				"children": [{
					"attrs": {
						"points": [58, 2426, 2179, 2387],
						"stroke": "#ffff80",
						"strokeWidth": 12.974658869395713,
						"name": "shape"
					},
					"className": "Line"
				}, {
					"attrs": {
						"x": 62.99915495900947,
						"y": 2425.908077773031,
						"sides": 3,
						"radius": 5,
						"rotation": -91.05341047542493,
						"fill": "#ffff80",
						"strokeWidth": 12.974658869395713,
						"name": "shape-triangle"
					},
					"className": "RegularPolygon"
				}, {
					"attrs": {
						"x": 2154,
						"y": 2372,
						"name": "label"
					},
					"className": "Label",
					"children": [{
						"attrs": {
							"fontSize": 77.84795321637428,
							"fontFamily": "Verdana",
							"fill": "#ffff80",
							"name": "text"
						},
						"className": "Text"
					}, {
						"attrs": {
							"height": 77.84795321637428
						},
						"className": "Tag"
					}]
				}]
			}]
		}]
	},
	"drawingsDetails": {
		"e17db3o4bhkr8": {
			"textExpr": "",
			"longText": "",
			"quant": null
		},
		"xlqbq0roptj1k": {
			"textExpr": "",
			"longText": "",
			"quant": null
		},
		"jy68jas9zz6vi": {
			"textExpr": "",
			"longText": "",
			"quant": null
		}
	}
}`

I drew 3 lines in this dicom. But when I used the `state.json` file. The 1st and 3rd drawings were retrieved. That too, the lines weren't visible at first. I had to select them from history window. But after that I wasn't able to edit these lines. To edit these I had to add one more line, and then I was able to edit these lines. It's very buggy. You can see the `state.json` file.

**Comment by salif-04** [comment]
No. We are not using yarn or npm scripts.

We simply linked all the js files to our php page.

**Comment by salif-04** [comment]
I took the live demo of dwv-jqmobile and dwv-jqui. Loaded the image, made some annotations on them, downloaded the image. Then again I loaded the image and tried to load the state(those I downloaded) manually, it showed the same error in both(dwv-jqmobile and dwv-jqui).

**Comment by ivmartel** [comment]
There seems to be something dwv does not like about your images... I'll investigate and tell you.

**Comment by ivmartel** [comment]
Ok, good one, it's not only your images, it's a general bug! State files with multiple shapes crash the app.

Can you try replacing this line [drawController.js#L395](https://github.com/ivmartel/dwv/blob/develop/src/app/drawController.js#L395) with `var stateGroup = statePosKids[0];` (changing the array index from `j` to `0`). It seems that shapes cannot belong to multiple groups, so if you affect a shape to a group it gets removed from the one it belong to before.

Tell me how it goes and thanks for spotting it!

**Comment by salif-04** [comment]
Where could we find the  drawController.js in dwv-jqui.

**Comment by salif-04** [comment]
We cannot locate the  drawController.js in dwv-jqui.

**Comment by ivmartel** [comment]
It's in dwv.

**Comment by anoob09** [comment]
It worked!
But now while declaring this in `dwv`
`var state = new dwv.State();
var json = state.toJSON(app);`
I am getting an error saying `app` is not defined. How to resolve this?

**Comment by ivmartel** [comment]
You need to call this code in the same context as where you create the app, in the demos that would be in the `applauncher` files.

**Comment by salif-04** [comment]
It worked well. Thanks for all the help. We appreciated it.

**Comment by salif-04** [comment]
The application cannot cannot distinguish between a arrow and a line.
On drawing an arrow and saving the state; after relaoding the state arrows are showed as lines.

**Comment by salif-04** [comment]
We are also unable to delete any of the annotations.

We are trying to delete by dragging and dropping the annotations to the red cross mark but it is not working.

**Comment by anoob09** [comment]
You need to check `edit mode` after loading the annotations through `JSON` to delete it.

**Comment by ivmartel** [comment]
For the arrow, I found a fix: change this line in [arrow.js#L61](https://github.com/ivmartel/dwv/blob/develop/src/tools/arrow.js#L61) to 
`var radius = 5 * style.getScaledStrokeWidth();` 
(change the number to fit your preferred size).

I'll have a look at the delete problem...

**Comment by salif-04** [comment]
Yes. Now the arrow head is displayed.

**Comment by salif-04** [comment]
I was trying to hide the **Download State** button `jQuery("#download-state").hide();` but it was not working? Why so?

**Comment by anoob09** [comment]
Is there any way to reduce the image load time? Chrome is taking 3.7-4 seconds to load the image.

**Comment by ivmartel** [comment]
Nearly there for the delete problem.

Improving the loading time on the dwv side needs work... Your image is quite large, can you make it smaller?

**Comment by anoob09** [comment]
I don't think we can compromise with the size here. Please let us know what can we to reduce the loading time.

**Comment by ivmartel** [comment]
Understood but I do not know of any easy solution... One thing would be to check that there are no bottlenecks in the code and that the code is the fastest it could be. Parsing the pixel data using web workers could help, this needs investigation...

**Comment by salif-04** [comment]
Hey. Did you fix the delete issue?

**Comment by ivmartel** [comment]
Yep cf #517

**Comment by salif-04** [comment]
Now its working well.

**Comment by ivmartel** [comment]
Good. Can you close the issue if you think it is resolved?

**Comment by salif-04** [comment]
Yes.
