### ISSUE TITLE
Integrating view function and anonymization with Flask

### ISSUE THREAD

**Issue by Viet995** [ivmartel/dwv#510]
Hello ivmartel!
I am conducting the web for DICOM image. But I do not know how to add it to Flask web application.
Can you help me this issue, please!?
Thank you so much!

**Comment by ivmartel** [comment]
You are talking about [flask](http://flask.pocoo.org/), the micro web framework written in Python?
I did not know it but by looking quickly at the docs, I guess you could just serve the index of one of the examples, [dwv-jqmobile](https://github.com/ivmartel/dwv-jqmobile) for ex. Not sure if there is a more tighter integration possible such as making dwv a component...

**Comment by Viet995** [comment]
Absolutely, the Flask is the framework of python. Currently, i just run the local website and use the sqlite database for local database.
Do you have any suggestion for run local without the yarn or npm?
Thank you so much

**Comment by ivmartel** [comment]
You just need yarn/npm to download the dependencies. The releases I do of the demos are fully functional, they do not need yarn/npm. See [dwv-jqmobile-0.1.0.zip](https://github.com/ivmartel/dwv-jqmobile/releases/download/v0.1.0/dwv-jqmobile-0.1.0.zip) for ex.

**Comment by Viet995** [comment]
Thank you so much!
I will try to use again.

Trương Ạnh Việt
Phone: 0945846565
Email: anhviet0606@gmail.com
Student at International University Ho Chi Minh City, Viet Nam.

2018-06-05 16:19 GMT+08:00 ivmartel <notifications@github.com>:

**Comment by Viet995** [comment]
I do not understand much about the Git installation.
Can I run your library without use Git app!?
Currently, I also use the Atom and I am trying to use yarn for integrating the your library on my Flask web.
Can you help me please! Or you know any keyword for building the link between Flask with your app

**Comment by ivmartel** [comment]
You just need to download the zip, extract the files and serve the folder from you flask code. No need for git nor yarn/npm.

**Comment by ivmartel** [comment]
Closing for now. Feel free to comment.
