### ISSUE TITLE
Preload Shapes

### ISSUE THREAD

**Issue by alexkavon** [ivmartel/dwv#511]
I need to be able to add preexisting shapes onto my dicom images upon initial load as well as add new shapes via the draw tool. Is this possible within the initial config. Perhaps something similar to:
```javascript
app.init({
  'containerDivId': 'dwv',
  'initShapes': [
    {
      type: 'ellipse',
      x: 100,
      y: 100,
      radiusX: 50,
      radiusY: 75
      stroke: 'red'
    }
  ]
......
})
```
Or perhaps specifying this through the html:
```html
<div className='drawDiv'>
  <Ellipse x="100" y="100" radiusX="50" radiusY="75" stroke="red" />
</div>
```

Or is there a better programmatic way to do this, that I'm missing?

**Comment by ivmartel** [comment]
You can use the application `loadURLs` with the url of a json state file to load a state after you loaded some associated data.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now. Feel free to reopen/comment if you need.
