### ISSUE TITLE
2x1 layout - have both series of images loading, but scrolling doesn't return to first series

### ISSUE THREAD

**Issue by DanTheMountainMan** [ivmartel/dwv#513]
Hi Yves,

I was trying to load 2 series of images side-by-side, scrolling works after the first load, and scrolling works after the second load on the next series, but I cannot get the scrolling to go back to the first series.  Any ideas on what controls which div to scroll?  I tried cloning the view variable and adding it back, but it still scrolls the same canvas.  Also, the events are still firing on both canvases, so I can potentially switch up and back through the events in toolBoxController, onMouch(event).

**Comment by ivmartel** [comment]
Hi, could you share your code to better understand?

**Comment by DanTheMountainMan** [comment]
I used 2 iFrames with drag and drop thumbnails, it works everywhere except
for Microsoft Edge.


-Dan

**Comment by ivmartel** [comment]
Close! About Microsoft Edge, does it give a specific error?

**Comment by DanTheMountainMan** [comment]
Closed, thanks for making DWV, it is a good project!


-Dan
