### ISSUE TITLE
Change Imaging Plane / View Mode

### ISSUE THREAD

**Issue by deSargeSoftware** [ivmartel/dwv#514]
Is there a way I could change the Imaging Plane / View Mode for a CT, in order to achieve something like this: https://fnndsc.github.io/ami/#viewers_quadview?
I need to be able to change the plane between these three:
- Axial
- Sagittal (lateral view)
- Coronal (frontal view)

from: https://sites.google.com/a/wisc.edu/neuroradiology/image-acquisition/the-basics
> There are three primary imaging planes that are utilized in neuroimaging: 
> - Axial plane: Transverse images represent "slices" of the body  
> - Sagittal plane: Images taken perpendicular to the axial plane which separate the left and right sides (lateral view)
> - Coronal plane: Images taken perpendicular to the sagittal plane which separate the front from the back. (frontal view)
Thank you.

**Comment by deSargeSoftware** [comment]
Is there anything started? If you point me to the right direction, I could probably help. Thanks. BTW, great job with the project ;).

**Comment by ivmartel** [comment]
Thanks, unfortunately nothing started yet... One first step would be to generate the views data in the [image](https://github.com/ivmartel/dwv/blob/develop/src/image/image.js) class.

**Comment by ivmartel** [comment]
Please refer to #4 for further information. Closing for now.

**Comment by alexqbm** [comment]
Did you achieve something related to what you originally posted,  @deSargeSoftware ? 
Thanks.
