### ISSUE TITLE
Will it possible to access OS system DICOM file in DWV viewer?

### ISSUE THREAD

**Issue by ManojSolanki** [ivmartel/dwv#520]
Hi Team,

Thanks for the valuable library.

We are having an application which is working on local server only. DICOM files can be located on any of the OS system paths. We are unable to load files from local system path to DWV viewer. 
Please let us know how can this achievable.

We have also checked in the Demo that DWV is having the option to select/browse DICOM from OS file system but in our case, we are having local file path only. And we need to load by the system path only.

Please help.

Thanks in advance.

**Comment by ivmartel** [comment]
For now, the only way to view local files in dwv is if the user selects them via a file selection through the browser (using the select file button) or via drag and drop. For security reasons, browsers only allow to read a file if the user explicitly provides it to the application. 

You cannot load a local file automatically from a web page, this will resolve in an error on most browsers.

If you really need this, then maybe have a look at [electronjs](https://electronjs.org/) that allows to embed some html/js in an installable executable that has more possibilities than a web page.

**Comment by ManojSolanki** [comment]
Hi @ivmartel ,

Yes, you are right. Even we are facing a problem with our web browser while accessing the file in DWV viewer.
Our app architecture doesn't allow to use electronjs js. As we are already working with WPF application. In our case, we are having a browser instance inside our WPF app in which we are loading angular and DWV viewer.

In our requirement user will select the path of files and we need to load selected files from that folder selected folder to DWV viewer pragmatically. We can not restrict the user to browse file or drag-drop files.

Please guide us to access the file from all file system of OS to our DWV viewer that would really help us.

**Comment by ivmartel** [comment]
You are saying that the user will select the DICOM files but not in the dwv viewer? Is that other UI another web page?

**Comment by ManojSolanki** [comment]
Yes, user will select only the path of DICOM files not in the DWV viewer. And this path will be selected on another web page.

**Comment by ivmartel** [comment]
If you have a [FileList](https://developer.mozilla.org/en-US/docs/Web/API/FileList) (created by an `<input>`), then you can load the files via the `app.loadFiles` method. Is that your case?

**Comment by ivmartel** [comment]
Hi, have you made some progress with this one?

**Comment by ivmartel** [comment]
Closing for now. Feel free to comment.
