### ISSUE TITLE
DWV Integration with Orthanc 

### ISSUE THREAD

**Issue by jagjotwadali** [ivmartel/dwv#523]
@ivmartel Hi .

I had already integrated DWV in telemedicine application(developed in .NET).

Now I want to implement DWV with Server . If I can use Orthanc or DICOOGLE as my application is developed in .NET.

I am reading Orthanc but I need a little help.

**Comment by ivmartel** [comment]
Check out the [dwv-orthanc-plugin](https://github.com/ivmartel/dwv-orthanc-plugin). It uses dwv 0.22 and should be updated.

**Comment by jagjotwadali** [comment]
I didn't understood completely this plugin dwv-orthanc-plugin.Can you provide any documentation or any other help .

**Comment by jagjotwadali** [comment]
I had installed dwv-orthanc-plugin and it is working .

Now I have two questions

1. Earlier I had integrated dwv viewer into telemedicine application  but now i want to integrate with dwv and the orthan plugin together with telemedicine application.is it possible?

2. dwv-orthanc-plugin supports jpeg ? I mean is it possible to upload jpeg images ?

**Comment by ivmartel** [comment]
Perfect!
1. it depends what you mean by telemedicine application, what functionality do you need?
2. yes, the plugin supports jpeg encoded dicoms

**Comment by jagjotwadali** [comment]
1. Currently ,I had integrated dwv dicom viewer into a telemedicine application(developed in .net framework). user can upload JPEG /DICOM image and then he/she can view the image/annotated image in the dicom viewer .The doctor can view the image/annotated image .Now DWV is working without any PACS or dicom server .I want the functionality of DICOM viewer and PACS server in my telemedicine application .My question to you is it possible to integrate orthanc dwv plugin with the telemedicine application .I do not have much idea about PACS server .In my understanding orthanc is a dicom server or mini pacs .

I always appreciate your  response and help .
Thanks a lot.

**Comment by ivmartel** [comment]
You're welcome. Could we continue this discussion on the dwv-orthanc-plugin repo? Best if you could create two issues with each of your questions.

**Comment by ivmartel** [comment]
Closing in the meantime, waiting for your questions on the dwv-orthanc-plugin repo.
