### ISSUE TITLE
Load dcm file

### ISSUE THREAD

**Issue by piyushtopale** [ivmartel/dwv#524]
How to load dcm file from local folder directory by manually setting path.
I also tried by using server path like 
app.loadURLs(["http://localhost:8095/ClientDoc/ImageResults/3121/3121_13_13_14_19.6193506.dcm"]);
but it showing RequestError: An error occurred while downloading 'http://localhost:8095/ClientDoc/ImageResults/3121/3121_13_13_14_19.6193506.dcm' (http status: 0).
or this is not valid dcm image.

**Comment by ivmartel** [comment]
First you can check that the viewer can load the data via file load or drag&drop. If it can, then the browser console log could give you more details about why it fails.

**Comment by piyushtopale** [comment]
Viewer can load data via file upload as well as drag&drop . 
In console i get the following issue.

proxyConsole.js:56 Error: Not a valid DICOM file (no magic DICM word found)
    at H.dicom.DicomParser.parse (dwv.min.js:3)
    at H.image.DicomBufferToView.convert (dwv.min.js:3)
    at H.io.DicomDataLoader.load (dwv.min.js:3)
    at XMLHttpRequest.<anonymous> (dwv.min.js:3)

I can not get the proper solution for that. Is there any way to allow all dcm files to load in viewer?

**Comment by ivmartel** [comment]
There seems to be a problem when retrieving the file. If you download it via its link and then try to load it, it fails, doesn't it?

**Comment by ivmartel** [comment]
Hi, have you made some progress with this one?

**Comment by ivmartel** [comment]
Could you share the file(s)? Do you have an idea of the max size? I can load files up to ~50MB.

**Comment by devmings** [comment]
you should add  MIME "x-lml/x-evm" for .dcm

**Comment by piyushtopale** [comment]
I have tried with MIME "x-lml/x-evm" but showing same issue.
Uncaught SyntaxError: Unexpected token <
In decode-jpegloss.js

I have attached some dcm files which not loaded properly.

[dcm.zip](https://github.com/ivmartel/dwv/files/2231468/dcm.zip)

**Comment by anoob09** [comment]
@piyushtopale I have successfully loaded 15 MB DICOM files. I think theirs some problem with the type of DICOM file you are using and not with the size of the file.

**Comment by devmings** [comment]
I found that cross-domain is not supported. Is that so？

**Comment by ivmartel** [comment]
@devmings cross domain is independent of dwv, it's a server setting that allows it or not (see [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)). 

Or were you asking @piyushtopale for his server settings?

**Comment by piyushtopale** [comment]
Hello everyone,
We have already allowed CORS in the middleware and mime type for the dicom. Following is the code snippet.

----------------------------------------------------------------------------------------------------
  //Enable CORS!
            app.UseCors(DefaultCorsPolicyName);

//Mime type
((FileExtensionContentTypeProvider)options.ContentTypeProvider).Mappings.Add(
                new KeyValuePair<string, string>(".dcm", "x-lml/x-evm")
                );
-----------------------------------------------------------------------------------------------------

Few files are working pretty fine but few files are getting stuck with error message in the console as
Uncaught SyntaxError: Unexpected token <
In decode-jpegloss.js

Need some insights on such behaviour of DWV.

**Comment by marlonnardi** [comment]
I have the same problem.
![dicom](https://user-images.githubusercontent.com/5359931/43414741-ae817422-9401-11e8-86fc-14223e680319.png)

**Comment by anoob09** [comment]
@marlonnardi you didn't include the decoder properly I guess.

**Comment by piyushtopale** [comment]
@ivmartel  i tried to load file from explorer as well as from url but in both ways it failed to load along with following error.

Uncaught SyntaxError: Unexpected token <
In decode-jpegloss.js

**Comment by ivmartel** [comment]
I had @marlonnardi by email and he fixed his problem.

@piyushtopale, by loading by file, I meant a drag and drop. I can do it with the demo (for ex [dwv-jqmobile](https://ivmartel.github.io/dwv-jqmobile/demo/stable/index.html)). I can also load your data via url on a local server. The problem must be in your setting that seems to corrupt the data.

**Comment by ivmartel** [comment]
@marlonnardi the babymri data that you reference in your html is not JPEG encoded so it does not need decoders. The DICOM file you provided is encoded and your code does not provide the decoders as in this example [applauncher](https://github.com/ivmartel/dwv-jqmobile/blob/v0.1.0/src/applauncher.js#L66) which explains why you get the `no decoder` error.

**Comment by marlonnardi** [comment]
thanks, is now working..

add this

`dwv.image.decoderScripts = {
        "jpeg2000": "decoders/pdfjs/decode-jpeg2000.js",
        "jpeg-lossless": "decoders/rii-mango/decode-jpegloss.js",
        "jpeg-baseline": "decoders/pdfjs/decode-jpegbaseline.js"
    };`
[sample_work.zip](https://github.com/ivmartel/dwv/files/2249466/sample_work.zip)

**Comment by ivmartel** [comment]
@piyushtopale any progress?

**Comment by ivmartel** [comment]
Closing for now. Feel free to comment.

**Comment by piyushtopale** [comment]
Sorry for late response, I was working for other things.
The issue has been resolved by updating decoder files in correct path, Previously it was not taking path from node modules . I use custom folder  path for that.
Thanks for your assistance.

**Comment by esties** [comment]
Hi all. I try to load .dcm file from local folder directory but without success so far. My goal is so simple. I want to load local dcm files and I want to scroll that's it. 

    dwv.gui.getElement = dwv.gui.base.getElement;
    dwv.gui.displayProgress = function (percent) {};

    dwv.image.decoderScripts = {
        "jpeg2000": "decoders/pdfjs/decode-jpeg2000.js",
        "jpeg-lossless": "decoders/rii-mango/decode-jpegloss.js",
        "jpeg-baseline": "decoders/pdfjs/decode-jpegbaseline.js"
    };

    var options = {
    "containerDivId": "dwv",
    "tools": {"Scroll": {}}
    };

    var app = new dwv.App();
    app.init(options);
    app.loadURLs(['DICOMDIR/MR000000','DICOMDIR/MR000001','DICOMDIR/MR000002']); 

result is one image without scroll. 
Please help

**Comment by esties** [comment]
And to run above source code correctly you just have to add	app.setTool("Scroll"); after init(options) function.
