### ISSUE TITLE
Need docs please to show how to install app on my server

### ISSUE THREAD

**Issue by geetee24** [ivmartel/dwv#526]
Missing the docs on how to get it running on my own web server and also give it a pointer to my data.

**Comment by ivmartel** [comment]
DWV is the core library. What you can install are demo integration that are in different repositories such as [dwv-jqmobile](https://github.com/ivmartel/dwv-jqmobile) (see [Examples#viewers-and-integrations](https://github.com/ivmartel/dwv/wiki/Examples#viewers-and-integrations) for the full list). Just download the release and it should be ready.

Pointing to your data can be made in different ways... Do you have any specific in mind? And just in case, have you seen the wordpress [plugin](https://wordpress.org/plugins/dicom-support/)?

**Comment by geetee24** [comment]
i can host my data on a cloud server but dont thnk I allowed to host the wordpress plugin. 

Regardless,, is there a documented sample that shows me how to provid ethe sample with a url to my data (on the same server).   

G

**Comment by geetee24** [comment]
the demo app gave me no insight on how to configure it to automatically load a bunch of data.  Note that the UI for loading via URL gave no feedback and then errored in a bunch of alert mesages

**Comment by ivmartel** [comment]
I hope my comment helped. Closing for now.
