### ISSUE TITLE
PR state of a dicom file

### ISSUE THREAD

**Issue by yimingluci** [ivmartel/dwv#527]
How can I save a PR state of a dicom file and then re-apply it using the dwv library?

**Comment by ivmartel** [comment]
I'm not familiar with DICOM Presentation States and do not know what would be needed to support them...  Any help is appreciated!

**Comment by yimingluci** [comment]
Hi, ivmartel. By Presentation states, I mean the annotations on the medical images.

**Comment by ivmartel** [comment]
Yes, you can save a json state file that contains the details about the annotations, checkout the `onStateSave` method in [application.js#L1031](https://github.com/ivmartel/dwv/blob/v0.23.6/src/app/application.js#L1031). You can load it back as a file or url. See also the tests in [tests/state](https://github.com/ivmartel/dwv/tree/v0.23.6/tests/state) for details.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment.
