### ISSUE TITLE
It is possible to add anchors on ruler drawing when clicking on any button 

### ISSUE THREAD

**Issue by ManojSolanki** [ivmartel/dwv#530]
Hello,

I want to add anchors on ruler line when any button pressed. Please suggest me if is possible.

Thanks

**Comment by ivmartel** [comment]
I guess it is doable. You would have to add code to the keydown method at [draw.js#L337](https://github.com/ivmartel/dwv/blob/develop/src/tools/draw.js#L337). The problem will be to choose the shape or maybe you just have one?

**Comment by ivmartel** [comment]
Did you close this issue because you fixed it? Can you share your solution?
