### ISSUE TITLE
No JPEG2000 Support when compiling with webpack

### ISSUE THREAD

**Issue by rrosen** [ivmartel/dwv#531]
Thanks for providing this amazing project!  We're using dwv in a Rails project and including it via webpack.  Most DICOM's are loading up fine but we're unable to get JPEG2000 support working.  I've added some custom configuration that makes JpxImage and its dependencies available as global variables, but something about the way webpack reads the main dwv.js file prevents it from seeing them.

Here's some example code
Webpack Config
```javascript
const webpack = require('webpack')
module.exports = {
  plugins: [
    new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery',
        Popper: ['popper.js', 'default'],
        JpxImage: ['dicom/jpeg2000-deps', 'JpxImage'],
        readUint16: ['dicom/jpeg2000-deps', 'readUint16'],
        readUint32: ['dicom/jpeg2000-deps', 'readUint32'],
        log2: ['dicom/jpeg2000-deps', 'log2'],
        ArithmeticDecoder: ['dicom/jpeg2000-deps', 'ArithmeticDecoder'],
    })
  ],
  module: {
    rules: [
      {
        test: require.resolve('dwv/decoders/pdfjs/util.js'),
        use: 'exports-loader?readUint16,readUint32,log2'
      },
      {
        test: require.resolve('dwv/dist/dwv'),
        use: 'imports-loader?this=>window'
      }
    ]
  },
}

```

jpeg-2000-deps.js
```
// Bundling JpxImage as a module so it can be made available with ProvidePlugin
import {readUint16, readUint32, log2} from "dwv/decoders/pdfjs/util"
console.log('readUint32', readUint32)
console.log('readUint16', readUint16)
window.readUint16 = readUint16.readUint16
window.readUint32 = readUint32.readUint32


export const ArithmeticDecoder = require('exports-loader?ArithmeticDecoder!dwv/decoders/pdfjs/arithmetic_decoder');
export const JpxImage = require('exports-loader?JpxImage!dwv/decoders/pdfjs/jpx');


export {readUint16}
export {readUint32}
export {log2}

window.ArithmeticDecoder = ArithmeticDecoder
window.JpxImage = JpxImage
```

our-custom-dicom-viewer.js
```
console.log('JpxImage', JpxImage)
console.log('readUint16', readUint16)
console.log('readUint32', readUint32)
console.log('log2', log2)
console.log('ArithmeticDecoder', ArithmeticDecoder)


console.log("loaded deps", window.JpxImage)
console.log("loading dwv")
const dwv = require('dwv/dist/dwv')

...
```

When I initialize dwv in this way and try to load a JPEG2000 image, it throws the No JPEG2000 support available error.

I was reading through Issue #399 and noticed the dwv-vue repository you mentioned there as an example of how to load dwv via webpack.  However, I'm noticing the [example application for that repo](https://ivmartel.github.io/dwv-vue/demo/stable/index.html) seems to have similar issues when trying to load JPEG2000 files.  I'm curious what it would take to get JPEG2000 support working in that application.

**Comment by ivmartel** [comment]
The way I made it work in the [dwv-react](https://github.com/ivmartel/dwv-react) project is to have the decoders as assets. I have to check if this is possible in the angular and vue one. Not sure if that could be a solution for you?

**Comment by ivmartel** [comment]
Did you make any progress on this one?

**Comment by rrosen** [comment]
Thanks for following up :). I got switched me to another project shortly after I filed this issue.  A co-worker picked it up and I think he’s trying a different approach without webpack

Rafe

**Comment by ivmartel** [comment]
Ok, closing for now. Feel free to comment to share your findings.
