### ISSUE TITLE
dwv orthanc plugin- to save or upload the JSON state

### ISSUE THREAD

**Issue by jagjotwadali** [ivmartel/dwv#547]
Hi @ivmartel  .

I understood Orthanc plugin and it is  working with orthanc server correctly.

Neither there is any possibility to save JSON state of annotations on the server or nor there is any possibility to upload it on the orthanc server.

Is there any provision to save the Json State on the server?

**Comment by ivmartel** [comment]
The current implementation only supports downloading the state file to the user, not to a server. In order to allow for that, the download should be redirected (not sure how) and the format would have to be supported by the PACS (maybe as Presentation State and RTStruct see #306)... Interesting work!

**Comment by jagjotwadali** [comment]
@ivmartel  Thanks for reply . I think orthanc dwv plugin should have this kind of feature in which a user can have the option to save the JSON state. 

Apart from this ,I am working on to call the Orthanc services through REST API .I will be thankful to you if you can answer my queries 

1. I have telemedicine application(esanjeevani.com) in which details of the patient are uploaded .I want to upload and view the DICOM images . My question to you is what is the best way to do it from option a or option b 
a) To call the REST API on the telemedicine website and then upload it and view it on telemedicine website itself?
b)Or  to redirect the page from telemedicine website to orthanc server where the user can upload and view the images ?

**Comment by ivmartel** [comment]
@jagjotwadali, sorry for the very late reply, did you make any progress?

**Comment by ivmartel** [comment]
Closing for now. Feel free to comment if you need.
