### ISSUE TITLE
Get draw position

### ISSUE THREAD

**Issue by axeforeverjumo** [ivmartel/dwv#549]
# Get draw postion (x, y, z, w)

I want it to make possible to get the draw area for download it.

![Save Draw Image](https://github.com/axeforeverjumo/images/blob/master/Selecci%C3%B3n_001.png?raw=true). Only way I imagin is to take draw positions and then use for example *image parser* to then save it.

I am thinking i can do it in **applauncher.js** in *myapp.addEventListener secction**

`myapp.addEventListener("draw-create", listener);`

and in **listener** changing the *function* to antoher one who take the draw area postions, if I can just donwload the image area will be perfect.

The goal is use it in octave for academic uses.

**Comment by ivmartel** [comment]
The `draw-create` event sends the id of the create shape, you would need to search for it in the draw list and get its position. But it will be the position in the canvas, not in the real world, it would need to be converted...

When you say `download the draw area`, do you mean the pixels? This is not possible but could be interesting.

**Comment by axeforeverjumo** [comment]
Sorry for late, was on working travel, really thanks for response. I want to download the "cropped image" as an image not pixels, it is possible?.

**Comment by ivmartel** [comment]
No, it is not available but it could be interesting!

**Comment by juanmanuelojeda** [comment]
Mr. Martel, I get the json file, how can I only extract the drawings id. Thanks for your time.

**Comment by ivmartel** [comment]
@axeforeverjumo there is always a way! Maybe easier to start with a rectangle, convert its coordinates in pixel position and extract this portion from the slice buffer.

@juanmanuelojeda, is it related to @axeforeverjumo's query? If not could you open another issue for this please?

**Comment by axeforeverjumo** [comment]
Yes you are right ivMartel, I did it. So now can where can I change the "colourmap" manually **in code** 
![PlainImage](https://github.com/axeforeverjumo/images/blob/master/JTDWV%20-%20Medical%20Image%20Viewer_003.png?raw=true?raw=true).

**Comment by ivmartel** [comment]
To complete my first answer, the world position of the shape can be obtained by using the shape indexes and the image geometry, see the `Geometry.indexToWorld` method [geometry.js#L262](https://github.com/ivmartel/dwv/blob/v0.25.2/src/image/geometry.js#L262).

**Comment by ivmartel** [comment]
Closing for now, follow #655 for updates on the crop tool. Feel free to comment if you need.
