### ISSUE TITLE
Dicom Web Viewer == Dicom Web Standard?

### ISSUE THREAD

**Issue by vsoch** [ivmartel/dwv#550]
Very silly question! Is this library set up to work nicely with the Dicom Web Standard? --> https://www.dicomstandard.org/dicomweb/ The names are very similar so I thought maybe? But "Dicom Web" and then switching out viewer vs. standard might just be a chance thing :) Thanks!

**Comment by ivmartel** [comment]
No, they are not the same. 

DICOMweb is a standard for how servers should interact with client applications, dwv is a DICOM Web Viewer (a client) that displays DICOM images. dwv does not, but could, consume DICOMweb services.

**Comment by vsoch** [comment]
I'm not done reviewing yet (and thank you for leaving this open in case I had more questions!) but I just wanted to say how beautiful / impressed I am with this viewer! It's a head above the other ones I've tested (thus far) and if we choose it I definitely look forward to helping with its development.

**Comment by vsoch** [comment]
thanks again!

**Comment by ivmartel** [comment]
Just corrected one of my statements above, I hope it is still clear...

**Comment by vsoch** [comment]
cool! Yes, thank you.
