### ISSUE TITLE
not certified for diagnostic use

### ISSUE THREAD

**Issue by vsoch** [ivmartel/dwv#554]
hey @ivmartel ! Could you clarify what you mean in the README about not being certified for diagnostic use?

> DWV is not certified for diagnostic use. Released under GNU GPL-3.0 license (see license.txt).

We want to use it in a real world setting, and are wondering about this note. Thanks!

**Comment by vsoch** [comment]
A bit of follow up after some wisdom from my colleague - does this mean that there isn't FDA approval? (and basically if used for diagnostic purpose and then there was some law suit, the party couldn't come around and blame the viewer.) This makes total sense!

**Comment by ivmartel** [comment]
You've got it. By certification, I mean medical software certification that the FDA or EU Notified Bodies can grant. This phrase is to remind people that dwv is not certified and that the software comes with no warranties and no possible liability of its authors (as said in the license).

The wikipedia [Medical software](https://en.wikipedia.org/wiki/Medical_software) page has more about standards used in certifications if you're interested.

**Comment by vsoch** [comment]
Awesome thank you! I will forward to my fellow viewer-lings.

**Comment by vsoch** [comment]
This answers my question, thanks for the speedy response! Closing issue.
