### ISSUE TITLE
slow processing speed when loading series with more than 100 Slices

### ISSUE THREAD

**Issue by frickt** [ivmartel/dwv#559]
Unnecessary buffer merging.

**Comment by frickt** [comment]
fixed with #558

**Comment by frickt** [comment]
Is there a reason why the buffer contains all slices?
to improve the performance even further, we could change the big buffer to a list of pointers to the original buffer, so we could omit the coping of all slices, what do you think?

**Comment by ivmartel** [comment]
No real reason, avoiding the copy looks like a good idea!

**Comment by frickt** [comment]
fixed with #569 
#558 can be discarded

**Comment by ivmartel** [comment]
Follow #569 for progress.
