### ISSUE TITLE
Dicom Slice order

### ISSUE THREAD

**Issue by frickt** [ivmartel/dwv#560]
I've a problem with the slice ordering of a series. not sure if 0020,1041 SliceLocation should be taken into account.

**Comment by frickt** [comment]
[example.zip](https://github.com/ivmartel/dwv/files/2333588/example.zip)

**Comment by ivmartel** [comment]
What is the problem with your data: are there misplaced slices or would you have it completely reversed?

**Comment by frickt** [comment]
the order is reversed. InstanceNumber is 1,2,3,4... where the calculated order through ImagePositionPatient goes the other way around. Other viewers like Synedra or Radiant works as expected first Image is InstanceNumber=1. Is the ImagePositionPatient wrong for this series or the calculation we do with it?

**Comment by ivmartel** [comment]
The code uses the `ImagePositionPatient` to determine the order of the slices according the their physical position in space. It uses the `ImageOrientationPatient` to guess the order. 

There seem to be two viewing conventions: radiological and neurological. They order slices differently, now I am not sure if this is file based or a user preference...

Related to #317, #261.

**Comment by frickt** [comment]
okay, thank you.
Seems to be an issue with the metatdata that the direction does not correspond between InstanceNumber and ImagePositionPatient. I'm not sure, if preferring the SliceLocation over ImagePatientPosition would lead into other problems...
