### ISSUE TITLE
A window level with a width of zero is not possible.

### ISSUE THREAD

**Issue by frickt** [ivmartel/dwv#561]
This exception gets thrown and shown on some images (full black). Could we prevent that and set 0 width to a default value of xx? throwing an error on a valid images seems no appropriate to me.

**Comment by ivmartel** [comment]
Would an extra check for zero width at window level creation ([view.js#L820](https://github.com/ivmartel/dwv/blob/develop/src/image/view.js#L820)) be enough? That would discard the wrong window level and the viewer will use another one from the list of defaults.

**Comment by ivmartel** [comment]
Closing, check #567 for progress.
