### ISSUE TITLE
Unable to abort RawImageLoader requests

### ISSUE THREAD

**Issue by frickt** [ivmartel/dwv#583]
the abort on RawImageLoader request does not work.
It's an issue with the UrlLoader.abort function, the readyState for these requests are UNSET and not LOADING as with DicomImageLoder.
As well the RawImageLoader.load function does not abort the image.onload async calls, so even after the abort, the images get rendered.

**Comment by Josecongas** [comment]
Hi @ivmartel , are you sure that this bug it's already fixed? I merge into my application the pull request #584 and it is not aborting the process for me. Thanks you in advance.

**Comment by ivmartel** [comment]
Hi @Josecongas, it is working for me: I try to load multiple pngs and cancel using crtl-x and the process gets cancelled. Now the images that have already been loaded still show, not sure if this is what you are expecting, the display could also be reset in this case.
