### ISSUE TITLE
Slice order MRT

### ISSUE THREAD

**Issue by lehnins** [ivmartel/dwv#586]
Hi,

I realy like your viewer so far, there's only one porblem: it displays the slice out of order.

I understand you use " 'Image Position Patient" to order them. My files don't contain that field, but they have "0020,0013,Image Number=1".
Is there a way to order them by this value or the filename or the index of the array given to "app.loadURLs" ?

Greetings

Lehnin

**Comment by ivmartel** [comment]
Using ImageNumber as a backup when there is no ImagePosition makes sense. I created #592 to implement it.

**Comment by ivmartel** [comment]
Follow #592 to see progress. Closing for now, feel free to comment if you need.
