### ISSUE TITLE
How to add more than one picture by parsing the picture's link

### ISSUE THREAD

**Issue by huamanlou** [ivmartel/dwv#589]
My pictures are saving another server，so I can not use the local folder to upload the pictures. I try the demo , but I just paste only one link  one time

**Comment by ivmartel** [comment]
I'm not sure I get your question, it seems related to providing multiple files via url, if it is check out [User-Stories multiple-data-url-scheme](https://github.com/ivmartel/dwv/wiki/User-Stories#dwv-urs-io-005-multiple-data-url-scheme).

**Comment by huamanlou** [comment]
By using app.loadURLs(arr) , I solute this problem. Thanks
