### ISSUE TITLE
Check evenness of string values when writing

### ISSUE THREAD

**Issue by tguiot** [ivmartel/dwv#590]
Hi,

while debugging some problem with our anonymized based on dwv, we've found out that the evenness of values is never checked before writing something with the DicomWriter class. We used to check in our own code so never had any problem with that, except for the meta header where odd length elements are sometimes written.

It seems like a relatively easy fix:

```javascript
//TO ADD, probably in some class in the utils folder or something
this.isEven = function(number) {
    return number % 2 == 0
}

//in DataWriter.js
this.writeString = function (byteOffset, str) {
        for ( var i = 0, len = str.length; i < len; ++i ) {
            view.setUint8(byteOffset, str.charCodeAt(i));
            byteOffset += Uint8Array.BYTES_PER_ELEMENT;
        }
        return byteOffset;

    //TO ADD
    if(!isEven(str.length)) {
        view.setUint8(byteOffset, 32);
        byteOffset += Uint8Array.BYTES_PER_ELEMENT;
    }
};
```
and something similar for the vr UI and OB.

If that looks correct at first glance, I'm even willing to propose a change, but I've never done that in github so I don't want to mess things. I'm not a professional developer, although I can read and write code...

**Comment by ivmartel** [comment]
Thanks for the code, do you have a reference in the standard that says that all fields must be of even length?

**Comment by tguiot** [comment]
Sure. It's in Part 5 of the standard.
[6.2 Value Representation (VR)](http://dicom.nema.org/MEDICAL/DICOM/current/output/chtml/part05/sect_6.2.html) (my emphasis):
> Values with VRs constructed of character strings, except in the case of the VR UI, shall be padded with SPACE characters (20H, in the Default Character Repertoire) when necessary **to achieve even length**. Values with a VR of UI shall be padded with a single trailing NULL (00H) character when necessary **to achieve even length**. Values with a VR of OB shall be padded with a single trailing NULL byte value (00H) when necessary **to achieve even length**.

> If a Value Field containing one or more UIDs is an odd number of bytes in length, the Value Field shall be padded with a single trailing NULL (00H) character to ensure that the Value Field is an even number of bytes in length.

[6.4 Value Multiplicity (VM) and Delimitation](http://dicom.nema.org/medical/Dicom/current/output/chtml/part05/sect_6.4.html) (my emphasis):
> Each string Value in a multiple valued character string may be of even or odd length, but the length of the entire Value Field (including "\" delimiters) **shall be of even length**. If padding is required to make the Value Field of even length, a single padding character shall be applied to the end of the Value Field (to the last Value), in which case the length of the last Value may exceed the Length of Value by 1.

> Only the last UID Value in a multiple valued Data Element with a VR of UI shall be padded with a single trailing NULL (00H) character when necessary to ensure that the entire Value Field (including "\" delimiters) is of **even length**.

[9.1 UID Encoding Rules](http://dicom.nema.org/medical/Dicom/current/output/chtml/part05/chapter_9.html#sect_9.1):

> If ending on an odd byte boundary, except when used for network negotiation (see PS3.8), one trailing NULL (00H), as a padding character, shall follow the last component in order to align the UID on an even byte boundary.

I haven't look in the code where multiple values are handled, but this might add a bit more complexity to the change

**Comment by tguiot** [comment]
Oh, and I first learned about this rule in this wonderful book: [Digital Imaging and Communications in Medicine (DICOM) - A Practical Introduction and Survival Guide](https://www.springer.com/gp/book/9783642108495)
Large portions can be read online [in Google Books](https://books.google.be/books?id=GpQmSXqhDcMC&printsec=frontcover&hl=fr#v=onepage&q&f=false)

**Comment by ivmartel** [comment]
I had a first go at this, check out commit 6cb576b and the 590-non-even-pad branch. What is missing is recalculating the length of the padded element...

**Comment by tguiot** [comment]
thanks. I commented directly in the code.

**Comment by ivmartel** [comment]
Moved to 0.28... I'm not sure of the VL and size calculation... I'm wondering if it should be done when the elements are created rather than just before writing.
