### ISSUE TITLE
Can I add Text from Tool?

### ISSUE THREAD

**Issue by yogen-darji-hs** [ivmartel/dwv#594]
Is there Adding Text supported to image?

Like we have in Fabric.js, we can add text to image

**Comment by yogen-darji-hs** [comment]
That's really quick reply. I love this DICOM viewer.

Double click will add "label" to existing drawing.

Can I add "standalone Label" only on image as Text only?

**Comment by ivmartel** [comment]
No... The idea is that at minimum you need an arrow to point to what you are annotating. What are you trying to label?

**Comment by yogen-darji-hs** [comment]
@ivmartel Thanks got you point.

One more question Can I load PNG image with URL something like following-

This is valid PNG image url but DWV tries to parse as DCM extension.

Can I force to load still as PNG type as URL has not *.png?

https://myazure.blob.core.windows.net/blob/c30IO+/fs/m/84xJnBe9TmY9qIa0M=?sv=2017-11-09&sr=b&sig=lcx%2FBE%2BetpeYYHvpLDJ%2FV2GAZxwIiOktWNEh3JJDGAg%3D&spr=https&sip=144.48.251.121&st=2018-10-30T06%3A07%3A05Z&se=2018-10-30T07%3A17%3A05Z&sp=r&rsct=image%2Fpng

**Comment by ivmartel** [comment]
You can load png files via url if the url contains a '.png', it is expecting the full file name, I did not anticipate a link like yours...

**Comment by yogen-darji-hs** [comment]
Again thanks for quick reply. Here is below how I achieved in case anyone face same issue.

// From URL, getting blob and then creating dummy "file" object and load that file now
 const blob = await (await fetch(myUrl)).blob();
 var file = new File([blob], "image.jpg", { type: 'image/png', lastModified: Date.now() });
 file['filename'] = file.name;
 dwvApp.loadFiles([file]);
