### ISSUE TITLE
Loading data directly from the a WADO "RetrieveStudy" call?

### ISSUE THREAD

**Issue by jmandel** [ivmartel/dwv#595]
I'm curious to know: if I have a server that only supports fetching an entire study, via "RetrieveStudy" (i.e., responding with HTTP multipart messages), is there a supported way to connect and load this study into dwv?

(Or if this question doesn't make sense, or if this is an obviously bad idea, I'd love to understand that :-))

Thanks!

**Comment by ivmartel** [comment]
Yes, it should work by providing the WADO uri of the data as detailed in [Dicom-Support#wado](https://github.com/ivmartel/dwv/wiki/Dicom-Support#wado).

**Comment by jmandel** [comment]
If I understood the docs right, this describes how to access data via "wado-uri" -- but I'm trying to ask about "wado-rs" (if that makes sense)? In other words, I'm looking to load data from a server that only knows how to respond to a request like:

```
curl --headers  -X GET --header "Accept: multipart/related; type=application/dicom` https://dicomserver/wadors/studies/${STUDY_UID}"
```

... which returns a multipart response. Does this make sense?

**Comment by ivmartel** [comment]
I think it does! dwv can only do http requests. Not sure if you can bind this curl to some http.

**Comment by jmandel** [comment]
What I'm describing is an HTTP request. It's just a slightly different HTTP reques than wado-uri; it's wado-rs, which uses an Accept header to negotiate the content type.

**Comment by ivmartel** [comment]
Ok, getting clearer. Some doc reference: 
 - [6.3 WADO-URI Response](http://dicom.nema.org/dicom/2013/output/chtml/part18/sect_6.3.html)
 - [6.5 WADO-RS Request/Response](http://dicom.nema.org/dicom/2013/output/chtml/part18/sect_6.5.html).

dwv expects one DICOM file per url so only the WADO-RS RetrieveInstance should work. This is used in the Orthanc plugin (see [Explorer/replace.js](https://github.com/ivmartel/dwv-orthanc-plugin/blob/v0.8.0/Explorer/replace.js)).

**Comment by jmandel** [comment]
OK. We're talking about RetrieveStudy, rather than RetrieveInstance

[6.5.1 WADO-RS - RetrieveStudy](http://dicom.nema.org/dicom/2013/output/chtml/part18/sect_6.5.html)
> This action retrieves the set of DICOM instances associated with a given study unique identifier (UID). The response can be DICOM or bulk data depending on the "Accept" type, and is encapsulated in a multipart MIME response.

... which should include a list of DICOM files in a multipart response. Is RetrieveStudy expected to work? If not, would you consider accepting a pull request adding this capability?

**Comment by ivmartel** [comment]
I don't expect RetrieveStudy to work... And yes, all pull requests are very welcome!!

**Comment by ivmartel** [comment]
I hope I answered your question, if so, can you please close the issue? And I am waiting for your pull requests!

**Comment by jmandel** [comment]
Yes, thanks!
