### ISSUE TITLE
MagicWand.Floodfill is not defined

### ISSUE THREAD

**Issue by yogen-darji-hs** [ivmartel/dwv#598]
@ivmartel I am using version 0.25.2 and while selecting tool 'Flood fill', I am getting error MagicWand.Floodfill is not defined.

Using with Angular 6
package.json
 "dwv": "^0.25.2",

I've also tried to add magic-wand.js in index.html but still getting same error.

Any workaround to run with Angular CLI?

**Comment by ivmartel** [comment]
I remember having troubles importing magic-wand in the module creation (see [module/intro.js](https://github.com/ivmartel/dwv/blob/v0.25.2/resources/module/intro.js)), not sure if things have changed since...

This will give problems in all framework integrations...

**Comment by yogen-darji-hs** [comment]
Yeah you are correct. If I made change in magic-wand.js to made it like export.defaults then it works.

I am now adding dwv.js directly from index.html(not from NPM) so this issue will be resolved.

**Comment by alexqbm** [comment]
Same problem here. Going to follow @yogen-darji-hs 's approach but still looks to me as a workaround rather than an actual solution.

**Comment by alexqbm** [comment]
Excuse me @yogen-darji-hs how did you exactly fixed the problem? Could you share that part of your code? I'm having trouble with the Magicwand dependency in Angular 8.

**Comment by alexqbm** [comment]
@yogen-darji-hs still having trouble using angular with dwv and magicwand. Please link me your code when you read this. Thanks.
