### ISSUE TITLE
Cannot append a slice with different orientation

### ISSUE THREAD

**Issue by huamanlou** [ivmartel/dwv#601]
When I upload folder contains 12 MR dcm pictures, about 2 or 3 pictures it alert ' Cannot append a slice with different orientation'， What is the meaning ? and how to solve this error?

**Comment by ivmartel** [comment]
Check out [Error-Messages#cannot-append-a-slice](https://github.com/ivmartel/dwv/wiki/Error-Messages#cannot-append-a-slice). You are most probably mixing data sets.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if  you need.

**Comment by fabrizzios** [comment]
is possible to show the entire serie even when the serie has one scout image , some CTs send the reconstruction files and include the scout in the serie
thanks
