### ISSUE TITLE
Does it support waveform data?

### ISSUE THREAD

**Issue by ppazos** [ivmartel/dwv#604]
Trying to open a waveform DICOM file got TypeError: n.getRawDicomElements(...).x7FE00010 is undefined

**Comment by ivmartel** [comment]
Unfortunately not... But it is in the [roadmap](https://github.com/ivmartel/dwv/wiki/Roadmap)...

Do you have some example displays?

**Comment by ivmartel** [comment]
Closing for now. I'm interested if you make any progress!
