### ISSUE TITLE
How to clear layout

### ISSUE THREAD

**Issue by levs1205** [ivmartel/dwv#606]
I was trying with reset, but not clear the principal layout,

**Comment by levs1205** [comment]
Yes, but it's not working, the image still appears.

**Comment by ivmartel** [comment]
Sorry I got confused, the `app.reset` method resets the internal variables but not the display. Check out the `app.onDisplayReset` method to reset the display ([application.js#L1172](https://github.com/ivmartel/dwv/blob/v0.25.2/src/app/application.js#L1172)). This method is used in the demo viewers such as [dwv-simplistic](https://github.com/ivmartel/dwv-simplistic).

**Comment by ivmartel** [comment]
I hope I answered your issue. Closing for now, feel free to comment if you need.
