### ISSUE TITLE
Conquest version 1.4.19c

### ISSUE THREAD

**Issue by marcelvanherk** [ivmartel/dwv#609]
I am providing integration of dwv in the latest version of conquest (using newweb). The new mechanism allows series and study level viewing in one source file (dwvviewer_starter.lua). With minimal changes, the dwv-simplistic script works for series if renamed to dwvviewer_starter.lua, changing the urlRoot line as follows:

local urlRoot = 'http://'..server_name..script_name

But I wondered if there a simple app using dwv that allows viewing at study level. Marcel

**Comment by marcelvanherk** [comment]
Integration file (WIP) is attached:

[dwvviewer_starter.zip](https://github.com/ivmartel/dwv/files/2612585/dwvviewer_starter.zip)

**Comment by ivmartel** [comment]
Looking good! And no, there is no study level viewer. You mean a page that would present snapshots of the series it contains?

**Comment by marcelvanherk** [comment]
Thanks,

Indeed. Allowing click or drag and drop of one series into the main viewer.
The snapshots could be generated with WADO as jpg's

Marcel

**Comment by marcelvanherk** [comment]
I guess what I can do first is make a conquest specific (Lua scripted)
study viewer page with thumbnails, and run DWV or another select viewer for
the clicked series in an iframe. I have an own viewer, DWV and also just
managed to couple Papaya.

regards,

Marcel

**Comment by ivmartel** [comment]
Looks like a good plan!

**Comment by ivmartel** [comment]
Hi @marcelvanherk, did you make any progress on this one?

**Comment by ivmartel** [comment]
ping @marcelvanherk ?

**Comment by ivmartel** [comment]
Regarding the study/series browser, I created #646.

**Comment by ivmartel** [comment]
Closing for now, to be followed in #646.
