### ISSUE TITLE
URL with GET parameter not supported.

### ISSUE THREAD

**Issue by ShinChven** [ivmartel/dwv#610]
Hi,

I am trying to use a access token to protect static file. However when I entered a URL with GET parameter like:
> http://domain.com/file/image.jpg?accesstoken=xxxx

dwv says:

> Not a valid DICOM file (no magic DICM word found)

Is it possible to support URL with GET parameters in the future?

ShinChven

**Comment by levs1205** [comment]
I had the same problem, but i found the solution.  Dwv always wait the file extension.

http://domain.com/file/image.jpg?accesstoken=xxxx&ext=.jpg

I hope this helps you.

**Comment by ivmartel** [comment]
Thanks @levs1205 for this quick fix! @ShinChven, you're right, the url parsing must be made smarter.

**Comment by ShinChven** [comment]
@levs1205 Thanks! I found this, too.

**Comment by arturojain** [comment]
Is there a way to fix detecting the file type after loading. i.e. Detecting the error and reloading while passing the format.

**Comment by arturojain** [comment]
Could we use the content/type from the response?

**Comment by arturojain** [comment]
ok, so it all works using the canLoadUrl for each loader in the list, meaning we could in theory modify it to use either magic number to detect other filetypes or the first bytes for DICOM?

**Comment by ivmartel** [comment]
Closing for now. Follow #650 for updates.
