### ISSUE TITLE
How to create an Ellipse in anguler with dwv.tool.EllipseFactory.prototype.create.

### ISSUE THREAD

**Issue by satanand7** [ivmartel/dwv#612]
I want to draw an ellipse with provided function dwv.tool.EllipseFactory.prototype.create.
it required these three parameters. (points, style, image).
please let me know the point array format which can draw an ellipse with dwv viewr.

I got this error when i pass the points array like `var points=[[10,10],[10,10]];`
```
ERROR TypeError: "points[0].getX is not a function"
```
actually i am not aware about the points array which is required. Please help.
Also let me know if any type of document you have to implement all functionality with this too.
I have read out the documentation here 
https://ivmartel.github.io/dwv/demo/stable/doc/dwv.math.Ellipse.html****
but can't find my solution.
Thanks in advanced.

**Comment by ivmartel** [comment]
Hi, sorry the doc should be clearer, the input for the create method is an array of `dwv.math.Point2D`.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
