### ISSUE TITLE
not fileload with get parameters  

### ISSUE THREAD

**Issue by Isksule** [ivmartel/dwv#613]
Hi,
In the setup function found in the loader file, how do I send it as an official parameter in the computer without selecting a file. just show the picture without selecting the file. Am I in the right function to do this?
loader.js \  

dwv.gui.base.FileLoad = function (app)
{
      this.setup = function()
    {
}
}

**Comment by ivmartel** [comment]
I am not sure I understand your question, are you looking for something like [loadURLs](https://github.com/ivmartel/dwv/blob/v0.25.2/src/app/application.js#L520) method?

**Comment by Isksule** [comment]
thanks ı solved
