### ISSUE TITLE
how to use a array in a loadurls ?

### ISSUE THREAD

**Issue by Isksule** [ivmartel/dwv#617]
dicom how to be in an array for example json I am doing but giving error.
Error: Not a valid DICOM file (no magic DICM word found).
[{"resim":"1.dcm"},{"resim":"1.dcm"},{"resim":"1.dcm"}]

how do it ?

**Comment by ivmartel** [comment]
The `loadURLs` methods takes a simple string array as input like `['1.dcm', '2.dcm', '3.dcm']`.

**Comment by Isksule** [comment]
I would like to pull it from the database but I can't show away because it is json. thank you

**Comment by Isksule** [comment]
file:///C:/Users/Lenovo/Desktop/pacs/index.html?input=http://localhost:8080/?file=1.dcm&file=2.dcm
ı get error . 
RequestError: An error occurred while retrieving the binary file (via http): http://localhost:8080/?file (status: 0).
pls help me  thanks

**Comment by ivmartel** [comment]
Followed in #618.

**Comment by imran-khani** [comment]
How can we use Ajax instead of directly loading the images?

**Comment by ivmartel** [comment]
Not sure I get your question @imran-khani. It does not seem related to this issue, can you open another one please?
