### ISSUE TITLE
Where is the viewer files ?

### ISSUE THREAD

**Issue by aalpa35** [ivmartel/dwv#622]
Where is the viewer files? 

https://localhost/viewer/index.html?input=https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dbbmri-53323851.dcm%26file%3Dbbmri-53323707.dcm%26file%3Dbbmri-53323563.dcm%26file%3Dbbmri-53323419.dcm%26file%3Dbbmri-53323275.dcm%26file%3Dbbmri-53323131.dcm&dwvReplaceMode=void

**Comment by ivmartel** [comment]
Not sure I understand your question, just in case, here is an answer regarding the different example viewers using dwv.

The viewers have been moved to their own project, for example the mobile one is now [dwv-jqmobile](https://github.com/ivmartel/dwv-jqmobile). See [Examples#viewers-and-integrations](https://github.com/ivmartel/dwv/wiki/Examples#viewers-and-integrations) for the full list.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
