### ISSUE TITLE
Unable to remove anchors from ellipse

### ISSUE THREAD

**Issue by satanand7** [ivmartel/dwv#623]
I have plot the ellipse bit I don't want to visible anchor after that. 
Is there any option to remove anchor from ellipse.
This is also happen with the the plotting of line in app.
Here is the code.

```javascript
var state = new dwv.State();
var currentFrame = CommonService.instance.dwvApp.getViewController().getCurrentFrame();
if (currentFrame == 0) {
  data.drawings.children[0].attrs.id = "slice-0_frame-0";
}
dwv.State.apply(CommonService.instance.dwvApp, data, currentFrame);
```

I haven't seen any option to remove anchor when we plot in the canvas of dwv app.
Can we have any option to remove anchor when we plot the particular shape to the app.
Thanks in advance.

**Comment by ivmartel** [comment]
It looks like a reasonable request, I'll see what I can do.

**Comment by ivmartel** [comment]
Sorry, not sure what I understood on Jan 7 but I do not any more... At draw or when loading a state, anchors do not appear. They appear when you select a shape to allow for its edition. Do you want to remove the edition ability?

**Comment by ivmartel** [comment]
Still interested in understanding your issue but closing for now, feel free to comment if you need.
