### ISSUE TITLE
How and where we can add the event to make it clickable, editable, and draggable?

### ISSUE THREAD

**Issue by ManojSolanki** [ivmartel/dwv#627]
I have draw a line with given options.

```javascript
var drawLayer = CommonService.instance.dwvApp.getDrawController().getDrawLayer();

var points = [];

points.push(chamber.width_axis["x"][0] + regionMinX);
points.push(chamber.width_axis["y"][0] + regionMinY);
points.push(chamber.width_axis["x"][1] + regionMinX);
points.push(chamber.width_axis["y"][1] + regionMinY);

var tmpShapeGroup = dwv.tool.RulerFactory.prototype.dynamicCreate(
  points, 
  CommonService.instance.dwvApp.style, 
  CommonService.instance.dwvApp.getImage());

drawLayer.add(tmpShapeGroup);

drawLayer.draw();
```

this line is not clickable, editable, and drag able.
After drawing many lines I can not edit any line. Please see screenshot.

Please let me know how and where we can add the event to make it clickable, editable, and draggable?
![image](https://user-images.githubusercontent.com/2775627/51455393-5a980b80-1d6f-11e9-95c5-80db5d573f28.png)

Thanks

**Comment by ivmartel** [comment]
You need to set the appropriate event listeners, not sure how this will work if you do it from outside the app. It is done partly in the `setShapeOn` method in [draw.js#L515](https://github.com/ivmartel/dwv/blob/v0.25.2/src/tools/draw.js#L515) and wherever you see the `shapeEditor` member.

Why are you creating the ruler using your own code? I would recommend creating your own shape tool instead.

**Comment by ivmartel** [comment]
Hi @ManojSolanki, did you manage to do what you wanted?

**Comment by ivmartel** [comment]
Closing for now. Feel free to comment if you need.

**Comment by amravazzi** [comment]
HI! You said in your last answer `I would recommend creating your own shape tool instead`. Would you have any directions on how to do that?
