### ISSUE TITLE
Autostart dicom movie

### ISSUE THREAD

**Issue by cmscopy** [ivmartel/dwv#628]
Hello,

How can you autostart an dicom movie when the file is loaded?

All the best!

**Comment by ivmartel** [comment]
Hi, you would need to add a listener on the data load and call the `play` method on the view controller. In a place where you have access to the app, something like:
```javascript
app.addEventListener("load-end", function() {
  app.getViewController().play();
});
```

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
