### ISSUE TITLE
How to Update older version with slice update?

### ISSUE THREAD

**Issue by Khankakar1** [ivmartel/dwv#629]
link 1: https://jsfiddle.net/ivmartel/8xmruou2/20/
these updates i want to add older version of DVW viewer? any hint?
older version Link2: https://github.com/ivmartel/dwv/tree/400-openjpeg
in other words where should i put the link1 code in link 2 project?

**Comment by ivmartel** [comment]
The [400-openjpeg](https://github.com/ivmartel/dwv/tree/400-openjpeg) branch did not have a lot of changes, I can merge develop in it if you want to use it. Is that what you are asking for?

**Comment by Khankakar1** [comment]
Main issue is when open complete volume of Study from zip folder the viewer does not allow me to view whole study. it gives me the error "cannot append a slice with different number of columns."
now i need to show complete volume of study in viewer, how should i do? thanks in advance

**Comment by ivmartel** [comment]
You maybe have mixed series in your zip files, see [Error-Messages#cannot-append-a-slice](https://github.com/ivmartel/dwv/wiki/Error-Messages#cannot-append-a-slice). The viewer does not allow for this so you need to 'clean' these zip files so that they only contain images of one series.

**Comment by Khankakar1** [comment]
Yes surely i have different series of studies maybe more then 3 in one volume generated by MR- CT machines and in these machines i do not have option of sending single series of study?
is there any solution for this problem?

**Comment by ivmartel** [comment]
I create #646 to add a series browser. Follow the issue to be update on its progress. 

Closing for now, feel free to comment if you need.
