### ISSUE TITLE
show or hide shape after init app

### ISSUE THREAD

**Issue by yogen-darji-hs** [ivmartel/dwv#630]
Hi @ivmartel 

Can I show/hide any specific shape like (arrow or Ruler) based on some condition after init.

**Comment by ivmartel** [comment]
Hi! The app has a `toogleGroupVisibility` (I need to fix the typo) at [application.js#L883](https://github.com/ivmartel/dwv/blob/v0.25.2/src/app/application.js#L883). Is that what you are looking for?

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
