### ISSUE TITLE
Error: Unsupported DICOM transfer syntax: '1.2.840.10008.1.2.5' (RLE)

### ISSUE THREAD

**Issue by ManojSolanki** [ivmartel/dwv#634]
Hi,

I got this error on loading DICOM image. I have also tried on your demo dwv viewer and got the same error. 
Attached error snapshot.

![errordiacom](https://user-images.githubusercontent.com/2775627/53091997-8b6b8c00-3539-11e9-8452-247627eec71f.png)

**Comment by ivmartel** [comment]
RLE (Run-length encoding) ([wikipedia](https://en.wikipedia.org/wiki/Run-length_encoding)) is not implemented... It could be done quite quickly, I was not sure if it was still used...

**Comment by ivmartel** [comment]
I created #636 to handle RLE data.

**Comment by ivmartel** [comment]
Fixed with #636.
