### ISSUE TITLE
Support for Ultrasound Region Calibration

### ISSUE THREAD

**Issue by sjmn** [ivmartel/dwv#641]
It appears that length measurements are not possible using DWV with many/most ultrasound images we are working with.  Instead of a value, '{length}' is displayed.  I suspect this is due to the issue cited 13+ years ago [here](https://groups.google.com/forum/#!msg/comp.protocols.dicom/xVo18Eqm0xk/xuUrflvaDiAJ).  I wonder if others here have interest in [US Region Calibration](http://dicom.nema.org/medical/dicom/2016e/output/chtml/part03/sect_C.8.5.5.html) and updating DWV to support it.  I'm very new to DICOM development and don't have any idea how much work this would involve.  Any advice or comment appreciated.

![Screen Shot 2019-03-12 at 3 32 24 PM](https://user-images.githubusercontent.com/6555421/54236400-71dab600-44e1-11e9-85e2-20e67025196a.png)

**Comment by ivmartel** [comment]
I did not know about this module and it looks interesting! Now I do not know how many US files contain this info, would you have some examples?

**Comment by sjmn** [comment]
Yes, I will create some demo studies and get back to you in the near future.  Thank you.

**Comment by sjmn** [comment]
I've attached 2 Dicom files - a still image and a cine loop each of which have the SequenceOfUltrasoundRegions field populated with an object.  Also attached a screenshot of what I see when I expand that object in OsiriX's metadata viewer.  


[dicom_files.zip](https://github.com/ivmartel/dwv/files/3076788/dicom_files.zip)
![Screen Shot 2019-04-13 at 5 12 51 PM](https://user-images.githubusercontent.com/6555421/56085814-d904c680-5e0f-11e9-9dcd-a1e1d7d7b358.png)

**Comment by ivmartel** [comment]
Wee this [documentation](https://www.radiantviewer.com/dicom-viewer-manual/length.html) of Radiant who supports echo calibration and manual calibration (chapter: 'Calibration of measurements').

**Comment by ivmartel** [comment]
I created #897 for manual calibration.
