### ISSUE TITLE
How should i run this project ? What all are the dependencies

### ISSUE THREAD

**Issue by koushikg14** [ivmartel/dwv#642]

**Comment by ivmartel** [comment]
You need `npm` or `yarn`. Get the code and type `yarn install` to get the dependencies. Then `yarn run start` to start the project, this will launch the tests. The scripts are listed on the landing [page](https://github.com/ivmartel/dwv#available-scripts).

If you want to view images, try one of the viewers: [dwv-jqmobile](https://github.com/ivmartel/dwv-jqmobile), [dwv-angular](https://github.com/ivmartel/dwv-angular), ... ([full list](https://github.com/ivmartel/dwv/wiki/Examples#viewers-and-integrations)).

**Comment by ivmartel** [comment]
I added detailed steps in the main readme.

I hope I answered your question. Closing for now, feel free to comment if you need.
