### ISSUE TITLE
How can we use tools integrated in the library?

### ISSUE THREAD

**Issue by DeenThatcher** [ivmartel/dwv#644]
Through your examples, I know how to initalize the App to use with some simple tools like **WindowLevel**, **ZoomAndPan**, **Scroll**. But what happen if I want to use **Draw** tool (like **Roi**) and set label for it like your example at (https://jsfiddle.net/ivmartel/Lu7udbvg/).
I've read in the **dist** folder that contains the **dwv.js** file and I tried below like other examples of yours:
`app.init({`
        `"containerDivId": "dwv",`
        `"tools": ["Draw"],`
        `"shapes": ["Roi"],`
    `});`
However, it definitely missed lots of things need to be initialized to use with.
Sorry I'm new to use JS library and I know you are very busy. But it would be nice if you guide me a little bit with that question or create a small example in JSFiddle. Thanks in advance!!

**Comment by ivmartel** [comment]
Sorry for taking so long to answer... Using the draw tool is not as simple as I wished... Here is a fiddle I am working on: [display example 2.1](https://jsfiddle.net/ivmartel/fugw49be/). It just tried with the arrow shape, some other ones were giving me an error with the translation dependency (i18next).

**Comment by DeenThatcher** [comment]
I really appreciate your answer, the fiddle seems to work very good with **Arrow** and **Roi** shape.
But when I take the code from the fiddle to my HTML file (with JavaScript inside) and run on **Chrome** (version **73.0.3683.103** on **Windows**), the console said that:
**Uncaught TypeError: Konva.Group dwv.js:20748 is not a constructor at new dwv.tool.Draw (dwv.js:20748)**
`var trash = new Konva.Group();`
**at dwv.App.init (dwv.js:272)**
`toolList.Draw = new dwv.tool.Draw(this, shapeList);`
**at (index):94** (This one is just the index in my code)
`app.init({`

**Comment by ivmartel** [comment]
You're missing the Konva dependency, it's a library that handles drawing. Check the resources in the fiddle, it has a link to [konva.min.js](https://cdn.rawgit.com/konvajs/konva/2.4.0/konva.min.js).

**Comment by DeenThatcher** [comment]
It works now, thanks for your guidance.
In near future, hope to see more fiddles with draw tool.
Have a nice day, sir.

**Comment by ivmartel** [comment]
You're welcome. If you consider this issue fixed, could you please close it, thanks.
