### ISSUE TITLE
how to display 3d model via dicom files

### ISSUE THREAD

**Issue by MichleLI** [ivmartel/dwv#645]
Thank you for this project and contributers!
I want to display 3d model from several dicom files.

**Comment by ivmartel** [comment]
dwv does not handle 3d views as, for example, those made with [threejs.org](https://threejs.org/). Regarding recreating a 3d volume from the DICOM slices, the plan is to start with MPR, see #4.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
