### ISSUE TITLE
Do not throw error if slices have different orientation

### ISSUE THREAD

**Issue by erilin** [ivmartel/dwv#648]
When loading slices with small differences (0.0001) error is thrown:
"Cannot append a slice with different orientation"

Is this really necessary?

**Comment by ivmartel** [comment]
The code uses strict equality, it's true that a tolerance could be added for float number comparison.

**Comment by erilin** [comment]
> The code uses strict equality, it's true that a tolerance could be added for float number comparison.

If I get som time maybe I create a pr

**Comment by arturojain** [comment]
Had to make the tolerance as high as 0.6, why can this be?

**Comment by ivmartel** [comment]
Not sure... Could you share the data that needs such a high tolerance?
