### ISSUE TITLE
Question about custom component

### ISSUE THREAD

**Issue by phungleson** [ivmartel/dwv#661]
Hi,

This is not an issue, but I couldn't think of a place to ask question, will close it if it is not appropriate.

I want to build a custom slider for changing the brightness (or hdr) of a dicom image?

Currently it seem to be working when I scroll inside the view, wonder if I can access that functionality and build my own component?

Thanks in advance!

**Comment by ivmartel** [comment]
You should be able to add external controls for the window/level. You will need one for each. You can control the window/level via the ViewController provided by `app.GetViewController`, it provides a `setWindowLevel` method. To display them on a slider, you will need to calculate their min/max, I'm not too sure what the formula is...

**Comment by phungleson** [comment]
Thanks a lot @ivmartel , I will check out `ViewController`, btw somewhat related, how do you display the historgram of the image? In some examples I saw you have it enable but couldn't figure out how, it can be helpful to build the component.

**Comment by phungleson** [comment]
I figured out, thanks
