### ISSUE TITLE
Encryption Types

### ISSUE THREAD

**Issue by rhankey72** [ivmartel/dwv#662]
Hello, what kind of URL encryption does this browser support?  Does it support any of the following?

AES 128 Encryption
Outside Firewall Access
Context Sending: OAUF2; SAML
Specifying patient and order information in retrieval

Also, can this product be used for corporate use?

**Comment by ivmartel** [comment]
Hi, the features you are asking for are outside the scope of dwv and more part of an implementation of a DICOM portal. For dwv, the data is expected to be decrypted and accessible, firewall or not. Regarding authentication, the [dwv-jqmobile](https://github.com/ivmartel/dwv-jqmobile) demo provides integration with the Google API OAuth2. All patient data is contained in the DICOM file.

Regarding licenses, the library is under GPL and I can license it under an MIT (or equivalent) one.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now. Feel free to comment if you need.
