### ISSUE TITLE
Colour Dicom Displayed Incorrectly

### ISSUE THREAD

**Issue by diannamcallister** [ivmartel/dwv#663]
This is what the Dicom is being displayed as:

![image](https://user-images.githubusercontent.com/43302576/59786262-d9e52900-9294-11e9-8b5e-ec0ce256ea3c.png)

But this is the true Dicom:

![image](https://user-images.githubusercontent.com/43302576/59786327-fd0fd880-9294-11e9-9327-8bb7a909ba57.png)

Here is a link to the source file: 
https://github.com/g-squared/cornerstoneWADOImageLoader/raw/master/test/US-PAL-8-10x-echo.dcm

Do you have any ideas on how to fix this issue?

@danielsnider

**Comment by ivmartel** [comment]
The library does not support the `PALETTE COLOR` photometric interpretation, I created #664 to fix this.

**Comment by danielsnider** [comment]
Thank you!! We'll look into it if we find the time. Likely not for a while
:(. Many thanks for your reply.
Daniel Snider ツ

**Comment by ivmartel** [comment]
Should be fixed with #664.
