### ISSUE TITLE
Incorrect Date and Time Parsing or Replacement

### ISSUE THREAD

**Issue by diannamcallister** [ivmartel/dwv#665]
Below is a picture of what is being displayed in the web dicom viewer vs. what is found when performing dcmdump. It sometimes performs incorrect parsing to modify the date or time, or it will replace the date with Invalid Date. Do you have any ideas on how to fix this issue?

![image](https://user-images.githubusercontent.com/43302576/59878117-7bdc4280-9375-11e9-98bd-447c273d7d5f.png)

@danielsnider
**Thank you!**

**Comment by ivmartel** [comment]
This date format is invalid, see: 
> The ACR-NEMA Standard 300 (predecessor to DICOM) supported a string of characters of the format YYYY.MM.DD for this VR. Use of this format is not compliant.

(ref: DA in [sect_6.2](http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html#table_6.2-1))

It would not be difficult to support, I could add a check for this format, interpret it and output a warning.

**Comment by danielsnider** [comment]
@ivmartel thanks for the info! We have a lot of different invalid dates and we still want to display them, can you point us in the right direction to disable date interpretation? For "DA", "TM", and "DT" types, we always want to display the original value. What is your use case for parsing dates? I don't see the need for us. I LOVE DWV by the way ❤.

**Comment by ivmartel** [comment]
The raw data comes as: 
> A string of characters of the format YYYYMMDD.

Thanks!

**Comment by danielsnider** [comment]
Ok. But how can we make a date like 1994.06.13 display as "1994.06.13"? Thanks!

**Comment by ivmartel** [comment]
If it does not respect to standard, we can save it as is. But I think I would prefer parsing it so that all dates display the same way. The code is there: [dicomElementsWrapper.js#L160](https://github.com/ivmartel/dwv/blob/v0.26.0/src/dicom/dicomElementsWrapper.js#L160).

**Comment by danielsnider** [comment]
@ivmartel amazing! Thanks
@diannamcallister, please give it a try.

**Comment by danielsnider** [comment]
Here's the fix that I used! Closes issue for me.
```diff
3  image-archive/dwv/dwv/src/dicom/dicomElementsWrapper.js 
@@ -129,12 +129,13 @@ dwv.dicom.DicomElementsWrapper.prototype.getElementValueAsString = function ( dicomElement, pretty )
{
    var str = "";
    var strLenLimit = 65;

    // dafault to pretty output
    if ( typeof pretty === "undefined" ) {
        pretty = true;
    }
+    pretty = false; // ALWAYS FALSE
    // check dicom element input
    if ( typeof dicomElement === "undefined" || dicomElement === null ) {
        return str;
    }
```

Unrelated to this issue. I also solved some of my other issues:
https://github.com/aim-sk/aim-platform/commit/33da419f74790c63aa11d744f49e52226e6e6e10
> - View up to 65000 character values
> - View mult-iline values
> - Size columns more appropriately
> - Don't try to parse values to make them "pretty"
> - Change assumed "UN" to "LT"
I thought you might be interested. I like these improvements.

**Comment by ivmartel** [comment]
I hope the commit fixes your problem, it parses both date formats to display them the same way.

About the other fixes, could you create a pull request?

**Comment by danielsnider** [comment]
I will try to make a pull request. It may take months for me to find the time. But I promise I will tryp
