### ISSUE TITLE
Displaying Dicom File from Parsed Image in browser

### ISSUE THREAD

**Issue by SHARANTANGEDA** [ivmartel/dwv#666]
I have parsed the array buffer to image using 'ImageFactory.create' as suggested in API.
But Iam facing a problem in loading that image onto canvas?
Any help would be appreciated...
This is the code I used to parse the file received from server.
```javascript
let dicomParser = new dwv.dicom.DicomParser();
dicomParser.parse(this.props.file.data);
let pixelBuffer = dicomParser.getRawDicomElements().x7FE00010.value;
let imageFactory = new dwv.image.ImageFactory();
let image = imageFactory.create( dicomParser.getDicomElements(),pixelBuffer );
let view = new dwv.image.View(image)
console.log({'Image Geo':image.getGeometry().getSize().getNumberOfColumns()})
console.log({ImageView: view.getImage()})
console.log({Image: image.getNumberOfFrames()})
```

**Comment by ivmartel** [comment]
As for the image, best to use the `dwv.image.ViewFactory` to create a view (as done there [dicomBufferToView.js#L60](https://github.com/ivmartel/dwv/blob/v0.26.0/src/image/dicomBufferToView.js#L60)).

**Comment by ivmartel** [comment]
I hope I answered you question. Did you make any progress?

**Comment by SHARANTANGEDA** [comment]
Yes I was able to crack it, thanks for the reply
