### ISSUE TITLE
How to customize drawing

### ISSUE THREAD

**Issue by mywsat** [ivmartel/dwv#668]
For example, ROI is drawn using the mouse-click event. If I want to use the mouse-move event and end the drawing at mouse-up, how do I implement it?

**Comment by mywsat** [comment]
For example, ROI is drawn using the mouse-click event. If I want to use the mouse-move event and end the drawing at mouse-up, how do I implement it?

**Comment by ivmartel** [comment]
You would need to change the mouse/touch events handler of the draw tool ([tools/draw.js](https://github.com/ivmartel/dwv/blob/v0.26.0/src/tools/draw.js)). 

A drawing is finished when all the points needed for a shape are drawn. This is defined in the `getNPoints` method of the shape factory, see for example [arrow.js#L18](https://github.com/ivmartel/dwv/blob/v0.26.0/src/tools/arrow.js#L18).

**Comment by ivmartel** [comment]
I hope I answered your question. Did you make any progress?

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
