### ISSUE TITLE
Duplicate an existing viewer

### ISSUE THREAD

**Issue by alexqbm** [ivmartel/dwv#671]
Hi.
I am currently instantiating a viewer using **new dwv.App()**. After that, I load an array of DICOM url's using the **loadUrls()** method. It takes a bit for all the DICOMs to load, but after the loading process everything is fine.
The reason why I open this issue is because I would like to know how could I duplicate an existing viewer. In the application that I am currently developing using DWV I have an already existing viewer with the DICOMs loaded in it, and at any time the user must be able to click a button to duplicate the existing viewer. However, I am not being able to implement this. I know that a viable solution would be to load the same DICOMs that are loaded in the original viewer in the new one, but the thing is that I must avoid reloading all the data a second time (due to time and efficiency reasons). 
My goal is to replicate the first viewer in a second one with all the information of the first already loaded in the copy. How would you suggest me to do it? 
Thanks in advance, ivmartel.

**Comment by alexqbm** [comment]
Missclicked and closed it. Sorry.

**Comment by alexqbm** [comment]
I was wondering if it's possible to initialize a viewer without loading any DICOMs, using instead an array buffer extracted from another viewer as the input. This is quite related to the **duplicate an existing viewer** issue, as you can imagine.

**Comment by ivmartel** [comment]
Initializing the viewer with an external buffer is not possible for now. May I ask why you want to duplicate the viewer?

**Comment by alexqbm** [comment]
I wanted to duplicate the viewer to allow the user to have two viewers and apply different tools to each of them (increase contrast in one while zooming in and increasing the brightness in the other, for example). Is part of my application.

Now that I know that this is not possible I would like to know if there is any way of creating a new viewer without a DICOM file. I would manipulate the canvas directly while taking advantage of the viewer tools. Do you know if this is possible?
