### ISSUE TITLE
Dicom viewer doesnt load certain dcm files and giving error "TypeError: Cannot read property 'value' of undefined"

### ISSUE THREAD

**Issue by umarscorpio** [ivmartel/dwv#673]
Hi, I have .dcm files and most of the files work but when I open some files it gives me error "TypeError: Cannot read property 'value' of undefined" .. I dont know why... can you please help me out in this.....

**Comment by ivmartel** [comment]
Could you share the file to give it a closer look?

**Comment by umarscorpio** [comment]
this is the file.please have a look...

**Comment by umarscorpio** [comment]
I have attached the file. have a look please
[IM2.zip](https://github.com/ivmartel/dwv/files/3472329/IM2.zip)

**Comment by ivmartel** [comment]
The data is missing image data information such as the number of rows (`x00280010`) and the number of columns (`x00280011`). Not sure why, but this is related with #695.

**Comment by ivmartel** [comment]
Closing for now, I need more details on how to load `RawDataStorage`...
