### ISSUE TITLE
How to the the current image or slice

### ISSUE THREAD

**Issue by timoangerer** [ivmartel/dwv#674]
How can I get the current slice that is being displayed? I want to store the current slice number of an MRI scan in react state but can't find a way to get the info out of the dwv app instance.

I've found the method getDrawDisplayDetails(), but it doesn't return anything when I call it.

**Comment by ivmartel** [comment]
You can listen for the `position-change` event, it returns the current position as `{...,i,j,k}`. Check out the [event list](https://github.com/ivmartel/dwv/wiki/API#events) on the wiki.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
