### ISSUE TITLE
Need new drawing type: fiducials (points)

### ISSUE THREAD

**Issue by TanmaySM** [ivmartel/dwv#675]
Need new drawing type: fiducials (points).

Currently no brush/pencil type tool is available in viewer.

**Comment by ivmartel** [comment]
Could you elaborate on what would be the use of these fiducials?

**Comment by ivmartel** [comment]
Example use case would be cool. Closing for now. Reopen / comment if you need.

**Comment by ncovgt2020** [comment]
Hi,

Thanks for sharing your project. I am reopening this issue for the brush/eraser functionality. Some examples of this functionality are [here](https://medium.com/labelbox/introducing-best-in-class-image-annotation-tools-for-computer-vision-applications-de5da8931d6e) (brush) and [here](https://www.youtube.com/watch?v=BrtueCikLA4). Those examples have other, more complex functions (auto segmentation, etc) but it would be cool to first have the basic brush/erase functionality. 

I was wondering if this could be included in the project. I have no experience with javascript nor web development and in deed are struggling to grasp the code base of this project. That being said, I will appreciate you could provide me some indications on how such functionality could be implemented and I would give it a try as time allows. For my use case, the final goal would be to have an "segmentation mode" in which by choosing a "label" and "color" one draws different sections of the image and internally retrieve the generated masks. This could then be used for generating datasets for learning algorithms.

Thanks
