### ISSUE TITLE
ask for installation

### ISSUE THREAD

**Issue by cristsaavedra** [ivmartel/dwv#677]
greetings everyone, 

I have the following question, I was reading about this library and I find it very good and I would like to implement it. I have downloaded the fonts from github but I got lost with the step by step installation. To be honest, I don't know if this can be installed in theory for a MVC project with visual studio 2017. If that were the case, someone knows how to do a clean installation so they can work on it.
The latter, with respect to the storage of DICOM files, can these be in a data repository or do they necessarily have to be in a database? If the answer is the second option, this database can be in sql server 2008 ?

I appreciate your help in advance and stay tuned for your comments

**Comment by ivmartel** [comment]
There should not be any problems using dwv in a MVC project, just include the minified release and refer to it in your html pages.
Dwv does not depend on a data base, it can take the raw file as input. So it should be fine with your sql server.

**Comment by ivmartel** [comment]
I hope I answered your question. Did you make any progress?

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
