### ISSUE TITLE
Is there a api document for all features?

### ISSUE THREAD

**Issue by gxf-style** [ivmartel/dwv#680]
Is there a api document for all features?Some features don't know how to use。for example：how to change file/folder/url?

**Comment by sanbangarh309** [comment]
please reply me too need this ???

**Comment by sanbangarh309** [comment]
hi @gxf-style  do you know that how to get all files from zip in load-progress or load-end event ???

**Comment by ivmartel** [comment]
The automated built documentation for the latest stable version (0.26 as of today) is available [here]( http://ivmartel.github.io/dwv/demo/stable/doc/index.html).

Could you please create another issue for your question?

**Comment by amravazzi** [comment]
It would be great if you provide more examples of more complex features.

**Comment by dattran2346** [comment]
Agree, need documents and example for more advance use rather than just show image and tool.

**Comment by ivmartel** [comment]
No problem in creating more fiddles! If you have any ideas for interesting scenarios, please suggest!

**Comment by ivmartel** [comment]
In b6ed9ab, I switched from using the [docstrap](https://github.com/docstrap/docstrap) JSDoc template to using [docdash](https://github.com/clenemt/docdash) which seems more navigable. I set it to only show public methods.
