### ISSUE TITLE
Retrieve all files from zip folder

### ISSUE THREAD

**Issue by sanbangarh309** [ivmartel/dwv#681]
hi ,
 I have zip file of 22 dcm files(single patient) and i want listing of all files on load-end or load-progress event. Anyone can tell me that is there any function to retrieve all files after load end or load-progress.
Regards
Sandeep Bangarh.

**Comment by sanbangarh309** [comment]
please anyone help me out from this.

**Comment by ivmartel** [comment]
There is nothing in the current code to retrieve the names of the unzipped files. This would need to go into the [zipLoader](https://github.com/ivmartel/dwv/blob/v0.26.0/src/io/zipLoader.js), not too sure how...

**Comment by sanbangarh309** [comment]
@ivmartel  thanx for reply.

> this.dwvApp = new dwv.App();
> this.dwvApp.loadURLs([anyziplink]);
then => 
this.dwvApp is contains any function by which we can get files or buffer of files ??

**Comment by ivmartel** [comment]
No there is not. In theory you are passing the files so you should have access to their content. Or are you in a context where you cannot?

**Comment by sanbangarh309** [comment]
yes, this zip link is coming from third party.

**Comment by ivmartel** [comment]
There is nothing in the code to do that at this time. File names are known only once JSZip has them loaded (in (src/io/zipLoader.js#L106)[https://github.com/ivmartel/dwv/blob/v0.26.0/src/io/zipLoader.js#L106]). The loader could send an event with the file names. Or you could unzip in your app with JSZip just to get the file names.

**Comment by ivmartel** [comment]
Please follow #701, it should allow for unzip data identification. Closing for now.
