### ISSUE TITLE
Load whole series and also view individual images separately

### ISSUE THREAD

**Issue by Mamta92** [ivmartel/dwv#684]
@ivmartel 

I've a use case where I'm supposed to load the whole series in the DICOM viewer. I was able to load all images (ranges anywhere between 150-1000) signed urls using the loadURLs() which accepts an array of urls. And immediately if I call the playSlices(), I can view all the images like a movie. Works great till here!

But after having loaded the whole series, I've also shown a list of images present under it to allow the user to view individual images as well along with playslices() feature. If I click on any one the images, i again call that loadURLs() with a single url. Now my whole images(urls) within series has been lost because I've overridden it with the simgle image url.

Now if I again use the playSlices() feature, it won't work because now it has only one image url loaded.
I don't want to again load all the images(because our images anywhere between 15-1000) on playSlices() method because they are signed urls which takes a lot of time to load.(Have currently implemented this one and it gives slight performance degradation because again all the images are loaded)

Is there any alternative where I can use both the (viewing the single image and play slices feature) without impacting the performance.?

Thanks.! Your help will be appreciated.
I've loved this dicom viewer so far. It works great!!

**Comment by sanbangarh309** [comment]
hi @Mamta92 ,
  Are you able to load whole series of dicom images included in zip or folder ?
  i.e series-000000 , series-000001 , series-000002 etc.. thses are folders of series includes dicom images and these series is zipped in single zip file. Are you able to load these type of file via loadurls or loadfiles function ? . It would be geat help fort me.
Thanx && Reagrds
Sandeep Bangarh

**Comment by ivmartel** [comment]
@Mamta92, by `playSlices()` you mean the `viewController.play()` method?
So, you have a main viewer and some snapshots bellow and you would like to link both, ie click on one snapshot and show it in the main viewer, is that it? It looks like what is done in the draw list (in [src/gui/generic.js#L311](https://github.com/ivmartel/dwv/blob/v0.26.0/src/gui/generic.js#L311)). What it does is that it sets the current position of the view controller by calling `app.getViewController().setCurrentPosition(pos)`. Would that fix your problem?

**Comment by ivmartel** [comment]
Waiting for feedback from @Mamta92... Closing for now, feel free to comment if you need.
