### ISSUE TITLE
Active Image Data Access.

### ISSUE THREAD

**Issue by rawl05** [ivmartel/dwv#686]
I'm not able to access the data related to the image(Slice) which is active (displayed on the viewer) within the series loaded. The data is SOPInstanceUID or InstanceNumber of the image, is there any way possible for this or any inbuilt function. Tried the getMeta() function but not able to get required data.

**Comment by ivmartel** [comment]
You are right the `SOPInstanceUID` and `InstanceNumber` are not available from the image meta. I¡m working on making the full header available after load, stay tuned for the next release!

**Comment by ivmartel** [comment]
Not sure if this is related to #683, but it got fixed.
The full image(s) meta to also now available once the data is loaded via the `app.getMeta`.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
