### ISSUE TITLE
Vue demo how to change the yellow ruler to green

### ISSUE THREAD

**Issue by yxwya** [ivmartel/dwv#687]

**Comment by ivmartel** [comment]
Original title: vue的demo怎么把黄色标尺改为绿色

**Comment by ivmartel** [comment]
The demos do not propose the shape colour change for now. I'm finishing some re-architecture and then this will be easier. Stay tuned...

**Comment by ivmartel** [comment]
Please refer to [dwv-vue/issues/69](https://github.com/ivmartel/dwv-vue/issues/69) for additional comments.
