### ISSUE TITLE
Can vue demo achieve the same functionality as jquerymobuile? Modify the color of the image

### ISSUE THREAD

**Issue by gf1371876** [ivmartel/dwv#688]
# @

**Comment by gf1371876** [comment]
dwv.tool.colourMaps = {
    "plain": dwv.image.lut.plain,
    "invplain": dwv.image.lut.invPlain,
    "rainbow": dwv.image.lut.rainbow,
    "hot": dwv.image.lut.hot,
    "hotiron": dwv.image.lut.hot_iron,
    "pet": dwv.image.lut.pet,
    "hotmetalblue": dwv.image.lut.hot_metal_blue,
    "pet20step": dwv.image.lut.pet_20step
};

**Comment by gf1371876** [comment]
vue demo可以实现跟jquerymobuile一样的功能吗？
修改影像的颜色

**Comment by gf1371876** [comment]
Error: Unknown tool: 'WindowLevel'
    at H.tool.Toolbox.setSelectedTool (dwv.min.js?0151:3)
    at ToolboxController.setSelectedTool (dwv.min.js?0151:3)
    at App.onChangeTool (dwv.min.js?0151:3)
    at VueComponent.onChangeTool (Main.vue?48a8:176)

**Comment by ivmartel** [comment]
Related to #687, same answer: The demos do not propose the shape colour change for now. I'm finishing some re-architecture and then this will be easier. Stay tuned...

**Comment by ivmartel** [comment]
Please refer to (dwv-vue/issues/70)[https://github.com/ivmartel/dwv-vue/issues/70] for the colour map chooser.
