### ISSUE TITLE
i'm use in cordova app, may i load file from local folder ?

### ISSUE THREAD

**Issue by auron105** [ivmartel/dwv#691]
i will  get jpg base64 data  and save jpeg file to local folder : 
1. get jpg file from local folder 
2. base64 convert to blob or can just use base64?

what solution can view?

thx~! sorry bad english

**Comment by ivmartel** [comment]
Loading from local files is only possible via a user file load via the app. If you have the url of the jpg file, you could load it directly.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
