### ISSUE TITLE
 How to preload data in the back end？I want to cache data in redis after preprocessing，This will speed up the presentation

### ISSUE THREAD

**Issue by wangpopo** [ivmartel/dwv#692]
![微信图片_20191223195952](https://user-images.githubusercontent.com/13417983/71356958-cd80b680-25be-11ea-9247-795f582fd172.png)
I wonder if I can generate data in the back end and return it to the front end for display.Or is there any other way of preloading to improve the presentation speed?

**Comment by ivmartel** [comment]
I'm not sure you would improve significantly the load speed by caching the data in the back end. What happens before your snapshot is the dicom parsing which in non compressed data case does not take long. It takes longer for compressed data but it is faster to transfer... 
For now I more looking into an on demand load / decompress.

**Comment by ivmartel** [comment]
Check out #342 for on demand load.

Closing for now, feel free to comment if you need.
