### ISSUE TITLE
Download the file after working with it

### ISSUE THREAD

**Issue by nphattai** [ivmartel/dwv#694]
I am doing graduate thesis on web for viewing dicom file and using dwv library. I have some questions:
1. After working with dicom file as change window level, apply the filter, ... how to download edited file ?
2. How to get the current drawing as an jpeg image. I need this image for calculating shape factors of the region by drawn and diagnostic the cancer. 
Thanks so much for helping.

**Comment by ivmartel** [comment]
1. the app can save a state that records the image view manipulations but not the result of applying a filter
2. the state also saves the definition of the shapes (in its own coordinates, you will need conversion there)

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.

**Comment by KunalBurangi** [comment]
How to use those states to convert it to dcm again

**Comment by ivmartel** [comment]
@KunalBurangi this is not supported. Relates to saving RT Struct (#306) and also saving Presentation State.
