### ISSUE TITLE
Calling `loadUrls` sends all requests simultaneously

### ISSUE THREAD

**Issue by amcgowan-blaccspot** [ivmartel/dwv#698]
When I call `App.loadUrls` each url is requested simultaneously. The viewer will not display any of the images until all requests have completed. 

Is there an option to get loadUrls to load in a smaller batch size and start displaying images as the request completes?

**Comment by amcgowan-blaccspot** [comment]
Realized I had some server issues that caused the majority of the performance issue. And see that the viewer is functional even during load.

**Comment by jjreicher** [comment]
Sorry to comment on the closed issue but @amcgowan-blaccspot any comment on the viewer functionality during load? We have loadurls running as well for a stack of 450 slices. The viewer won't scroll until the entire stack is loaded. Any input appreciated!

**Comment by ivmartel** [comment]
@jjreicher I guess your problem was solved in #984?

**Comment by jjreicher** [comment]
Goodness! Forgot to respond here! Yes see reference above for solution.
