### ISSUE TITLE
How to upload multiple files from local disk to viewer alternate to drag and drop?

### ISSUE THREAD

**Issue by Nagaraj8088** [ivmartel/dwv#699]
The drag and drop become difficult for mobile view, Is it possible to upload files manually and view all files on the web?
Eg: click choose file button and select files to view.

**Comment by ivmartel** [comment]
The [dwv-jqmobile](https://github.com/ivmartel/dwv-jqmobile) and [dwv-jqui](https://github.com/ivmartel/dwv-jqui) provide a load button which can load local files. Or if you have the url, you can pass it to them.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
