### ISSUE TITLE
Refactor data load events and handlers

### ISSUE THREAD

**Issue by ivmartel** [ivmartel/dwv#701]
Data load events and handler methods must be refactored to follow similar APIs such as the one of the [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) or the [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest).
* ´load´ must be fired when the load is successful
* ´load-end´ must be fired when the load finishes whether successfully (after load) or unsuccessfully (after abort or error)
* all handlers must take an event as parameter
* events must be augmented to provide context info

(events type will stay the same, externally, to maintain compatibility)

**Comment by ivmartel** [comment]
_(copied from #709)_

The idea of #701 refactoring is:
- `load-start` is sent at the beginning of a load
- `load-end` is (always) sent at the end of a load, for successful and non successful loads
- `load-progress` is sent to report progress at different intermediate load steps, it should send a 100% but this is not guaranteed
- `load-item` is sent when a load item is successful
- `load` is sent when the full load is successful
- `error` is sent when an error is received
- `abort` is sent when the load is aborted

A load is when you launch a load process, whatever the number of files/urls you try to load.

For an example case of loading 10 links with no errors, you will receive:
- one `load-start`
- multiple `load-progress`
- 10 `load-item`
- no `error`
- one `load`
- one `load-end`

For an example case of loading 10 links with 2 erroneous, you will receive:
- one `load-start`
- multiple `load-progress`
- 8 `load-item`
- 2 `error`
- no `load`
- one `load-end`

I hope this makes it clearer. I am open to questions and suggestions!

**Comment by Mamta92** [comment]
Is this available in latest release of v0.27.0?

**Comment by ivmartel** [comment]
Yes!
