### ISSUE TITLE
load-event listener should be called if load-error/load-abort is called.

### ISSUE THREAD

**Issue by Mamta92** [ivmartel/dwv#702]
@ivmartel 

I have 100 images out which 40 images are failing. I have listened to load-error method on the client side which listens to these 40 errors and shows the customized popup for each image that is failing. So basically in this case the popup appears 40 times.

I would like to handle all the 40 errors in a single go. As in I need an indication that n number of images have failed after final processing so that I can show in a single popup 40 images have  failed instead of 40  popups.

I saw in #701´load-end´ must be fired when the load finishes whether successfully (after load) or unsuccessfully (after abort or error). Is this done?

**Comment by ivmartel** [comment]
#701 is nearly done, I'm planning on merging before the end of the week. The dev branch is [701-load-api](https://github.com/ivmartel/dwv/tree/701-load-api).

**Comment by Mamta92** [comment]
@ivmartel ,

Is there some error codes assigned to each of the error messages?
for example 'Cannot append a slice with different number of rows',Cannot append a slice with different photometric interpretation etc etc?

I want to handle error messages based on error codes!

**Comment by ivmartel** [comment]
For now, the `load-error` event contains the error which in turns contains a message and the stack trace.
I was not planning on having numeric codes, is that what you are referring to? Wouldn't the message be enough?

**Comment by ivmartel** [comment]
I merged #703 yesterday, I hope it helped!

**Comment by ivmartel** [comment]
Closing for now. Please comment on #701 or here if you need.

**Comment by Mamta92** [comment]
@ivmartel ,
For the error codes, we want the error messages to be shown more gracefully. So 'Cannot append a slice with different  photometric value' or something like that...If we have proper error codes being sent along with the error messages..It would be of great use.
