### ISSUE TITLE
Develop branch code is not working

### ISSUE THREAD

**Issue by Mamta92** [ivmartel/dwv#708]
I tried copying and pasting dwv.js into my project from build/dist folder of develop branch. It is not working.I built the code using grunt build.Can you please check? I'm using Angular 8.

**Comment by ivmartel** [comment]
v0.27 changes the API quite significantly. Checkout changes on the [120-dwv-0-27](https://github.com/ivmartel/dwv-angular/tree/120-dwv-0-27) branch of dwv-angular for an idea of what to update.

**Comment by Mamta92** [comment]
I wanted code of https://github.com/ivmartel/dwv/pull/703. Will this be available in  [ 120-dwv-0-27](https://github.com/ivmartel/dwv-angular/tree/120-dwv-0-27) ?

**Comment by ivmartel** [comment]
It is available in `120-dwv-0-27` with a build of the latest dwv code.

**Comment by Mamta92** [comment]
I'm not able to find https://github.com/ivmartel/dwv/issues/701 in 120-dwv-0-27.. The package.json still contains 0.26 version for dwv. Where can i see the build files?

**Comment by ivmartel** [comment]
As you mention, the way to use dwv with changes of #701 (and any non published dwv) is to build it and then add it manually to your angular project dependencies. But as with any intermediate version, I cannot guaranty that it will work. The safest is to wait for a release, I should not be too long...

In the case you can't wait, what error is it giving?

**Comment by Mamta92** [comment]
The thing I want to know is how many images failed to load out of n images? That is why I was looking out for load-abort and load-end events which could have helped me in displaying such message.

**Comment by Mamta92** [comment]
I was able to listen to load-error event and was able to fetch all of the failed images responses individually. But I want to know the total number of images that failed

**Comment by ivmartel** [comment]
Counting the number of times that you receive `load-error` is not enough?

**Comment by Mamta92** [comment]
But how do I know when all of the error messages have been recieved.I need to show it in the ui that out of X, y images failed to load.

**Comment by Mamta92** [comment]
Do you mean to say If for a series out of 10 images, 2 images fail..Then I'll receive load-end for 10 images and load-error for 2 images?

**Comment by ivmartel** [comment]
You will receive one `load-end` and 2 `load-error`. `load-end` is sent at the end of the load, successful or not. I answered in more details in #709.

**Comment by ivmartel** [comment]
Sorry, the event to listen to for errors is not `load-error` but `error`.
I just commit code to the branch of dwv-angular that counts the error as I suggest, I hope it helps.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
