### ISSUE TITLE
Event descriptions needed

### ISSUE THREAD

**Issue by Mamta92** [ivmartel/dwv#709]
Can you tell me the purpose of the following events:-
load-start
load-progress
load-item
load-error
load-end
load-abort

**Comment by Mamta92** [comment]
@ivmartel ,

load-progress will always reach 100% right irrespective of the load-error/load-abort events?

**Comment by ivmartel** [comment]
The idea of #701 refactoring is:
- `load-start` is sent at the beginning of a load
- `load-end` is (always) sent at the end of a load, for successful and non successful loads
- `load-progress` is sent to report progress at different intermediate load steps, it should send a 100% but this is not guaranteed
- `load-item` is sent when a load item is successful
- `load` is sent when the full load is successful
- `load-error` is sent when an error is received
- `load-abort` is sent when the load is aborted

A load is when you launch a load process, whatever the number of files/urls you try to load.

For an example case of loading 10 links with no errors, you will receive:
- one `load-start`
- multiple `load-progress`
- 10 `load-item`
- no `load-error`
- one `load`
- one `load-end`

For an example case of loading 10 links with 2 erroneous, you will receive:
- one `load-start`
- multiple `load-progress`
- 8 `load-item`
- 2 `load-error`
- no `load`
- one `load-end`

I hope this makes it clearer. I am open to questions and suggestions!

**Comment by ivmartel** [comment]
I just updated my previous comment, the error event type is `error`, not `load-error`. Same for `abort`.

**Comment by ivmartel** [comment]
Also check out the new urlsLoader test: [urlsLoader.test.js](https://github.com/ivmartel/dwv/blob/develop/tests/io/urlsLoader.test.js) for an in depth view of the load events.

Closing for now, feel free to comment if you need.
