### ISSUE TITLE
Issue loading some JPX encoded dcm files.

### ISSUE THREAD

**Issue by rawl05** [ivmartel/dwv#718]
I'm facing issue when I try to load a particular series in the viewer and it gives me a error.

Error: JPX Error: Unsupported COD options (selectiveArithmeticCodingBypass); in the console.

The DICOM images are not visible in the viewer.

Screenshot attached:
![Screenshot (31)](https://user-images.githubusercontent.com/37844947/77924809-ca821a00-72c1-11ea-90dc-668b6ccd88a6.png)

**Comment by ivmartel** [comment]
Relates to #349.

**Comment by ivmartel** [comment]
If you could share the failing data, that would help a lot!

**Comment by ivmartel** [comment]
Closing for now. Check #400 for news if related. Feel free to comment if you need.
