### ISSUE TITLE
Too many file request causing an issue

### ISSUE THREAD

**Issue by Mamta92** [ivmartel/dwv#720]
I have a series having around 1500 images, that needs to load. I'm using loadURLs() method and passing the api link to get the images and this sends 1500 request in the network tab to the api.
There is some issue with this as for few images i get 'zone-evergreen.js.pre-build-optimizer.js:2952 GET https://a/b/xxxxx.xxxx.xxxx.xxx.xxxx.dcm net::ERR_INSUFFICIENT_RESOURCES'.

Can we load this in batches in the viewer? As In first giving 500, 500...after regular intervals or something?

**Comment by Mamta92** [comment]
@ivmartel  any update?

**Comment by ivmartel** [comment]
I would prefer to implement a standard pattern if one exists for this case, I had a quick look but did not find anything. If you have any suggestions, I would be happy to ear them!

**Comment by ivmartel** [comment]
Relates to #722 and #697.

**Comment by ivmartel** [comment]
Relates to #730.

**Comment by ivmartel** [comment]
Check out branch [730-load-url-queue](https://github.com/ivmartel/dwv/tree/730-load-url-queue) for a tentative implementation.

**Comment by ivmartel** [comment]
#780 has been merged, that should fix this issue. Closing for now, feel free to comment if you need.

**Comment by jjreicher** [comment]
Running into the same error described, just ~150 images or so (only successfully loads ~10). Compiled 0.28.0 but didn't seem to make a difference. Would appreciate any thoughts on troubleshooting steps!

**Comment by ivmartel** [comment]
Do you get the same error as the one that started this issue (`net::ERR_INSUFFICIENT_RESOURCES`)? If you get another, which one?

**Comment by jjreicher** [comment]
Yes, same error. 
With 0.28.0 I tried adjusting my loadURLs call to batch also...did not make a difference:
`app.loadURLs(stack, {batchsize: 5});`

**Comment by jjreicher** [comment]
batchSize, not batchsize. ugh. Seems like it may be working. Will do more testing and reply if any issues come up relevant to the thread.
