### ISSUE TITLE
DicomDataLoader will attempt to load wado urls with contentType=image/jpeg

### ISSUE THREAD

**Issue by amcgowan-frozenmountain** [ivmartel/dwv#721]
If the DicomDataLoader appears before the RawImageLoader in `dwv.io.loaderList` it will attempt to load wado urls with a content type of image/jpeg. This results in a error with invalid dicom data. 

As a work around I've manually set the order of the dwv.io.loaderList to ensure RawImageLoader appears first. 

This is occurring since the DicomDataLoader canLoadUrl method checks for the absence of an extension. If there is no extension, it will return true. 

https://github.com/ivmartel/dwv/blob/2cc6ff4cd305dc7a41598da122f257596cec4116/src/io/dicomDataLoader.js#L126

This likely also needs a check on content type to ensure the url is not going to load image data as opposed to dicom data.

**Comment by ivmartel** [comment]
Sorry if I messed that one up, I'll add some test to make sure this works as it should in future releases.
