### ISSUE TITLE
TypeError when loading image from azure blob using rest api

### ISSUE THREAD

**Issue by EldarPolitkin** [ivmartel/dwv#734]
```
Uncaught TypeError: Cannot read property 'bitsAllocated' of undefined
    at decode-jpegloss.js:12
```
when you try to load an dcm file from azure data lake gen 2 blob storage using a REST api 
if you try to load this file directly it works ok

while trying to find a solution looked at decode-jpegloss.js line 12
```javascript
var bpe = event.data.meta.bitsAllocated / 8
```
when looked at the event.data , there is no meta
if you delete the meta and change all event.data.meta. to just event.data all works ok (tested only in dev tools)

I'm pretty sure it will make all local files not to work

**Comment by ivmartel** [comment]
Hi, is it data you could share? Or even better, can you share the azure link?

**Comment by ivmartel** [comment]
I hope you found a solution to this, if so, I'm interested in how you did.

Closing for now, feel free to comment if you need.
