### ISSUE TITLE
Error: Cannot merge object with same ids

### ISSUE THREAD

**Issue by arturojain** [ivmartel/dwv#738]
I'm getting the following error: `Error: Cannot merge object with same ids:` on `v0.27.0` while loading many CTs that on `v0.26.0` didn't show such error.

This can hurt really bad both performance and experience since many of the files that show this error are shown as black frames.

**Comment by ivmartel** [comment]
This error happens when merging files meta data and the merged object already contains the info to merge, as if you were loading slices twice, is it possible?

**Comment by arturojain** [comment]
I'm anonymizing some examples to share.

**Comment by arturojain** [comment]
Related to #763

**Comment by ivmartel** [comment]
I can now load multiple jpeg data with commit 269e1c3. If anyone can test it, that would be welcome!
