### ISSUE TITLE
Brush/erase tool

### ISSUE THREAD

**Issue by ncovgt2020** [ivmartel/dwv#741]
Hi,

Thanks for sharing your project.This is in reference to #675  for the brush/eraser functionality. Some examples of this functionality are [here](https://medium.com/labelbox/introducing-best-in-class-image-annotation-tools-for-computer-vision-applications-de5da8931d6e) (brush) and [here](https://www.youtube.com/watch?v=BrtueCikLA4). Those examples have other, more complex functions (auto segmentation, etc) but it would be cool to first have the basic brush/erase functionality. 

I was wondering if this could be included in the project. I have no experience with javascript nor web development and in deed are struggling to grasp the code base of this project. That being said, I will appreciate you could provide me some indications on how such functionality could be implemented and I would give it a try as time allows. For my use case, the final goal would be to have an "segmentation mode" in which by choosing a "label" and "color" one draws different sections of the image and internally retrieve the generated masks. This could then be used for generating datasets for learning algorithms.

Thanks

**Comment by ivmartel** [comment]
I saw your examples, dwv follows a logic of contouring rather than painting, wouldn't that be enough?

dwv uses [konvajs](https://konvajs.org/) for drawing, so anything you can see in the demos should be doable here.

**Comment by ncovgt2020** [comment]
Hi, I will check konvajs.  

In principle the brush functionality seems to be adequate for very irregular objects with smooth contours. After trying the ROI tool to generate smooth contours, it was my perception that the very working principle of selecting corners does not adapt for smooth contours, i.e. one would need an impractical amount of corners -and clicks- to generate an smooth contours. Yet, this is my perception with limited knowledge of the codebase.
