### ISSUE TITLE
Not able to render image properly with YBR_RCT Photometric Interpretation

### ISSUE THREAD

**Issue by sutirthpatel** [ivmartel/dwv#742]
any idea how to render the actual image with YBR_RCT Photometric Interpretation, I am not able to render actual image.

**Comment by ivmartel** [comment]
I'm missing test data for that one, if you can share some, it should not be to complicate to add support.

**Comment by ivmartel** [comment]
Still interested in test data if anyone has some!

Closing for now, feel free to comment if you need.
