### ISSUE TITLE
append a slice with different orientation

### ISSUE THREAD

**Issue by fabrizzios** [ivmartel/dwv#748]
i unstestrand that dwv needs de image positiion to ordering stuffs, but is possible to show the entire serie even when the serie has one scout image , some CTs send the reconstruction files and includes the scout in the same serie

thanks

**Comment by ivmartel** [comment]
Relates to #646. 

Do you know if the scout is clearly identified and could be filtered out?

**Comment by fabrizzios** [comment]
i dont know, but i'm uploading one serie, another viewers separate the scouts as a new serie. but asuming that dwv doesnt not do mpr process, i would be better just that the scouts could be shown at the end of the same serie, what to you think about it?
[series.zip](https://github.com/ivmartel/dwv/files/5337310/series.zip)

Thanks

**Comment by ivmartel** [comment]
Closing for now, follow #646 for updates. Feel free to comment if you need.
