### ISSUE TITLE
How can I save an object (example: ruler, rectangle and etc) in JSON and load it then?

### ISSUE THREAD

**Issue by LexaDel** [ivmartel/dwv#752]
How can I save an object (example: ruler, rectangle and etc) in JSON and load it then?

**Comment by ivmartel** [comment]
Yes, this is handled by the [state](https://github.com/ivmartel/dwv/blob/v0.27.0/src/app/state.js) class. See [application.getState()](https://github.com/ivmartel/dwv/blob/v0.27.0/src/app/application.js#L662) to save and [application.loadFiles()](https://github.com/ivmartel/dwv/blob/v0.27.0/src/app/application.js#L414) to load a state.

**Comment by ivmartel** [comment]
I hope my comment helped. Closing for now, feel free to comment if you need.
