### ISSUE TITLE
how to load a blob file?

### ISSUE THREAD

**Issue by JingfeiPeng** [ivmartel/dwv#754]
I am trying to load a dicom blob file that I got from a rest API. I tried both loadFiles and loadURLs and both has different errors:
```
(imgBlob: Blob) => {
        const file = new File([imgBlob], 'PatientDicom.dcm', {type: 'application/dicom', lastModified: Date.now()})
        app.loadFiles([file]);
}
```
This has error: `Cannot read property 'name' of undefined`
```
(imgBlob: Blob) => {
        const urlCreator = window.URL || window.webkitURL;
        var objectURL = urlCreator.createObjectURL(imgBlob);
        app.loadURLs([objectURL]);
}
```
This has error: `"Uncaught SyntaxError: Unexpected token '<'"`

The way I used these two ways might just be wrong. In essence I just want to load a blob file into DWV app. Much appreciated if some guides can be given 

The following is the code for `app` 
```
    const app = new dwv.App();

    app.init({
      "containerDivId": "dwv",
      "tools": null
    }); 
   .... (same setup as dwv-react)
```

**Comment by ivmartel** [comment]
Loading the blob via a File looks like the right way. The code expects the file to have a 'name' property to know how to load it, see [loadController.js#L24](https://github.com/ivmartel/dwv/blob/develop/src/app/loadController.js#L24). It could default when there is none, I'll see what I can do...

**Comment by JingfeiPeng** [comment]
The file already has a name property though.
The second parameter 'PatientDicom.dcm' is the name property.
new File([imgBlob], 'PatientDicom.dcm', {type: 'application/dicom', lastModified: Date.now()})

**Comment by ivmartel** [comment]
This is a different problem, your dicom file is not valid, check out [Error-Messages#not-a-valid-dicom-file](https://github.com/ivmartel/dwv/wiki/Error-Messages#not-a-valid-dicom-file) and this [comment](https://github.com/ivmartel/dwv/issues/188#issuecomment-443123867) on #188 for more. if you still have troubles, you can open a new issue.
