### ISSUE TITLE
Select multiple local Dcm files and report errors.

### ISSUE THREAD

**Issue by MicroSsq** [ivmartel/dwv#755]
Error: Cannot merge object with same ids: 3, id2: 3。
I tested the demos of Jqui and Vue, and they all have this situation

**Comment by MicroSsq** [comment]
I found that it has something to do with DCM format pictures. If you use the pictures in your demo, there will be no problem. The pictures need special processing? @ivmartel

**Comment by ivmartel** [comment]
Related to #738.

**Comment by ivmartel** [comment]
As in #738, can you share some data to recreate the problem? I'm not sure what is creating such situation...

**Comment by MicroSsq** [comment]
> As in #738, can you share some data to recreate the problem? I'm not sure what is creating such situation...

I have sent the document to ivmartel@gmail.com mailbox

**Comment by MicroSsq** [comment]
> > As in #738, can you share some data to recreate the problem? I'm not sure what is creating such situation...
> 
> I have sent the document to [ivmartel@gmail.com](mailto:ivmartel@gmail.com) mailbox

@ivmartel  Did you receive the mail?

**Comment by ivmartel** [comment]
Yes, I will try to check it today.

**Comment by ivmartel** [comment]
The code tries to sort the dicom metadata using the 'InstanceNumber' tag which your data does not have. I need to find a backup plan to handle this case...

**Comment by MicroSsq** [comment]
> The code tries to sort the dicom metadata using the 'InstanceNumber' tag which your data does not have. I need to find a backup plan to handle this case...

Ok，Waiting for your good news.

**Comment by arturojain** [comment]
Possible explanation in #763

**Comment by ivmartel** [comment]
> The code tries to sort the dicom metadata using the 'InstanceNumber' tag which your data does not have. I need to find a backup plan to handle this case...

I was wrong, your data has 'InstanceNumber's, your problem is the same as #763 since your data is jpeg encoded.

**Comment by ivmartel** [comment]
I can now load multiple jpeg data with commit 269e1c3. If anyone can test it, that would be welcome!
