### ISSUE TITLE
How to call tool box functions from outside script

### ISSUE THREAD

**Issue by santho5** [ivmartel/dwv#756]
hi. I am using dwv-jqui for my project and i got few questiosn.

how can i call a tool box function from outside the native scripts.
For example , if i want to change the tool by clicking a custom made button by calling app.setTool('Draw'); through a custom script function, how is it possible.?
when i call this from a js script it says app is not defined.
can you help me with this please

also in dwv-jqui is it possible to load url problematically without inputing in browser URL
like which function we should use to load URLs

how can we load state.json programatically in dwv-jqui
which function do this job?

Thanks .. waiting fro your help

santosh

**Comment by ivmartel** [comment]
I replied to your issue in [dwv-jqui/issues/31](https://github.com/ivmartel/dwv-jqui/issues/31).
