### ISSUE TITLE
next/previous slice key binding

### ISSUE THREAD

**Issue by arturojain** [ivmartel/dwv#761]
I see ctrl + arrow left/right on macOS changes spaces too. Is there a function we can call to create our own keyboard bindings?

**Comment by ivmartel** [comment]
Yes, since v0.27.0 it is up to the client to set the event handlers. dwv provides a default [onKeyDown](https://github.com/ivmartel/dwv/blob/v0.27.0/src/app/application.js#L759) that you can use or you can set your own. Check out the demo apps to see how this is done.

**Comment by arturojain** [comment]
Thanks! I have modified to implement my own.
