### ISSUE TITLE
StudyDate vs SeriesDate when displaying overlay

### ISSUE THREAD

**Issue by arturojain** [ivmartel/dwv#765]
I'm having an issue when a study is acquired in multiple days, the overlay keeps showing the same date due to usage of StudyDate for the overlay.

**Comment by ivmartel** [comment]
You can change the displayed data of the overlay by modifying the overlay file of your language, doesn't it not work?

**Comment by arturojain** [comment]
Never thought about `overlay.json`. Thank you very much!
