### ISSUE TITLE
The ruler cannot calculate the length

### ISSUE THREAD

**Issue by BillJC-Liu** [ivmartel/dwv#766]
The ruler cannot calculate the length In the dwv-vue project . How can I use it correctly. 
![image](https://user-images.githubusercontent.com/30457197/88613555-46e60780-d0c0-11ea-9f3e-b07c474cb154.png)

**Comment by ivmartel** [comment]
Echo data does not come with pixel spacing so it is impossible to measure distances without some extra information. I'm sorry but I do not have a solution to this problem...

Related to #295.

**Comment by ivmartel** [comment]
Relates to #641.

**Comment by ivmartel** [comment]
Check out the status of #641 for updates. Closing for now, feel free to comment if you need.
