### ISSUE TITLE
multislice shortcode for wordpress.

### ISSUE THREAD

**Issue by smartydoctor** [ivmartel/dwv#768]
I'm sorry for disturbing you again. What is the shortcode for wordpress multislice images?
please, give an example with short code. I tried to use similar code [gallery size="large" ids="233,234,235,236,237,238,239,240,241,242"] but not working, showing regular images. I use similar code [dcm gallery size="large" ids="233,234,235,236,237,238,239,240,241,242"] but not working too (blank)
thanks again

**Comment by ivmartel** [comment]
I answered in [dwv-jqmobile/issues/28](https://github.com/ivmartel/dwv-jqmobile/issues/28).

Best to ask questions about the wordpress plugin on its support [page](https://wordpress.org/support/plugin/dicom-support/).
