### ISSUE TITLE
Heat Map on dwv/angular

### ISSUE THREAD

**Issue by MounikaAV** [ivmartel/dwv#774]
Hi,
In my project, I am using the dwv-angular library for displaying the radiology images.
Now I want to show heatmap on those images. Can you help me with how should I can complete my task?

Thanks in Advance.

**Comment by ivmartel** [comment]
Hi @MounikaAV, what do you mean by heat map?

**Comment by MounikaAV** [comment]
Hi @ivmartel,
Sorry for the late reply.
Heatmap in the sense on the image which I am displaying the viewer, per pixel I need to show and color it like an overlay.

**Comment by ivmartel** [comment]
Ok, relates to #585, no real plans for now but could arrive before the end of the year...

**Comment by MounikaAV** [comment]
Ok thank you, we will be waiting for new release.
