### ISSUE TITLE
Drawing custom shapes 

### ISSUE THREAD

**Issue by JacobChwastek** [ivmartel/dwv#776]
Hello, me and my team are using dwv-react.
I can't figure out how can I draw just point2D or Circle
I have tried creating prototypes of existing factories and it worked out quite fine,
but my goal is to create for example 3 point using mouse rather than passing corridinates and 
then generate circle
Should I create custom factory or update existing one (if its possible)

Thank you in advance

**Comment by ivmartel** [comment]
Yes, a new factory is need for new shapes. They define the number of points that are needed so that the draw code knows when to stop listening to mouse move. For the circle, start from the ellipse, it should be quite similar.

**Comment by wulucxy** [comment]
@JacobChwastek is this finished?

**Comment by JacobChwastek** [comment]
@wulucxy  Yes, we have somehow managed to achieve the desired goal.
