### ISSUE TITLE
Error in loading different file types(eg. jpeg, png) than DCIM through loadURLs

### ISSUE THREAD

**Issue by namanguptaten** [ivmartel/dwv#777]
I have created a url using blob as we have bytearray and passing that url to **loadURLs** function but that is unable to load that file

**Comment by ivmartel** [comment]
Relates to #739. It should be fixed in v0.27.1, if you can try the code of the v0.27 branch and confirm it is ok, that would be great!

**Comment by namanguptaten** [comment]
We have done it by overiding getViewFromDOMImage as in that support was not there to show jpeg or png via blob


dwv.image.getViewFromDOMImage = function (image, origin)
                        {
                            // image size
                            var width = image.width;
                            var height = image.height;

                            // draw the image in the canvas in order to get its data
                            var canvas = document.createElement('canvas');
                            canvas.width = width;
                            canvas.height = height;
                            var ctx = canvas.getContext('2d');
                            ctx.drawImage(image, 0, 0);
                            // get the image data
                            var imageData = ctx.getImageData(0, 0, width, height);

                            // image properties
                            var info = [];
                            if ( typeof image.origin === "string" ) {
                                info.push({ "name": "origin", "value": image.origin });
                                info.push({ "name": "fileName", "value": "" });
                                info.push({ "name": "fileType", "value": dwv.type });
                            } else {
                                info.push({ "name": "fileName", "value": image.origin.name });
                                info.push({ "name": "fileType", "value": image.origin.type });
                                info.push({ "name": "fileLastModifiedDate", "value": image.origin.lastModifiedDate });
                            }
                            info.push({ "name": "imageWidth", "value": width });
                            info.push({ "name": "imageHeight", "value": height });

                            var sliceIndex = image.index ? image.index : 0;
                            info.push({ "name": "imageUid", "value": sliceIndex });

                            // create view
                            var imageBuffer = dwv.image.imageDataToBuffer(imageData);
                            var view = dwv.image.getDefaultView(
                                width, height, sliceIndex, [imageBuffer], 1, sliceIndex);

                            // return
                            return {
                            data: {
                                view: view,
                                info: info
                            },
                            source: origin
                            };
                        };
