### ISSUE TITLE
Cannot get past install

### ISSUE THREAD

**Issue by clairestreb** [ivmartel/dwv#779]
Followed **yarn install** instruction from readme.md, but it failed. Tried **npm install**, and that failed, too. Please see attached file [dwvCannotGetPastInstall.pdf](https://github.com/ivmartel/dwv/files/5261762/dwvCannotGetPastInstall.pdf) for error messages. Any advice?

**Comment by ivmartel** [comment]
The yarn error is weird...

> C:\Users\UserName\Downloads\dwv>yarn install
   yarn install v1.22.5
   [1/4] Resolving packages...
   [2/4] Fetching packages...
   error An unexpected error occurred: "https://registry.yarnpkg.com/i18next-xhr-backend/-/i18next-xhr-backend-2.0.0.tgz: write EPROTO 15692:error:141A10F4:SSL routines:ossl_statem_client_read_transition:unexpected message:c:\\ws\\deps   \\openssl\\openssl\\ssl\\statem\\statem_clnt.c:395:".

It looks more like a connection issue, if you try again, it gives the same error?

Regarding npm, it seems the install finished ok, the vulnerabilities are just warnings, you do not have to run `npm audit`.

**Comment by clairestreb** [comment]
OK, don't like the High warning, but was able to **yarn run test**. Please close issue (it looks like I'm not allowed to).

**Comment by ivmartel** [comment]
Are you building the `master` branch? This is not the latest code, for that I use the `develop` branch and it only gives me one low warning. Develop will be merged in master at the 0.28 release.
