### ISSUE TITLE
Why not use react framework?

### ISSUE THREAD

**Issue by shivasuri** [ivmartel/dwv#785]
Curious why https://github.com/ivmartel/dwv-react was left behind for this project? What were the shortcomings using react?

**Comment by ivmartel** [comment]
I has not been left behind, it's just that react did not get as many updates than angular or vue. In terms of functionality, they all provide the same and they all haven't received the care they should have since the release of dwv v0.27.0.

**Comment by ivmartel** [comment]
Closing for now. All PR on the react project and this one are welcome!
