### ISSUE TITLE
 shape can't be deleted in mac

### ISSUE THREAD

**Issue by wulucxy** [ivmartel/dwv#801]
Mac `backspace` keycode is 8，while https://github.com/ivmartel/dwv/blob/d0ef7a2a20c60032967990e45b085409e26ffd6c/src/tools/draw.js#L343
has only work for windows。

**Comment by ivmartel** [comment]
`46` is the key code for a (forward) `delete`. On a mac, if you do not have the key on your keyboard, I think you need to do a `Fn` + `Delete` for a forward delete

**Comment by wulucxy** [comment]
thanks for the reply。
So，how can stop drawing shape when I accident trigger drawing?
do we have any shortcuts（like `esc`）?

**Comment by ivmartel** [comment]
There is no `esc` but it is a good idea.

**Comment by ivmartel** [comment]
Closing for now, follow #849 for the `Esc` shortcut. Feel free to comment if you need.
