### ISSUE TITLE
how to install the newest beta version?

### ISSUE THREAD

**Issue by wulucxy** [ivmartel/dwv#802]
I have lot's image to upload(500+)，I think the newest version（0.28-beta）`batchSize` options meet the requirement。

But can you release this version on `npm` for usage?

thanks。

**Comment by ivmartel** [comment]
I have a few issues left to resolve before the release, I'm hoping to do it in the next 2 weeks.

In the mean time, you can build the code manually (`yarn run build`) and add it to your `node_modules`.

As a ref, `batchSize` was introduced in #780.

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
