### ISSUE TITLE
I want to see the demo system, but I need the account password. What is the account number

### ISSUE THREAD

**Issue by LingZ12** [ivmartel/dwv#814]
I want to see the demo system, but I need the account password. What is the account number

**Comment by ivmartel** [comment]
Not sure what you mean by 'demo system'... There is a demo page (https://ivmartel.github.io/dwv/) and it does not need a password...

**Comment by LingZ12** [comment]
the demo page show this
![image](https://user-images.githubusercontent.com/36194330/100718941-eb71b080-33f6-11eb-8188-bfa958ca6eb9.png)

**Comment by ivmartel** [comment]
When trying to access https://ivmartel.github.io/dwv/?

**Comment by LingZ12** [comment]
yes，Just visit https://ivmartel.github.io/dwv/；Displays the login box

**Comment by ivmartel** [comment]
Sorry I can't reproduce, it works fine on my side in Chrome and Firefox... This dialogue does not come from me...

**Comment by LingZ12** [comment]
thanks

**Comment by wulucxy** [comment]
@LingZ12 maybe come from VPN

**Comment by ivmartel** [comment]
I hope you solved your problem. Closing for now, feel free to comment if you need.
