### ISSUE TITLE
demo issue when uploading images

### ISSUE THREAD

**Issue by DavideOnGitHub** [ivmartel/dwv#817]
Hi, I have a problem when uploading a 361 image series (tried with less images too) of DICOM images by folder option in DWV demo. Only first image of series is uploaded/displayed and "load errors have occured" popup is showed. I tried with both Firefox and Chrome browsers.

![DWV_load_error](https://user-images.githubusercontent.com/75609605/101338541-66b2e680-387d-11eb-887d-a8a9f81f2b4e.jpg)

**Comment by ivmartel** [comment]
Could you share the content of the console log please?

**Comment by DavideOnGitHub** [comment]
You mean the browser console log?
If yes here it is. Thank you
[DWV_console_log.txt](https://github.com/ivmartel/dwv/files/5653164/DWV_console_log.txt)

**Comment by ivmartel** [comment]
Ok, it's an error due to files having different meta data. When trying to merge the meta data, dwv cannot find the content and throws a `Error: Cannot merge object with same ids: 1, id2: 1`. This test needs to be relaxed, I'll see what I can do.

**Comment by DavideOnGitHub** [comment]
Ok thank you!
I'm trying your application because the company I work for might be interested. I sent you an email about it, let me know if you have received it. Thanks again

**Comment by ivmartel** [comment]
I got the email and will answer soon, thanks!

**Comment by ivmartel** [comment]
Please follow #828 for progress on this.
