### ISSUE TITLE
how can I add anchors based on shape

### ISSUE THREAD

**Issue by wulucxy** [ivmartel/dwv#818]
![image](https://user-images.githubusercontent.com/5326403/101565982-2d0ee680-3a09-11eb-8088-e6989c99ae4a.png)

Hi， @ivmartel，thanks for the great working for this project。

I have a question:

I have made some algorithm to annotate the `dicom` files，so how can `add/edit` the anchors based on the shape I created?

thanks for your help。

**Comment by ivmartel** [comment]
I need to check Konva to see if this is possible.

**Comment by ivmartel** [comment]
Editing the anchor is already available. Add an anchor could be done via a special interaction, such as `ctrl` + `click` on the shape.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment.
