### ISSUE TITLE
New tools

### ISSUE THREAD

**Issue by arunjoshtech** [ivmartel/dwv#829]
Dear Team, 
How can we add missing tools like  Probe, Reference Line,
Mpr to the viewer? Kindly advise to use this viewer in realtime.

**Comment by ivmartel** [comment]
Regarding MPR, see #4. I'm getting there very slowly...
If you need a specific functionality, please create an issue for it.
I'm planning on releasing 0.28.0 at the beginning of next year.

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
