### ISSUE TITLE
hot to watch shapeGroup change?

### ISSUE THREAD

**Issue by wulucxy** [ivmartel/dwv#833]
![image](https://user-images.githubusercontent.com/5326403/102885378-3cbd0f00-448e-11eb-9d36-0a5c204230e1.png)

My situation is that：

when shape group change，the info table immediately update what has changed。

I have reviewed the code，neither `drawEnd` or `drawChange` event has not exposed，so how can I do this feature?

**Comment by ivmartel** [comment]
I hope you found a solution to your question. Feel free to comment if you need.
