### ISSUE TITLE
How do urls load in reverse order

### ISSUE THREAD

**Issue by javelang** [ivmartel/dwv#834]
HI! :
I need your help!

I am using URLs to load images, but when I throw the URLs array in, I find that the loading order is opposite to the order of URLs array I dropped in. What I want is to load in the order of URLs array I dropped in.

I try to be in dwv.image.Geometry . appendorigin (origin, index) to change the order of the origins array. However, I will find that the loading sequence is not coherent. The last image is the image that I first requested the connection to return, which bothers me.

If you are free, please help me solve this problem! thank you!

**Comment by ivmartel** [comment]
Hi, are you talking about the order in which the files are downloaded or the order in which they appear?

For the display, the order is defined by the 'imagePositionPatient' dicom tag. It is true the app could provide an option for head first or not.

**Comment by ivmartel** [comment]
I hope this answers your question, closing for now, feel free to comment if you need.

**Comment by javelang** [comment]
ivmartel：
 Thank you for your reply. I have understood it now. I customize a slice index field to add to the origin array, and then rewrite the sorting logic to get the sorting method I want
