### ISSUE TITLE
How can I reset draw event when slice-change event fired

### ISSUE THREAD

**Issue by wulucxy** [ivmartel/dwv#835]
![image](https://user-images.githubusercontent.com/5326403/102985069-87e82800-4549-11eb-8882-463a9bd96bdd.png)
When I accidentally trigger `mousedown` event on one slice，then I go to next slice，the `mousemove` event will follow up，this is very annoying。

after I debug the source code, I think these is some bug here：
https://github.com/ivmartel/dwv/blob/3b75e7fbc8/src/tools/draw.js#L265
``` js
  // do we have all the needed points
  if (points.length === currentFactory.getNPoints()) {
    // store points
    onFinalPoints(points);
    // reset flag
    started = false;
  } else {
    // remove temporary flag
    if (typeof points[points.length - 1].tmp !== 'undefined') {
      delete points[points.length - 1].tmp;
    }
    // TODO：here should reset the `started` flag
    started = false
  }
```
Did me miss something?

**Comment by ivmartel** [comment]
There are some draw cases where the `mouseup` does not mean the end of the draw, I think that's why the flag is not reset. You have a point, the draw should be reset when changing slices.

**Comment by ivmartel** [comment]
But I have a question, how did you manage to both start drawing and change slice?

**Comment by ivmartel** [comment]
I hope my answer helped and the commit fixed your issue. Closing for now, feel free to comment if you need.
