### ISSUE TITLE
setDrawing should not fire `draw-create` event

### ISSUE THREAD

**Issue by wulucxy** [ivmartel/dwv#836]
https://github.com/ivmartel/dwv/blob/bc7c8d2b575fbda0f7b4d51e047aa8fe9bd64c13/src/app/drawController.js#L438，

there should be set `slient` to be true。

**Comment by ivmartel** [comment]
Could you justify why if should be silent? If the event bothers you, can't you stop listening while calling the `setDrawings` method?

**Comment by wulucxy** [comment]
this is my case：
```
dwvApp.addEventListener('draw-create', ({ id }) => {
  // when new drawing created, mean some lesion are created
  state.lesions.push({
    id: generateUuid(),
    ....moreProps
  });
});
```
So，if the request from `API` but not `user` will be annoying。
