### ISSUE TITLE
how to cancel request when page is unloaded?

### ISSUE THREAD

**Issue by wulucxy** [ivmartel/dwv#839]
when `loadUrl` is fired，event if the page is unloaded，the requests will still be fired，

SO，how can I cancel these request when page is unloaded?

**Comment by ivmartel** [comment]
The app class has a `abortLoad` (see [application.js#L457](https://github.com/ivmartel/dwv/blob/v0.27.1/src/app/application.js#L457)) method to cancel a load.

**Comment by wulucxy** [comment]
yes，thanks
