### ISSUE TITLE
How do I pass mutiple dicom files url in the Dicom input - parameter url 

### ISSUE THREAD

**Issue by ruchi1234** [ivmartel/dwv#841]
Hi,
I just want to pass the multiple files in the URL and show that on Dicom viewer and when use SCROLL then all Dicom files scroll one by one which comes on URL.

All URL of files is coming from AWS S3. THIS means I have not a DICOM ROOT ( according to this issue--
https://github.com/ivmartel/dwv-react/issues/33 ). 
All are individual URLs and I am not able to use all files together and perform the SCROLL functionality on them.

**Comment by ivmartel** [comment]
Check out this doc: [User-Stories#dwv-urs-io-005-data-url-scheme](https://github.com/ivmartel/dwv/wiki/User-Stories#dwv-urs-io-005-data-url-scheme). Does it resolve your issue?

**Comment by ruchi1234** [comment]
I have used this. Still, It does not resolve my issue.

**Comment by ivmartel** [comment]
You mean that each slice is on a different server? I'm not sure how the code would behave if you do not pass a root, it maybe needs to be updated to support this case.

**Comment by ruchi1234** [comment]
Yes, all URL is individual we can not find root URL. May you please provide the update that supports this case.

**Comment by ruchi1234** [comment]
I am still waiting for the reply Please provide the solution of this

**Comment by ivmartel** [comment]
Check out progress in #843. Closing for now, feel free to comment if you need.

**Comment by ruchi1234** [comment]
How I will send the URL in the input parameter please send an example with the encode URL and also with resolved (without encoding URL). So I can use it.

**Comment by ivmartel** [comment]
For example:
root = `http://ivmartel.github.io/dwv/demo/static/index.html?input=`
list = `?key=http://x.babymri.org/?53320924&key=http://x.babymri.org/?53320925&key=http://x.babymri.org/?53320926`
option = `&dwvReplaceMode=void`

Full url = root + urlencode(list) + option

Will resolve to: 
- http://x.babymri.org/?53320924
- http://x.babymri.org/?53320925
- http://x.babymri.org/?53320926

This will be available in v0.28 which is not available yet. I hope this helps, if not, could you send an example of the urls you are trying to open?

**Comment by ruchi1234** [comment]
Hi, @ivmartel 
I have updated dwv in the -0.28.1 version, I am using this on Reactjs it when I pass a single file on parameter this gives me this error, And how I will pass multiple files on URL at a time and shows all on scrolling feature. 
![image](https://user-images.githubusercontent.com/273250/109161423-0b6a0380-779d-11eb-9c62-3e8fd4a61d60.png)

**Comment by ivmartel** [comment]
I've had troubles with the react demo too, not sure what is happening, I need to check... Can you create an issue there? ([dwv-react](https://github.com/ivmartel/dwv-react))
