### ISSUE TITLE
How can I load an online dcm file link？

### ISSUE THREAD

**Issue by xkmy** [ivmartel/dwv#842]
i want to load online dcm file , like this:http://xxx.com/dcm/1_0.dcm
i use loadUrls but he reported an error , i tried many times but it didn't work 
![image](https://user-images.githubusercontent.com/44152845/104609875-76182180-56be-11eb-8f47-550ec7b4f74d.png)

i hope you can helo me, thank you ！！

**Comment by xkmy** [comment]
sorry,it's me accidentally wrote the url wrong ...  thanks you !!

**Comment by ivmartel** [comment]
Ok, closing then!
