### ISSUE TITLE
Modify state.json filename

### ISSUE THREAD

**Issue by arturojain** [ivmartel/dwv#856]
Is there a way to change the name for the `state.json` file when it is downloaded?

**Comment by ivmartel** [comment]
The file name is defined in the dwv client, for example here in dwv-jqmoble: [appgui.js#L127](https://github.com/ivmartel/dwv-jqmobile/blob/772924f43079fcaa39742f0e95db5655fc2b58b7/src/appgui.js#L127). You would like the state file name to be unique?

**Comment by arturojain** [comment]
This is more than enough for me. Thanks!
