### ISSUE TITLE
Get drawings without downloading state.json

### ISSUE THREAD

**Issue by arturojain** [ivmartel/dwv#857]
Is it possible to get the current state of the drawings without downloading the `state.json`?

**Comment by ivmartel** [comment]
You can get the drawings manually from the app, check out the code of the state to see how it is done: [state.js#L33](https://github.com/ivmartel/dwv/blob/v0.27.1/src/app/state.js#L33).

**Comment by ivmartel** [comment]
Hi @arturojain, did my answer help you?

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
