### ISSUE TITLE
why same value for positionchange and valuechange

### ISSUE THREAD

**Issue by anupzone** [ivmartel/dwv#873]
<img width="521" alt="Screenshot 2021-02-19 at 4 29 00 PM" src="https://user-images.githubusercontent.com/4955675/108496124-ab241f00-72cf-11eb-822f-136e56b2b288.png">

**Comment by ivmartel** [comment]
The `value` gives you the event to listen to, then in the `format` you can use elements of the array that is returned. So both line listen to the same event but display different values.

**Comment by anupzone** [comment]
ok got it. thanks :)
