### ISSUE TITLE
make thumbs of slices

### ISSUE THREAD

**Issue by mohamedsharaf** [ivmartel/dwv#88]
i need to know the idea on how to make thumb of slices 
             var image = app.getImage();
                var dataWidth = image.getSize().getNumberOfColumns();
                var dataHeight = image.getSize().getNumberOfRows();

```
            var view = app.getView();
            var pos = view.getCurrentPosition();
            var currentSliceNumber = pos.k;

            var mycanvas = document.getElementById("mycanvas");
            mycanvas.width = dataWidth;
            mycanvas.height = dataHeight;
```

//this is just test to make sure canvas work using red rect
                var ctx = mycanvas.getContext("2d");
                ctx.fillStyle = "red";
                ctx.fillRect(10, 10, 50, 50);

//-----------this next line not work
 //how to get this i know i can read it from canvas imageLayer but need through code
                var imageData = view.getImage();
                ctx.putImageData(imageData, 0, 0);
//------------------------------------

how to get thumb of slice zero and put in canvas for later making it html image via to dataurl

**Comment by ivmartel** [comment]
This one is a bit old. One solution is also to play with the size (via css) of the different layer divs.
