### ISSUE TITLE
Add circle draw shape

### ISSUE THREAD

**Issue by ivmartel** [ivmartel/dwv#885]
The draw tool must be able to draw circle shapes.

**Comment by yashsharma16** [comment]
Hello, I am trying to add shapes, circles, and rectangles in the draw part, how can I implement dwv.math.Circle

**Comment by ivmartel** [comment]
Check out the examples, there is one with draw: https://jsfiddle.net/ivmartel/fugw49be/ (change the draw option to be circle)

**Comment by yashsharma16** [comment]
Thanks for replying its working, but I have 1 more question I want to add multiple options in the top bar, like currently from your previous example I have Draw, WindowLevel, and ZoomAndPan, I tried adding Circle, rectangle in array but it's not working

like this: Draw: {
          options: ['Ruler','Circle','Rectangle'],//it should come as a option for more shapes-edit
          type: 'factory',
          events: ['drawcreate', 'drawchange', 'drawmove', 'drawdelete']
        }


---------------------------------------------------------------------
and on
 // activate tool once done loading
app.addEventListener('load', function () {
  app.setTool('Draw');
  app.setDrawShape(tools.Draw.options[0]);
});

I want to add an event based on the option selected by the user from the top menu,
please guide me on this also,

**Comment by ivmartel** [comment]
You need to add a select for the draw shape, when clicked, you can call `setDrawShape` with the selected shape.
