### ISSUE TITLE
Lack of tools and how to add it

### ISSUE THREAD

**Issue by arunjoshtech** [ivmartel/dwv#894]
Dear DWV it is my big doubts, why limitted tools in the viewer.
How to add or develop tools like HU value, magnifier, reference line, invert, cob angle, mpr in the viewer?
And why DWV team is not focussing to add all the tools?

**Comment by ivmartel** [comment]
Hi @arunjoshtech!  The tools are coming... but it takes time! For now I am focusing on adding more flexible layers to the viewer, this in order to help support MPR (#4) which I hope will come in a not so far future... All help appreciated!

**Comment by ivmartel** [comment]
I hope I answered your question, closing for now, feel free to comment if you need.
