### ISSUE TITLE
Scroll feature not working with PNGs

### ISSUE THREAD

**Issue by RLeipe** [ivmartel/dwv#895]
First of all respect and thanks for this great project!

I am trying to get the scroll feature working on PNGs. Minimal reproducible example would be the [fiddle](https://jsfiddle.net/ivmartel/zvt0xemc/), just replacing the app.loadUrls line with `app.loadURLs(["https://i.imgur.com/KHiR78c.png","https://i.imgur.com/TKfY5Ps.png","https://i.imgur.com/jw8I1Lf.png"]);`
Same number of slices as the .dcm version, but no scrolling. What am I missing, or is this simply not possible?

**Comment by RLeipe** [comment]
Might this be because they have a different resolution (as they are just rough crops)? Trying to load them in the dwv-jqui demo i get `Error: Cannot append a slice with different number of columns`

If so, is there a way to allow pngs with different to be scrolled through anyway?

**Comment by ivmartel** [comment]
The code will not accept images with different number of rows or columns since this does not happen with a scanner. Would it be difficult to have all images with the same resolution?

**Comment by ivmartel** [comment]
Hi @RLeipe, did you make any progress on this issue?

**Comment by rakeshsoni18** [comment]
How can I create multiple instances?

**Comment by ivmartel** [comment]
@rakeshsoni18 I'm not sure I get your question, multiple instances of what?

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
