### ISSUE TITLE
How to set spacing of PNGs for length measuring

### ISSUE THREAD

**Issue by RLeipe** [ivmartel/dwv#896]
I want to use the Ruler tool on PNGs, but cant't figure out how to set the spacing for a PNG so that the `getWorldLength()` function can work  (If I even understood correctly how it works). How and where would I do this?

**Comment by ivmartel** [comment]
I created #897 to allow for manual calibration: for data that do not provide pixel spacing, the user should be able to specify it manually. The app should provide a `setImageSpacing` method that would set the spacing of the image. From then, the measuring tools should work.

**Comment by RLeipe** [comment]
Thanks, that's exactly it.

**Comment by RLeipe** [comment]
One thing I'm still not getting: When using the [DWV Static](https://ivmartel.github.io/dwv-jqui/demo/stable/index.html?input=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2F7%2F7f%2FBrain_MRI_112010_rgbca.png) on a png, using the ruler still results in "mm" being shown after the length (which seems  to be just the number of pixels). Since the mm seems to only be displayed if there is a spacing set:

`var length = line.getWorldLength(spacing.getColumnSpacing(),
    spacing.getRowSpacing());
  if (length !== null) {
    quant.length = {value: length, unit: dwv.i18n('unit.mm')};
  }`
There seems to be some way in which dwv static has made at least that work. How is that?

**Comment by ivmartel** [comment]
You're right, the code sets a default spacing for DOM images (see [domReader.js#L45](https://github.com/ivmartel/dwv/blob/v0.28.2/src/image/domReader.js#L45)), which is wrong...

**Comment by ivmartel** [comment]
Closing for now, please comment on #897 if you need.
