### ISSUE TITLE
Canvas area exceeds the maximum limit (width * height > 16777216)

### ISSUE THREAD

**Issue by arturojain** [ivmartel/dwv#902]
In some iOS devices the following error can occur:

`Canvas area exceeds the maximum limit (width * height > 16777216). `

This causes no image to show, only the overlay. As far as I can find it is due to a memory limit and a possible solution is to limit `Konva.pixelRatio`

This should also apply to Android devices, but I don't have a device for testing. I'm using dwv `0.28.0-beta`

**Comment by ivmartel** [comment]
Here are some different browser limits: [jhildenbiddle/canvas-size#test-results](https://github.com/jhildenbiddle/canvas-size#test-results).
The method that fits the canvas size to the available size must use this limit to find the appropriate size.

**Comment by ivmartel** [comment]
Also see: [canvas#maximum_canvas_size](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas#maximum_canvas_size) on MDN.
