### ISSUE TITLE
An error was reported during drawing Angle on the mobile phone

### ISSUE THREAD

**Issue by lizesheng0313** [ivmartel/dwv#904]
![image](https://user-images.githubusercontent.com/23352222/114133124-22714900-9938-11eb-8f6c-441b1893ac4c.png)

this.dwvApp.setDrawShape('Protractor') on phone an error occurred  

Mobile terminal drawing error, drag to report an error

Thank you all for your help

**Comment by ivmartel** [comment]
The protractor for mobile is a bit tricky, you have to hold still to create the middle point...

The full flow is: 
1. press and drag to create the first line
2. keep your finger at the same position for half a second, that creates the middle point
3. move to the final point and remove your finger

Is that your problem? If you just press a point and move out, it gives an error, but not the same as yours...

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
