### ISSUE TITLE
multiple viewer in same page for multiple serious load

### ISSUE THREAD

**Issue by mohamedsharaf** [ivmartel/dwv#91]
simple need to add more than one player in the same window 
```js
var app=new dwv.app();

var app2=new dwv.app();

var app3=new dwv.app();
```

how this can be done

**Comment by ivmartel** [comment]
#124 should fix this: it allows multiple app instances on the same page. Each app having its own data. 

Beware that this is not a multi-slice view of one data. It could be used that way, but there would not be any synchronisation of the views.
