### ISSUE TITLE
missing properties in ellipse shape

### ISSUE THREAD

**Issue by oz-keisar-d** [ivmartel/dwv#931]
when we draw 'ellipse' on a dicom we don't get the  following data 

1. Minimum of pixel values within the ROI
1. Maximum of pixel values within the ROI
1. Average of pixel values within the ROI
1. Median of pixel values within the ROI
1. Standard deviation of pixel values within the ROI

* in the rectangle shape we did get the data except 'Median'.

dwv version '0.27.1'

![Screenshot 2021-05-25 135530](https://user-images.githubusercontent.com/78786942/119486852-604bf480-bd61-11eb-981e-8bec95dec1b3.png)

is there an option to get the data in the current version or does it needs extra development?

thanks.

**Comment by ivmartel** [comment]
This will come in the next version: 0.29.0. Relates to #871.

**Comment by oz-keisar-d** [comment]
thanks for the answer!

is there a due date for release?

**Comment by ivmartel** [comment]
Good question... I could do one with what is currently in the repo...

**Comment by oz-keisar-d** [comment]
it will be great, ill wait for the new releas.
thanks!

**Comment by ivmartel** [comment]
Ok, stay tuned for the release (~next week or the one after). Closing for now, please comment on #871 if you need.
