### ISSUE TITLE
"Uncaught SyntaxError: Unexpected token '<'" with JPEG lossless and baseline decoders

### ISSUE THREAD

**Issue by haochiz** [ivmartel/dwv#936]
Hi, we are using the library for our react app and I got the error "No JPEG ... decoder provided". After adding the following code

```
dwv.image.decoderScripts = {
    "jpeg2000": "node_modules/dwv/decoders/pdfjs/decode-jpeg2000.js",
    "jpeg-lossless": "node_modules/dwv/decoders/rii-mango/decode-jpegloss.js",
    "jpeg-baseline": "node_modules/dwv/decoders/pdfjs/decode-jpegbaseline.js"
};
```

I then got "Uncaught SyntaxError: Unexpected token '<'" from JPEG lossless and baseline decoders. JPEG2000 does not give this error but the images do not show correctly (image is blank). It works fine with uncompressed dicom and .jpg/.png images. Am I missing something obvious? 

Thank you!

**Comment by ivmartel** [comment]
Best to post dwv-react issues on its [repo](https://github.com/ivmartel/dwv-react).

Your error is probably related to #5: for web workers, I had to copy the decoders to the public folder in order for them not to be compiled.

It is working for this [example](https://ivmartel.github.io/dwv-react/demo/stable/index.html?input=https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2Fosirix-cerebrix.dcm) with a JPEG2000 data.

**Comment by haochiz** [comment]
Thank you! I got it to work by manually copying the decoders like you suggested.
