### ISSUE TITLE
Load progress of multiframe studies

### ISSUE THREAD

**Issue by toropok** [ivmartel/dwv#942]
Hi,

Is there any method or workaround to monitor load progress for multi frame studies (US, XA)?
Particularly, a LoadProgress event fires only once for these types of studies when the load is completed. we use loadURLs method.

regards,
leo

**Comment by ivmartel** [comment]
In order to show intermediate progress, the HTTP request needs to send a value for its [Content-Length](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length) so that the progress can be calculated. Does your server send this information?

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
