### ISSUE TITLE
LoadURLs in a sliding window 

### ISSUE THREAD

**Issue by fgugliottago** [ivmartel/dwv#954]
Hi,

I would like to understand if there is a way to load images with a sliding window algorithm; let me explain better:
Let's assume that we have a series with 300 images and I want to load 20 images per time.
What I am doing is to load images from 1 to 20, then 20 to 40, and so on.. 
By doing this I can only scroll 20 images per time, and if I want to go back to 1-20 images I need to redownload the content.

So is there any possibility to save previous content? For example:
1) call loadURLs(imagesFrom1To20)
2) save images 1 to 20
3) call loadURLs(imagesFrom20To40)
4) view images 1 to 40

Thanks in advance, best regards.

**Comment by ivmartel** [comment]
I think I get the idea, in the line of #342... It will also need some sort of cache.

**Comment by fgugliottago** [comment]
@ivmartel 
My idea was to cache other images and when needed call the loadImageObjects. Do you mean this?

**Comment by ivmartel** [comment]
Sorry for the late reply @fgugliottago, but yes something along this way. Did you manage to implement something?

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.

**Comment by leehonleon** [comment]
how can i addEventListen to wheel
