### ISSUE TITLE
fit viewer to non square container

### ISSUE THREAD

**Issue by oz-keisar-d** [ivmartel/dwv#958]
is there a way to fit the viewer into a non-square container so that he will fill all of the available space?

**Comment by ivmartel** [comment]
I made some changes regarding this for #952 to support anisotropic pixels. The logic can be found in the [layerController.js#L278](https://github.com/ivmartel/dwv/blob/develop/src/app/layerController.js#L278). I hope this helps for your question...

**Comment by oz-keisar-d** [comment]
I'm talking about the viewer itself, not the DICOM image.

for example in version "0.27.1" i used 

`
 const containerSize = dwvApp.getLayerContainerSize();
 const { width, height } = containerSize;
 getImageLayer.setWidth(width);
 getImageLayer.setHeight(height);
 getDrawController.resizeStage(width, height, scale);
`
then I changed the zoom to 1.5.

so what I get is the viewer that fits its container that wast square and the Dicom was at 1.5 zoom 

I didn't find a way to do so in version "0.29.1".

is there a way to do so in the new version?


thanks for answering!

**Comment by ivmartel** [comment]
The new release (0.30.0) should help you. The viewer should fit better to the provided div, whatever its size but still keeping the pixel ratio of the data.
I hope I answered your question. Closing for now, feel free to comment if you need.

**Comment by ivmartel** [comment]
This should be fixed in v0.33.
