### ISSUE TITLE
Viewer Issue - display images in reverse order

### ISSUE THREAD

**Issue by NivTiko** [ivmartel/dwv#961]
hi, 

when I add DICOM scan image from sagittal position the order of the images in the viewer are in the wrong order(reverse).
the issue is only with the images. the data/information are correct and in the correct order.

maybe you have some solution for that? 

how to handle this situation?

I attached zip file with DICOM files that can reproduce the issue.
[sagittal scan.zip](https://github.com/ivmartel/dwv/files/6777157/sagittal.scan.zip)

thanks,
Niv

**Comment by ivmartel** [comment]
The sorting is done according to the `ImagePositionPatient` but does not use the PatientPosition (head/feet first), so maybe this is your issue.

Related: #261, #462, #834.

**Comment by ivmartel** [comment]
The next release (0.30.0) has a lot of changes and some regarding the slice sorting, even though I think it displays data the same was as before. If this is still an issue, please re-open this issue or create a new one.
Closing for now.
