### ISSUE TITLE
display more than one view

### ISSUE THREAD

**Issue by lilei2333** [ivmartel/dwv#966]
Hi ivmartel,
It seems that I could only get one view in a page. However, it's common to show three or four views when displaying 3-d brain image. I wonder if dwv could do this? The example is captured by [ITK-SNAP](http://www.itksnap.org/pmwiki/pmwiki.php?n=Main.HomePage)
![捕获](https://user-images.githubusercontent.com/72367071/126608137-6adb74bf-f276-443a-bc35-518a7cb24f17.PNG)

**Comment by ivmartel** [comment]
This is a work in progress... Your snapshot also shows MPR, which is also in progress (see #4)...

**Comment by ivmartel** [comment]
See #133 for multi views.

**Comment by ivmartel** [comment]
Multi view and MPR will be available in the next release (0.30.0). Closing for now, feel free to comment if you need.
