### ISSUE TITLE
annotation properties on drag end are not updated

### ISSUE THREAD

**Issue by oz-keisar-d** [ivmartel/dwv#968]
after resizing annotation the properties are updated according to the changes

but after dragging  annotation in the viewer the properties are not updated according to the changes

thanks.

**Comment by ivmartel** [comment]
Confirmed! This is a current limitation that needs to be fixed in the future. All help is appreciated!

**Comment by pacientk** [comment]
Hi!
Are there any updates?

**Comment by ivmartel** [comment]
Nothing to report on my side...
