### ISSUE TITLE
I have an idea how to improve the work with Service Worker (decoders)

### ISSUE THREAD

**Issue by GlosusHidden** [ivmartel/dwv#983]
For example, you need to open a file of 100 slides that need to be processed through the decoder jpeg2000.
So every time you download decode-jpeg2000 and then 'jpx.js', 'util.js', 'arithmetic_decoder.js' from importScritps.

It seems to me that this is not very good. It is a lot of traffic and you need to store decoders somewhere in the internet.

So idea:
1. Merge decoder and all it's importScritps in one file
2. Squeeze it
3. Import it as string 
`const jpeg2000 = require('raw-loader!./jpeg2000.js');`
4. Convert to Blob:
`const jpeg2000Blob = new Blob([jpeg2000], {type: 'application/javascript'})`
5. Create URL from Blob:
`URL.createObjectURL(jpeg2000Blob)`
6. Use this result URL as decoderScripts for library. 

Then everything will work offline

**Comment by ivmartel** [comment]
Thanks, it looks interesting! I guess it is similar to what is done in the background of the [web-workers](https://webpack.js.org/guides/web-workers/) handling of webpack.

**Comment by ivmartel** [comment]
It also made me realise about #993, so thanks again!

**Comment by ivmartel** [comment]
Follow #1127 for progress.
