### ISSUE TITLE
Scroll loaded images while waiting for others to load?

### ISSUE THREAD

**Issue by jjreicher** [ivmartel/dwv#984]
As above--any way to achieve this? Tried manipulating the examples and couldn't make this go.

**Comment by jjreicher** [comment]
Posted for posterity:
If you initialize scroll (setTool) with a "loadstart" it won't work because you need at least one image loaded. If you go with "loaditem" you can do it but you need to add a counter so it only runs after at least one image is loaded. Maybe better ways to do this but worked for me.

**Comment by ivmartel** [comment]
Good point! I would even recommend doing the `setTool('Scroll')` after the first `renderend` event to be sure some data was loaded and rendered.
