### ISSUE TITLE
How to get the pixel data from loaded dicom file?

### ISSUE THREAD

**Issue by cbj921** [ivmartel/dwv#999]
Hi ivmartel,
   I want to get the pixel data from loaded dicom file, but I just get "..." from dwv.app.getMetaData().PixelData, I need pixel matrix from the file,but I couldn't find corresponding API to get it, so I wanted to consult with you.  I will very happy If you have free time to answer me .

**Comment by ivmartel** [comment]
The meta data does not contain the pixel data to not duplicate it with the 'real' data. In a load event, `event.data` is an object made of the image object (`.image`) and the meta data (`.info`). Check out the [dwv.image.Image](https://ivmartel.github.io/dwv/doc/stable/dwv.image.Image.html) doc to see what you can do with pixel data.

**Comment by cbj921** [comment]
Ivmartel,Thank you very much for your answer, I will carefully check the corresponding documents. 
Here is another thorny question to consult you, we currently do a three-view labeled system, I used three dwvapp to control the state of views, and now,I want to use the tool of scroll to change the pictures of three views by rolling the wheel once.But I can not understand the event of Scroll and setTool('scroll'),so I would like to ask you about the idea of this requirement.
Finally, if there are any communication groups related to the project, please let me know. Thank you very much.
![image](https://user-images.githubusercontent.com/48042203/134005611-305b164d-7f40-487d-9d96-a5ae6aa01804.png)

**Comment by cbj921** [comment]
Ivmartel, thank you very much !

**Comment by ivmartel** [comment]
I hope I answered your question. Closing for now, feel free to comment if you need.
